### ISSUE TITLE
[Core System] : Core System -  Functionality

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#1]
**Goal**:
Architect and analyse different issues like uniform header design, message structure and validation as well as error handling, notification and implement utility functions and retrofit throughout the code base

**Dependencies**:
- None currently

**Comment by elnyry-sam-k** [comment]
closing this as Mojaloop v14.1.0 is published and new features will now follow Mojaloop reference architecture (such as vNext)
