### ISSUE TITLE
Trace labels doesn't match the service

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#1001]
**Summary**:
Trace labels are not changing through the different services and handlers.
Entry service for prepare a transfer is 'ml_transfer_prepare'
Its labels are: 
```            
labels: {
                transactionType: 'transfer',
                transactionAction: 'prepare',
                ....
            }
```
all next services throughout the flow has the same labels for transactionType and transactionAction, which is not correct.

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
Each service to has corresponding transactionType and transactionAction. 

**Steps to Reproduce**
  1. Prepare a transfer
  2. Check Kibana APM for trace spans and their labels. 
  

**Specifications**
  - Component: Event framework utilization all components
  - Version: 8.1.0
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by: @vgenev 

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by elnyry** [comment]
After initial review, we feel that this is appropriate as it is, since the service level detail is visible using other fields anyway.
