### ISSUE TITLE
JWS headers (fspiop-uri , fspiop-http-method) not returning for the switch originated messages - block transfers scenario - OSS DEV

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#1037]
**Summary**:
When checking the JWS headers functionality for the messages that are originated at switch, switch is supposed to send FSPIOP-URI and FSPIOP-HTTP-Method but not FSPIOP-Signature.for the current block transfer scenario, these two are missing  FSPIOP-URI and FSPIOP-HTTP-Method.

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**

1. Run block transfer scenario from the Golden_Path2. Observe the headers at the final response received by payerfsp.3.  FSPIOP-URI and FSPIOP-HTTP-Method should be returned with values /transfers/{ID}/error and "PUT" respectively.

**Steps to Reproduce**
  1. Run block transfer scenario from the Golden_Path2. Observe the headers at the final response received by payerfsp.

**Specifications**
  - Component (if known): CL
  - Version:
  - Platform: AWS
  - Subsystem: Mojaloop
  - Type of testing: Functional
  - Bug found/raised by: Sri

**Notes**:
**Request:curl -X POST \**
http://dev1-ml-api-adapter.mojaloop.live/transfers \
-H 'Accept: application/vnd.interoperability.transfers+json;version=1' \
-H 'Accept-Encoding: gzip, deflate' \
-H 'Cache-Control: no-cache' \
-H 'Connection: keep-alive' \
-H 'Content-Length: 1065' \
-H 'Content-Type: application/vnd.interoperability.transfers+json;version=1.0' \
-H 'Date: Sun, 27 Oct 2019 18:24:34 GMT' \
-H 'FSPIOP-Destination: payeefsp' \
-H 'FSPIOP-Source: payerfsp' \
-H 'Host: dev1-ml-api-adapter.mojaloop.live' \
-H 'Postman-Token: 2bf075fa-d6d4-4f75-a478-fad29cd1d4be,5403d6ea-f810-4b9f-ae9d-69511b026982' \
-H 'User-Agent: PostmanRuntime/7.18.0' \
-H 'cache-control: no-cache' \
-d '{"transferId": "e8910444-0033-4baf-9804-7d6db62db676","payerFsp": "payerfsp","payeeFsp": "payeefsp","amount": {"amount": "1923.76","currency": "USD"},"expiration": "2019-10-27T18:34:34.192Z","ilpPacket": "AQAAAAAAAADIEHByaXZhdGUucGF5ZWVmc3CCAiB7InRyYW5zYWN0aW9uSWQiOiIyZGY3NzRlMi1mMWRiLTRmZjctYTQ5NS0yZGRkMzdhZjdjMmMiLCJxdW90ZUlkIjoiMDNhNjA1NTAtNmYyZi00NTU2LThlMDQtMDcwM2UzOWI4N2ZmIiwicGF5ZWUiOnsicGFydHlJZEluZm8iOnsicGFydHlJZFR5cGUiOiJNU0lTRE4iLCJwYXJ0eUlkZW50aWZpZXIiOiIyNzcxMzgwMzkxMyIsImZzcElkIjoicGF5ZWVmc3AifSwicGVyc29uYWxJbmZvIjp7ImNvbXBsZXhOYW1lIjp7fX19LCJwYXllciI6eyJwYXJ0eUlkSW5mbyI6eyJwYXJ0eUlkVHlwZSI6Ik1TSVNETiIsInBhcnR5SWRlbnRpZmllciI6IjI3NzEzODAzOTExIiwiZnNwSWQiOiJwYXllcmZzcCJ9LCJwZXJzb25hbEluZm8iOnsiY29tcGxleE5hbWUiOnt9fX0sImFtb3VudCI6eyJjdXJyZW5jeSI6IlVTRCIsImFtb3VudCI6IjIwMCJ9LCJ0cmFuc2FjdGlvblR5cGUiOnsic2NlbmFyaW8iOiJERVBPU0lUIiwic3ViU2NlbmFyaW8iOiJERVBPU0lUIiwiaW5pdGlhdG9yIjoiUEFZRVIiLCJpbml0aWF0b3JUeXBlIjoiQ09OU1VNRVIiLCJyZWZ1bmRJbmZvIjp7fX19","condition": "HOr22-H3AfTDHrSkPjJtVPRdKouuMkDXTR4ejlQa8Ks"}'

- Severity when opened:
- Priority when opened:

**Comment by elnyry** [comment]
@sri-miriyala which versions of ml-api-adapter and central-ledger was this found this on?

**Comment by oderayi** [comment]
@elnyry @sri-miriyala This issue should be fixed for `ml-api-adapter` by this PR https://github.com/mojaloop/ml-api-adapter/pull/245

**Comment by elnyry** [comment]
Thanks Steven.

**Comment by elnyry** [comment]
@sri-miriyala can you please verify this on a deployment done with helm v8.4.0.. on the two dev environments the core team uses, this is not an issue.

**Comment by sri-miriyala** [comment]
Sure, thank you.

**Comment by elnyry** [comment]
Closing this, as this has been confirmed on more than 2 deployments. Please re-open if there is a repro somewhere, with all the details.
