### ISSUE TITLE
Wrong error message displayed when you use incorrect expiration time format during the prepare transfer process 

### ISSUE THREAD

**Issue by bogere** [mojaloop/project#1054]
**Summary**:
When preparing a transfer, the transfer is rejected because you have badly formed input such as expiration. Let say you are preparing the transfer and the expiration is Date format instead of ISOString format.
```
curl --fail -X POST \
    http://${CLUSTER_IP}/transfers \
    -H 'Accept: application/vnd.interoperability.quotes+json;version=1' \
    -H 'Content-Type: application/vnd.interoperability.quotes+json;version=1.0' \
    -H 'Cache-Control: no-cache' \
    -H "Date: $DATE" \
    -H "FSPIOP-Destination: $PAYEE_FSP_ID" \
    -H "FSPIOP-Source: $PAYER_FSP_ID" \
    -H 'Host: ml-api-adapter.local' \
    -d '{
  "transferId": "'$TRANSFER_ID'",
  "payeeFsp": "'$PAYEE_FSP_ID'",
  "payerFsp": "'$PAYER_FSP_ID'",
  "amount": {
    "amount": "100",
    "currency": "'$CURRENCY'"
  },
  "ilpPacket": "AQAAAAAAAABkEGcuZXdwMjEuaWQuODAwMjCCAhd7InRyYW5zYWN0aW9uSWQiOiJmODU0NzdkYi0xMzVkLTRlMDgtYThiNy0xMmIyMmQ4MmMwZDYiLCJxdW90ZUlkIjoiOWU2NGYzMjEtYzMyNC00ZDI0LTg5MmYtYzQ3ZWY0ZThkZTkxIiwicGF5ZWUiOnsicGFydHlJZEluZm8iOnsicGFydHlJZFR5cGUiOiJNU0lTRE4iLCJwYXJ0eUlkZW50aWZpZXIiOiIyNTYxMjM0NTYiLCJmc3BJZCI6IjIxIn19LCJwYXllciI6eyJwYXJ0eUlkSW5mbyI6eyJwYXJ0eUlkVHlwZSI6Ik1TSVNETiIsInBhcnR5SWRlbnRpZmllciI6IjI1NjIwMTAwMDAxIiwiZnNwSWQiOiIyMCJ9LCJwZXJzb25hbEluZm8iOnsiY29tcGxleE5hbWUiOnsiZmlyc3ROYW1lIjoiTWF0cyIsImxhc3ROYW1lIjoiSGFnbWFuIn0sImRhdGVPZkJpcnRoIjoiMTk4My0xMC0yNSJ9fSwiYW1vdW50Ijp7ImFtb3VudCI6IjEwMCIsImN1cnJlbmN5IjoiVVNEIn0sInRyYW5zYWN0aW9uVHlwZSI6eyJzY2VuYXJpbyI6IlRSQU5TRkVSIiwiaW5pdGlhdG9yIjoiUEFZRVIiLCJpbml0aWF0b3JUeXBlIjoiQ09OU1VNRVIifSwibm90ZSI6ImhlaiJ9",
  "condition": "otTwY9oJKLBrWmLI4h0FEw4ksdZtoAkX3qOVAygUlTI",
  "expiration": "'$EXPIRATION_DATE'"
  }'
```
The error response indicates that you are using transferId that is not  a valid guuid format yet it is supposed to show that expiration data is not valid.
```
{
    "errorInformation": {
        "errorCode": "3102",
        "errorDescription": "Missing mandatory element - Transfer Id must be in a valid GUID format."
    }
}
```
This causes confusion to the developers who think that their transferId is not in valid format yet  the format being used is correct. 

**Severity**:
Low

**Priority**:
Medium,

**Expected Behavior**
Error message should reflect that expiration data is not valid and should use the ISOString format instead

**Steps to Reproduce**
  1. Launch the central-ledger and the ml-api-adapter stack
  2. Send the prepare transfer request  as shown in the summary or just use postman tool using transferId 
      in valid guuid format and expiration in Date format.
  3. You should see the error of bad request . status 400

**Specifications**
  - Component (if known): ml-api-dapter and central-ledger
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing: Postman
  - Bug found/raised by:  @bogere

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by elnyry** [comment]
@bogere , good to see you trying things out..

The error seems good to me.. the transferId is showing from the log as
```"transferId": "'$TRANSFER_ID'" ``` which is not a valid GUID format.

Let me know if you have any questions.

For us too see if anything is wrong with 'expiration' field, try a request with the rest of the fields populated correctly..

**Comment by elnyry** [comment]
@bogere closing this, as this isn't an issue. Feel free to reach out
