### ISSUE TITLE
sendRequest adds multiple entries to the error extensionList

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#1072]
**Summary**:
sendRequest adds multiple entries to the error extensionList when an error occurs when a request is sent out using the central-services-shared library.

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
The cause should be populated in the extensions value with the relevant information about the error being thrown. 

**Steps to Reproduce**
  1. POST a new participant on ALS without the oracle being up
  2. Inspect error being thrown
  3. Note the error is changed to include request information that is not useful

**Specifications**
  - Component (if known): central-services-shared
  - Version: 8.4.3
  - Platform: OSS
  - Subsystem: ALS
  - Type of testing: local/regression
  - Bug found/raised by: TIPS @rmothilal 

**Notes**:
 To be fixed in conjunction with https://github.com/mojaloop/project/issues/1071

- Severity when opened: Medium
- Priority when opened: Medium

## Pull Requests ##
- [x] https://github.com/mojaloop/central-services-shared/pull/137

**Comment by oderayi** [comment]
@Rajiv This story needs a bit more detail especially regarding the expected behaviour. 
For instance, should we just add the 'cause' key to the extensionList with value containing the error message, or should all the existing keys be collapsed into a single object and added to a single 'cause' key/value entry?

**Comment by rajiv** [comment]
@oderayi sorry i cannot help with this project. please tag the correct person.

**Comment by elnyry** [comment]
@rmothilal ^^

**Comment by oderayi** [comment]
Thank you @rajiv.
