### ISSUE TITLE
GET /transfers resulting a different error code and description than before when the request coming from a FSP that is not associated with the original transfer

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#1084]
**Summary**:
When running GET /transfer request from a FSP that is not associated with the original transfer, there used to be a error code "3208" and error description "Requested FSP is not associated with the transfer". But with latest version, am seeing that error code "3000" with error description "Generic client error"

**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Expected Behavior**

Error code: '3208'
Error description: "Requested FSP is not associated with the transfer"

**Steps to Reproduce**
  1. send POST /quotes and then POST /transfers requests from payerfsp to payeefsp
  2. do a GET /transfer on the above sent transferId with FSPIOP-Source "testfsp1"
  3. look at the response at testfsp1 /callbacks endpoint

**Specifications**
  - Component (if known): CL
  - Version: 8.5.0
  - Platform: MAC OS
  - Subsystem: Mojaloop
  - Type of testing: Functional
  - Bug found/raised by: Sri

**Notes**:
Request : POST /quotes
curl -X POST \
  https://extgw.public.tips-sandbox.live:8243/fsp/1.0/quotes \
  -H 'Accept: application/vnd.interoperability.quotes+json;version=1' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Authorization: Bearer c8ac5079-6fc3-3375-a17d-1119afcd1ac7' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 572' \
  -H 'Content-Type: application/vnd.interoperability.quotes+json;version=1.0' \
  -H 'Date: {{quoteDate}}' \
  -H 'FSPIOP-Destination: payeefsp' \
  -H 'FSPIOP-HTTP-Method: POST' \
  -H 'FSPIOP-Signature: {{fspiopSignature}}' \
  -H 'FSPIOP-Source: payerfsp' \
  -H 'FSPIOP-URI: /quotes' \
  -H 'Host: extgw.public.tips-sandbox.live:8243' \
  -H 'Postman-Token: 86dc2fa3-89a4-4276-92cb-824d055b3e67,c145b432-c21b-4f0d-9254-42d7b260cbf0' \
  -H 'User-Agent: PostmanRuntime/7.20.1' \
  -H 'cache-control: no-cache' \
  -d '{{quoteRequest}}'

2. POST /transfers
curl -X POST \
  https://extgw.public.tips-sandbox.live:8243/fsp/1.0/transfers \
  -H 'Accept: application/vnd.interoperability.transfers+json;version=1' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Authorization: Bearer c8ac5079-6fc3-3375-a17d-1119afcd1ac7' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 1267' \
  -H 'Content-Type: application/vnd.interoperability.transfers+json;version=1.0' \
  -H 'Date: Thu, 28 Nov 2019 00:53:29 GMT' \
  -H 'FSPIOP-Destination: payeefsp' \
  -H 'FSPIOP-HTTP-Method: POST' \
  -H 'FSPIOP-Signature: {{fspiopSignature}}' \
  -H 'FSPIOP-Source: payerfsp' \
  -H 'FSPIOP-URI: /transfers' \
  -H 'Host: extgw.public.tips-sandbox.live:8243' \
  -H 'Postman-Token: 445ce24b-f4e8-467f-beaf-350ddc098fc8,5ce5cc56-6a1a-4f2c-b5b3-c12e327599e1' \
  -H 'User-Agent: PostmanRuntime/7.20.1' \
  -H 'cache-control: no-cache' \
  -d '{{transferRequest}}'

3. GET /transfers

curl -X GET \
  https://extgw.public.tips-sandbox.live:8243/fsp/1.0/transfers/349d865f-a0a9-4b64-9c0e-15bada8df5de \
  -H 'Accept: application/vnd.interoperability.participants+json;version=1' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Authorization: Bearer 88de18fb-2684-349c-80c6-8386092b5cc7' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/vnd.interoperability.transfers+json;version=1.0' \
  -H 'Date: Thu, 28 Nov 2019 06:05:52 GMT' \
  -H 'FSPIOP-Source: testfsp1' \
  -H 'Host: extgw.public.tips-sandbox.live:8243' \
  -H 'Postman-Token: fa37986c-cdcf-4258-a9e7-cde3094d5ea4,33e8a0e4-1307-4836-a745-dca6727cec7d' \
  -H 'User-Agent: PostmanRuntime/7.20.1' \
  -H 'cache-control: no-cache'

Response for the above GET /transfers:
<img width="415" alt="Screen Shot 2019-11-28 at 1 06 13 AM" src="https://user-images.githubusercontent.com/38143240/69781194-5d2b7480-117b-11ea-80c2-a3cdc82a2650.png">

- Severity when opened:
- Priority when opened:

**Comment by elnyry** [comment]
Not a bug!

Error Framework now uses sdk-standard-components that has all the errors from the API Definition v1.0. The implementation now uses standard codes and error descriptions (no hard-coding). List can be seen here: https://github.com/mojaloop/sdk-standard-components/blob/master/src/lib/errors/index.js

For reference, here are the details for error code **3208** from the Spec, which clearly do not apply to this case
**Name**: _Transfer ID not found_
**Description**: _Provided Transfer ID was not found on the server._
