### ISSUE TITLE
'eventPlugin' unit test failing in central-services-shared

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#1101]
**Summary**:
In central-services-shared eventPlugin.test.js, the `create and finish a child span with http context headers` test is failing due to `span.spanContext.parentSpanId` being `undefined`.

**Severity**: Medium
**Priority**: Medium

**Expected Behavior**
All tests should pass.

**Steps to Reproduce**
  1. Clone central-services-shared repo
  2. Update dependencies, specifically `@mojaloop/event-sdk` to 8.6.1
  3. Run unit test. You would notice one test failure.

**Specifications**
  - Component (if known): event-sdk
  - Version: 8.6.1
  - Platform:
  - Subsystem: central-services-shared
  - Type of testing: Local/Unit Test
  - Bug found/raised by: @oderayi 

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by lewisdaly** [comment]
In `event-sdk` `v8.6.1`, the `tracestate` header is required, otherwise it defaults to creating a new context.

I added this `tracestate` header to the test, and everything works as expected.
