### ISSUE TITLE
Redis error when starting up mojaloop-simulator, scheme-adapter exiting

### ISSUE THREAD

**Issue by vandaillyes-modusbox** [mojaloop/project#1119]
**Summary**:
I am trying to start up the mojaloop-simulator but I get some redis-related error message, which prevents the scheme-adapter from running. The error says:

```
scheme-adapter_1  | {
scheme-adapter_1  |   app: 'mojaloop-sdk-inboundCache',
scheme-adapter_1  |   err: {
scheme-adapter_1  |     stack: 'Error: Redis connection to redis1:6379 failed - getaddrinfo ENOTFOUND redis1\n' +
scheme-adapter_1  |       '    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)',
scheme-adapter_1  |     message: 'Redis connection to redis1:6379 failed - getaddrinfo ENOTFOUND redis1',
scheme-adapter_1  |     errno: 'ENOTFOUND',
scheme-adapter_1  |     code: 'ENOTFOUND',
scheme-adapter_1  |     syscall: 'getaddrinfo',
scheme-adapter_1  |     hostname: 'redis1'
scheme-adapter_1  |   },
scheme-adapter_1  |   msg: 'Error from REDIS client getting subscriber',
scheme-adapter_1  |   timestamp: '2019-12-12T09:57:41.241Z'
scheme-adapter_1  | }
scheme-adapter_1  | Error: Redis connection to redis1:6379 failed - getaddrinfo ENOTFOUND redis1
scheme-adapter_1  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
scheme-adapter_1  |   errno: 'ENOTFOUND',
scheme-adapter_1  |   code: 'ENOTFOUND',
scheme-adapter_1  |   syscall: 'getaddrinfo',
scheme-adapter_1  |   hostname: 'redis1'
scheme-adapter_1  | }
```

Based on help I got in the mojaloop-simulator channel, the resolution is to amend the scheme-adapter.env file. 

`CACHE_HOST=redis1`

should say

`CACHE_HOST=redis`

**Severity**:
High

**Priority**:
Medium

**Expected Behavior**
All three components of the simulator should be up and running (scheme-adapter, redis, sim).

**Steps to Reproduce**
  1. git clone https://github.com/mojaloop/mojaloop-simulator.git
  2. cd mojaloop-simulator/src
  3. docker-compose build
  4. docker-compose up

**Specifications**
  - Component (if known): mojaloop-simulator
  - Version: v8.2.0
  - Platform:  Linux VM running Ubuntu 18.04.3 LTS
  - Subsystem:
  - Type of testing: local / manual
  - Bug found/raised by: @vandaillyes-modusbox 

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by vijayg10** [comment]
#1119
