### ISSUE TITLE
ml-api-adapter /swagger.json fails

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1120]
**Summary**:
The `/swagger.json` endpoint on `ml-api-adapter` fails.

It looks like this is caused by mixing and matching `@hapi/joi` versions.

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
The `/swagger.json` endpoint should return the swagger spec.

**Steps to Reproduce**
  1. start the ml-api-adapter
  2. `curl localhost:3000/swagger.json`
  3. observe the following error:
```json
{"errorInformation":{"errorCode":"2001","errorDescription":"Internal server error - Cannot mix different versions of joi schemas"}}
```

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by:

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by lewisdaly** [comment]
Looks like this is blocked by: https://github.com/mojaloop/project/issues/1108

We can't upgrade everything to `@hapi/joi` 16+ until this is resolved.

**Comment by lewisdaly** [comment]
Hmm. Unfortunately the fix with #1108 didn't do the trick, so there's likely some other dependency issues to fix before this works again.

**Comment by lewisdaly** [comment]
It also looks like there is no version of `@hapi/hapi` that supports `@hapi/joi:16.X.X`, so I think the only way to fix this is to upgrade to `@hapi/hapi:19.X.X`. 

That has another whole host of issues, since the latest version of hapi drops support for node `10.X.X`

**Comment by elnyry** [comment]
Fixed as of Sprint10.2 (seeing swagger fine)

**Comment by lewisdaly** [comment]
Great!
