### ISSUE TITLE
DevSecOps Initiative Epic 1: JavaScript to Typescript Convention 

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1126]
Context
Typescript is the best option, this decision has been made already by the design authority, which recommended it to be preferred but not mandatory.
Objectives
“Document code quality and security benefits of converting JavaScript to Typescript” and provide recommendations to facilitate a decision-making process on whether TS should be mandatory, or if for only for certain critical components.

Stories

TBC

**Comment by lewisdaly** [comment]
Closing this Epic in favour of unified DevSecOps epic: https://github.com/mojaloop/project/issues/1213
