### ISSUE TITLE
DevSecOps Initiative Epic 3: Open Source Security (vulnerabilities, compliance, and operational risk) 

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1128]
**Context:**

The focus of the epic is to establish a framework, standards, guidelines and tools needed to secure and simplify management of Mojaloop open source assets in order to:

- Stay compliant with open source license usage agreements 
- Ensure consistent use of non-vulnerable and non-obsolete open source components and dependencies in the project.
- Provide a complete and accurate inventory of all open source and third-party components used during builds

**Objectives:**

- Review and redefine Mojaloop open source security and compliance requirements - license usage policies.
- Review and evaluate the effectiveness of in place efforts to address this.
- Establish a framework, standards, Guidelines and adopt Toolset for addressing Open Source Security and Compliance in Mojaloop.

**Stories:** 

1. Review and redefine Mojaloop Open Source Security & Compliance – Godfrey. Lewis, Victor & Miguel
2. Establish a framework, standards, Guidelines and adopt Toolset for addressing Open Source Security and Compliance in Mojaloop
3. Tools Review and Improvement

- Evaluate the current NPM integration work against the initial targets – All
- Identify and implement improvements focusing on the quick wins (before PI next week) for improvement – All
- Measure against one or two of the advanced commercial offering (Whitesource or Blackduck depending with the commercial feasibility) to check if they are any major gap or blind spots – All
- Research more open source complimentary tools to NPM – All

- Ensure and test the integration of the new tools into our CI\CD Pipeline

4. Document and communicate the epic output to the community - Godfrey

**Comment by lewisdaly** [comment]
Closing this Epic in favour of unified DevSecOps epic: https://github.com/mojaloop/project/issues/1213
