### ISSUE TITLE
DevSecOps Initiative Epic 4: Static Code Analysis (SCA) Integration

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1129]
**Context:**

Code security was never addressed through a formal process hence the need for the introduction of secure coding standards and security testing early in the development lifecycle – at development, build and integration stages. 

Although various efforts from community contributors to improve code security and perform their component level security testing is greatly acknowledged, however there is still a need to establish secure coding standard and addition of more security testing gates with every pull request before check-in. All the new SCA tools to be adopted must fully support automation and integration into the CI\CD pipeline environment - CircleCI.

**Objectives:**

•	Introduce code level security vulnerabilities & quality checks by performing a full end to end static code analysis using open source tools at code check-in and integrating testing phases.
•	Evaluate current efforts (SQ and OWASP dependency Check) in addressing this and identify areas of improvement to attain quick wins.
•	Evaluate and adopted more open source SCA to close any existing gaps 
•	Document and communicate code security standards and rules for code acceptance. 

**Stories:** 

1.	Evaluate current efforts (SQ and OWASP dependency Check) in addressing this – All
2.	Identify areas of improvement (quick wins) - All
3.	Evaluate more open source SCA tools to close gaps – This will be major focus area until next PI Meeting – Godfrey and Victor
4.	Establish security triage management tools, process and methodologies – Godfrey & Victor
5.	Establish a secure coding standard and communicate to the contributors – Godfrey, Pedro & Victor
6.	Define and document the following: - Godfrey & Victor

**Comment by lewisdaly** [comment]
Closing this Epic in favour of unified DevSecOps epic: https://github.com/mojaloop/project/issues/1213
