### ISSUE TITLE
DevSecOps Initiative Epic 6: Threat Modelling

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1131]
**Context:**

A threat modelling process is designed to empower participants in the software development process to efficiently deliver secure software by identifying threats and mitigating them early in the requirement\design phase. When implemented properly, it will help:

•	Produce software that is secure by design
•	Prioritize security efforts according to true risk
•	Step into the mind of an attacker and identify attack vectors
•	Enables the development teams to predictably and effectively define security problems early in the process.
•	Document and share application security knowledge amongst all DevOps stakeholders.

With the introduction of this to Mojaloop, we hope to drastically improve our effort of developing secure software by enabling ourselves to understand key assets and potential design vulnerabilities that exist in your application. It must be repeated to account for changes in the threat landscape and additions of new functionality to the platform. Below are key benefits of a threat modelling exercise on major application development project like ours:

•	A powerful way to identify potential threats, visualize risk and understand the security of the software system.
•	Multi-disciplinary effort in which all team members think about and address threats:
	A process for management consultants to elicit security requirements
	A way for architects to realize and mitigate design problems.
	A road map for developer to write secure code.
	A starting point to create robust security minded test plans.
•	The most reliable way to:
	Understand architecture and security requirements
	Find business-process and system-level security issues alike
	Assess probability, harm, priority, and impact

**Objectives:**
The threat modelling process is designed to highlight risks early in the software development lifecycle to increase the focus on application security throughout design and development and below are key objectives of the epic:
•	Introduce threat modelling to Mojaloop is the authoritative source of security requirements.
•	Define and adopt a threat modelling framework and standard 
•	Perform modelling on critical parts of the Mojaloop platform and access the results.

**Stories:**

1.	Define and document requirements for Threat Modelling – Godfrey
2.	Adopt and document a Threat Modelling Methodology – Godfrey & Victor
3.	Test the methodology on a limited, refine it and approve the final version – Godfrey, Victor & Pedro
4.	Implement on critical part of the platform and on new features as a quick win – All
5.	Document the threat modelling process for community adoption and use – Godfrey 
6.	Apply to the rest of Mojaloop platform - All

**Comment by lewisdaly** [comment]
Closing this Epic in favour of unified DevSecOps epic: https://github.com/mojaloop/project/issues/1213
