### ISSUE TITLE
DevSecOps Initiative Epic 7: Cloud Security (AWS Instance)

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1132]
**Context:**
To evaluate the security and compliance level of the current AWS based instance and use it as standard to establish a cloud security standard and recommendations for implementor.

**Objectives:**
•	Review and define Mojaloop cloud security and compliance requirements
•	Evaluate security of the current implementation on AWS and identify areas for improvements
•	Define a new AWS cloud deployment standard and communicate feedback to the community

**Stories:**
1.	Define cloud infrastructure security requirements - Godfrey
2.	Develop a cloud security framework with options of using both native cloud provider features and open source tools – Godfrey & Victor
3.	Document a new Mojaloop specific cloud infrastructure security baseline. Godfrey & Victor
4.	Assess the security level of the current AWS instance against this new baseline – Godfrey & Victor

**Comment by lewisdaly** [comment]
Closing this Epic in favour of unified DevSecOps epic: https://github.com/mojaloop/project/issues/1213
