### ISSUE TITLE
DevSecOps Initiative Epic 8: Establish a DevSecOps Framework

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1133]
**Context:**
All the DevSecOps Epics(1-7) are part a bottom up approach in defining Mojaloop DevSecOps strategy, framework and implementation plan. After next year’s PI Meeting, we will begin a process developing a top down approach incorporating all the successes from our current initiative. Depending with how fast Victor and I can move, we maybe have a draft framework for review at the convening. 

Objectives:
•	Define and formalize an end to end framework for Majaloop DevSecOps Integration
•	Map existing security controls (as per current defined DevSecOps Epics) against the new framework & Identify gaps
•	Identification more areas of focus (Epics) for a comprehensive coverage of security and compliance within Mojaloop 
•	Document and communicate standards, tools and scripts to the community
Stories:
1.	Define, document and approve an end to end Mojaloop DevSecOps framework – Godfrey & Victor
2.	Map existing security controls against the new framework & Identify gaps – Godfrey & Victor
3.	Develop an implementation roadmap – Godfrey & Victor
4.	Document and communicate standards, tools and scripts to the community - Godfrey

**Comment by lewisdaly** [comment]
Closing this Epic in favour of unified DevSecOps epic: https://github.com/mojaloop/project/issues/1213
