### ISSUE TITLE
Content Length limit is less than value specified in quotes Swagger.json

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1137]
**Summary**:
In POST /Quotes, As per https://raw.githubusercontent.com/mojaloop/quoting-service/master/src/interface/swagger.json, the content-length the API supports up to 5242880 bytes, it responded with http status code 413 for 1.2 MB.

**Severity**:
(Low)

**Priority**:
(Medium, Low)

**Expected Behavior**
Post/ Quote should be supported a content-length of 5242880 bytes
![Screenshot 2019-12-20 13 50 27](https://user-images.githubusercontent.com/53434415/71259226-dd369b80-232f-11ea-917c-3bcbae22fc80.png)

**Steps to Reproduce**
  1. curl -X POST \
  http://dev1-quoting-service.mojaloop.live/quotes \
  -H 'Accept: application/vnd.interoperability.quotes+json' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Authorization: Bearer {{TESTFSP1_BEARER_TOKEN}}' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 776' \
  -H 'Content-Type: application/vnd.interoperability.quotes+json;version=1.0' \
  -H 'Date: Fri, 20 Dec 2019 13:25:11 GMT' \
  -H 'FSPIOP-Destination: payeefsp' \
  -H 'FSPIOP-Signature: {"signature":"iU4GBXSfY8twZMj1zXX1CTe3LDO8Zvgui53icrriBxCUF_wltQmnjgWLWI4ZUEueVeOeTbDPBZazpBWYvBYpl5WJSUoXi14nVlangcsmu2vYkQUPmHtjOW-yb2ng6_aPfwd7oHLWrWzcsjTF-S4dW7GZRPHEbY_qCOhEwmmMOnE1FWF1OLvP0dM0r4y7FlnrZNhmuVIFhk_pMbEC44rtQmMFv4pm4EVGqmIm3eyXz0GkX8q_O1kGBoyIeV_P6RRcZ0nL6YUVMhPFSLJo6CIhL2zPm54Qdl2nVzDFWn_shVyV0Cl5vpcMJxJ--O_Zcbmpv6lxqDdygTC782Ob3CNMvg\",\"protectedHeader\":\"eyJhbGciOiJSUzI1NiIsIkZTUElPUC1VUkkiOiIvdHJhbnNmZXJzIiwiRlNQSU9QLUhUVFAtTWV0aG9kIjoiUE9TVCIsIkZTUElPUC1Tb3VyY2UiOiJPTUwiLCJGU1BJT1AtRGVzdGluYXRpb24iOiJNVE5Nb2JpbGVNb25leSIsIkRhdGUiOiIifQ"}' \
  -H 'FSPIOP-Source: payerfsp' \
  -H 'Host: dev1-quoting-service.mojaloop.live' \
  -H 'Postman-Token: 081f7753-8334-4bb2-ac6b-6fb0052c1c48,4875f2f7-885a-4b8f-9ffc-44b682d7bb58' \
  -H 'User-Agent: PostmanRuntime/7.20.1' \
  -H 'cache-control: no-cache' \
  -d '{
  "quoteId": "0b71d6f5-889e-4e99-8c9b-bc852d310e89",
  "transactionId": "f05e4c47-05e0-488f-b293-7ff2a09e2ea9",
  "payer": {
    "partyIdInfo": {
      "partyIdType": "MSISDN",
      "partyIdentifier": "{{payerMSISDN}}",
      "fspId": "payerfsp"
    },
    "personalInfo": {
      "complexName": {
        "firstName": "Mats",
        "lastName": "Hagman"
      },
      "dateOfBirth": "1983-10-25"
    }
  },
  "payee": {
    "partyIdInfo": {
      "partyIdType": "MSISDN",
      "partyIdentifier": "22556999125",
      "fspId": "payeefsp"
    }
  },
  "amountType": "SEND",
  "amount": {
    "amount": "60.1234",
    "currency": "USD"
  },
  "transactionType": {
    "scenario": "TRANSFER",
    "initiator": "PAYER",
    "initiatorType": "CONSUMER"
  },
  "note": "hej"
}'
  2. Make sure in above code, increase the content in 'note' around 1.2 MB or more
  3. Send the Quote - 413 is responded 
<img width="1031" alt="Screenshot 2019-12-20 13 53 11" src="https://user-images.githubusercontent.com/53434415/71259321-1a029280-2330-11ea-9d18-30623123dd69.png">

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by:@amarmodus

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by mdebarros** [comment]
Note that this is most like due to the Ingress Controller configuration, here is an example on an annotation that is needed for Nginx to allow for bigger payload sizes --> https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#custom-max-body-size
