### ISSUE TITLE
Refactor the Central-Ledger CircleCI Integration & Functional scripts

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#114]
PR with changes made to forensic-logging-sidecar(FLS): https://github.com/mojaloop/forensic-logging-sidecar/pull/5

This PR to be used as the reference for the re-factoring.

**Acceptance Criteria**
- [ ] The CircleCI Integration scripts for Central-Ledger must reflect in style the FLS sidecar test scripts
- [ ] The CircleCI functional scripts for Central-Ledger must reflect in style the FLS sidecar test scripts
- [ ] Use changes in PR:https://github.com/mojaloop/forensic-logging-sidecar/pull/5 as reference

**Comment by elnyry** [comment]
Not applicable right now
