### ISSUE TITLE
Deploy & Test snyk as an addtional tool for open source vulnerability scanning & fixing 

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1155]
## **Goal**:
To compliment current open source vulnerability scanning and fixing tool (snyk - has one of the largest open source vulnerability database)

**Tasks**:
- [ ] TBD [ @? ]

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: Pedro
- QA/Review: Miguel

**Comment by lewisdaly** [comment]
Follow up a long-lived location for these findings.

**Comment by pedrosousabarreto** [comment]
findings recorded here: https://github.com/mojaloop/documentation/blob/master/code_quality_security/snyk_investigation.md
