### ISSUE TITLE
Deploy & Test snyk as a tool for container security scanning & fixing 

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1158]
## **Goal**:
Explore snyk for contairner security scanning & fixing.

**Tasks**:
- [ ] TBD [ @? ]

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Closing as this is a duplicate of #1555
