### ISSUE TITLE
Update & Communicate Contributor's guide with new security measures & processes

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1160]
## **Goal**:
As a Mojaloop Adopter
I'd like to have access to guidance regarding security measures & processes for Mojaloop
so that I can follow them and use to report vulnerabilities and issues

The goal is to Update & Communicate Contributor's guide with new security measures & processes once they have been finalized post tool integration and testing 

**Tasks**:
- [ ] TBD [ @? ]

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by godfreykutumela** [comment]
Hello @elnyry so far we have the vulnerability reporting procedure and application security summary ready for publication so please guide us on the best place to publish them...both are living documents and we will update them should there by any changes before the end of the PI.

**Comment by godfreykutumela** [comment]
This is a sprint to sprint tasks to upload completed documentation on relevant places. We will close it at the of last sprint.

**Comment by millerabel** [comment]
Can you add a definition of “Done” and other Story (or Epic) template facets?

**Comment by godfreykutumela** [comment]
Noted @millerabel and I will liase with @elnyry to effect this change.

**Comment by elnyry** [comment]
@godfreykutumela  here is a link you can use for the ‘Vulnerability reporting procedure’ and ‘Mojaloop Application Security Summary’ docs: https://mojaloop.io/documentation/code_quality_security/readme.html

The actual docs (as PDFs) are here: https://github.com/mojaloop/documentation-artifacts/tree/master/presentations/discussion-docs
