### ISSUE TITLE
Mojaloop Docker-Bench Configuration and Policy Recommendation

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1162]
## **Goal**:
To provide: 
1. a set of recommendations for the kubernetes environment which will host a mojaloop deployment
2. a list of helm changes to bring the actual deployed environment more into line with the docker-bench recommendations

**Tasks**:
- [ ] TBD [ @? ]

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
@godfreykutumela I'm a little confused by this ticket. My impression from our discussions and my own research is that we need to run `docker-bench` against a docker host environment (i.e. Kubernetes), and not an individual _image_.

As discussed in our previous calls, I think we should look at how the OSS community can take advantage of the `docker-bench` tool (which I think is already built into kubernetes), and provide:
1. a set of recommendations for the kubernetes environment which will host a mojaloop deployment
2. a list of helm changes to bring the actual deployed environment more into line with the `docker-bench` recommendations

@mdebarros and @pedrosousabarreto do you have any other thoughts or ideas about the above?

**Comment by godfreykutumela** [comment]
Noted @lewisdaly and yes I agree with the approach. If it is become too wide I think it will be best to base our recommendations on best practice standards and advice adoptors to further refine based on their quality, compliance and security. I change the story accordingly to reflect the new approach.

**Comment by godfreykutumela** [comment]
merged into new stories under DevSecOps epic
