### ISSUE TITLE
GET /parties failing due to ALS issue in regression testing

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1182]
**Summary**:
GET /parties failing due to ALS issue in regression testing

![image](https://user-images.githubusercontent.com/53434415/72977323-30d35380-3dcc-11ea-9487-95c4bbe0a674.png)

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**

![image](https://user-images.githubusercontent.com/53434415/72977264-0ed9d100-3dcc-11ea-9de1-f4c6000f242d.png)

**Steps to Reproduce**
  1.Run the Golden path postman collection for p2p_happy_path SEND QUOTE
  or
run following curl command
```
curl --location --request GET 'http://dev2-account-lookup.mojaloop.live/parties/MSISDN/27713803912' \
--header 'Accept: application/vnd.interoperability.parties+json;version=1' \
--header 'Content-Type: application/vnd.interoperability.parties+json;version=1.0' \
--header 'FSPIOP-Source: payerfsp' \
--header 'Date: Wed, 22 Jan 2020 16:51:24 GMT'
```

**Specifications**
Component (if known): central-services
Version: Interim (internal) v8.8.0
Platform: Dev 2, AWS
Subsystem:ALS
Type of testing: Regression testing
Bug found/raised by: @amarmodus

**Notes**:

- Severity when opened:
- Priority when opened:

## Pull Requests ##
- [x] https://github.com/mojaloop/account-lookup-service/pull/225

**Comment by elnyry** [comment]
Validated on AWS `dev2` envt and works now (GP tests pass 100%)
