### ISSUE TITLE
Combine and Update the following duplicated documents as required

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#119]
Issue raised by @georgi-sgbg.                       

1. Duplication of the following documents:

- https://github.com/mojaloop/mojaloop/blob/develop/contribute/Tools%2C-technology%2C-and-process-choices.md

- https://github.com/mojaloop/docs/blob/develop/decisions.md

2. The decisions in the above documentation is also out of date, and should be updated as required

**Comment by georgi-sgbg** [comment]
I've also fixed some broken links and few spelling issues in other documents while reading.
