### ISSUE TITLE
Quoting service: PUT /quotes/{id} should accept "Accept" header like POST /quotes

### ISSUE THREAD

**Issue by ezolnbl** [mojaloop/project#1191]
**Summary**:
Currently when calling the above described endpoint it gives back a 202 HTTP response however at backend the call fails because in the quotes.js -> handleQuoteUpdate method still validates this header but the post method handleQuoteRequest was already fixed earlier in another bugfix.
If called without Accept header the call fails because there is no Accept header presented.
This is a blocking issue and should be fixed asap.

Error:
"Update for quote 47dd7bd8-df39-4c4f-8da3-ca09a21b44b6 failed: "accept" header should not be sent in callbacks."

**Tasks**
- [ ] Reproduce
- [ ] Fix bug
- [ ] Update tests to cover bug

**Severity**:
High

**Priority**:
Critical

**Expected Behavior**
PUT /quotes/{id} endpoint should be called with or without Accept header

**Steps to Reproduce**
  already described above

**Specifications**
  - Component: quoting-service
  - Version: 8.8.1-snapshot

**Notes**:
Change of PUT handler method 'handleQuoteUpdate' was introduced at 2019-09-02 
Fix of POST handler method 'handleQuoteRequest' was introduced at 2019-11-20

**Comment by elnyry** [comment]
@ezolnbl: Please excuse me for asking this again for confirmation, but are you saying "_PUT /quotes/{id} should accept "Accept" header_" ?

Please review sections 10.3.3 and 10.4.8 from the [API Definition document](https://github.com/mojaloop/mojaloop-specification/blob/master/documents/supporting-documentation/API%20Definition%20v1.0.pdf), which kind of motivated this change ( to not allow Accept headers on callbacks / PUT calls)

**Comment by ezolnbl** [comment]
If i call the endpoint without Accept header i get a validation error:
{
  "errorInformation": {
    "errorCode": "3101",
    "errorDescription": "Malformed syntax - Invalid accept header"
  }
}
If i call the endpoint with Accept header i get a 202 and at backend i get this:
{ message:
   'Update for quote b38b633b-f14a-4cfa-9573-2d420cc17d4b failed: "accept" header should not be sent in callbacks.',
  replyTo: 'localdev01',
  apiErrorCode:
   { code: '3100',
     message: 'Generic validation error',
     httpStatusCode: 400,
     name: 'VALIDATION_ERROR',
     type:
      { regex: '^31[0-9]{2}$',
        description: 'Client Validation Error',
        httpStatusCode: 400,
        name: 'CLIENT_VALIDATION_ERROR' } },
  extensions: undefined,
  cause: undefined }

**Comment by elnyry** [comment]
Ok, yeah this needs to be fixed. As I indicated earlier, PUT shouldn't need (or have) accept header.. Thanks for the response.

**Comment by ezolnbl** [comment]
this validation resides in the central-services-shared, I think either that module should be modified to add an exception about PUT calls or the quote service to ignore accept header silently and do not throw a blocking exception

**Comment by elnyry** [comment]
@ezolnbl feel free to raise a Pull Request.. If not someone from the core team will look at it today..

**Comment by ezolnbl** [comment]
javascript is not my area 🐢

**Comment by elnyry** [comment]
> javascript is not my area 🐢

Ok, no problem :-)..

**Comment by oderayi** [comment]
So here my findings:

> If i call the endpoint without Accept header i get a validation error:
{
"errorInformation": {
"errorCode": "3101",
"errorDescription": "Malformed syntax - Invalid accept header"
}
}
- This could not be reproduced. If you're using Postman to test the scenario, if you observe the Postman's console log for the request, you would see that Postman is actually adding the "Accept" header with value "*/*" to the request automatically. Currently, there is no way to stop Postman from sending those default headers.

The same is true for curl but with curl you can override that behavior by specifying the header with no value i.e  
```
curl -X PUT \
  http://quoting-service.local:3002/quotes/7c23e80c-d078-4077-8263-2c047876fcf6 \
  -H 'Accept:' \   
  -H 'Accept-Encoding: gzip, deflate' \
...
```
So I had to use curl to send a valid request for this endpoint and overriding the header as described above.

> If i call the endpoint with Accept header i get a 202 and at backend i get this:
{ message:
'Update for quote b38b633b-f14a-4cfa-9573-2d420cc17d4b failed: "accept" header should not be sent in callbacks.',
replyTo: 'localdev01',
apiErrorCode:
{ code: '3100',
message: 'Generic validation error',
httpStatusCode: 400,
name: 'VALIDATION_ERROR',
type:
{ regex: '^31[0-9]{2}$',
description: 'Client Validation Error',
httpStatusCode: 400,
name: 'CLIENT_VALIDATION_ERROR' } },
extensions: undefined,
cause: undefined }

This is correct and expected behavior.

**Comment by ezolnbl** [comment]
I am using Insomnia not Postman but the behaviour is the same, it is adding the Accept header as "*/*" but i think the outcome is very misleading and by validating a header on backend level the call should not fail but instead the header should be ignored/removed.

**Comment by oderayi** [comment]
@elnyry What do you think?

**Comment by oderayi** [comment]
> I am using Insomnia not Postman but the behaviour is the same, it is adding the Accept header as "*/*" but i think the outcome is very misleading and by validating a header on backend level the call should not fail but instead the header should be ignored/removed. (as it is already handled at POST method)

POST /quotes expects "Accept" header.

**Comment by elnyry** [comment]
> I am using Insomnia not Postman but the behaviour is the same, it is adding the Accept header as "*/*" but i think the outcome is very misleading and by validating a header on backend level the call should not fail but instead the header should be ignored/removed. (as it is already handled at POST method)

We're following the spec here, so I'm not sure if we should change functionality because a few testing tools do not support it..

**Comment by elnyry** [comment]
> @elnyry @ezolnbl
> So here are my findings:
> 
> > If i call the endpoint without Accept header i get a validation error:
> > {
> > "errorInformation": {
> > "errorCode": "3101",
> > "errorDescription": "Malformed syntax - Invalid accept header"
> > }
> > }
> 
> * This could not be reproduced. If you're using Postman to test the scenario, and you observe the Postman's console log for the request, you would see that Postman is actually adding the "Accept" header with value "*/*" to the request automatically. Currently, there is no way to stop Postman from sending those default headers.
> 
> The same is true for curl but with curl you can override that behavior by specifying the header with no value i.e
> 
> ```
> curl -X PUT \
>   http://quoting-service.local:3002/quotes/7c23e80c-d078-4077-8263-2c047876fcf6 \
>   -H 'Accept:' \   
>   -H 'Accept-Encoding: gzip, deflate' \
> ...
> ```
> 
> So I had to use curl to send a valid request for this endpoint and overriding the header as described above.
> 
> > If i call the endpoint with Accept header i get a 202 and at backend i get this:
> > { message:
> > 'Update for quote b38b633b-f14a-4cfa-9573-2d420cc17d4b failed: "accept" header should not be sent in callbacks.',
> > replyTo: 'localdev01',
> > apiErrorCode:
> > { code: '3100',
> > message: 'Generic validation error',
> > httpStatusCode: 400,
> > name: 'VALIDATION_ERROR',
> > type:
> > { regex: '^31[0-9]{2}$',
> > description: 'Client Validation Error',
> > httpStatusCode: 400,
> > name: 'CLIENT_VALIDATION_ERROR' } },
> > extensions: undefined,
> > cause: undefined }
> 
> This is correct as reported.

Thanks @oderayi

**Comment by elnyry** [comment]
@ezolnbl - Feel free to look at the Simulators (that are used for QA / testing to send callbacks) in this regard 
- https://github.com/mojaloop/simulator
- https://github.com/mojaloop/mojaloop-simulator
