### ISSUE TITLE
DRAFT - Double JSON Encoding Body Format Error

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#1195]
**Summary**:
When sending a Transfer request with a double JSON encoded body format, the response from ML-API-Adapter service does not respond with a valid error. Instead the message is then processed by the prepare handler which results in an error being printed to logs as such:

```
centralledger-handler-transfer-prepare generate an error: PrepareHandler::prepare::dupCheck::Undefined binding(s) detected when compiling SELECT. Undefined column(s): [transferId] query: select * from 'transferDuplicateCheck' where 'transferId' = ?--P0 . 
```

**Severity**:
Medium

**Priority**:
Low

**Expected Behavior**

ML-API-Adapter should validate the incoming request against the API specification, and respond with an invalid message response.

**Steps to Reproduce**
  1. TBD
  2.
  3.

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by: @mdebarros 

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by mdebarros** [comment]
Some notes:

```centralledger-handler-transfer-prepare generate an error: PrepareHandler::prepare::dupCheck::Undefined binding(s) detected when compiling SELECT. Undefined column(s): [transferId] query: select * from 'transferDuplicateCheck' where 'transferId' = ?--P0 .```

**Comment by elnyry-sam-k** [comment]
This will be re-opened when there is a repro
