### ISSUE TITLE
Outline version negotiation protocol

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1200]
## **Goal**:
As a `switch implementer`
I want to `understand how Mojaloop APIs will negotiate and handle version mismatches`
so that I `effectively implement such means`

**Tasks**:
- [ ] TBD [ @? ]

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: TBC

**Comment by elnyry** [comment]
@lewisdaly this is already implemented in the testing toolkit: https://github.com/mojaloop/ml-self-testing-toolkit as specified in the API Spec v1.0

I'm thinking we can borrow this into the core as well after some discussions, but the implementation is there.

I do agree however, that this needs more visibility..

**Comment by lewisdaly** [comment]
Great, yeah if we can link to both a spec and a reference implementation for the version negotiation stuff.

**Comment by elnyry** [comment]
Presented at the PI10 community event
