### ISSUE TITLE
Internal Versioning Discussion

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1202]
## **Goal**:
As an `OSS maintainer`
I want to `discuss how internal microservices, messages and databases should be versioned`
to `understand the scope of such versioning implementations`

**Tasks**:
- [ ] TBD [ @? ]

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: TBC

**Comment by lewisdaly** [comment]
I think we've covered some of this already, although I think we might need to abandon the `PI.Sprint.Increment` based versioning sometime in the future, so that we can have both npm packages and docker images supported at `Minor` level.

For example, if we have a `central-ledger:v10.0.0`, and `central-ledger:v11.0.0` both supported at the same time within the LTS, we need to be able to rebuild `v10.0.1` to include security patches.

**Comment by elnyry** [comment]
hi Lewis, yeah I think we need to move away from the Sprint versioning scheme, I'm just waiting for the opportune time to propose that without creating ambiguity. I think (may be I'm the only onoe), we have a good thing going, so we need to make sure that change when it happens, is well documented and made aware to all the stake holders..

May be we can start communicating that from the upcoming PI, if we can come to a consensus on that. Let me add some text regarding that in the versioning proposal. How about we pick up say PI11 kickoff and then start using the Semantic versioning strictly from then on.. anyway lets discuss that in detail in the context of the versioning proposal.

**Comment by lewisdaly** [comment]
> (may be I'm the only onoe),

No, I do agree with you that the cadence is not something we should just throw away.

> May be we can start communicating that from the upcoming PI, if we can come to a consensus on that.

Yeah sounds good. I'm thinking we could potentially add a separate field in the `package.json` files for the existing `PI.Sprint.Increment` to aid with the transition for a few months, for example:

```
{
  "name": "quoting-service",
  "description": "Quoting Service hosted by a scheme",
  "license": "Apache-2.0",
  "version": "1.0.1",
  "ml_tag": "9.5.4",
   ...
}
```

**Comment by lewisdaly** [comment]
So I think we've covered the `npm module` and `docker image` components to this with our switch to semantic versioning.

The outstanding discussion points are around database schema and kafka messages.

At the moment, the schemas for our different databases are updated in lock step with our microservices which _own_ them, (ie. `mojaloop/central-ledger` for the settlement and central_ledger database)

As for the kafka messages, if I understand correctly at the moment, these are tightly coupled to the API itself, which makes a lot of sense. @elnyry-sam-k do we have a central, comprehensive list of each of the the kafka messages and their formats?

In some of my research around message versioning, one approach was to use a message schema validator, which ensures that messages published to Kafka conform to a pre-specified format.

**Comment by elnyry-sam-k** [comment]
hi @lewisdaly - yeah we do have an internal format following lime protocol; I think here's an example: https://docs.mojaloop.io/documentation/mojaloop-technical-overview/event-framework/#31-json-example
