### ISSUE TITLE
Produce an example version matrix

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1203]
## **Goal**:
As a `switch implementer`
I want an `example version matrix for all propsed api/service/internal versions`
so I `can understand how mojaloop supported versions will be implemented and communicated`

**Tasks**:
- [ ] TBD [ @? ]

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: TBC

**Comment by elnyry** [comment]
Presented at PI10 community event
