### ISSUE TITLE
Define backwards compatiblity strategy & scope

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1204]
## **Goal**:
As a `Hub operator`
I want to `understand how Mojaloop will manage backwards compatibility`
so that I `can plan for managing versions across participants connected to the hub`

**Tasks**:
- [ ] TBD [ @? ]

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: TBC

**Comment by lewisdaly** [comment]
I think we've covered this appropriately in the working doc, although I wonder at what point we need to think more deeply about implementation... perhaps after we've proposed the initial proposal to the DA and CCB?

**Comment by elnyry** [comment]
Presented the initial proposal at the PI10 community event. A proposal for standard regarding 'implementation' and 'deployment' versioning and version support are goals for PI-10
