### ISSUE TITLE
Documentation issue :  need to specify microk8s version 1.15 

### ISSUE THREAD

**Issue by tdaly61** [mojaloop/project#1229]
**Summary**:
In the deployment Guide/Local Setup Linux doc https://docs.mojaloop.io/documentation/deployment-guide/local-setup-linux.html need to specify version 1.15 of microk8s in the microk8s install instructions 

**Severity**:
Low

**Priority**:
Low

**Expected Behavior**
Need to update microk8s install instructions to specify v1.15 i.e. update doc to say 
`sudo snap install microk8s --classic --channel=1.15/stable  
 `

**Steps to Reproduce**
  1.
  2.
  3.

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by: Tom Daly 

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by yosheeck** [comment]
That info is already exposed at "troubleshooting": https://mojaloop.io/documentation/deployment-guide/deployment-troubleshooting.html

**Comment by elnyry** [comment]
Thanks Roman @yosheeck . @tdaly61 is this good enough you think?

**Comment by millerabel** [comment]
I think the current deployment doc, that does not specify the required max version, is misleading. If we know we must limit the max version, we should say that in the deployment doc, as @tdaly61 suggests.

I’m also noting that we don’t show the required use of sudo which is also misleading. The commands won’t succeed as written.

The goal should be to get folks past the install as smoothly as possible, not lead them quickly into the troubleshooting section!

— Miller


> On Feb 13, 2020, at 6:27 AM, Sam <notifications@github.com> wrote:
> 

﻿
Thanks Roman @yosheeck . @tdaly61 is this good enough you think?

**Comment by elnyry-sam-k** [comment]
Deployment guide updated to reflect needed changes
