### ISSUE TITLE
Create Basic Tests for Prepare Process for DFSP 1

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#124]
**Goal**:
Create Basic Tests for Prepare Process for DFSP 1
**Tasks**:
- [x] Update existing JMeter scripts to send Payment requests via the stub

**Acceptance Criteria**:
- [x] Payments are executed (on stubs/mocks for testing purposes)

**Dependencies**:
- [x] #125

**Comment by elnyry** [comment]
There were about 6 or so unplanned/ additional stories that we took up in Sprint 1.2 to deliver POCs and the requirements surrounding it (Design, Infrastructure), so a couple of stories had to be pushed out to 1.3; This is one of them.

**Comment by elnyry** [comment]
Murthy confirmed this is completed. Scripts uploaded here: https://github.com/mojaloop/test-scripts
