### ISSUE TITLE
GET - ParticipantsByTypeAndID - http code and status code wrong

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1243]
**Summary**:

1. With Malformed Type - 400 expected with 3101 error code
<img width="762" alt="Screenshot 2020-02-25 12 40 24" src="https://user-images.githubusercontent.com/53434415/75248833-d95e4400-57cc-11ea-86b0-e99ff2cc6032.png">

2. With Malformed Header - 400 expected with 3101 error code
<img width="779" alt="Screenshot 2020-02-25 12 41 45" src="https://user-images.githubusercontent.com/53434415/75248801-c64b7400-57cc-11ea-8359-1ec1ea74ce31.png">

3. With Missing Mandatory ID - 400 expected with 3102/3101 error code 
<img width="778" alt="Screenshot 2020-02-25 12 45 37" src="https://user-images.githubusercontent.com/53434415/75248788-bcc20c00-57cc-11ea-9abe-0f7a70809dab.png">

4. With Missing mandatory header - 400 expected with 3102 error code
<img width="781" alt="Screenshot 2020-02-25 12 43 59" src="https://user-images.githubusercontent.com/53434415/75248705-8b494080-57cc-11ea-83b2-795e98b30b5f.png">

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
Mentioned above

**Steps to Reproduce**
```
curl --location --request GET 'http://dev1-account-lookup.mojaloop.live/participants/XYZ/27713803912' \
--header 'Accept: application/vnd.interoperability.participants+json;version=1' \
--header 'Date: Tue, 25 Feb 2020 12:43:34 GMT' \
--header 'FSPIOP-Source: payerfsp'
```

**Specifications**
  - Component (if known):
  - Version: 8.8.0
  - Platform:
  - Subsystem:ALS
  - Type of testing: Postman
  - Bug found/raised by: @amarmodus 

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by elnyry** [comment]
Validated on `dev2`

#1 Invalid 'Type'
Request:
```
curl --location --request GET 'http://dev2-account-lookup.mojaloop.live/participants/XYZ/27713803912' \
--header 'Accept: application/vnd.interoperability.participants+json;version=1' \
--header 'Connection: keep-alive' \
--header 'Content-Type: application/vnd.interoperability.participants+json;version=1.0' \
--header 'Date: Thu, 27 Feb 2020 14:22:02 GMT' \
--header 'FSPIOP-Source: payeefsp' \
--header 'Postman-Token: 7aa4c9f3-1738-49f0-8904-7821e2336692,4127ff87-7d17-483c-8e3e-f0b562a16d84' \
--header 'User-Agent: PostmanRuntime/7.11.0' \
--header 'accept-encoding: gzip, deflate' \
--header 'cache-control: no-cache' \
--data-raw ''
```
Response code observed - 400, body:
```
{
    "errorInformation": {
        "errorCode": "3101",
        "errorDescription": "Malformed syntax - 'Type' URI path parameter"
    }
}
```

#2 With Malformed Header
Request:
```
curl --location --request GET 'http://dev2-account-lookup.mojaloop.live/participants/MSISDN/27713803912' \
--header 'Accept: xyz' \
--header 'Connection: keep-alive' \
--header 'Content-Type: application/vnd.interoperability.participants+json;version=1.0' \
--header 'Date: Thu, 27 Feb 2020 14:22:02 GMT' \
--header 'FSPIOP-Source: payeefsp' \
--header 'Postman-Token: 7aa4c9f3-1738-49f0-8904-7821e2336692,4127ff87-7d17-483c-8e3e-f0b562a16d84' \
--header 'User-Agent: PostmanRuntime/7.11.0' \
--header 'accept-encoding: gzip, deflate' \
--header 'cache-control: no-cache' \
--data-raw ''
```
Response code observed - 400, body:
```
{
    "errorInformation": {
        "errorCode": "3101",
        "errorDescription": "Malformed syntax - Invalid accept header"
    }
}
```

#3 With Missing Mandatory ID
Request:
```
curl --location --request GET 'http://dev2-account-lookup.mojaloop.live/participants/MSISDN/' \
--header 'Accept: application/vnd.interoperability.participants+json;version=1' \
--header 'Connection: keep-alive' \
--header 'Content-Type: application/vnd.interoperability.participants+json;version=1.0' \
--header 'Date: Thu, 27 Feb 2020 14:22:02 GMT' \
--header 'FSPIOP-Source: payeefsp' \
--header 'Postman-Token: 7aa4c9f3-1738-49f0-8904-7821e2336692,4127ff87-7d17-483c-8e3e-f0b562a16d84' \
--header 'User-Agent: PostmanRuntime/7.11.0' \
--header 'accept-encoding: gzip, deflate' \
--header 'cache-control: no-cache' \
--data-raw ''
```
Response code observed - 404, body:
```
{
    "errorInformation": {
        "errorCode": "3002",
        "errorDescription": "Unknown URI - Not Found"
    }
}
```

#4 With Missing mandatory header
Request:
```
curl --location --request GET 'http://dev2-account-lookup.mojaloop.live/participants/MSISDN/27713803912' \
--header 'Accept: application/vnd.interoperability.participants+json;version=1' \
--header 'Connection: keep-alive' \
--header 'Content-Type: application/vnd.interoperability.participants+json;version=1.0' \
--header 'Date: Thu, 27 Feb 2020 14:22:02 GMT' \
--header 'Postman-Token: 7aa4c9f3-1738-49f0-8904-7821e2336692,4127ff87-7d17-483c-8e3e-f0b562a16d84' \
--header 'User-Agent: PostmanRuntime/7.11.0' \
--header 'accept-encoding: gzip, deflate' \
--header 'cache-control: no-cache' \
--data-raw ''
```
Response code observed - 400, body:
```
{
    "errorInformation": {
        "errorCode": "3102",
        "errorDescription": "Missing mandatory element - fspiop-source is required"
    }
}
```

**Comment by elnyry** [comment]
@amarmodus please note that we have quoting service and transfers working the same way for missing IDs and I think we need to keep it uniform. If we need to change it, we need a new issue to change it everywhere.

I think this ready to be closed!

**Comment by amarmodus** [comment]
<img width="1278" alt="Screenshot 2020-02-28 01 13 48" src="https://user-images.githubusercontent.com/53434415/75501315-9caa6c80-59c7-11ea-9692-174e27b7d4c1.png">

GET /Participants error code issues closed - validated in Dev 2 environment
