### ISSUE TITLE
Validations of payer and payee are wrong.

### ISSUE THREAD

**Issue by agalaguz** [mojaloop/project#1247]
**Summary**:
The validation of Payee and Payer is done as a string, however, it should be an object. 
Assuming the gol of string validation was to validate `FspId` only.
`payee: Joi.string().required().min(1).max(32).description('Financial Service Provider of Payee').label('@ A valid Payee FSP number must be supplied. @'),`

**Severity**:
Low

**Priority**:
Low

**Expected Behavior**
Payer and Payee validation to be done as an object, something like this.
```
payee: Joi.object().keys({
            partyIdInfo: Joi.object().keys({
	            fspId: Joi.string().required().min(1).max(32).description('Financial Service Provider of Payee').label('@ A valid Payee FSP number must be supplied. @')
	        }).required()
          }).required()
```

**Steps to Reproduce**
  1. Open https://github.com/mojaloop/simulator/commit/7666e467d603f09a3a57669d8b2e7a2a56bc9570#diff-4607e4ce9584bfc6fdb5b8ab965a7d6c
  2. Find validation change for `POST /transactionRequests`
  3. See that `payee` and `payer` are validated as strings

Kind regards,
Anton

**Comment by elnyry** [comment]
Included in https://github.com/mojaloop/simulator/releases/tag/v9.2.4
