### ISSUE TITLE
POST - ParticipantsByTypeAndID - missing mandatory element is accepted with 202

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1249]
**Summary**:
POST - ParticipantsByTypeAndID - missing mandatory element like currency in body/data should be sent 400 http code and 

1. Missing currency in the body when sending POST 
```
curl --location --request POST 'http://dev1-account-lookup.mojaloop.live/participants/MSISDN/27713803912' \
--header 'Accept: application/vnd.interoperability.participants+json;version=1' \
--header 'Date: Sat, 29 Feb 2020 01:29:03 GMT' \
--header 'FSPIOP-Source: payerfsp' \
--header 'Content-Type: application/vnd.interoperability.participants+json;version=1.0' \
--data-raw '{
	"fspId": "payeefsp"
}'
```

2. When sending fspid with more than 32 char

```
curl --location --request POST 'http://dev1-account-lookup.mojaloop.live/participants/MSISDN/27713803912' \
--header 'Accept: application/vnd.interoperability.participants+json;version=1' \
--header 'Date: Sat, 29 Feb 2020 01:34:07 GMT' \
--header 'FSPIOP-Source: payerfsp' \
--header 'Content-Type: application/vnd.interoperability.participants+json;version=1.0' \
--data-raw '{
	"fspId": "123456789012345678901234567890123",
	"currency": "USD"
}'
```

3. When sending 0 char in fspid
```
curl --location --request POST 'http://dev1-account-lookup.mojaloop.live/participants/MSISDN/27713803912' \
--header 'Accept: application/vnd.interoperability.participants+json;version=1' \
--header 'Date: Sat, 29 Feb 2020 01:34:07 GMT' \
--header 'FSPIOP-Source: payerfsp' \
--header 'Content-Type: application/vnd.interoperability.participants+json;version=1.0' \
--data-raw '{
	"fspId": "",
	"currency": "USD"
}'
```

4. When sending multiple currency (USD , GBP, more elements in the field) - expecting 3103
```
curl --location --request POST 'http://dev1-account-lookup.mojaloop.live/participants/MSISDN/27713803912' \
--header 'Accept: application/vnd.interoperability.participants+json;version=1' \
--header 'Date: Sat, 29 Feb 2020 01:34:07 GMT' \
--header 'FSPIOP-Source: payerfsp' \
--header 'Content-Type: application/vnd.interoperability.participants+json;version=1.0' \
--data-raw '{
	"fspId": "payeefsp",
	"currency": "USD,GBP"
}'
```

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
400 http code with error code of 3101 

**Steps to Reproduce**
  1. use cURL code from above

**Specifications**
  - Component (if known):
  - Version:8.8.0
  - Platform:
  - Subsystem:ALS
  - Type of testing:Postman 
  - Bug found/raised by:@amarmodus

**Notes**:
<img width="1281" alt="Screenshot 2020-02-29 01 39 53" src="https://user-images.githubusercontent.com/53434415/75598560-74d50a80-5a94-11ea-9577-d820319a56ab.png">

- Severity when opened:
- Priority when opened:

**Comment by rmothilal** [comment]
@amarmodus @elnyry I have made fixes for issues 2, 3 and 4. I don't believe issue 1 is valid please advise

**Comment by elnyry** [comment]
@rmothilal @amarmodus - I agree about 1. 'Currency' is not a 'required' field, so that is correct

**Comment by rmothilal** [comment]
![Screenshot 2020-03-02 at 19 15 58](https://user-images.githubusercontent.com/16662558/75700172-4f294a80-5cba-11ea-91f0-58d8855207c9.png)

**Comment by elnyry** [comment]
Updated estimate as its 3 issues (and not just 1 bug)

**Comment by amarmodus** [comment]
verified in Helm release v9.2.0

Bugs 2,3,4 are valid and fixe - updated OSS API collection and assertions too.

<img width="1278" alt="Screenshot 2020-03-05 14 07 21" src="https://user-images.githubusercontent.com/53434415/75989158-aca3de00-5eea-11ea-91a3-a48f40b960df.png">
