### ISSUE TITLE
Build a secure Docker Golden Image

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1251]
## **Goal**:
Build new template image that conforms to all our container security standards for developers to build on it as a base image.

**Tasks**:
- [ ] TBD [ @? ]

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
We discussed this already. Since we are using docker build targets, there is nothing special that a golden image would give us. 

Our images at the moment are pretty much the vanilla `node:12.16.0-alpine` docker image with our code and the installed node_modules.

**Comment by godfreykutumela** [comment]
Noted and we can leave this one closed @lewisdaly
