### ISSUE TITLE
Fix automation failure test cases for v9.2.0 finance portal 

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1254]
**Summary**:
1. When checking manually(http://dev2-finance-portal.mojaloop.live/), the settlement windows does not open. 

2. Also automation test failures shows 22 step failures across different steps.

<img width="956" alt="Screenshot 2020-03-05 00 16 24" src="https://user-images.githubusercontent.com/53434415/75935725-028b6e00-5e78-11ea-8dad-4534f7be9f9a.png">

[ExtentReports helm v9.2.0.zip](https://github.com/mojaloop/project/files/4290287/ExtentReports.helm.v9.2.0.zip)

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**

**Steps to Reproduce**
  1. Follow https://github.com/mojaloop/test-scripts/tree/master/selenium readme.md
  2. Run the selenium test to replicate the result
 

**Specifications**
  - Component (if known):
  - Version: v9.2.0 (dev 2)
  - Platform:
  - Subsystem: Finance portal (Dev 2)
  - Type of testing: UI automation
  - Bug found/raised by:@amarmodus

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by amarmodus** [comment]
v10.1.0 (dev 2) test results are as follows

<img width="1669" alt="Screenshot 2020-05-11 18 08 33" src="https://user-images.githubusercontent.com/53434415/81591310-24dbc380-93b4-11ea-8e2b-da479d61d0d0.png">

**Comment by elnyry** [comment]
Here are the versions used 

```
finance-portal-ui: v9.4.0
finance-portal-backend: v9.4.5
settlement-management: v8.8.2
settlement-operator: v9.2.1
```

**Comment by Kalaston** [comment]
Hi @amarmodus 
can you try to run the failing tests locally and tell me the issues? trying to open a window manually does seem to work on my end, if this is an issue related to selenium tests, we may need to update them.

**Comment by amarmodus** [comment]
Hi @Kalaston 
Yes, manually i can see settlement window open and ok.

I can run only from dev 2 port, please find the config properties for selenium tests. please let me know if you can run. i update topaginationset alone 1+current date for the run.

```
chromedriverlocation=.\\Drivers\\windows\\chromedriver.exe
chromedriverlocationlinux=./Drivers/linux/chromedriver
chromedriverlocationmac=./Drivers/mac/chromedriver
PortalUrldev=http://dev2-finance-portal.mojaloop.live/
usernameadmindev=emerson
passwordadmindev=emerson123
usernameuserdev=emerson1F
passworduserdev=emerson1123
dev_transfers=http://dev2-ml-api-adapter.mojaloop.live/transfers
dev_quotes=http://dev2-quoting-service.mojaloop.live/quotes
dev_token=7c7bc8a6-5495-31b8-af7b-9d71b3c9f217
sim_dev=http://dev2-simulator.mojaloop.live
transferiddev=7b7a68c6-7e23-46ab-8164-fb69710abc12
getaccounturidev=http://dev2-central-ledger.mojaloop.live/participants/
#
#ccpayer_DEV=
#ccpayee_DEV=
#cctestfsp1_DEV=
#cctestfsp2_DEV=
#cctestfsp3_DEV=
#cctestfsp4_DEV=
win1_DEV=43
win2_DEV=42
next_win_DEV=4
prev_win_DEV=6
last_win_DEV=2
fileext_win=.xml
fileext_linux=
fileext_mac=.xml
testfsp4_account_dev=13
frompaginationset_DEV=2019-12-24
topaginationset_DEV=2020-05-13
```

**Comment by elnyry-sam-k** [comment]
FP version now active is v3.. outdated
