### ISSUE TITLE
email notifications not received on mowali deployment

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#1267]
**Summary**:
The emails for limit adjustment and ndc breach are not delivered

**Severity**:
High

**Priority**:
Meiduim

**Expected Behavior**
Mails are delivered for the events when they are generated, according rules.

**Steps to Reproduce**
  1. Deploy central-event-processor and email-notifier services as part of the backend services
  2. set email addresses for fsps and hub operator
  3. adjust limit or reach ndc limit threshold

**Specifications**
  - Component (if known): central-event-processor, email-notifier
  - Version: 9.2.0 & 9.2.2 
  - Type of testing: functional
  - Bug found/raised by: @Kalaston 

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by vgenev** [comment]
fixed:
* https://github.com/mojaloop/central-event-processor/pull/165
* https://github.com/mojaloop/email-notifier/pull/138

**Comment by elnyry** [comment]
Thanks @vgenev
