### ISSUE TITLE
Benchmark our open source license management tool against commercial tools

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1269]
## **Goal**:
This benchmark is specific to NPM license audit package and for commercial I recommend Blackduck

**Tasks**:
- [ ] TBD [ @? ]

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry** [comment]
@godfreykutumela - is this still blocked? Please review and move to an appropriate pipeline
