### ISSUE TITLE
Benchmark our static code analysis tool against commercial tools

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1270]
## **Goal**:
This is specific to sonarcube against checkmarx .

**Tasks**:
- [ ] TBD [ @? ]

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry** [comment]
@godfreykutumela - is this still blocked? Please review and move to an appropriate pipeline

**Comment by godfreykutumela** [comment]
Still blocked for this PI
