### ISSUE TITLE
Quote rejection by Payee FSP not forwarded to Payer FSP

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#1276]
**Summary**:
While rejecting a quote from the Payee FSP side with the below request, rejection notification was not forwarded to the Payer FSP.

Request:
- Endpoint: 
    `PUT /quotes/cd708dbb-293c-46d1-831d-f60a358d7d20/error`
 - Headers:
```
{
"connection" :["0" :"close"],
"content-length" :["0" :"63"],
"content-type" :["0" :"application/vnd.interoperability.quotes+json;version=1.0"],
"date" :["0" :"Mon, 23 Mar 2020 12:28:57 GMT"],
"fspiop-destination" :["0" :"{"signature":"iU4GBXSfY8twZMj1zXX1CTe3LDO8Zvgui53icrriBxCUF_wltQmnjgWLWI4ZUEueVeOeTbDPBZazpBWYvBYpl5WJSUoXi14nVlangcsmu2vYkQUPmHtjOW-yb2ng6_aPfwd7oHLWrWzcsjTF-S4dW7GZRPHEbY_qCOhEwmmMOnE1FWF1OLvP0dM0r4y7FlnrZNhmuVIFhk_pMbEC44rtQmMFv4pm4EVGqmIm3eyXz0GkX8q_O1kGBoyIeV_P6RRcZ0nL6YUVMhPFSLJo6CIhL2zPm54Qdl2nVzDFWn_shVyV0Cl5vpcMJxJ--O_Zcbmpv6lxqDdygTC782Ob3CNMvg\",\"protectedHeader\":\"eyJhbGciOiJSUzI1NiIsIkZTUElPUC1VUkkiOiIvdHJhbnNmZXJzIiwiRlNQSU9QLUhUVFAtTWV0aG9kIjoiUE9TVCIsIkZTUElPUC1Tb3VyY2UiOiJPTUwiLCJGU1BJT1AtRGVzdGluYXRpb24iOiJNVE5Nb2JpbGVNb25leSIsIkRhdGUiOiIifQ"}"],
"fspiop-source" :["0" :"developpayeefsp"],
"host" :["0" :"mojaloop.s9.jc"],
"traceparent" :["0" :"00-2a7b0938b73244758ea13c468a543819-2a9ad549a521adca-30"],
"user-agent" :["0" :"GuzzleHttp/6.5.1 curl/7.64.0 PHP/7.4.1"],
"x-forwarded-for" :["0" :"10.10.69.3"],
"x-forwarded-proto" :["0" :"http"],
"x-real-ip" :["0" :"10.10.69.3"]
}
```
- Body:
```JSON
{ "errorInformation" :{ "errorCode" :"5103", "errorDescription" :"" } } 
```

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
- Payer FSP should receive a quote rejection callback

**Steps to Reproduce**
  1.
  2.
  3.

**Specifications**
  - Component (if known):
  - Version: 8.8.0
  - Platform:
  - Subsystem: Quoting Service
  - Type of testing:
  - Bug found/raised by: **Anton Galaguz** via [Slack](https://mojaloop.slack.com/archives/CPT4BK49X/p1584970606086800)

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by oderayi** [comment]
## Update as tested in the current version of QS (v9.4.0-snapshot) ##
- The error endpoint for quotes requires `errorDescription` to be specified in the `errorInformation` object. Empty `errorDescription` is not permitted.
- fspiop-destination as specified in the error report does not appear to be valid:
  `"fspiop-destination" :["0" :"{"signature":"iU4GBXSfY8twZMj1zXX1CTe3LDO8Zvgui53icrriBxCUF_wltQmnjgWLWI4ZUEueVeOeTbDPBZazpBWYvBYpl5WJSUoXi14nVlangcsmu2vYkQUPmHtjOW-yb2ng6_aPfwd7oHLWrWzcsjTF-S4dW7GZRPHEbY_qCOhEwmmMOnE1FWF1OLvP0dM0r4y7FlnrZNhmuVIFhk_pMbEC44rtQmMFv4pm4EVGqmIm3eyXz0GkX8q_O1kGBoyIeV_P6RRcZ0nL6YUVMhPFSLJo6CIhL2zPm54Qdl2nVzDFWn_shVyV0Cl5vpcMJxJ--O_Zcbmpv6lxqDdygTC782Ob3CNMvg\",\"protectedHeader\":\"eyJhbGciOiJSUzI1NiIsIkZTUElPUC1VUkkiOiIvdHJhbnNmZXJzIiwiRlNQSU9QLUhUVFAtTWV0aG9kIjoiUE9TVCIsIkZTUElPUC1Tb3VyY2UiOiJPTUwiLCJGU1BJT1AtRGVzdGluYXRpb24iOiJNVE5Nb2JpbGVNb25leSIsIkRhdGUiOiIifQ"}"],`
- The error endpoint will also fail if the quote does not already exist in the switch i.e POST /quote that generates the quoteId must have succeeded before the error callback can be successful

**Comment by elnyry** [comment]
@oderayi thanks for the observations. Can you also please confirm the behavior in valid scenarios, i.e., both required fields are included with valid headers, is the relaying of the error message happening as expected?

Items #1 and #2 look good, I'm not sure about #3 since in pass through mode, the Switch wouldn't store anything, so I think we should just let the error message through..

**Comment by oderayi** [comment]
@elnyry Correct, with pass through the error callback is relayed correctly.

**Comment by elnyry** [comment]
Thanks @oderayi - we can close this one then..
