### ISSUE TITLE
GET,PUT /authorizations - fix http status and error status code

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1285]
**Summary**:

Following authorizations request fix for http status and error code.

- [ ]  ~1. POST /authorizations - this should give 405 status code as it is unsupported HTTP method~tg [@oderayi] --> needs new story to handle this scenario uniformly on all the resources.
   > Requires further investigation and brainstorming [@rmothilal]
- [ ] 2. GET / authorizations/{ID} [@oderayi]
    - [x] a. With date header missing - currently 202 - expected - 400 with appropriate 3102 code
    - [x] b. With fspiop-source  header missing - currently 202 - expected - 400 with appropriate 3102 code
    - [x] c. With ID missing - currently 404 - expected - 400 with appropriate 3xxx code
    > 404 seems correct here.
    - [x] d. With Content-Type missing/wrong - currently 202 - expected - 400 with appropriate 3102 code
    - [x] e. With accept header missing - currently 202 - expected - 400 with appropriate 3102 code
    - [x] f.  With retriesLeft/amount/authenticationType/currency missing(query parameter)  - currently 3100 - more appropriate - 3102 (missing mandatory element)
    - [ ] ~g. With wrong retriesLeft(floating number instead of integer), currently 3100 - more appropriate - 3101(Malformed syntax) ~
    - [x] h. wrong authentication type (instead of OTP or QRCODE), currently 3100 - more appropriate - 3101(Malformed syntax)
 
3. PUT / authorizations
    - [x] a. With date header missing - currently 200 - expected - 400 with 3102 code
    - [x] b. With fspiop-source  header missing - currently 200 - expected - 400 with 3102 code
    - [x] c. With Content-Type missing/wrong - currently 200 - expected - 400 with 3102 code
      > `Content-Type` header needs to be:
      > application/vnd.interoperability.authorizations+json;version=1.0
    - [x] d. With accept header missing - currently 200 - expected - 400 with 3102 code
      > `Accept` header needs to be: application/vnd.interoperability.authorizations+json;version=1
    - [x] e. With authentication/authenticationValue/authenticationType/responseType - missing(data)  - currently 3100 - more appropriate - 3102 (missing mandatory element)
    - [ ] ~f. With extra data member("authenticationValue1": "234567")  - currently 3100 - more appropriate - 3103 (Too many elements)~

**Severity**:
Medium

**Priority**:
Low

**Expected Behavior**
In summary

**Steps to Reproduce**

1. POST /Authorizations
```
curl --location --request POST 'http://dev1-transaction-requests-service.mojaloop.live/authorizations/' \
--header 'Accept: application/vnd.interoperability.transactionRequests+json;version=1' \
--header 'Content-Type: application/vnd.interoperability.transactionRequests+json;version=1.0' \
--header 'Date: Thu, 02 Apr 2020 23:32:13 GMT' \
--header 'fspiop-source: payerfsp' \
--header 'fspiop-destination: payeefsp'
```

2. GET /authorizations/{ID}
```
curl --location --request GET 'http://dev1-transaction-requests-service.mojaloop.live/authorizations/e5d71e6b-c5c1-419d-83e8-a5868a912958?authenticationType=OTP&retriesLeft=2&amount=102&currency=USD' \
--header 'Accept: application/vnd.interoperability.transactionRequests+json;version=1' \
--header 'Content-Type: application/vnd.interoperability.transactionRequests+json;version=1.0' \
--header 'Date: Thu, 02 Apr 2020 23:33:11 GMT' \
--header 'fspiop-source: payerfsp'
```
remove header accordingly

3. PUT /authorizations/
curl --location --request PUT 'http://dev1-transaction-requests-service.mojaloop.live/authorizations/4e2c9738-c607-4e18-99cd-301caec8bcd4' \
--header 'Accept: application/vnd.interoperability.transactionRequests+json;version=1' \
--header 'Content-Type: application/vnd.interoperability.transactionRequests+json;version=1.0' \
--header 'Date: Mon, 06 Apr 2020 10:42:24 GMT' \
--header 'fspiop-source: payeefsp' \
--header 'fspiop-destination: payerfsp' \
--header 'Content-Type: text/plain' \
--data-raw '{
  "authenticationInfo": {
    "authentication": "OTP",
    "authentication
 ": "234567"
  },
  "responseType": "REJECTED"
}'

**Specifications**
  - Component (if known):
  - Version: Helm v9.2.0
  - Platform:
  - Subsystem: authorizations
  - Type of testing: postman
  - Bug found/raised by: @amarmodus 

**Notes**:

- Severity when opened:
- Priority when opened:

## Pull Requests ##
- [x] https://github.com/mojaloop/transaction-requests-service/pull/30
- [x] https://github.com/mojaloop/central-services-shared/pull/209

**Comment by oderayi** [comment]
1. No-repro with v9.4.2
  > Response code: 404 Not Found
  > Response body:
```
  {
    "errorInformation": {
        "errorCode": "3002",
        "errorDescription": "Unknown URI - Not Found"
    }
}
  ```

**Comment by amarmodus** [comment]
Updated similar set of observation for PUT/ request too. @oderayi

**Comment by elnyry** [comment]
@amarmodus I think we need to validate this same issue for other resources (quotes, transfers) whether we're seeing 405 or not, in case you haven't already done that..

**Comment by oderayi** [comment]
@rmothilal @elnyry @amarmodus As a fallout of discussion with Rajiv, this story will now be blocked for further investigation regarding 405 response code implementation. Some sort of route white-listing might be required.

**Comment by elnyry** [comment]
Thanks @oderayi . We need a new issue to handle the scenario for HTTP 405 uniformly across resources..

**Comment by amarmodus** [comment]
https://github.com/mojaloop/project/issues/1314 - a followup issue created for validation of this task, and bugs yet to be fixed. @oderayi & @elnyry

**Comment by elnyry** [comment]
Follow-up item #1314
