### ISSUE TITLE
Fix OSS Helm release v9.2.0 for GP collection failures

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1288]
**Summary**:
OSS Helm release v9.2.0 got 40+ failures(Mostly settlements related) in latest GP regression run.

<img width="1602" alt="Screenshot 2020-04-06 23 07 48" src="https://user-images.githubusercontent.com/53434415/78610436-bcea0880-785c-11ea-898e-98f019de1239.png">

**Severity**:
High

**Priority**:
Critical

**Expected Behavior**
GP collection pass with nil failures.

**Steps to Reproduce**
  1. Deploy OSS Helm v9.2.0 default and run the GP collection.

**Specifications**
  - Component (if known):
  - Version:Helm v9.2.0
  - Platform:
  - Subsystem:
  - Type of testing:Regression GP Collectiong
  - Bug found/raised by:@amarmodus

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by elnyry** [comment]
Being addressed in #1323
