### ISSUE TITLE
[CI-CD DevOps] : CI/CD & Kubernetes

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#13]
**Goal**:
Ensure best practises are always adhered to by employing a seamless development path and making sure all code goes through extensive testing cycles, peer reviews and regression testing. Put the design in place and implement the continual integration and continual deployment processes to streamline development, testing and delivery.

**Dependencies**:
- None currently

**Comment by elnyry** [comment]
Stories part of this Epic closed and this has been open for quite a while, so closing it for now. New topics/features identified will need new Epics to stay up to date
