### ISSUE TITLE
End to End Review of the OSS On-Boarding Process - Tools, Process and Documentation

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1307]
## **Goal**:

Investigate the current OSS on-boarding process, identify major problems and improvement areas, explore various solution options and adopt a solution framework on which feasible solutions will be based on.

**Tasks**:
- [ ] TBD [ @? ]

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Review done, created a story here with next steps, gaps to be addressed: https://github.com/mojaloop/project/issues/2453
