### ISSUE TITLE
Security Vulnerabilities - https://github.com/moment/moment

### ISSUE THREAD

**Issue by kjw000** [mojaloop/project#131]
Several repo's have code with a dependency on https://github.com/moment/moment 
Versions before 2.19.3  (we are using 2.18.1) for Node.js is prone to a regular expression denial of service via a crafted date str.

Recommend to upgrade.

The following repos are impacted:
https://github.com/mojaloop/mock-pathfinder/network/dependencies
https://github.com/mojaloop/central-directory/network/dependencies
https://github.com/mojaloop/central-ledger/network/dependencies
https://github.com/mojaloop/forensic-logging-sidecar/network/dependencies

**Comment by elnyry** [comment]
Discussed this with the team on March 22nd and it looks like this is fixed on the develop branch. Will close this out when master is updated as well.

**Comment by elnyry** [comment]
Done for central-ledger. Will use #292 to track the others
