### ISSUE TITLE
Unable to start the interop mule services

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#132]
User yzaki16 has an issue:
_"I m unable to start the interop mule services. Can any 1 guide me for it.
I places the interop app in mule/app folder and start the mule... it showing mule-config.xml not found."_

**Comment by elnyry** [comment]
Hi yzaki16, I think we'll need more details here. To start with, can you please state what you are trying to do and the steps you followed? (Example: Trying to run the Mojaloop system locally, followed steps in a particular link etc). 

Having said all that, I want to know if you deployed the domain (interop-domain) before deploying the apps; Also need to make sure that the default wrapper.conf in /conf under MULE_HOME is over-written with the one provided in interop-devops and also place mule-l1p.properties file there (if it was not copied there by the Ansible scripts)?

**Comment by yzaki16** [comment]
@elnyry Thanks for the support. I dont know the exact process of deploying the interop services.. Im just following the mojaloop documentation although its not step by step by I get some success to configure the dfsp machines... now I need to connect it with IST through interop services.
if u have any linked which can guide me through the process let me know.

**Comment by elnyry** [comment]
Just to make sure, is [this](https://github.com/mojaloop/interop-devops/blob/develop/README.md) the link you used for setup? (Please note that these instructions currently apply to mac/linux only). There's also a video linked in that doc, please take a look.

**Comment by yzaki16** [comment]
@elnyry im following the same, but didnt check the video.

Video link unable to access, giving error on drop box ...The folder ‘/Level One OSS Team Share/Phas...’ doesn’t exist.

**Comment by yzaki16** [comment]
@elnyry : can I get ur contact details... so we can discuss better in quick manner.

Also, Im sharing with you what I did...

I setup 4 VM machines as shared by you.

then on dfsp1, I downloaded all the components having prefix dfsp- <component_name>, all these are node js components and run quiet nicely working fine. I can access them from USSD simulator (dfsp-ussd)
also create dfsp2 same like it.

Now I want to setup interop and central services so I can make the transaction from dfsp1 to dfsp2

**Comment by elnyry** [comment]
Ok, sure my e-mail is "sam at modusbox dot com", I'll delete this once you send me an email.. I'll share the setup video privately as well for now and think of a good public location for it soon.

**Comment by yzaki16** [comment]
Thanks for the support, waiting for Video link

**Comment by elnyry** [comment]
Resolved over e-mails. Confirmed as 'known memory limitation' related issue. yzaki16 will try it out on the tested and recommended configuration and will get back.
