### ISSUE TITLE
Authorizations endpoint not included in Setup FSPs postman script

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#1337]
**Summary**:
There is a issue with the postman collection when we create FSP data/endpoints, there needs to be an endpoint for authorizations with the type as FSPIOP_CALLBACK_URL_AUTHORIZATIONS we also need to add this to the seeds file for endpointType table in central-ledger

**Severity**:
Medium

**Priority**:
Critical

**Expected Behavior**
When the authorizations endpoint is called in the transaction-request-service the request should be forwarded to the correct endpoint

**Steps to Reproduce**
  1. call the put autorizations/{ID} 
  2. error should be thrown with regards to invalid template
 
**Specifications**
  - Component (if known): postman repo and central-ledger
  - Version: 10.1.0
  - Platform:
  - Subsystem:
  - Type of testing: regression
  - Bug found/raised by: @mdebarros @rmothilal 

**Notes**:

- Severity when opened: Medium
- Priority when opened: Critical

**Comment by mdebarros** [comment]
This issue is fixed with https://github.com/mojaloop/postman/pull/109
