### ISSUE TITLE
Ansible script for Rancher/Kubernetes etc

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#134]
Ansible script for Rancher which can then be used to setup Kubernetes etc

Need to fill-out the details for this: Creating this based on Miller's requests during Sprint 1.2 demo session.

**Comment by lewisdaly** [comment]
@elnyry is this one still relevant? Or is it a little outdated now?

**Comment by elnyry** [comment]
yeah, I think so.. and this can be covered as part of IaC or other stuff..
