### ISSUE TITLE
PAYEE flag disables notification to PAYER

### ISSUE THREAD

**Issue by Dorota-MB** [mojaloop/project#1381]
**Summary**:
SEND_TRANSFER_CONFIRMATION_TO_PAYEE flag controls also sending final notification to PAYER in certain scenarios, for example 1. on timeout and 2. on invalid fulfillment. Therefore disabling this flag for PAYEE disables also notification to PAYER in those scenarios.

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
When I run a scenario where the transfer will be timed out in Central ledger and thus the notification needs to be sent to sender FSP and receiver FSP. I see it is timed out in Central ledger timeout handler as per the attached logs, but the notification not reached either Payer or Payee FSPs.
1. Run quotes request
2. Run transfers request (prepare)
3. As configured, the receiver FSP will not respond to this POST /transfers request
4. Hence it should be timed out in Central ledger as per transfer expiration sent from sender FSP + CL timeout time (which is 60+15 sec)
5. Payer FSP should be receiving this notification of this transfer ABORTED due to expired
6. Payee FSP should be receiving this notification of this transfer ABORTED due to expired.

**Steps to Reproduce**
1. Run Quotes request
2. Run Transfers request (POST for prepare)
3. As configured, the receiver FSP will not respond to this POST /transfers request
4. Hence it should be timed out in Central ledger as per transfer expiration sent from Payer FSP + CL timeout time (which is 60+15 sec)
5. Payer FSP did not receive any response from switch
6. Payee FSP did not receive any response from switch

**Specifications**
  - Component (if known): central services
  - Version: 
  - Platform: Azure
  - Subsystem: notifications?
  - Type of testing: 
  - Bug found/raised by: Sridevi Miriyala

**Notes**:
Logs:
```
[mowbkd-centralledger-handler-timeout-68b549b45b-jv95x centralledger-handler-timeout] "FSPIOP-Destination": "testfsp3"
[mowbkd-centralledger-handler-timeout-68b549b45b-jv95x centralledger-handler-timeout] "Content-Type": "application/vnd.interoperability.transfers+json;version=1.0"
[mowbkd-centralledger-handler-timeout-68b549b45b-jv95x centralledger-handler-timeout] "Date": "Thu, 30 Apr 2020 13:19:30 GMT"
[mowbkd-centralledger-handler-timeout-68b549b45b-jv95x centralledger-handler-timeout] "FSPIOP-Source": "switch"
[mowbkd-centralledger-handler-timeout-68b549b45b-jv95x centralledger-handler-timeout] }
[mowbkd-centralledger-handler-timeout-68b549b45b-jv95x centralledger-handler-timeout] "payload": {
[mowbkd-centralledger-handler-timeout-68b549b45b-jv95x centralledger-handler-timeout] "errorInformation": {
[mowbkd-centralledger-handler-timeout-68b549b45b-jv95x centralledger-handler-timeout] "errorCode": "3303",
[mowbkd-centralledger-handler-timeout-68b549b45b-jv95x centralledger-handler-timeout] "errorDescription": "Transfer expired"
[mowbkd-centralledger-handler-timeout-68b549b45b-jv95x centralledger-handler-timeout] }[mowbkd-centralledger-handler-timeout-68b549b45b-jv95x centralledger-handler-timeout] }[mowbkd-centralledger-handler-timeout-68b549b45b-jv95x centralledger-handler-timeout] },[mowbkd-centralledger-handler-timeout-68b549b45b-jv95x centralledger-handler-timeout] "metadata": {
[mowbkd-centralledger-handler-timeout-68b549b45b-jv95x centralledger-handler-timeout] "correlationId": "dd72c7c2-0898-4019-bcd5-3f3887390f10",
[mowbkd-centralledger-handler-timeout-68b549b45b-jv95x centralledger-handler-timeout] "event": {
[mowbkd-centralledger-handler-timeout-68b549b45b-jv95x centralledger-handler-timeout] "type": "notification",
[mowbkd-centralledger-handler-timeout-68b549b45b-jv95x centralledger-handler-timeout] "action": "timeout-received",
[mowbkd-centralledger-handler-timeout-68b549b45b-jv95x centralledger-handler-timeout] "createdAt": "2020-04-30T13:19:30.202Z",
[mowbkd-centralledger-handler-timeout-68b549b45b-jv95x centralledger-handler-timeout] "state": {
[mowbkd-centralledger-handler-timeout-68b549b45b-jv95x centralledger-handler-timeout] "status": "error",
[mowbkd-centralledger-handler-timeout-68b549b45b-jv95x centralledger-handler-timeout] "code": "3303",
[mowbkd-centralledger-handler-timeout-68b549b45b-jv95x centralledger-handler-timeout] "description": "Transfer expired"
[mowbkd-centralledger-handler-timeout-68b549b45b-jv95x centralledger-handler-timeout] }[mowbkd-centralledger-handler-timeout-68b549b45b-jv95x centralledger-handler-timeout] }[mowbkd-centralledger-handler-timeout-68b549b45b-jv95x centralledger-handler-timeout] }
```
- Severity when opened:
- Priority when opened:
[investigate-5073.pdf](https://github.com/mojaloop/project/files/4664460/investigate-5073.pdf)

## Pull Requests ##
- [x] https://github.com/mojaloop/ml-api-adapter/pull/436
- [x] https://github.com/mojaloop/central-ledger/pull/736
- [x] https://github.com/mojaloop/central-services-shared/pull/227

**Comment by elnyry** [comment]
@Dorota-MB - I made some changes to the issue, can you please provide the version details please, so that we can attempt a repro?

**Comment by Dorota-MB** [comment]
@sri-miriyala can you please update the issue as per Sam's request?

**Comment by sri-miriyala** [comment]
@elnyry-sam-k @oderayi  did you get enough information on this? Which release it is fixed?
