### ISSUE TITLE
/participants/{name}/accounts URI has become case-sensitive

### ISSUE THREAD

**Issue by shashi165** [mojaloop/project#1384]
**Summary**:
`/participants/{name}/accounts` URI has become case-sensitive in the latest version of central-ledger
In the earlier versions prior to v9.2.0 it was case-insensitive

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
For the participant `Hub`
earlier the URIs ` GET /participants/hub/accounts` and `GET /participants/Hub/accounts`, both used to work.
In the latest version of central-ledger(v10.1.0) 
The URI  ` GET /participants/hub/accounts`  no longer works, only  ` GET /participants/Hub/accounts`  works

**Steps to Reproduce**
  1. deploy older version of central-ledger (v8.8.0) and test that both the above mentioned URIs work
  2. deploy the latest version of central-ledger (v10.1.0) and test both the URIs -
  

**Specifications**
  - Component (if known): central-ledger
  - Version: v10.1.0
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by: @shashi165 

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by elnyry** [comment]
Updated helm release notes to call this out as a breaking change - https://github.com/mojaloop/helm/releases/tag/v10.1.0
