### ISSUE TITLE
Fix Post/ Quotes header destination or source and payload payee validation 

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1385]
**Summary**:
When Post/Quotes sent with correct header and wrong fspid in payload, then the headers not used for ALS routing and also validation between header value & Payload value missing

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
1. it should be validating the headers against the payload to ensure that its a valid quote
2. headers not used for routing

**Steps to Reproduce**
  1. Post a quote with destination and payload with different payeefsp
  2. callback fails

```
curl --location --request POST 'http://dev2-quoting-service.mojaloop.live/quotes' \
--header 'Accept: application/vnd.interoperability.quotes+json;version=1' \
--header 'Content-Type: application/vnd.interoperability.quotes+json;version=1.0' \
--header 'Date: Fri, 21 Dec 2018 12:19:49 GMT' \
--header 'FSPIOP-Source: payerfsp' \
--header 'FSPIOP-Destination: payeefsp' \
--header 'FSPIOP-Signature: {"signature":"iU4GBXSfY8twZMj1zXX1CTe3LDO8Zvgui53icrriBxCUF_wltQmnjgWLWI4ZUEueVeOeTbDPBZazpBWYvBYpl5WJSUoXi14nVlangcsmu2vYkQUPmHtjOW-yb2ng6_aPfwd7oHLWrWzcsjTF-S4dW7GZRPHEbY_qCOhEwmmMOnE1FWF1OLvP0dM0r4y7FlnrZNhmuVIFhk_pMbEC44rtQmMFv4pm4EVGqmIm3eyXz0GkX8q_O1kGBoyIeV_P6RRcZ0nL6YUVMhPFSLJo6CIhL2zPm54Qdl2nVzDFWn_shVyV0Cl5vpcMJxJ--O_Zcbmpv6lxqDdygTC782Ob3CNMvg\",\"protectedHeader\":\"eyJhbGciOiJSUzI1NiIsIkZTUElPUC1VUkkiOiIvdHJhbnNmZXJzIiwiRlNQSU9QLUhUVFAtTWV0aG9kIjoiUE9TVCIsIkZTUElPUC1Tb3VyY2UiOiJPTUwiLCJGU1BJT1AtRGVzdGluYXRpb24iOiJNVE5Nb2JpbGVNb25leSIsIkRhdGUiOiIifQ"}' \
--header 'FSPIOP-HTTP-Method: POST' \
--header 'FSPIOP-URI: /quotes' \
--header 'Authorization: Bearer 1180cb0d-fcb9-47db-a901-1aef931415cc' \
--header 'Content-Type: text/plain' \
--data-raw '{{quoteRequest}}'
```

**PR**
- [ ] https://github.com/mojaloop/quoting-service/pull/248

**Specifications**
  - Component (if known):
  - Version: 10.1.0
  - Platform:
  - Subsystem:
  - Type of testing: Manual testing
  - Bug found/raised by: @amarmodus, @mdebarros 

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by elnyry** [comment]
hey @amarmodus - the routing should happen based on the headers, but the validation (with the values in the message body) part - we'll need to skip that one, to allow several extension use cases..

**Comment by shashi165** [comment]
Hi @elnyry-sam-k 
On the dev env we have `"SIMPLE_ROUTING_MODE": false` so the quote request will be logged in the database and routing is as below
1. When you send a quote request with invalid payer/payee name in the payload, then the database query fails and we get error. 
2. If you send a request with valid payer/payee in the payload then request is routed using the endpoints for the payer/payee specified in the payload. https://github.com/mojaloop/quoting-service/blob/9ac9910c9ca0d5951abee30397ab74bdc86e170d/src/model/quotes.js#L379-L383


If we have `"SIMPLE_ROUTING_MODE": true` then the routing is
1. When you send a quote request with invalid payer/payee name in the payload, then there is no validation and requested is routed to the endpoints for the source/destination specified in the headers.
2. When you send a quote request with valid payer/payee name in the payload, then the requested is routed to the endpoints for the source/destination specified in the headers.

**Comment by mdebarros** [comment]
> * When you send a quote request with invalid payer/payee name in the payload, then there is no validation and requested is routed to the endpoints for the source/destination specified in the headers.

Would this not result in a further error if there is no payee(request)/payer(response) that matches the routing headers? 

I.e. there should be no URLs to route the request too.

**Comment by elnyry-sam-k** [comment]
Thanks @shashi165 , @mdebarros 

Here's what I think:
1. For both modes of routing - we need to validate that Payer and Payee FSPs exist for both the values in the headers and the body/payload.
2. When `SIMPLE_ROUTING_MODE` is false, we still need to use the headers for routing - but lets discuss this to account for how current implementations may be using this.

**Comment by shashi165** [comment]
> > * When you send a quote request with invalid payer/payee name in the payload, then there is no validation and requested is routed to the endpoints for the source/destination specified in the headers.
> 
> Would this not result in a further error if there is no payee(request)/payer(response) that matches the routing headers?
> 
> I.e. there should be no URLs to route the request too.

Yes, it will fail at some point.
