### ISSUE TITLE
QA - Validate/test bugfix #737

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1392]
## **Goal**:
As a maintainer of the OSS codebase, QA 
I want to make sure that new releases are checked for regressions
so that releases are validated before being accepted or released to the public

This specific story is for writing regression postman tests for bugs  #737
so that it confirms the bugs are fixed

**Tasks**:
- [ ] Tests for https://github.com/mojaloop/project/issues/737 [ @? ]
  - [ ] Validate

**Acceptance Criteria**:
- [ ] Regression tests in postman are available for bugs:
  - [ ] #737 

## **Pull Requests**:
- [ ] 

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: 
- QA/Review:

**Comment by elnyry-sam-k** [comment]
This should now be covered by the MojaSim collection that was used to validate v10.4.0
