### ISSUE TITLE
[CI-CD DevOps] : Core System - Performance and Scalability

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#14]
**Goal**:
All efforts from a database point of view should have been taken care of as far as performance and scalability is concerned, At this point, take care of these factors at code level by considering microservices, refactoring and parallel processing and implement those designs in the code base.

**Dependencies**:
- None currently

**Comment by elnyry** [comment]
Stories part of this Epic closed and this has been open for quite a while, so closing it for now. New topics/features identified will need new Epics to stay up to date
