### ISSUE TITLE
Investigate and Propose developer best practices for a multi-versioned world

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1402]
## **Goal**:
As an OSS Developer, I want to better understand how my code changes will impact end users so I can ensure I am writing code in a backwards-compatible manner.

So far we have discussed:
- feature switches and libraries to manage them
- automated changelogs

**Tasks**:
- [ ] TBD [ @? ]

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Ideally, we could get a running changelog of breaking changes (and I suppose features) hub operators need to be aware of for each given release, all compiled nicely in the helm release notes.

**Comment by lewisdaly** [comment]
So we've been starting some discussions and testing out using conventional commit messages, combined with the `standard-version` npm package to:
1. Generate new version numbers
2. Auto-generate a changelog
3. Perform a release automatically

**Comment by elnyry-sam-k** [comment]
@lewisdaly can we close this now - as automated releases are supported on some repos?

**Comment by lewisdaly** [comment]
Sure.
