### ISSUE TITLE
QA: not validating a received transfer with an expiration date in the past

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1416]
**Summary**:
receives a transfer with an expiration date in the past, but the validation is not working

This is the testing ticket for https://github.com/mojaloop/central-ledger/issues/678

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**

**Steps to Reproduce**
  1. Send a quote 
  2. Send a transfer with the expiration 10 minutes ago
  3. the transfer reaches the payee simulator despite the transfer is expired

**Specifications**
  - Component (if known): central-ledger
  - Version: v8.7.1 / verified with OSS team version: v9.3.0
  - Platform: N/A
  - Subsystem: N/A
  - Type of testing: manual
  - Bug found/raised by: @chinogarcia

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by amarmodus** [comment]
tested with postman and fix confirmed with central-ledger:v10.3.0. 

<img width="1487" alt="Screenshot 2020-06-03 10 55 44" src="https://user-images.githubusercontent.com/53434415/83626449-5861d600-a58d-11ea-9afd-17b7c5b3bb54.png">

**Comment by elnyry** [comment]
Thanks @amarmodus - thats great!
