### ISSUE TITLE
Fix golden path regression test failures in dev 2

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#1428]
**Summary**:
 
Duplicate quotes and duplicate transfers are failing in current dev 2 golden path regression test.
There are are other failures in send quotes and sent transfers.

![image](https://user-images.githubusercontent.com/53434415/84150998-96ae3800-aa5a-11ea-89ef-bba618551880.png)

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**

**Steps to Reproduce**
  1. Run OSS-New-Deployment-FSP-Setup to deployed dev 2 
  2. Run the golden path regression test 

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing: regression Golden path test
  - Bug found/raised by:@amarmodus

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by amarmodus** [comment]
1) Duplicate transfer : 

For a duplicate transfer, the callback sends fsip-source as payeefsp. expected is 'switch'

```
{"headers":{"x-forwarded-for":"10.1.2.146","content-type":"application/vnd.interoperability.transfers+json;version=1.0","fspiop-source":"payeefsp","fspiop-destination":"payerfsp","date":"2020-06-09T14:44:03.000Z"
```

**Comment by elnyry-sam-k** [comment]
Thanks Amar

**Comment by amarmodus** [comment]
Block transfer failure test cases : 
No call back response for the following transfer calls/
```
GET http://dev2-simulator.mojaloop.live/payerfsp/correlationid/69a5ab7e-d0f6-43c2-9ed1-da4b0b20c103

and 

GET http://dev2-simulator.mojaloop.live/payerfsp/callbacks/69a5ab7e-d0f6-43c2-9ed1-da4b0b20c103

```

**Comment by amarmodus** [comment]
duplicate quote failure case:

1. Send a quote
2. Again send the same quote as duplicate id. 

no error thrown for duplicate quote id.

**Comment by amarmodus** [comment]
send Quote - destination FSP not found, for following request, no response given.
```
curl --location --request POST 'http://dev1-quoting-service.mojaloop.live/quotes' \
--header 'Authorization: Bearer {{TESTFSP1_BEARER_TOKEN}}' \
--header 'Content-Type: application/json' \
--data-raw '{
  "quoteId": "c0e04720-6e09-41b5-aad6-9001627df874",
  "transactionId": "ef73a8b1-085e-4798-865a-a5f713cb329d",
  "payer": {
    "partyIdInfo": {
      "partyIdType": "MSISDN",
      "partyIdentifier": "{{payerMSISDN}}",
      "fspId": "payerfsp"
    },
    "personalInfo": {
      "complexName": {
        "firstName": "Mats",
        "lastName": "Hagman"
      },
      "dateOfBirth": "1983-10-25"
    }
  },
  "payee": {
    "partyIdInfo": {
      "partyIdType": "MSISDN",
      "partyIdentifier": "23123123412",
      "fspId": "payeefspNOTFOUND"
    }
  },
  "amountType": "SEND",
  "amount": {
    "amount": "60.11",
    "currency": "USD"
  },
  "transactionType": {
    "scenario": "TRANSFER",
    "initiator": "PAYER",
    "initiatorType": "CONSUMER"
  },
  "note": "hej"
}'
```


see Send Quote_SEND - 9- Destination FSP NOT FOUND in GP collection.

**Comment by vijayg10** [comment]
I tested with the latest helm master and couldn't find any of these errors. Everything is working fine with helm master branch. It might resolved due to the recent central-ledger upgrade, not sure.

**Comment by elnyry-sam-k** [comment]
Thanks @vijayg10
