### ISSUE TITLE
SettlementModel required error even after providing the settlement model in the request

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#1438]
**Summary**:
When I try creating the settlement on a closed window, I got "Settlement Model" required error even though the request body is containing the settlement model.

**Severity**:
High

**Priority**:
Critical

**Expected Behavior**
. The create settlement on a closed window should be successful

**Steps to Reproduce**
  1.  Create the settlement model using this below curl:
curl -L -X POST 'http://dev2-central-ledger.mojaloop.live/settlementModels' \
-H 'Content-Type: application/json' \
--data-raw '{
  "name": "DEFERREDNET",
  "settlementGranularity": "NET",
  "settlementInterchange": "MULTILATERAL",
  "settlementDelay": "DEFERRED",
  "requireLiquidityCheck": true,
  "ledgerAccountType": "POSITION",
  "autoPositionReset": true
}'
  2. Send quote and transfer between payerfsp and payeefsp
  3. Close the window
4. Create settlement on closed window, then you will see the below error:
{
    "errorInformation": {
        "errorCode": "3102",
        "errorDescription": "Missing mandatory element - \"settlementModel\" is required"
    }
}

Curl for the above create settlement is:
curl -L -X POST 'http://dev2-central-settlement.mojaloop.live/v1/settlements' \
-H 'Content-Type: application/json' \
-H 'FSPIOP-Source: hub_operator' \
-H 'Authorization: Bearer {{HUB_OPERATOR_BEARER_TOKEN}}' \
--data-raw '{
  "settlementModel": "DEFERREDNET",
  "reason": "TESTING",
  "settlementWindows": [
    {
      "id": {{closedWindowID}}
    }
  ]
}'

**Specifications**
  - Component (if known): central services
  - Version: 10.1.0
  - Platform: Mac OS
  - Subsystem: central Settlements
  - Type of testing: Functional
  - Bug found/raised by: Sri

**Notes**:
Not able to run settlements in DEV2 env.

- Severity when opened:
- Priority when opened:

**Comment by ndonnan** [comment]
Hi @sri-miriyala I tried now by getting the latest closed window on dev2, 16.

**Request:**
curl -L -X POST 'http://dev2-central-settlement.mojaloop.live/v1/settlements' -H 'Content-Type: application/json' -H 'FSPIOP-Source: hub_operator' --data-raw '{"settlementModel": "DEFERREDNET", "reason": "TESTING", "settlementWindows": [{"id": 16}]}'

**Response:**
{"id":9,"settlementModel":"DEFERREDNET","state":"PENDING_SETTLEMENT","reason":"TESTING","createdDate":"2020-06-15T09:24:07.000Z","changedDate":"2020-06-15T09:24:07.000Z","settlementWindows":[{"id":16,"state":"PENDING_SETTLEMENT","reason":"TESTING","createdDate":"2020-06-12T16:01:18.000Z","changedDate":"2020-06-15T09:24:07.000Z","content":[{"id":16,"state":"PENDING_SETTLEMENT","ledgerAccountType":"POSITION","currencyId":"USD","createdDate":"2020-06-14T13:09:46.000Z","changedDate":"2020-06-15T09:24:07.000Z"}]}],"participants":[{"id":2,"accounts":[{"id":3,"state":"PENDING_SETTLEMENT","reason":"TESTING","netSettlementAmount":{"amount":205.1099,"currency":"USD"}}]},{"id":3,"accounts":[{"id":5,"state":"PENDING_SETTLEMENT","reason":"TESTING","netSettlementAmount":{"amount":-5.1099,"currency":"USD"}}]},{"id":8,"accounts":[{"id":15,"state":"PENDING_SETTLEMENT","reason":"TESTING","netSettlementAmount":{"amount":-200,"currency":"USD"}}]}]}

I tried by pasting the above create settlement post request and got the same error as you but after reformatting the curl command to be on a single line it went through

**Comment by elnyry-sam-k** [comment]
@sri-miriyala - can you please respond to Neal; If this is not an issue now, can this be closed?

**Comment by sri-miriyala** [comment]
I haven't seen this issue after this instance. Am ok to close this.

**Comment by elnyry-sam-k** [comment]
Thank you @sri-miriyala
