### ISSUE TITLE
Update Pull Panda Slack integration before October

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1482]
## **Goal**:
As an `OSS Maintainer`
I want to `update pull panda before it reaches it's end of life`
so that `developers can continue to receive pull request notifications in slack`

I received this email from Github today:

![Screen Shot 2020-07-15 at 12.41.51 pm.png](https://images.zenhubusercontent.com/5cd963af3613073e20e46e60/5998948b-3fbd-40d0-a060-229f7adb5177)

Or in a PDF format:
[https://app.zenhub.com/files/116650553/daf57396-f942-4b3a-ab98-e7af6ee49f67/download](https://app.zenhub.com/files/116650553/daf57396-f942-4b3a-ab98-e7af6ee49f67/download)

**Tasks**:
- [ ] investigate migration options, it looks like slack might just auto-update automatically, but we should know for sure 
- [ ] TBD [ @? ]

**Acceptance Criteria**:
- [ ] updated configuration or advice on the pull panda slack integration
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
@lewisdaly - is this still relevant :-) ?

**Comment by elnyry-sam-k** [comment]
@lewisdaly closing this for now... please reopen if still relevant
