### ISSUE TITLE
Testing & Streamlining QA: Scoping & planning

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1491]
Scoping & planning: 

 - Create a list of sequence diagrams, folders in PM tests (can be from scratch)
 - Identify priority, sequencing. 

> [Open in MURAL](https://app.mural.co/t/pdp5338/m/pdp5338/1595840452582?wid=0-1595844579274) ![image](https://user-images.githubusercontent.com/2573142/30230004-a70b171c-94ba-11e7-95f6-53290185d9b7.png)
> CORE - PDP

**Comment by oderayi** [comment]
[Sequence Diagrams & Postman Tests.docx](https://github.com/mojaloop/project/files/4994043/Sequence.Diagrams.Postman.Tests.docx)
