### ISSUE TITLE
Design the flow and UI to implement the Hub role 

### ISSUE THREAD

**Issue by georgi-logodazhki** [mojaloop/project#1499]
## **Goal**:
`As a` DFSP
`I want to` Design the flow and UI to implement the Hub role in Testing Toolkit
`so that` I can proceed with implementation of “Hub” role that will allow me to test Payer and Payee FSP side functionality simultaneously

**Tasks**:
- [x] technical design of the backend with sequence diagrams 
- [x] UI design

**Acceptance Criteria**:
- [x] Designs are up-to date

## **Accountability**:
- Owner: @georgi-logodazhki @vijayg10 
- QA/Review: @elnyry-sam-k

**Comment by vijayg10** [comment]
**Backend sequence diagram**

![Hub only mode backend design](https://user-images.githubusercontent.com/33152110/89303961-809fab00-d68a-11ea-8fc3-1c14a9b0c67e.png)

**Comment by vijayg10** [comment]
**UI Design**
![Hub only mode - UI design](https://user-images.githubusercontent.com/33152110/89306383-6c10e200-d68d-11ea-9bde-2445641f36c8.png)
