### ISSUE TITLE
Assess changes needed in the MojaSim collection (relative to LegacySim's) [2.021]

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1518]
## **Goal**:
As an Adopter of Mojaloop
I want to have the MojaSim Golden path test collection contain tests for new features(& bug fixes) added after 8.8
so that I can use the MojaSim collections for regression testing and validating the new features.

This story provides the list of items needed to be ported over.

Note from 1464:
Legacy Sim to Mojasims collection  
       Following folders 
       -  Bug Fixes Folder (#998 , 1009, 981, 990, 1331, 1378, 849, 949, 742, 733, 956, 883, 1032)
       -  transaction request service ( health, received state, reject state, error framework, authorizations, authorizations -error framework)
       -  quoting service folder 
       -  p2p on us transfer ( 4 request)

Folders missing in Legacy collections (updated in this story)
       - get_transfers 

**Tasks**:
- [x] Document the difference (delta) between the MojaSim and Legacy postman collections so that MojaSim collection has improved coverage and includes tests added to the LegacySim collection

**Acceptance Criteria**:
- [x] 'Delta' - tests that are missing in MojaSim collection relative to LegacySim collection is documented.

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: @amarmodus , @elnyry-sam-k

**Comment by amarmodus** [comment]
<img width="898" alt="Screenshot 2020-08-04 01 21 53" src="https://user-images.githubusercontent.com/53434415/89269993-9d0ff900-d632-11ea-8e76-47ab038e63f7.png">

**Comment by amarmodus** [comment]
[Porting to Mojasim task 1218.pdf](https://github.com/mojaloop/project/files/5021948/Porting.to.Mojasim.task.1218.pdf)
