### ISSUE TITLE
Investigate and resolve bug with GET bulk transfer error callback

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#1523]
**Summary**:
Tests for negative scenario (payee_abort) reveals that the callback URI and payload are not as expected.

**Severity**: Medium

**Priority**: Low

**Expected Behavior**
Tests should pass.

**Steps to Reproduce**
  1. Run bulk transfer test for payee abort scenario
  2. Observe test results especially callback payload for PayerFSP
  3. Test should fail

**Specifications**
  - Component (if known):
  - Version: v11.0.0
  - Platform: 
  - Subsystem: Central Ledger
  - Type of testing: Regression
  - Bug found/raised by: @georgi-logodazhki / @oderayi 

**Notes**:

- Severity when opened:
- Priority when opened:

## Pull Requests ##
- [x] https://github.com/mojaloop/central-ledger/pull/768
- [x] https://github.com/mojaloop/postman/pull/154
- [x] https://github.com/mojaloop/helm/pull/352

**Comment by oderayi** [comment]
![Screenshot from 2020-07-31 09-46-18](https://user-images.githubusercontent.com/2910495/89017759-be12da00-d312-11ea-8d68-d7a1ec35feb0.png)

**Comment by oderayi** [comment]
![Screenshot from 2020-07-29 14-19-40](https://user-images.githubusercontent.com/2910495/89017805-cc60f600-d312-11ea-9f88-163878f59c5f.png)

**Comment by elnyry-sam-k** [comment]
Thanks @oderayi , @rmothilal
