### ISSUE TITLE
Review documentation steps for getting TTK up and running

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1529]
**Summary**:
Unable to get the TTK running with instructions from documentation

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
TTK is up and running after following steps from the documentation

**Steps to Reproduce**
  1. [Docs link](https://github.com/mojaloop/ml-testing-toolkit/blob/master/documents/User-Guide-Onboarding-HUB.md#1-running-the-toolkit)

**Specifications**
  - Component (if known): Testing toolkit
  - Version: 10.6.0 / 10.6.1
  - Platform:
  - Subsystem:
  - Type of testing: 
  - Bug found/raised by:

**Tasks**:
- 

**Notes**:

- Severity when opened:
- Priority when opened:

**Notes**:
```
$ docker-compose up
Pulling mojaloop-testing-toolkit-ui (mojaloop/ml-testing-toolkit-ui:v10.6.1)...
ERROR: manifest for mojaloop/ml-testing-toolkit-ui:v10.6.1 not found: manifest unknown: manifest unknown> 
$ docker pull mojaloop/ml-testing-toolkit-ui:v10.6.1
Error response from daemon: manifest for mojaloop/ml-testing-toolkit-ui:v10.6.1 not found: manifest unknown: manifest unknown
```

**Comment by vijayg10** [comment]
Its not a bug. The user opened the wrong URL.
I added the proper URL to some documentation files.
