### ISSUE TITLE
Design Canonical Data Model (CDM) of the Central-ledger services to align with Mojaloop API

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#153]
**Goal**:
As a developer I would like to design the Canonical Data Model (CDM) of the API so that I can use it as reference for implementation

**Tasks**:
- [x] Design Canonical Data Model (CDM) of the API

**Acceptance Criteria**:
- [x] A Canonical Data Model (CDM) is designed for the central-ledger services to align with the Mojaloop API and documented

**Dependencies**:
- None currently

**Comment by kjw000** [comment]
@elnyry - where is the doc for this one?

**Comment by elnyry** [comment]
hi Kim, the migration scripts are updated to reflect this. Here is the diagram..
![central-ledger-schema-5](https://user-images.githubusercontent.com/10507686/39142815-5ed74302-4749-11e8-8669-d1f203924109.png)
