### ISSUE TITLE
Configure Existing Mojaloop Helm Install to include Self-Testing Toolkit

### ISSUE THREAD

**Issue by yosheeck** [mojaloop/project#1535]
Configure Existing Mojaloop Helm Install to include Self-Testing Toolkit as an optional (enabled by default) part of the deployment

## **Goal**:
As a mojaloop dev/admin
I want to be able to use Self-Testing Toolkit as part of deployment
so that I can easily test the deployed software

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by ramakrishnan-sankar** [comment]
Deprecated by #1536
