### ISSUE TITLE
Design CDM for Stream processing

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#155]
**Goal**:
As a developer I would like to Design CDM for Stream processing so that I can use it for developing a re-usable common stream library.

**Tasks**:
- [x] Design CDM for Stream processing

**Acceptance Criteria**:
- [x] A CDM (JSON schema) for Stream processing is available and can be used for the 'common streaming library'

**Dependencies**:
- None currently

**Comment by mdebarros** [comment]
Looked at several messaging standards:

- http://limeprotocol.org/
- https://xmpp.org/extensions/xep-0295.html
- http://www.odata.org/documentation/odata-version-3-0/json-verbose-format/

Decision: Lime protocol
Reason: Lightweight messaging protocol based on xmpp for json specifically.

**Comment by mdebarros** [comment]
@ksatya77, @lazolalucas, @rmothilal please review so I can close

**Comment by mdebarros** [comment]
PR created: https://github.com/mojaloop/central-services-shared/pull/12

See Docs: https://github.com/mojaloop/central-services-shared/blob/feature/%23148DesignImplementCommonStreamingLibrary/src/kafka/protocol/readme.md

**Comment by mdebarros** [comment]
bump
