### ISSUE TITLE
Community Engagement - Create a new document structure for CQS

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1556]
## **Goal**:
`As an OSS Contributor

`I want to` review the documentation structure for code qaulity and security initiative
  
`so that` it can be re-arranged for ease of access by the community

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @kjw000

**Comment by godfreykutumela** [comment]
Include guidelines and templates for standards/guidelines to be published @rasputtintin

**Comment by godfreykutumela** [comment]
@lewisdaly @rasputtintin @pedrosousabarreto @elnyry-sam-k please review and let's aim to finalize by next week wednesday.
[CQS Documentation Structure - 06 Oct 2020 v1.0.docx](https://github.com/mojaloop/project/files/5340610/CQS.Documentation.Structure.-.06.Oct.2020.v1.0.docx)

**Comment by lewisdaly** [comment]
A couple minor notes @godfreykutumela :

- "Standards and guidelines are basically recommended" -> "Standards and guidelines are recommended"  (remove word basically)
- Under Standards and Guidelines > 3) Data Protection Standards > a)	Secure Kafka and Zookeeper Standard
  - Maybe this could be more generic, something like "Secure Internal Messaging Standards"?

- "ii.	Archery" - is this meant to be anchore-cli? I haven't heard of Archery

**Comment by godfreykutumela** [comment]
Thanks, @lewisdaly, and I will update comments accordingly. Yes, I will remove Archery for now as I don't think it was ever deployed and tested - It is a different tool from Anchore-cli. Check it here - https://www.archerysec.com/

**Comment by godfreykutumela** [comment]
@lewisdaly, in the meantime, you can start creating hyperlinks to the actual documents. I plan to start with that later next week, so I would appreciate it to help fast track the process.
