### ISSUE TITLE
TTK - Bug in outbound request execution - Backend is not sending the outboundProgress events for parties error callbacks

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1567]
**Summary**:
In the testing toolkit `outbound request page`, when executing a test case with expected error callbacks are not getting notified with outboundProgress websocket events from the backend.

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
The test case execution page should get the timely notifications incase of error callbacks.

**Steps to Reproduce**
  1. Open Outbound Request Page
  2. Load DFSP p2p sample
  3. Execute the test case against a mojaloop simulator without provisioning the user in the simulator
  4. The parties request will not get the response

**Specifications**
  - Component (if known): Testing toolkit UI / Backend
  - Version: v10.6.1
  - Bug found/raised by: @vijayg10 
  - Reviewers: @elnyry-sam-k @rmothilal 

**Pull Requests**
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/92
- [x] https://github.com/anttiviljami/openapi-backend/pull/109
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/93
- [x] https://github.com/mojaloop/helm/pull/370

**Comment by vijayg10** [comment]
This bug is from the API spec itself. The FSPIOP api spec contains two resources "**_put /parties/{Type}/{ID}/error_**" and "**_put /parties/{Type}/{ID}/{SubID}_**". The openapi-backend library is unable to route the incoming requests to the specified operation because they both look similar. This issue can be with the other openapi based libraries also. Need to discuss with the team and decide on the necessary action.

**Comment by elnyry-sam-k** [comment]
From an OpenAPI Spec point of view, `put /parties/{Type}/{ID}/error` and `put /parties/{Type}/{ID}/{SubID}` are perfectly valid resources, we need to look at the openapi-backend thats having issues and how to work around this.. Would like to catch up soon..

**Comment by vijayg10** [comment]
Sam, I think you are right. The problem is with the matchOperation function implementation in the openapi-backend library. The library is matching the regular expression and taking the first item in the array. 
```
    // find matching operation
    const match = _.chain(templatePathMatches)
      // order matches by length (specificity)
      .orderBy((op) => op.path.length, 'desc')
      // then check if one of the matched operations matches the method
      .find(({ method }) => method === req.method)
      .value();
```
I will refactor this to pickup the path with least variables and try to raise a PR on openapi-backend library by explaining the bug. Lets see whether they approve it or not. If they won't, can we maintain the modified source of openapi-backend as part of our source?

**Comment by elnyry-sam-k** [comment]
Thanks @vijayg10 for looking into this and quickly finding the root-cause. Lets start interacting with lib owners and a PR would be a great start; we can reassess our way forward based on their response (or non-response :-) )

**Comment by vijayg10** [comment]
I refactored the code in openapi-backend library and raised a pull request (https://github.com/anttiviljami/openapi-backend/pull/109). Let's wait for their approval, until then I am changing this story to blocked.

**Comment by vijayg10** [comment]
PR (anttiviljami/openapi-backend#109) is merged. Waiting for the openapi-backend release, expected this week.

**Comment by vijayg10** [comment]
A new version of the openapi-backend library is released. Updated the version in TTK.
