### ISSUE TITLE
Broken Links to postman collections

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1574]
**Summary**:
In both the `mojaloop/postman` [`README.md`](https://github.com/mojaloop/postman#1-collections) and in the [Automated Testing](https://docs.mojaloop.io/documentation/contributors-guide/tools-and-technologies/automated-testing.html) section of the documentation, there are broken and outdated links to the postman collections.

In order to make onboarding easier, we need to:
1. Clean up duplicate or unused/outdated postman collections
    - Perhaps we can make an `./archive` directory for those collections we don't want to delete, but also don't want to confuse new users with
2. Establish some better naming and versioning conventions for postman collections
3. Fix up our documentation to refer to the postman collections correctly

**Severity**:
High

**Priority**:
Medium

**Expected Behavior**
- When I click on links to postman collections, they should resolve correctly
- When a new postman collection is created, it should follow good naming conventions

**Steps to Reproduce**
  1.
  2.
  3.

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by: @lewisdaly 

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by lewisdaly** [comment]
Some recommendations for collection naming conventions:

- We remove the word `mojaloop` from the collections as it's redundant.
- Never use the word `new` or `old` in a collection name. We should rely on either git or exact release names which correlate to help releases
- decide on using underscores `_` or dashes `-` to separate out words/sections . We should never use spaces, since that makes scripting much harder. Alternatively we could use CasesToSeparateOutWords, but that gets harder to read in my opinion

**Comment by lewisdaly** [comment]
First PR to clean up the readme references: https://github.com/mojaloop/postman/pull/159

**Comment by lewisdaly** [comment]
Fixed in the postman repo, but now we need to address it in the documentation repo.

We might be better off looking at the naming conventions first, so we have better consistency and don't break links again.

**Comment by elnyry-sam-k** [comment]
@lewisdaly , can it be closed with
- https://github.com/mojaloop/documentation/pull/269 and
- https://github.com/mojaloop/postman/pull/184

**Comment by lewisdaly** [comment]
Yeah I'd say so. Do we need to release the documentation?
