### ISSUE TITLE
[CI-CD DevOps] : Core System - Operations

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#16]
**Goal**:
Architect and analyse how the system needs to report back to a central monitoring system regarding the state of operation and health in order for the kubernetes management to operate at optimum level.

**Dependencies**:
- None currently

**Comment by elnyry** [comment]
Stories part of this Epic closed and this has been open for quite a while, so closing it for now. New topics/features identified will need new Epics to stay up to date
