### ISSUE TITLE
Refactor shared-services logging

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#161]
**Goal**:
As a developer I would like to _refactor shared-services logging_ so that I can have access to underlying logging framework

**Tasks**:
- [x] Refactor shared-services logging

**Acceptance Criteria**:
- [x] Shared-services logging is refactored so that logging is configurable/accessible

**Dependencies**:
- None currently

**Comment by lazolalucas** [comment]
PR closed : https://github.com/mojaloop/central-services-shared/pull/10
Notes:
Code coverage failing due to tests missing for Producer/Consumer new code.

**Comment by mdebarros** [comment]
bump
