### ISSUE TITLE
Disable Demo Fraud and Risk Management System (FRMS)

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#163]
**Goal**:
As a developer I would like to _Find & Disable Demo FRMS_ so that I can exact payments without any demo functionality.

**Tasks**:
- [x] Find & Disable Demo FRMS

**Acceptance Criteria**:
- [x] The Demo FRMS where it is present can be disabled.

**Dependencies**:
- None currently

**Comment by HenkKodde** [comment]
Move to QA review.

**Comment by HenkKodde** [comment]
Updates was reviewed and approved.
Note - High-Risk, Low-Risk and Blacklist are still hardcode values for demonstration purposes and would need to be looked at as part of a new story.

**Comment by HenkKodde** [comment]
Story completed.
