### ISSUE TITLE
Migration user lock issue - [5]

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#172]
**Goal**:
As a developer I want to address Migration user lock issue

**Tasks**:
- [x] Address Migration user lock issue

**Acceptance Criteria**:
- [x] Migration user lock issue

**Dependencies**:
- Current issue with knex -> https://github.com/tgriesser/knex/issues/2534

**Comment by ZARDeonBotha** [comment]
Issue logged with KNEX previously : https://github.com/tgriesser/knex/issues/2234
Rajiv posted a message regarding this issue logged if the fix is also working in our KNEX version0.14.6

**Comment by mdebarros** [comment]
Blocked due to @bothadeon being on leave.

**Comment by rmothilal** [comment]
Changes still not completed on knex library as of 05/06/2018 00:27am CAT
https://gitter.im/tgriesser/knex

**Comment by elnyry** [comment]
Duplicate, already resolved.
