### ISSUE TITLE
email-notifier service failing in mojaloop default setup

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1724]
**Summary**:
email-notifier service/pod is failing to come up on a default mojaloop deployment. This issue wasn't observed during the previous helm release (v11.0.0)
```
ReplicaSet "d1-114-1-emailnotifier-..." has timed out progressing.; Deployment does not have minimum availability.

CrashLoopBackOff: Back-off 5m0s restarting failed container=emailnotifier pod=....
```

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
email-notifier pod/services comes up normally and sends out emails as configured

**Steps to Reproduce**
  1. Deploy v10.4.0 mojaloop charts (official release)
  2. View status of email-notifier service/pod

**Specifications**
  - Component (if known): email-notifier
  - Version: v9.5.0 
  - Platform: AWS
  - Subsystem: email-notifier (k8s deployment managed by Rancher)
  - Type of testing: Manual
  - Bug found/raised by: @elnyry-sam-k 

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by mdebarros** [comment]
Both dev1 and dev2 email-notifiers are now up and running, and reporting healthy.

The issue was a bad configuration for the SMTP server --> https://github.com/mojaloop/email-notifier/blob/master/config/default.json#L2

**Comment by mdebarros** [comment]
Also set up a PR to make the SMTP config general: https://github.com/mojaloop/email-notifier/pull/168
