### ISSUE TITLE
TTK Web UI - Auto saving not working some times

### ISSUE THREAD

**Issue by georgi-logodazhki** [mojaloop/project#1753]
**Summary**:
Auto saving not working some times

**Severity**:
High

**Priority**:
Medium

**Expected Behavior**
Auto saving must always work

**Steps to Reproduce**
  1.
  2.
  3.

**Specifications**
  - Component (if known): TTK Web UI
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by: @vijayg10 

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by elnyry-sam-k** [comment]
Not reproducible as of Sprint 12.1 - please reopen if there's a repro
