### ISSUE TITLE
Helm upgrade v10.4.0 -> v11.0.0 upgrade issues

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#1759]
**Summary**:
There's an issue upgrading from helm v10.4.0 -> v11.0.0 with default config

**Severity**:
Medium

**Priority**:
High

**Expected Behavior**
Helm upgrade succeeds without any issue

**Steps to Reproduce**
  1. Helm install v10.4.0 (default config) `helm install --namespace xxxx d2-116-2 --version 10.4.0 mojaloop/mojaloop`
  2. Helm upgrade to v11.0.0 (default config) `helm upgrade --namespace xxxx d2-116-2 --version 11.0.0 mojaloop/mojaloop
`
  3. Logs below
```
Error: UPGRADE FAILED: rendered manifests contain a new resource that already exists. Unable to continue with update: existing resource conflict: namespace: xxxx, name: d2-116-2-account-lookup-service-admin, existing_kind: apps/v1, Kind=Deployment, new_kind: apps/v1, Kind=Deployment
```
4. Logs with `helm upgrade --namespace xxxx d2-116-2 --version 11.0.0 mojaloop/mojaloop --dry-run --debug`
```
upgrade.go:84: [debug] preparing upgrade for d2-116-2
upgrade.go:92: [debug] performing update for d2-116-2
Error: UPGRADE FAILED: rendered manifests contain a new resource that already exists. Unable to continue with update: existing resource conflict: namespace: xxxx, name: d2-116-2-account-lookup-service-admin, existing_kind: apps/v1, Kind=Deployment, new_kind: apps/v1, Kind=Deployment
helm.go:75: [debug] existing resource conflict: namespace: xxxx, name: d2-116-2-account-lookup-service-admin, existing_kind: apps/v1, Kind=Deployment, new_kind: apps/v1, Kind=Deployment
rendered manifests contain a new resource that already exists. Unable to continue with update
helm.sh/helm/v3/pkg/action.(*Upgrade).performUpgrade
	/private/tmp/helm-20200317-45091-md2sa4/src/helm.sh/helm/pkg/action/upgrade.go:221
helm.sh/helm/v3/pkg/action.(*Upgrade).Run
	/private/tmp/helm-20200317-45091-md2sa4/src/helm.sh/helm/pkg/action/upgrade.go:93
main.newUpgradeCmd.func1
	/private/tmp/helm-20200317-45091-md2sa4/src/helm.sh/helm/cmd/helm/upgrade.go:137
github.com/spf13/cobra.(*Command).execute
	/private/tmp/helm-20200317-45091-md2sa4/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
	/private/tmp/helm-20200317-45091-md2sa4/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	/private/tmp/helm-20200317-45091-md2sa4/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
	/private/tmp/helm-20200317-45091-md2sa4/src/helm.sh/helm/cmd/helm/helm.go:74
runtime.main
	/usr/local/Cellar/go@1.13/1.13.8/libexec/src/runtime/proc.go:203
runtime.goexit
	/usr/local/Cellar/go@1.13/1.13.8/libexec/src/runtime/asm_amd64.s:1357
UPGRADE FAILED
main.newUpgradeCmd.func1
	/private/tmp/helm-20200317-45091-md2sa4/src/helm.sh/helm/cmd/helm/upgrade.go:139
github.com/spf13/cobra.(*Command).execute
	/private/tmp/helm-20200317-45091-md2sa4/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
	/private/tmp/helm-20200317-45091-md2sa4/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	/private/tmp/helm-20200317-45091-md2sa4/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
	/private/tmp/helm-20200317-45091-md2sa4/src/helm.sh/helm/cmd/helm/helm.go:74
runtime.main
	/usr/local/Cellar/go@1.13/1.13.8/libexec/src/runtime/proc.go:203
runtime.goexit
	/usr/local/Cellar/go@1.13/1.13.8/libexec/src/runtime/asm_amd64.s:1357
```

**Specifications**
  - Component (if known): Helm
  - Version: v11.0.0
  - Platform: AWS (k8s)
  - Subsystem: helm upgrade
  - Type of testing: release / manual
  - Bug found/raised by: @elnyry-sam-k 

**Notes**:

- Severity when opened: medium
- Priority when opened: high

**Comment by mdebarros** [comment]
I have not been able to reproduce the exact issue above, but I have picked up at the upgrade fails on upgrading Kafka due to the following change --> https://github.com/helm/charts/commit/c194bce22cf6eae521bdd79d12ee04d9b1cd3e50

**Comment by mdebarros** [comment]
As a result of changes made at the dependency level (i.e. Kafka), we will not be able to support upgrades in v11.0.0.

Going forward, I propose that all external dependencies are removed from the Mojaloop helm charts, and are instead deployed as a separate pre-requisite step. The rationale behind this being:
- We currently do not see any Mojaloop switch implementors using these dependencies in QA/Prod environments. They instead have chosen to either deploy their own dependencies or rely on managed services instead.
- The tightly coupled external dependencies are proving to be an issue for the Mojaloop Helm chart upgradability as we do not have any control over them, by externalizing them we remove the tight coupling of the default Mojaloop Helm deployments. This ensures that the onus is on the deployer to ensure that all dependencies are deployed as necessary.
- This also ensures that any Mojaloop Helm deployment can be easily undeployed without impacting the persistence layer (i.e. data stores, persistent message streams, etc). This is useful for deploying new versions that do not support upgrades (i.e. similar to v10.4.0 -> v11.0.0).

This would mean that we would need to add instructions on how these dependencies can be deployed to the "Deployment Guide" documentation. 

> I have not been able to reproduce the exact issue above, but I have picked up another issue causing the upgrade to fail due to the following change to the Kafka helm chart --> [helm/charts@c194bce](https://github.com/helm/charts/commit/c194bce22cf6eae521bdd79d12ee04d9b1cd3e50)
> 
> Investigating options on how to handle this issue.
