### ISSUE TITLE
api-snippets: Amount regular expression is wrong

### ISSUE THREAD

**Issue by kkzeng** [mojaloop/project#1769]
**Summary**:
The regex pattern for the format of Amounts is wrong.
For example, 1.00 is not matched by the pattern.

**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Expected Behavior**

**Steps to Reproduce**
  1.
  2.
  3.

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by:

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by elnyry-sam-k** [comment]
hey @kkzeng - this is not a bug; it is expected behavior.

Here's the data model and examples list for this data type from the API Definition: https://docs.mojaloop.io/mojaloop-specification/documents/API%20Definition%20v1.0.html#7213-amount

**Comment by kkzeng** [comment]
> hey @kkzeng - this is not a bug; it is expected behavior.
> 
> Here's the data model and examples list for this data type from the API Definition: https://docs.mojaloop.io/mojaloop-specification/documents/API%20Definition%20v1.0.html#7213-amount

Thanks for pointing it out @elnyry-sam-k, I wasn't sure so I created a ticket first. I will close this now
