### ISSUE TITLE
Mowali GDPR Initiative Support - Focusing on the unstructured data elements

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1783]
## **Goal**:
`As a ` CQS Workstream Contributor

`I want to` support Mowali on their GDPR initiative
  
`so that` they are successful in their compliance program.

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: Medium

**Uncertainty**: Medium

---

**Tasks**:
- [ ] TBD [ @godfreykutumela  ]

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @godfreykutumela

**Comment by elnyry-sam-k** [comment]
@godfreykutumela moving this to 13.1 so that we can close the 12.6 milestone out.. hope thats ok, if not please take necessary action.
