### ISSUE TITLE
Implementation of the new CQS Document Structure

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1787]
## **Goal**:
`As a` OSS Developer

`I want to` develop a new and updated documentation schema for CQS stuff
  
`so that` I can have all CQS related information from one place while enabling the ease of update as well.

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [ ] Develop and implement a new CQS Doc schema [ @? ]

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @godfreykutumela

**Comment by godfreykutumela** [comment]
To further break this into 3 stories

**Comment by godfreykutumela** [comment]
This is completed and I am busy preparing the information to be uploaded @lewisdaly

**Comment by lewisdaly** [comment]
Thanks @godfreykutumela
