### ISSUE TITLE
PI-12.1: Personas in Mojaloop

### ISSUE THREAD

**Issue by JaneS99** [mojaloop/project#1791]
PI-12: Persona's in Mojaloop participant world:

As the Marketing Manager for the Mojaloop foundation
I have a a body of work that describes many personas who would be involved in Mojaloop
I will share this work with the core team on the Accelerate Engagement Work stream
so that we are able to assess the as-is position and determine the further work required to describe personas and their value propositions.

Acceptance Criteria:

1. The file will be shared early in the week of 2 Nov 2020
2. All recipients will read the documents 
3. The participants will bring their analysis to the call scheduled for 4 November

**Comment by elnyry-sam-k** [comment]
I think this is now done.
