### ISSUE TITLE
DevSecOps - Perform WhiteSource License and Security scans

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1792]
## **Goal**:
`As a` OSS developer

`I want to` run WhiteSource based security and license audit scan
  
`so that` I can baseline the results against current tools - NPM Audit

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: Medium - We are new to WhiteSource and will be trying on the Github based repo for the first time so might run into support issues - don't the level of complexity at this stage

**Uncertainty**: Medium - I can't be estimated hence we decided on a middle ground which is medium.

---

**Tasks**:
- [ ] TBD [ @godfreykutumela @lewisdaly 

**Done**
- [ ] Acceptance Criteria pass TBD @godfreykutumela 
-

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @lewisdaly

**Comment by godfreykutumela** [comment]
Hi, @lewisdaly. I have opened an issue for the WhiteSource vs. NPM comparative scans, so please assist in defining tasks and setting target milestones.

**Comment by godfreykutumela** [comment]
Hi @lewisdaly Just let me know when we can start this - you can do the code prep and scanning with the agent and I will handle the reporting end on the portal.

**Comment by lewisdaly** [comment]
@godfreykutumela I've processed 3 repos up in Whitesource at the moment, I might just need a hand putting together the excel report.

**Comment by godfreykutumela** [comment]
Hi @lewisdaly Please give me the WhiteSource project name and I will check the results in the portal. Also please rerun npm audit on the 3 repos so that we compare using updated results.

**Comment by lewisdaly** [comment]
@godfreykutumela `mojaloop-test`. And yep, we can grab the results from npm audit either from github's advisories or our latest build on each repo

**Comment by lewisdaly** [comment]
Ran this for 3 repos, will re run across all core repos.

**Comment by lewisdaly** [comment]
@godfreykutumela I've run again for all "core" repos:

[https://app.zenhub.com/files/116650553/33c1782a-38cc-442d-80b6-29d1d4ffafed/download](https://app.zenhub.com/files/116650553/33c1782a-38cc-442d-80b6-29d1d4ffafed/download)

[https://app.zenhub.com/files/116650553/19ec90b8-4562-4fd3-ad3b-eb365766f80e/download](https://app.zenhub.com/files/116650553/19ec90b8-4562-4fd3-ad3b-eb365766f80e/download)

**Comment by godfreykutumela** [comment]
Hi @lewisdaly I have reviewed the results from the last scan with all repos so let me know when you're to do a joint review and agree on the next steps.

**Comment by lewisdaly** [comment]
Thanks Godfrey - perhaps this thursday?

**Comment by godfreykutumela** [comment]
Cool just text when ready.

**Comment by lewisdaly** [comment]
Follow up:


## Licenses
- GPL 2.0 for node-forge in `ml-testing-toolkit-ui` and `finance-portal-ui`


@lewisdaly todo

**Comment by godfreykutumela** [comment]
Thanks, @lewisdaly and lets open investigation tickets for those 2 GPL findings.
