### ISSUE TITLE
DevSecOps - As an administrator I need to know who has access to what repos

### ISSUE THREAD

**Issue by kjw000** [mojaloop/project#1807]
## **Goal**:
As an administrator I need to know who has access to what repos. 

`I want to create report per repo to list each repo and the people and their access level (read, write, maintain, admin)
  
`so that` we can ensure we remove anyone that no loner should have write, maintain or admin access.  To do this via the UI you need to go to each repo individually, go to the insight tab and people tab.  We should run this monthly.

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
Thanks @kjw000, I'll take a look

**Comment by lewisdaly** [comment]
I think this http request (per repo) will do it:

```bash
curl \                                                                                                                                                                                                  
       -H "Accept: application/vnd.github.v3+json" \
       -u lewisdaly:$GITHUB_TOKEN \
       https://api.github.com/repos/mojaloop/pisp/collaborators
```

GitHub v3 API Reference: https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#list-repository-collaborators

**Comment by kjw000** [comment]
thanks this is great.

**Comment by lewisdaly** [comment]
Question from call: Can we use the api to add the "org maintainers" group to all repos?

**Comment by kjw000** [comment]
thanks Lewis

**Comment by godfreykutumela** [comment]
> Question from call: Can we use the api to add the "org maintainers" group to all repos?

I think so

**Comment by lewisdaly** [comment]
This is done - we have the list: https://drive.google.com/file/d/1MjLaNthgAfHmOtZ33MdDf2swdXtc3ba6/view?usp=sharing

**Comment by lewisdaly** [comment]
Also in a more traditional format: [https://app.zenhub.com/files/116650553/92359f92-413a-4bc7-a77b-465d364f836e/download](https://app.zenhub.com/files/116650553/92359f92-413a-4bc7-a77b-465d364f836e/download)

**Comment by godfreykutumela** [comment]
Noted, thanks @lewisdaly
