### ISSUE TITLE
Update mojaloop/sdk-scheme-adapter to use mojaloop/api-snippets.

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1818]
@kleyow commented on [Thu Jul 30 2020](https://github.com/mojaloop/mojaloop/issues/391)

## **Goal**:
As a developer I want to use api-snippets for open api schemas so that leverage it's maintainability and one source of truth-ness.

**Tasks**:
- [ ] Update any interfaces in service to use api-snippets.

**Acceptance Criteria**:
- [ ] Designs are up-to date
- [ ] Tests pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by mdebarros** [comment]
@elnyry-sam-k @lewisdaly I believe this was already done.

I think we can close this?

**Comment by elnyry-sam-k** [comment]
Yes, thanks @mdebarros , I think so..
