### ISSUE TITLE
Fix the /documentation & /swagger.json endpoints for account-lookup-service

### ISSUE THREAD

**Issue by shashi165** [mojaloop/project#1861]
**Summary**:
Fix the `GET /documentation` and point and expose `swagger.json` as JSON on `GET /swagger.json` endpoints for account-lookup-service

**Severity**:
Medium

**Priority**:
Low

**Expected Behavior**
`GET /documentation` endpoint should return the documentation for the service
`GET /swagger.json` endpoint should return the `swagger.json` as raw JSON

**Steps to Reproduce**
  1. run GET /documentation request on account lookup service
  2. run GET /swagger.json request on account lookup service
  

**Specifications**
  - Component (if known): account-lookup-service
  - Version: v11.1.3
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by: @shashi165 

**Notes**:

- Severity when opened: Medium 
- Priority when opened: Low

**Pull Requests**:
- [x] https://github.com/mojaloop/account-lookup-service/pull/375

**Comment by elnyry-sam-k** [comment]
Followed up with #1868
