### ISSUE TITLE
Mowali Support - Establish a PII data management framework

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#1880]
## **Goal**:
`As a` OSS CQS team

`I want to` support Mowali with the establish a PII data management framework
  
`so that` they can have clearly established data retention timeframe with deletion rules.

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: Medium

**Uncertainty**: Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @godfreykutumela 
- QA/Review: @godfreykutumela

**Comment by elnyry-sam-k** [comment]
@godfreykutumela moving this to 13.1 so that we can close the 12.6 milestone out.. hope thats ok, if not please take necessary action.
