### ISSUE TITLE
Investigate automated spell check of MD files during check-in

### ISSUE THREAD

**Issue by kjw000** [mojaloop/project#1903]
## **Goal**:
`As a` contributor want a service to perform spell check on my mark down documents.

Ability to spell check md files during the ci/cd files.  
Came across this. https://github.com/rojopolis/spellcheck-github-actions

**Acceptance Criteria**:
- Documents are spell checked before they are merged

**Comment by elnyry-sam-k** [comment]
@kjw000 , @lewisdaly - here's an existing style guide: https://docs.mojaloop.io/documentation/contributors-guide/documentation/documentation-style-guide.html (for word docs primarily, but docs nonetheless )

**Comment by lewisdaly** [comment]
This is a great idea. The only challenge I see is the amount of false positives for technical words and appreviations.

**Comment by godfreykutumela** [comment]
@elnyry-sam-k and @lewisdaly what is the update on this issue? can we move it to blocked or close it if there is no further work done on it?

**Comment by lewisdaly** [comment]
@godfreykutumela it's on my backlog - I haven't had the chance to get to it yet.

**Comment by godfreykutumela** [comment]
Not relevant this PI!
