### ISSUE TITLE
operator-settlement - upgrade to @hapi/hapi and write tests

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#1905]
**Summary**:
operator-settlement uses an outdated and vulnerable version of `hapi`. It needs to be updated, but there aren't enough unit tests to verify any upgrade.

**Severity**:
Medium

**Priority**:
?

**Specifications**
  - Component (if known): operator-settlement
  - Version: `v9.2.1`
  - Subsystem:
  - Bug found/raised by: dependabot

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by godfreykutumela** [comment]
Hi @lewisdaly what is the status of this issue? Can we close it this PI or defer it to next one?

**Comment by lewisdaly** [comment]
Yeah I'm not sure. I think we can defer it. I don't even know if operator-settlement is being used much or at all. @elnyry-sam-k do you know more details about this repo? Is it actively being used?

**Comment by elnyry-sam-k** [comment]
@lewisdaly this is part of the finance portal, its not feature rich right now, but still part of mojaloop. With the discussions around FXP features that Mowali uses, if and when its donated to OSS, it should become fully functional. Up to that point, I think we have to maintain status quo :-)...

**Comment by lewisdaly** [comment]
Cool, thanks @elnyry-sam-k . I'll remove the dependabot notices for this repo for now then since they are just adding noise. I'll also close this for now, we can always reopen again once there is more stuff happening with FXP.
