### ISSUE TITLE
Audit issue with `event-stream`, Widdershins child dependency

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#1908]
**Summary**:
License audit scan currently fails in CircleCI due to incompatible license string ("Custom")  used in version `3.3.4` of `event-stream` library, a child dependency of Widdershins in use in `central-services-shared` for API documenattion.

However, the latest version of `event-stream` fixed the issue but `Widdershins` still uses the older version.

A temporary workaround is to:
 - First, delete the entire "node_modules" directory
 - In "package-lock.json", locate every `event-stream` occurence with vesion `3.3.4` and delete
 - Ensure `event-stream` version `4.0.1` is added as a dependency in `package.json`
 - Run `npm install`
 - Ensure that there are no occurency of `event-stream` version `3.3.4` in `package-lock.json`

A more permanent solution would be for Widdershins to update to the latest `event-stream` version, or an exception be made in the CI config for `event-stream` version `3.3.4`.

**Severity**: Low

**Priority**: Medium

**Expected Behavior**

**Steps to Reproduce**
  1. Ensure central-services-shared is v11.5.3 or above
  2. Run `npm install`
  3. Push to remote to trigger CI build
  4. License audit job should fail

**Specifications**
  - Component (if known): Central Srvices Shared
  - Version: v11.5.3
  - Platform: 
  - Subsystem:
  - Type of testing: 
  - Bug found/raised by: @oderayi 

**Notes**:

- Severity when opened: Low
- Priority when opened: Medium

**Comment by mdebarros** [comment]
I think the correct approach is to submit a PR to Widdershins to upgrade the dependency.

**Comment by mdebarros** [comment]
PR created https://github.com/mojaloop/license-scanner/pull/18 to add this to the exclude list.

Both Github, and NPM.org specify the license as MIT. 

That can be reverted once the corresponding dependencies have been updated.

**Comment by mdebarros** [comment]
> PR created [mojaloop/license-scanner#18](https://github.com/mojaloop/license-scanner/pull/18) to add this to the exclude list.
> 
> Both Github, and NPM.org specify the license as MIT.
> 
> That can be reverted once the corresponding dependencies have been updated.

Hotfix for the previous PR: https://github.com/mojaloop/license-scanner/pull/19
