### ISSUE TITLE
10 - Updating the MojaPay PISP demo application to generate real FIDO credentials, fix crashes in common scenarios, etc.

### ISSUE THREAD

**Issue by eoln** [mojaloop/project#1911]
# acceptance criteria

- implement FIDO credential creation and attestation steps between MojaPay and PISP Demo Server
- fix crashes when navigating between different pages
- hook up with DFSP login page redirects and deep links for end to end demo

**Comment by elnyry-sam-k** [comment]
Thanks Lewis.. this is now done!
