### ISSUE TITLE
1 - Full coverage of error scenarios in PISP-focused flows

### ISSUE THREAD

**Issue by kleyow** [mojaloop/project#1915]
- Error codes defined for PISP scenarios (codes, description, submitted proposal to CCB/SIG)
- Error scenarios for transfers supported on the DFSP side
- Error scenarios for linking supported on the DFSP side
- Error scenarios for transfers supported on the PISP side
- Error scenarios for linking supported on the PISP side

**Comment by elnyry-sam-k** [comment]
As confirmed with JJ, Kevin, Lewis and the team - all known error scenarios are now covered.. (from sequence diagrams and other docs)
