### ISSUE TITLE
Network Security examine and mitigage risks associated with any pod to any pod network access

### ISSUE THREAD

**Issue by tdaly61** [mojaloop/project#1926]
it appears that within the default installation of mojaloop all pods are deployed to a single (perhaps the default) namespace and there seems to be little visible network controls between deployed pods.  The immediate implication of this is that all pods can talk to all pods and hence if any pod is compromised => all pods and the entire system could become compromised.  

Reducing the "attack surface" of the system is  normal and best practice for kubernetes deployments

Especially given the financial transactional nature of mojaloop,  allowing all pod to all pod network access seems like a particular risk as an attack that compromised both sides of a transaction might be both lucrative for the intruder whilst also being easier to hide i.e. harder to audit and monitor against ..at least compared to limited/necessary pod to pod communication model.

I am new to the project, so perhaps much of this is in planning or catered for at deployment or has been discussed  but I did not spot it in the security docs nor the current deployment instructions and not in the current helm charts.  

Certainly whilst deployment to cloud providers such as GKE can provide good ingress/egress network security to the cluster, it still begs the question of if the simplicity and current convenience of the all pod to all pods single namespace deployment is worthy of the increased attack surface as even with the enhanced security features of the cloud providers much "perimeter security" still depends upon the mojaloop deployment and cluster admin. 

regards.

**Comment by lewisdaly** [comment]
@godfreykutumela this would be great to bring up with the Mowali guys and see if they can share some of their experiences related to pod security.

**Comment by elnyry-sam-k** [comment]
We need to discuss this on the DA, definitely.. Thanks @tdaly61

**Comment by godfreykutumela** [comment]
Noted @elnyry-sam-k @lewisdaly For me this is a runtime issue and at the moment we are not touching much on those issues especially on the PaaS layer. This is one of the reasons why we need to set up the lab so that we can test run time config and issue a best practice standard for implementors to adopt based on something we first tested ourselves. Let's discuss further later today. @rasputtintin.

**Comment by tdaly61** [comment]
@godfreykutumela  @lewisdaly  @elnyry-sam-k : I hear what you are saying and I am not trying to introduce complexities to the project but I wonder what happens if or even when one of your customers suffers an attack.  As well as the damage to their business will this reflect badly on the project as a whole. In the sales cycle/implementation agreement does language exist that makes securing the deployment a responsibility for the "customer/deployer", alternatively is there somewhere prominent in the Mojaloop documentation that clearly states the need for kubernetes security to be implemented on deployment and at runtime ?    It would seem to me if the customer/deployer has not mitigated attack risk by sufficiently reducing the attack surface of both the kubernetes control plane and the kubernetes data plane (i.e. pods and apps) then if they suffer a break-in they might well come back and blame the developers/project  at least to some degree and if there is no clear statement of responsibility then it will be unclear as to who was indeed responsible.  So can I suggest that if possible someone do a bit of an audit on the existing accounts. I think you really need to know things like: are they using a cloud provider for their k8s or are they hosting k8s themselves. If they host it themselves there is a LOT more effort to secure the K8S control plane BUT in general this is what cloud providers will do.   Have they implemented RBAC ,pod security policies and a network policy with something like calico to prevent all pod to pod comms and hence lower attack surface (again is there a reason that mojaloop allows any to any pod communications) and generally taken steps to secure the K8S data plane in line with well documented K8S best practice ?  If your customers have not done this then they are "at risk" and I would urge a fairly urgent mitigation project if they have done this and the risk is far reduced then perhaps the first step is to add something to the documentation and perhaps make everyone (customers,deployers , participants) well aware of it.  Again as I am new to the project I am just learning so perhaps doc exists today or you have good confidence in the deployments , but based on the Mojaloop doc I have read and the way the system deploys today ..... there seems to be at least some reason to pursue this line  for the long term good of the project.

**Comment by elnyry-sam-k** [comment]
thanks @tdaly61 - agree with all points here.. we definitely need documentation of best practices around k8s security and policies and revisit separation of groups of services as well (for example transfers (and settlements) related services can be on a separate cluster since those deal with updating of positions and funds in general whereas look-ups, quotes don't really affect them)

**Comment by godfreykutumela** [comment]
Hi @tdaly61 All pointed noted and below are we have and/or planning connected to the point :

1. Documentation Update - We are busy in the process of documenting all security efforts taken to protect Mojaloop as part of the Code Quality and Security Workstream. This will be completed by end of January 2021

2. Statement of responsibility between Customer/ Deployers and Mojaloop OSS Team - We are driving this from a standard perspective and so far we have complete it for PCI DSS v3 and ISO27 000 and NIST are next - There are awaiting the availability of a production-grade instance. See attached sheet.

3. We have identified this risk late in 2019 as part of our deployment experience from Mowali and have mitigated by advocating for the adoption of CIS Benchmark for Cloud Providers while working on a Mojaloop specific and tested cloud security configurations. This is part of our PI 8 Feedback report to the community and will be reflected in our updated documentation around security. Once completed we will issue a reference implementation reflecting some of the proposed config above from @elnyry-sam-k's comments.

Definitely @tdaly61 you're not introducing any complexity but providing us with much-needed feedback on this critical aspect of cloud security. I will ensure that this fast track within our CQS work and keep everyone posted all the way.

**Comment by tdaly61** [comment]
Hi @godfreykutumela 

Ahh this sounds pretty good.
Some follow ups if I may. 
1. I am happy to review the Documentation Update if that is of any use.
2. How are you driving these standards into the deployments ? Is there something I can read there ? 
3. So are you saying that the work is progressing to have a reference deployment with RBAC, network security , pod security policies etc ?  If so is there anything to look at yet as I could incorporate into a mini-loop variant perhaps as it develops ?  

thanks again for the info/clarifications

**Comment by godfreykutumela** [comment]
Hi, @tdaly61 I will update you as have those available.

Regarding driving standards into deployment - we issue those as guidelines for implementors to adopt and in certain cases, we have reference implementations in place. Please also note we do provide security advisory support to implementors so if you're implementing Mojaloop let us know if you need help on any security aspect of the hub operations.

**Comment by godfreykutumela** [comment]
Happy to do a catch-up call with you on this topic, Tom @tdaly61

**Comment by tdaly61** [comment]
Hi @godfreykutumela , I am happy to contribute here *if* I can so that might be a good idea.  I am obviously in the same TZ as @lewisdaly but aware of the conf for next week , so should we schedule for Monday following the conf ?

**Comment by godfreykutumela** [comment]
Noted Tom @tdaly61 and I will send you placeholder the following Monday the 18th, and I will make it a morning session for me which will be around 1-3 pm your time.

**Comment by godfreykutumela** [comment]
Agreement from the meeting today:

- Tom has offered to contribute to the CQS team in helping define a default CIS aligned security configuration for Pod to Pod access
- Contribute to the development of the Kubernetes security standard 

Next Steps

- Provide Tom with access to Mojaloop learning site 
- Miguel to present a deep dive on Mojaloop Architecture and flows
- Godfrey and Victor to present the current security controls and thinking for the PaaS layer 
- Godfrey to create 2 Github issues for the PoD security configuration and Kubernetes Security Standard - to be addressed in PI 13
