### ISSUE TITLE
[pisp] Discuss if AuthenticationType and AuthenticationValue should be coupled at a higher level in the schema

### ISSUE THREAD

**Issue by kleyow** [mojaloop/project#1941]
## **Goal**:
`As a` stakeholder I want openapi to enforce valid AuthenticationTypes and Values

`I want to` discuss AuthenticationType and AuthenticationValue being coupled at a higher level
  
`so that` there is a possibility openapi validators can catch mismatched types and values. 

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: Low

**Uncertainty**: Low

Instead of 
```
    AuthenticationInfo:
      title: AuthenticationInfo
      description: Data model for the complex type AuthenticationInfo
      required:
        - authentication
        - authenticationValue
      type: object
      properties:
        authentication:
          $ref: "#/components/schemas/AuthenticationType"
        authenticationValue:
          $ref: "#/components/schemas/AuthenticationValue"
```

something like this

```
    AuthenticationInfo:
      title: AuthenticationInfo
      description: Data model for the complex type AuthenticationInfo
      required:
        - authentication
        - authenticationValue
      type: object
      oneOf:
        - $ref: '#/components/schemas/OTPAuthenicationTypeAndValue'
        - $ref: '#/components/schemas/QRCODEAuthenicationTypeAndValue'
        - $ref: '#/components/schemas/U2FAuthenicationTypeAndValue'
```
---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
@kleyow is this now irrelevant since we've updated the API schema?

**Comment by kleyow** [comment]
Yes I think so.
