### ISSUE TITLE
TTK OBJ#1 - Bugs identified in test case editor

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1946]
**Summary**:
The following are the issues identified while trying to create test cases
- [x] ~~If I duplicate a file in collection manager and edit some assertions in the new file, the content in the original file is being changed sometimes~~ (Can't reproduce it)
- [x] When I save the entire folder after total execution, the test case IDs are being changed in the files.
- [x] For PUT requests, the override URL is not allowing to change the value (the changes are not being visible, on reopen the window, we could see the changes)
- [x] If I copy entire raw code of assertions and paste it including the square brackets, the browser is crashing
- [x] Duplicate a test case, that is not being reflected into folderData and is not being saved
- [x] When select all and paste the text in body, null is being appended at the end
- [x] When trying to edit body with wrong syntax by pasting something, some times all the body is gone when I close and open the test case editor
- [x] Unable to edit the body of put /participants/testfsp2/accounts/11
- [x] Send single test case is not working after few executions

**Severity**:
High

**Priority**:
Medium

**Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit-shared-lib/pull/7
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/75

**Specifications**
  - Component (if known): TTK UI
  - Version: latest
  - Bug found/raised by: @vijayg10

**Comment by modusemerson** [comment]
Hi @vijayg10   I saw we have the option to duplicate request within the same TC which is great but now the problem I see is that
I cannot re-organize the scripts within the same test case... 

For example I duplicate the first request in this test case and the new (duplicate) is located last in the list of request and there is no way to move any request within every test case

![image](https://user-images.githubusercontent.com/44206161/103304211-a4fb7b80-49cd-11eb-98a7-75261ac7ce7c.png)

**Comment by vijayg10** [comment]
> Hi @vijayg10 I saw we have the option to duplicate request within the same TC which is great but now the problem I see is that
> I cannot re-organize the scripts within the same test case...
> 
> For example I duplicate the first request in this test case and the new (duplicate) is located last in the list of request and there is no way to move any request within every test case
> 
> ![image](https://user-images.githubusercontent.com/44206161/103304211-a4fb7b80-49cd-11eb-98a7-75261ac7ce7c.png)

Hi @modusemerson , you can use the option in test case menu to re-arrange the requests. Yeah it is now a bit difficult to find that option. We should place that in a better place.
![Screenshot 2020-12-29 at 11 45 18 PM](https://user-images.githubusercontent.com/33152110/103304987-02281900-4a30-11eb-819b-5ac061731229.png)

**Comment by modusemerson** [comment]
Ohh thanks @vijayg10  thats really helpful!

Also I noticed this issue, I have a environment variable that I saved in a previous request and then I try to use this variable as a Parameter in another request and Im not able to get the value in there.. I can access the value from the PRE-REQUEST/POST-request screen but not from here....  am I doing something wrong @vijayg10  ?

![image](https://user-images.githubusercontent.com/44206161/103309506-e0507700-49da-11eb-9696-2ea8b77cb2f5.png)
