### ISSUE TITLE
TTK is not being deployed with published mojaloop helm

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#1957]
**Summary**:
The testing toolkit is not being deployed with the published mojaloop helm version 11.0.0
(Observation: The dependency charts of ml-testing-toolkit chart are missing in the published mojaloop chart. i.e _mojaloop/charts/ml-testing-toolkit/charts_ )

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
When I deploy the mojaloop helm version 11.0.0, I should get the testing toolkit related services running in the cluster along with mojaloop core services.

**Steps to Reproduce**
  1. Run the command `helm install --dry-run mojaloop mojaloop/mojaloop  > ./tmp_with_ttk.yaml`
  2. Observe the file tmp_with_ttk.yaml
  3. You can't see testing toolkit related deployments in that other than few lines which are related to ttk-post-hook, not the actual ttk service.

**Specifications**
  - Component (if known): helm/mojaloop
  - Version: 11.0.0
  - Bug found/raised by: @lewisdaly @vijayg10 

**Notes**:

**Comment by mdebarros** [comment]
PR created https://github.com/mojaloop/helm/pull/406

The issue was due to the ordering of helm charts specified in the `package.sh`, i.e. the Mojaloop helm chart was being packaged before the TTK chart....thus resulting in the missing dependencies required by the TTK chart.

**Comment by mdebarros** [comment]
PR https://github.com/mojaloop/helm/pull/407 for master branch
