### ISSUE TITLE
[api-snippets][account-lookup-service][als-consent-oracle] Needs investigation. Update PartyTypeId with CONSENT Enum.

### ISSUE THREAD

**Issue by kleyow** [mojaloop/project#1964]
## **Goal**:
`As a` developer

`I want to` add CONSENT enum to PartyTypeId to our various reliant schemas
  
`so that` validation will pass successfully

This needs investigation in terms of the participant look up process to see if PartyTypeId is actually sent and needed to be updated with a CONSENT Enum.
This also brings up the discussion that CONSENT isn't technically related to a "Party".

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by lewisdaly** [comment]
While we are doing this, we should also add the `THIRD_PARTY_LINK` enum, which was proposed by Michael in the v0.1 API Draft.

>  This also brings up the discussion that CONSENT isn't technically related to a "Party".

This is a good point. We've bandied about the idea of doing similar lookups with the ALS (I suppose you would say non-'account' related), but this is the first time we are doing it. 

@MichaelJBRichards do you have any thoughts about overusing the enum name `PartyTypeId` for non "party" related information?
