### ISSUE TITLE
Incorrect links in Documentation

### ISSUE THREAD

**Issue by RobReeve** [mojaloop/project#1980]
**Summary**:
Links in Mojaloop Specification Overview failing

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
Click on a link - it does not 404.

**Steps to Reproduce**
  1. Go to https://docs.mojaloop.io/mojaloop-specification/
  2. Click on HyperLink call "This Document" for example in Glossary
  3. Get 404

**Specifications**
  - Component (if known): Mojaloop Specification Overview
  - Version: Production
  - Platform: GitBooks / GitHub
  - Subsystem:
  - Type of testing: Manual
  - Bug found/raised by: RobReeve

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by elnyry-sam-k** [comment]
Should be fixed now with the latest release: https://github.com/mojaloop/mojaloop-specification/releases/tag/v11.0.0

Thanks @RobReeve for raising this..

**Comment by RobReeve** [comment]
Thanks @elnyry-sam-k 
The [Glossary](https://docs.mojaloop.io/mojaloop-specification/fspiop-api/documents/Glossary.html) 
Link to ITU-Int (external doc) is not working. From memory this [link](https://www.itu.int/dms_pub/itu-t/opb/tut/T-TUT-ECOPO-2018-PDF-E.pdf) is the final glossary, it is possible the original link was to the proposed text and this was the formal output.

There might be one or 2 buried in the deeper documentation - but with a quick scan, I could not see any at the top of documents.

**Comment by elnyry-sam-k** [comment]
This is now fixed as well - https://docs.mojaloop.io/mojaloop-specification/fspiop-api/documents/Glossary.html . Thanks Rob....
