### ISSUE TITLE
Central-Directory Functional Tests are broken

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#201]
**Goal**:
As a developer I want the Central-Directory Functional Tests to pass

**Tasks**:
- [ ] Fix Central-Directory Functional Tests                  

**Acceptance Criteria**:
- [ ] Central-Directory Functional Tests pass 100%

**Dependencies**:
n/a

**Comment by elnyry** [comment]
This may not be applicable anymore or will be taken up after central directory is updated to conform to the Mojaloop Spec.
