### ISSUE TITLE
Postman Golden Path collection is failing because of test: Check Settlements Error #956

### ISSUE THREAD

**Issue by vgenev** [mojaloop/project#2013]
**Summary**:
Golden Path test: Check Settlements Error #956 is failing with @hapi/joi module v17.1.1 in central-settlement service. As error object has changed after release 16.0.0: https://github.com/sideway/joi/issues/2037 (see: any.allowOnly -> any.only)

**Severity**:
(Medium)

**Priority**:
(Critical)

**Expected Behavior**
Golden path test should pass without errors. 

**Steps to Reproduce**
  1. Start Settlement service
  2. Send Request for Check Settlements Error #956 from Postman Golden collection
  3. Settlement Service returns:

```
{
    "errorInformation": {
        "errorCode": "3100",
        "errorDescription": "Generic validation error - \"state\" must be one of [OPEN, CLOSED, PENDING_SETTLEMENT, SETTLED, ABORTED]"
    }
}
```

should return:

```
{
    "errorInformation": {
        "errorCode": "3101",
        "errorDescription": "Malformed syntax - \"state\" must be one of [OPEN, CLOSED, PENDING_SETTLEMENT, SETTLED, ABORTED]"
    }
}
```

**Specifications**
  - Component (if known): central-settlement
  - Version: v12.0.0
  - Platform: helm v12
  - Subsystem:
  - Type of testing: functional
  - Bug found/raised by: @vgenev @mdebarros 

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by elnyry-sam-k** [comment]
Fixed and validated
