### ISSUE TITLE
ALS doesn't like the `CONSENTS` type

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2015]
**Summary**:
When setting up the consent oracle, I can register an oracle at the ALS Admin service, but I can't register a participant to that oracle:

```
curl -s -X POST $ELB_URL/account-lookup-service/participants/CONSENTS/123 \
  -H 'Accept: application/vnd.interoperability.participants+json;version=1' \
  -H 'Content-Type: application/vnd.interoperability.participants+json;version=1.0' \
  -d '{
    "fspId": "dfspa"
    }'
{"errorInformation":{"errorCode":"3100","errorDescription":"Generic validation error - .path.Type should be equal to one of the allowed values"}}
```

I think we need to revise the swagger definitions to allow for the `CONSENTS` type to get this to work.

**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Expected Behavior**
I should be able to call `POST /participants/CONSENTS/...` and `POST /parties/CONSENTS/...`

**Specifications**
  - Component (if known): ALS
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by: @lewisdaly 

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by elnyry-sam-k** [comment]
Thanks @lewisdaly - but this seems like a feature request / change and not a bug, since it needs a new `TYPE` addition

**Comment by kleyow** [comment]
@lewisdaly It's CONSENT not CONSENTS, try that.

Pretty sure I added it to the `-pisp` builds 
https://github.com/mojaloop/account-lookup-service/blob/pisp/master/src/interface/api-swagger.yaml#L1174
https://github.com/mojaloop/account-lookup-service/blob/pisp/master/src/interface/admin-swagger.yaml#L551

**Comment by lewisdaly** [comment]
Wow... I feel like a bit of a ninny. Thanks @kleyow .

**Comment by lewisdaly** [comment]
> Thanks @lewisdaly - but this seems like a feature request / change and not a bug, since it needs a new `TYPE` addition

Yes indeed it is. I was thinking more for the scope of the existing changes it's a bug (and apparently it isn't). Looking from the perspective of the adoption of the pisp work upstream into Mojaloop, it is certainly a change request for the CCB to look at.

**Comment by lewisdaly** [comment]
Ok - I finally got around to testing this again, and it's looking fine to me.
