### ISSUE TITLE
Establish requirements for forensic logging, auditing

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#2029]
## **Goal**:
`As a` OSS developer

`I want to have a full view of all the requirements related to forensic logging, auditing
  
`so that` I can design an end to end solution which addresses all through a design change

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: Medium > Our platform is unique so we need to search deeper for this to ensure that nothing is missed in the process

**Uncertainty**: Low > It is archiveable

---

**Tasks**:
- [ ] TBD [ @? ]

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @MichaelJBRichards 
- QA/Review: @godfreykutumela

**Comment by lavaughan** [comment]
Hi there

Would advise this team connect to the existing workstreams already talking about this... Pedro running sessions, Adrian and Michael engaged, me from product requirements needs.  2 workstreams: feature baseline + business process needs.

Lesley-Ann

**Comment by godfreykutumela** [comment]
Noted will do @lavaughan

**Comment by rasputtintin** [comment]
@godfreykutumela please see updated story

**Comment by godfreykutumela** [comment]
Hi @MichaelJBRichards can you please have a look at this one from a business requirement perspective.

**Comment by godfreykutumela** [comment]
The logging, audit and forensic requirements will be defined as part of the Domain-Driven Development Sessions and brought here as input for further analysis and the output as input in the architecture review and redesign work. Please note @pedrosousabarreto and help track this in the problem/Solution space.

**Comment by godfreykutumela** [comment]
We will receive this from the feature baseline and business processes workstream.

**Comment by godfreykutumela** [comment]
Merged into the reference architecture
