### ISSUE TITLE
FRMS Platform Security Review and Validation

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#2034]
## **Goal**:
`As a` OSS Security Architect

`I want to` advise the FRMS team on how best to integrate security into the core of the platform
  
`so that` I can:

- Secure the FRMS module by design.
- Test and Validation Implemented Security controls

**Acceptance Criteria**:
- [ ] TBD

**Complexity**:  Medium 

**Uncertainty**:  Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @rasputtintin 
- QA/Review: @godfreykutumela

**Comment by elnyry-sam-k** [comment]
Closing as this hasn't been touched in a year and a half; please re-open when this becomes active again and if needed

**Comment by godfreykutumela** [comment]
Thanks @elnyry-sam-k
