### ISSUE TITLE
Document existing CICD policies and controls on code generation and storage, identify gaps, applicable standards and make recommendations.

### ISSUE THREAD

**Issue by rasputtintin** [mojaloop/project#2037]

**Comment by godfreykutumela** [comment]
@rasputtintin please set up a meeting with @lewisdaly

**Comment by rasputtintin** [comment]
@godfreykutumela Lewis is unavailable this week. We shall schedule a session next week.

**Comment by godfreykutumela** [comment]
Hi @rasputtintin This issue is a bit broad so I will reach out to assist in breaking it down to smaller and actionable issues.
