### ISSUE TITLE
Define the scope for the demonstration of our security model in lab or sandbox environment

### ISSUE THREAD

**Issue by rasputtintin** [mojaloop/project#2041]
## **Goal**:
`As a` Security Architect

`I want to set the scope for demonstration of our security model 1.0
  
`so that I can support the product council initiative to build an end to end Mojaloop demo for showcasing all key functions of the Mojaloop platform including all deployed security features. 

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: Low

**Uncertainty**: Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @rasputtintin @bukasaaime 
- QA/Review: @godfreykutumela @lewisdaly

**Comment by godfreykutumela** [comment]
Below is a list of suggested features to demonstrate:

1. End to end security monitoring dashboard
2. Certificate management process using the Payment Manager
3. Payment flows with and without JWS and MTLS
4. User Administration Portal
5. API Keys/Token generation process
6. ILP interlock

**Comment by lewisdaly** [comment]
> 1. End to end security monitoring dashboard
Sounds hard and like a lot of work

> 2. Certificate management process using the Payment Manager
I think we will get this with the IAC

> 3. Payment flows with and without JWS and MTLS
Already got this

> 4. User Administration Portal
Sounds hard and like a lot of work

> 5. API Keys/Token generation process
Can you be more specific? API Keys for what?

>6. ILP interlock
We already have this with the current lab

**Comment by godfreykutumela** [comment]
It seems there are various stakeholders within Mojaloop addressing the requirements and scope for the show and tell platform and we will align and support with security once the functionality scope and approach are decided and communicated. @lewisdaly please track this for us as discussed.
