### ISSUE TITLE
[testing-toolkit-ui] - "Add Header" selector includes a leading comma

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2053]
**Summary**:
When adding a predefined header in the ttk request editor, a leading comma is added to the Header, making the request fail validation

**Severity**:
Low - but really annoying ;)

**Priority**:

**Expected Behavior**

**Steps to Reproduce**
  1. Open Testing Toolkit UI > Outbound Request (e.g. http://eggmm-ttk.beta.moja-lab.live/admin/outbound_request)
  2. Add a new test case, and open the request editor > Editor
  3. Select any API and resource at random, and scroll down to the "Headers" section
  4. Click "Add Header" and select any header (e.g. `Date`)
  5. Observe the leading comma in the resulting text box

![ttk-bug-2](https://user-images.githubusercontent.com/1683980/108029690-d0b9ea00-707d-11eb-961b-aecf6ecf3da1.png)

**Specifications**
  - Component (if known): ml-testing-toolkit-ui
  - Version: `v11.5.0`

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by mdebarros** [comment]
@vijayg10 FYI

**Comment by vijayg10** [comment]
@lewisdaly This bug is resolved in the recent version of TTK. Can you please confirm?

**Comment by vijayg10** [comment]
This issues was resolved
