### ISSUE TITLE
Investigate GPL licenses after scan

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2094]
## Summary
Investigate some of the GPL findings from he recent whitesource scan on the following projects:
- [ ] ml-testing-toolkit-ui 
- [ ] finance-portal-ui

The package found was `node-forge`

**Comment by godfreykutumela** [comment]
Hi @lewisdaly Node-Forge has a BSD license so we can default instead of GPL - https://index.whitesourcesoftware.com/gri/app/reader/resource/content/asString/3f5c6caf-5100-45c6-920e-9e8e5ae744e9

**Comment by lewisdaly** [comment]
Ok, cool. That looks good to me.

**Comment by godfreykutumela** [comment]
Thanks @lewisdaly and I will close it now.
