### ISSUE TITLE
GET /parties/Type/ID/SubID does not return partySubIdOrType in the body

### ISSUE THREAD

**Issue by shashi165** [mojaloop/project#2102]
**Summary**:
`GET /parties/Type/ID/SubID` on the account-lookup-service does not return `partySubIdOrType` in the body

Request:
```
curl 'http://dev1-account-lookup-service/parties/MSISDN/27713803912/30'
  -H 'accept: application/vnd.interoperability.parties+json;version=1.0'
  -H 'content-type: application/vnd.interoperability.parties+json;version=1.0'
  -H 'date: Mon, 08 Mar 2021 14:44:32 GMT'
  -H 'fspiop-source: testingtoolkitdfsp'
  -H 'traceparent: 00-aabbb5baba213423f84f3ceba11c68ef-0123456789abcdef0-00'
  -H 'user-agent: axios/0.21.1'
  --compressed
  ```

Response:
```
   "party": {
      "partyIdInfo": {
        "partyIdType": "MSISDN",
        "partyIdentifier": "27713803912",
        "fspId": "payeefsp"
      },
      "personalInfo": {
        "complexName": {
          "firstName": "Test",
          "middleName": "Test",
          "lastName": "Test"
        },
        "dateOfBirth": "1984-01-01"
      },
      "name": "Test PayeeFSP"
    }
  }
```
The root cause is legacy oracle simulator not returning  `partySubIdOrType` in the body for `GET /parties/Type/ID/SubID` hence the `account-lookup-service` is not returning that in the body(since `account-lookup-service` just forwards the response from the oracle simulator)
**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**

response should have `partySubIdOrType` in the body
```
   "party": {
      "partyIdInfo": {
        "partyIdType": "MSISDN",
        "partyIdentifier": "27713803912",
        partySubIdOrType: 30
        "fspId": "payeefsp"
      },
      "personalInfo": {
        "complexName": {
          "firstName": "Test",
          "middleName": "Test",
          "lastName": "Test"
        },
        "dateOfBirth": "1984-01-01"
      },
      "name": "Test PayeeFSP"
    }
  }
  ```

**Steps to Reproduce**
  1. add a party with a `partySubIdOrType`
  2. get party with that partySubIdOrType
  

**Specifications**
  - Component (if known): `sdk-scheme-adapter`
  - Version:  v11.3.2
  - Platform: Mojaloop
  - Subsystem:
  - Type of testing: testing tool kit
  - Bug found/raised by: @shashi165 

**Notes**:

This issue is caused by incorrect property name in `party` object sent by `mojaloop-simulator` while transforming the `party` object to mojaloop format in `sdk-scheme-adapter`

- Severity when opened: Medium
- Priority when opened: Medium

**PRs**:

 - [x] https://github.com/mojaloop/mojaloop-simulator/pull/93

**Comment by elnyry-sam-k** [comment]
As we discussed, this is not a bug @shashi165 ..

The Switch itself just relays the information passed on by an FSP (here by a simulator), so unless the Switch really doesn't accept a message (`PUT /parties`) with `partySubIdOrType` included, it is not a bug..
