### ISSUE TITLE
Proposal: Identity and Access Management (IAM) for Mojaloop - Kube2iam

### ISSUE THREAD

**Issue by bukasaaime** [mojaloop/project#2118]
## **Goal**:
`As a` Security Specialist

`I want to` Investigate Identitiy and Access Management (IAM) for Kubernetes Cluster using AWS IAM. The AWS IAM can later be replaced by an other clould or on prem equivalent IAM system.
  
`so that` microservices can be permissioned according to an IAM assumed role by an IAM subsystem.  In this keys, I will be examining the **kube2aim** service.

**kube2iam**

Provide IAM credentials to containers running inside a Kubernetes cluster based on annotations.
Context.

Traditionally in AWS, service level isolation is done using IAM roles. IAM roles are attributed through instance profiles and are accessible by services through the transparent usage by the aws-sdk of the ec2 metadata API. When using the aws-sdk, a call is made to the EC2 metadata API which provides temporary credentials that are then used to make calls to the AWS service.
Problem statement.

The problem is that in a multi-tenanted containers based world, multiple containers will be sharing the underlying nodes. Given containers will share the same underlying nodes, providing access to AWS resources via IAM roles would mean that one needs to create an IAM role which is a union of all IAM roles. This is not acceptable from a security perspective.

**Solution**

The solution is to redirect the traffic that is going to the ec2 metadata API for docker containers to a container running on each instance, make a call to the AWS API to retrieve temporary credentials and return these to the caller. Other calls will be proxied to the EC2 metadata API. This container will need to run with host networking enabled so that it can call the EC2 metadata API itself.

![image](https://user-images.githubusercontent.com/33176495/110782959-7113c080-8270-11eb-8768-4384a096c11e.png)

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: High. IAM involves working with role and permissions and their mapping to the different services on a granular level.

**Uncertainty**: Medium. Time constraint.

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @bukasaaime 
- QA/Review: @godfreykutumela

**Comment by bukasaaime** [comment]
Continuing evaluation.

**Comment by godfreykutumela** [comment]
Hi @bukasaaime was this issue completed? Please update it accordingly!
