### ISSUE TITLE
Create Settlement for Closed Window getting Failed

### ISSUE THREAD

**Issue by sivachundur** [mojaloop/project#2126]
**Summary**:
Getting this error message while running the CREATE settlements tests in MMD-QA we run some transfers within the window we should be allowed to create a new settlement

Req:
`POST 'https://extgw.qa.pre.myanmarpay-pre.io:8243/settlements/1.0/settlements'
![image-20210319-011545](https://user-images.githubusercontent.com/52545930/111797341-15d87280-88ef-11eb-8311-68424dfca740.png)
`

Res:
```
{
    "errorInformation": {
        "errorCode": "3100",
        "errorDescription": "Generic validation error - Inapplicable windows 6"
    }
}
```

It is throwing the same error from TTK and postman

**Severity**:
High

**Priority**:
Critical

**Expected Behavior**

**Steps to Reproduce**
  1. Trigger the test "Create Settlement for Closed Window" in Goldenpath mojaloop collection

**Specifications**
  - Component (if known): Settlement
  - Version: 
  - Platform: MMD-QA
  - Subsystem:
  - Type of testing: Postman & TTK
  - Bug found/raised by: Emerson Pereira

**Notes**:

- Severity when opened: High
- Priority when opened: High

**Analysis**
The below Kafka  error seen in the pod:  **mojaloop-centralsettlement-5fcc445bc7-xxxx** when it is creating the handler for consumer.

```
2021-03-16T14:52:38.989Z - error: Consumer::onError()[topics='topic-settlementwindow-close'] - Error: Local: Broker transport failure
    at Function.createLibrdkafkaError [as create] (/opt/central-settlement/node_modules/@mojaloop/central-services-stream/node_modules/node-rdkafka/lib/error.js:402:10)
    at /opt/central-settlement/node_modules/@mojaloop/central-services-stream/node_modules/node-rdkafka/lib/client.js:340:28)
2021-03-16T14:52:38.989Z - warn: CreateHandler::connect - error: Error: broker transport failure
```

**Comment by shashi165** [comment]
Restarting the kafka pod fixed the issue
