### ISSUE TITLE
Reported vulnerability in the account-lookup-service-api 

### ISSUE THREAD

**Issue by godfreykutumela** [mojaloop/project#2131]
## **Goal**:
`As a` OSS-MPQS team

`I want to investigate the reported vulnerability from Mowali in the account-lookup-service-api 
  
`so that I can put a remediation plan in place and also avoid future occurrence 

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: Low

**Uncertainty**:  Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: @godfreykutumela

**Comment by elnyry-sam-k** [comment]
@godfreykutumela - is this a generic issue for the regular alerts that dependabot /snyk provides or is it related to a specific vulnerability?

**Comment by godfreykutumela** [comment]
@elnyry-sam-k It was picked up by Snyk on Mowali's end so can we check if it was ever picked by dependabot and also check if is not a false positive

**Comment by lewisdaly** [comment]
@godfreykutumela do you have a link to the vulnerability?

**Comment by godfreykutumela** [comment]
This is resolved. Mowali to pick up updates directly from Mojaloop repositories or indicate if they want to make use of the ML operator in the future.

**Comment by elnyry-sam-k** [comment]
Thats great to hear! Thanks @godfreykutumela and everyone who made it so!
