### ISSUE TITLE
Deliver capability and (role based) access to DFSPs to request and view a Settlement Reconciliation Report

### ISSUE THREAD

**Issue by Dorota-MB** [mojaloop/project#2220]

**Comment by PaulGregoryBaker** [comment]
- [ ] Build part of the Settlements and Transactions BC abstract layer that provides information (& access) needed for DFSPs to request and view a settlement reconciliation report. The interfaces need to be in line with reference architecture and have RBAC authorization and logging. 
- [ ] Demonstrate how an FSP can generate and view a Settlement Reconciliation report.
