### ISSUE TITLE
[sdk-standard-component] TypeScript error: use of unexported/undeclared members in namespace

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#2235]
**Summary**:
The SDK Standard Component's typing file (index.d.ts) make references to the following undeclared members resulting in transpilation error in dependent TypeScript projects:
```
-  tpAPI.Schemas.ConsentsIDPatchResponse
-  tpAPI.Schemas.ConsentsIDPutResponseUnsigned
-  tpAPI.Schemas.ConsentRequestsIDPutResponseOTPAuth
-  tpAPI.Schemas.ConsentRequestsIDPutResponseWebAuth
```
All failed references were made from `sdk-standard-components/index.d.ts` typing file.

**Severity**: High

**Priority**: Critical

**Expected Behavior**
Transpilation from TypeScript to JavaScript should work correctly.

**Steps to Reproduce**
  1. Import sdk-standard-component into a TypeScript project
  2. Attempt to transpile
  3. Transpilation should fail with errors listing above undeclared references

**Specifications**
  - Component (if known): sdk-standard-component
  - Version: 15.6.1
  - Platform: 
  - Subsystem: Standard Component
  - Type of testing: 
  - Bug found/raised by: @oderayi 

**Notes**:

- Severity when opened: High
- Priority when opened: Critical

**Comment by kleyow** [comment]
"@mojaloop/api-snippets": "^12.3.5" must be installing a later version. Those components were compeletly removed. I'll push a PR that removes them.

**Comment by elnyry-sam-k** [comment]
@oderayi thanks to Kevin for looking into this.. Does the new release https://github.com/mojaloop/sdk-standard-components/releases/tag/v15.10.4 help? Please confirm

**Comment by elnyry-sam-k** [comment]
Thanks to @kleyow for fixing and @oderayi for confirming, closing it now.
