### ISSUE TITLE
Central Shared Services - Header validation does not take into account valid structure

### ISSUE THREAD

**Issue by JohannWNel** [mojaloop/project#2246]
**Summary**:
Currently, when ingesting requests, the header validation confirms that the correct headers are sent in the correct structure. Unfortunately, some integrations send the headers with formatting that is not taken into account even though the header is valid. The headers that are being passed for example is the following:  
`application/vnd.interoperability.parties+json; version=1`  
The reason for the failure is due to the space that gets added after the semi-colon.   
Due to limitations in .Net C#, [discussed in this git issue](https://github.com/dotnet/runtime/issues/30171), the header is passed in this manner.  
We are using .Net5 to build our DFSP adapter.  

So the issue is when the regex validates the header the space forces the validation to fail.

**Severity**:
Low

**Priority**:
Critical

**Expected Behavior**
Headers should be accepted with a space following the semi-colon, based on the [specification](https://datatracker.ietf.org/doc/html/rfc7231#section-3.1.1.1).

**Steps to Reproduce**
  1. Call `{{HOST_ACCOUNT_LOOKUP_SERVICE}}/parties/MSISDN/1234567890` with accept header `application/vnd.interoperability.parties+json; version=1`  

**Specifications**
  - Component (if known): Central Shared Services - header Validation
  - Version:
  - Platform: 
  - Subsystem:
  - Type of testing:
  - Bug found/raised by: Johann Nel

**Notes**:

- Severity when opened: Low
- Priority when opened: Critical

**Comment by JohannWNel** [comment]
I am looking at doing the fix myself, might just need a bit of guidance.

**Comment by elnyry-sam-k** [comment]
Thanks for the issue @JohannWNel ... will wait for your PR.. please include @vijayg10 , @mdebarros , @vgenev and @elnyry-sam-k as reviewers on your PR and we can continue the discussion there...

**Comment by elnyry-sam-k** [comment]
@JohannWNel - please confirm if you got a chance to deploy these new versions and if the issues are sorted.. we can close this out..

Thank you very much!

**Comment by elnyry-sam-k** [comment]
Included in https://github.com/mojaloop/helm/releases/tag/v13.0.0
