### ISSUE TITLE
Helm release upgrades from v12.0.0 fail when changing the Mojaloop-Simulator Helm Chart version

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2302]
**Summary**:

Helm release upgrades from v12.0.0 fail when upgrading the Mojaloop-Simulator Helm Chart version:

```log
The Deployment "dev3-sim-payeefsp-scheme-adapter" is invalid: MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**

Upgrades from 12.0.0 to 12.x.x should be successful.

**Steps to Reproduce**
  1. Install v12.0.0 with default config
  2. Upgrade v12.0.0 to v12.1.0 (WIP: https://github.com/mojaloop/helm/pull/436) with default config

**Specifications**
  - Component (if known): Helm
  - Version: v12.x.x
  - Platform: Helm
  - Subsystem: Mojaloop-Simulators Helm Chart
  - Type of testing: Manual
  - Bug found/raised by: @mdebarros

**Notes**:

- Severity when opened: Medium
- Priority when opened: Medium

**Comment by mdebarros** [comment]
The issue is caused due to labels not following [best practices](https://github.com/helm/charts/blob/master/REVIEW_GUIDELINES.md#for-deployments-statefulsets-daemonsets-appsv1beta2), specifically:

Selector labels (such as `app.kubernetes.io/name`) should not contain any Helm version-specific or release-specific information as the field is immutable:

> spec.selector.matchLabels defined in Deployments/StatefulSets/DaemonSets >=v1/beta2 must not contain helm.sh/chart label or any label containing a version of the chart, because the selector is immutable. The chart label string contains the version, so if it is specified, whenever the Chart.yaml version changes, Helm's attempt to change this immutable field would cause the upgrade to fail.

WIP [Helm release v12.1.0] includes changes to Mojaloop-Simulator specification to aligned labels to best practices -> https://github.com/mojaloop/helm/pull/436/commits/1b8c0bbeefedde765df62774a4e2d7436a14ac5d.

This, unfortunately, means that v12.1.0 Helm Release will be breaking. As such the version was bumped up to v13.0.0 to reflect this.

**Comment by elnyry-sam-k** [comment]
@mdebarros would you recommend enhancing/fixing mojaloop simulator chart to avoid this issue in the future?

**Comment by mdebarros** [comment]
> @mdebarros would you recommend enhancing/fixing mojaloop simulator chart to avoid this issue in the future?

I have aligned the selectorLabels to best practices in Helm v13.0.0 release, and this issue should not impact upgrades going forward.
