### ISSUE TITLE
Using header configurable param in Fixed Callback results in an `undefined` value

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2310]
**Summary**:
I've got the TTK set up to respond to a `GET /services` request with a `PUT /services` callback.

I want the `FSPIOP-Destination` header for the callback to be dynamic, based on the participant who send the `GET /services`. This looks like it should be possble (see screenshot below), but when I test everything the `FSPIOP-Destination` header is `undefined`.

![ttk_issue_1.png](https://images.zenhubusercontent.com/5cd963af3613073e20e46e60/1dea7381-39bf-4efa-a681-36ccaa40d98b)

![ttk_issue_2.png](https://images.zenhubusercontent.com/5cd963af3613073e20e46e60/aa8b9a47-efcf-45d1-851b-61c70a18bedf)

![ttk_issue_3.png](https://images.zenhubusercontent.com/5cd963af3613073e20e46e60/da6a3df5-83f9-4d90-8b36-f67a56453338)

**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Steps to Reproduce**
  1. Based on ttk config of participant-list-service in pisp repo (https://github.com/mojaloop/pisp/tree/master/docker-local/participant-list-service)
  2. In callback rules > event > FSPIOP-Destination > "Add configurable param to be the `FSPIOP-Source` header 
  3. Send a `GET /services/THIRD_PARTY_LINK` call to the ttk. This should result in the `FSPIOP-Destination` header of the callback to be equal to the value of the `FSPIOP-Source`
  4. Observe that the actual `FSPIOP-Destination` header of the callback is `undefined`

**Specifications**
  - Component (if known): ml-testing-toolkit
  - Version: `v11.8.1`
  - Platform: docker, linux host
  - Subsystem:
  - Bug found/raised by: @lewisdaly 

**Notes**:

I suspect this could have something to do with how the header keys are capitalized vs not capitalized in different places. I've also tested with many different permutations trying to access the header value object.

- Severity when opened:
- Priority when opened:

**Comment by lewisdaly** [comment]
@vijayg10 that screenshot shows using `{$request.headers.FSPIOP-Source}` but I should note that that was after I played around with it a bit.

The default value when using the "Add Configurable Parameter" button is `{$request.header.FSPIOP-Source}`, which is resulting in the same `undefined` issue noted above.

**Comment by kleyow** [comment]
![image](https://user-images.githubusercontent.com/5932442/123250602-def69780-d4af-11eb-8953-f700de4c61d1.png)
![image](https://user-images.githubusercontent.com/5932442/123250651-ef0e7700-d4af-11eb-93ed-3317381f244a.png)

@lewisdaly try using lower case `{$request.headers.fspiop-source}`.

**Comment by kleyow** [comment]
I bit weird that the inbound and outbound of the TTK have different case styles.

**Comment by kleyow** [comment]
Hmm. So if I remove the lowercasing of what I believe to be here https://github.com/mojaloop/ml-testing-toolkit/blob/56e58f5a0185b26a1363152843d46d873cf8f779/src/lib/rulesEngineModel.js#L314 means that we will need to update all tests/callbacks/requests that do not use the right Capitalization leading into somewhat of a breaking change for all tests that are sending requests to the TTK improperly(?), which is something that needs to be fixed anyway(?).

@lewisdaly @vijayg10 lmk what is the prefered solution. Leaving as is for now. Changing it to proper capitlization and poke everyone to make sure their heads are capitalized.

**Comment by vijayg10** [comment]
@kleyow In my opinion, we can check if all the incoming headers to TTK are normalised.
If that's the case, then during template variables replacement we should also normalise the variable name. Then users don't need to worry about the case in the header variables.

**Comment by kleyow** [comment]
@vijayg10 Sounds good.

**Comment by kleyow** [comment]
https://github.com/mojaloop/ml-testing-toolkit-ui/pull/102

**Comment by lewisdaly** [comment]
@vijayg10 I'm still experiencing this issue. I suspect it goes deeper than the UI normalization of headers.

components:
- ml-testing-toolkit `v13.1.0`
- ml-testing-toolkit-ui: `v13.0.1`


Here's some more screenshots of the problem:

- configuration: using the correct headers

![ttk_1.png](https://images.zenhubusercontent.com/5cd963af3613073e20e46e60/34f680f0-c6a2-413e-acee-ecae9fbc924d)


- callback logs - the `FSPIOP-Destination` value is still undefined in the callback


![ttk_2.png](https://images.zenhubusercontent.com/5cd963af3613073e20e46e60/1bfe5c5e-878a-4782-ad5e-7647e76badd9)

**Comment by lewisdaly** [comment]
Additionally, I'm noticing that when I select "Add Header" from the predefined list, the key seems to always get an extra `,` in front of it.

![ttk_3.png](https://images.zenhubusercontent.com/5cd963af3613073e20e46e60/1fb1b781-8ff8-4d6b-b0ed-871055c2d6b5)

**Comment by lewisdaly** [comment]
Ok, I think I see the issue. When I use the ui to set up the callback rule, it puts in `{$request.header.fspiop-source}` when it should be `${request.headers.fspiop-source}`.

When I changed that value, the callback seemed to have the correct headers in the callback (no `undefined`). So perhaps this is a UI issue still.

**Comment by kleyow** [comment]
Issue should now be fixed in v13.0.2

**Comment by vijayg10** [comment]
Thanks Kevin and Lewis
