### ISSUE TITLE
Thirdparty API - PISP MUST translate from their `payer.partyIdType` and `payer.partyIdentifier` before issuing a `POST /thirdpartyRequests/transactions`

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2316]
**Summary**:
This is a design bug that I've only just spotted when trying to link everything together... I'm not sure why we haven't seen it yet on our e2e tests.

The issue is that the `THIRD_PARTY_LINK` partyId type is being sent in the `POST /thirdpartyRequests/transactions`.

When the Payer DFSP requests a quotation, this is the PartyIdType that they use (along with the rest of the fields of the party). I think this is incorrect. Either:
1. The PISP should send a FSPIOP v1.1 compatible `Party` object for the `payee` field in `POST /thirdpartyRequests/transactions` (this is my preferred approach, since is puts less work on the DFSP), or
2. The DFSP, before requesting the quotation in `POST /quotes` can translate the `THIRD_PARTY_LINK` Party to the FSPIOP-compatible party

On a practical level (for now), that means that the quoting service (which doesn't know about `THIRD_PARTY_LINK`) cannot accept `POST /quotes` requests with a `partyIdType` of `THIRD_PARTY_LINK`. In API snippets, we've strictly defined the partyIdType for the `POST /thirdpartyRequests/transactions` to _only_ allow `THIRD_PARTY_LINK`, so a request from the PISP -> Payer DFSP -> Payee DFSP will never make its way through without a `400 Bad Request` somewhere.

#### Temporary Fix (doesn't address design considerations, but will fix the tests):
We allow all partyIdTypes (including `THIRD_PARTY_LINK`) in the request body of the `POST /thirdpartyRequests/transactions` call.

**Severity**: Medium

**Priority**: Medium

**Comment by lewisdaly** [comment]
> 2. The DFSP, before requesting the quotation in POST /quotes can translate the THIRD_PARTY_LINK Party to the FSPIOP-compatible party

On further thought (and the light of day). This needs to be the longer term solution.

The reason for that is, the PISP uses the `THIRD_PARTY_LINK` Party to communicate with the DFSP the `source of funds` as established during the account linking. 

So I suppose we can figure out how to implement that on our simulators, and add such an implementation to the backlog.

**Comment by eoln** [comment]
here is how the THIRD_PARTY_LINK problem is handled now: https://github.com/mojaloop/thirdparty-scheme-adapter/blob/master/src/models/dfspTransaction.model.ts#L183

**Comment by lewisdaly** [comment]
Thanks @eoln . I guess the best solution for this would be to add another backend request call for the DFSP to convert from a `THIRD_PARTY_LINK` Payer  to a valid `FSPIOP Payer`

**Comment by lewisdaly** [comment]
@kleyow perhaps a better workaround (instead of changing the API) is simply modify https://github.com/mojaloop/thirdparty-scheme-adapter/blob/master/src/models/dfspTransaction.model.ts#L183 to change the `PartyIdType`

I know you've already made changes to the API, but this workaround seems a little cleaner to me in the longer term. What do you think?

**Comment by kleyow** [comment]
@lewisdaly sure that can work. what should I change the `PartyIdType` to though?

**Comment by lewisdaly** [comment]
I think we could make a temporary config variable - `TEMP_OVERRIDE_QUOTES_PARTY_ID_TYPE`, and just set it to MSISDN. 

I've got space in my schedule to work on this tomorrow morning btw

**Comment by lewisdaly** [comment]
I think a longer term solution to this problem is to add a backend request between the 3p-scheme-adapter and the DFSP backend to lookup the _real_ party information given the `THIRD_PARTY_LINK` party information

**Comment by eoln** [comment]
I would suggest extending PISPTransferModel to do this extra step before asking for a quote

**Comment by elnyry-sam-k** [comment]
@lewisdaly - Kevin mentioned that we have a workaround for this now; do you think this can be closed or are there still tasks pending here?

**Comment by lewisdaly** [comment]
This will be resolved by mojaloop/project#2430
