### ISSUE TITLE
2.3.6. ML-API-Adapter - Integration Tests

### ISSUE THREAD

**Issue by ksatya77** [mojaloop/project#234]
**Goal**:
As a developer I would like to implement Integration tests for ML-API-Adapter

**Tasks**:
- [ ]  Integration Tests

**Acceptance Criteria**:
- [ ] Integration tests pass the coverage check
- [ ] CI pipeline gets executed successfully

**Dependencies**:
- [ ] #164 
- [ ] #238

**Comment by elnyry** [comment]
Adding this as tasks under item #197 and closing this one out
