### ISSUE TITLE
Create Initial Business Operations Framework Design Document for approval by Mojaloop DA

### ISSUE THREAD

**Issue by chris-me-law** [mojaloop/project#2404]
## **Goal**:
`As a` a member of the Design Authority 

`I want to` have visibility of all essential implementation details, system architecture, system components and design decisions
  
`so that` I can gain stakeholder and community approval to begin implementing the design

**Acceptance Criteria**:
- [x] Verify that a Design Document outline the key design principals has been created
- [x] Verify that the document and supporting material is source controlled
- [x] Verify that the Design Document as been presented and made accessible to the Mojaloop DA
- [x] Verify that the Design Document accepted by the Mojaloop DA

**Complexity**: High 
- Includes an element of design discovery and implementation

**Uncertainty**: High
- Plugging OathKeeper into WSO2 might not be possible

---

**Design Documentation Tasks**:
- [x] Fill in Keto Overview - Russell
- [x] OathKeeper and Keto Interaction - Russell
- [x] Provide an example of that mapping (single Tuple) - Russel
- [x] Provide an example of Permission Inheritance - Russel

**Done**
- [ ] Acceptance Criteria pass
- [ ] Document is in markdown and meets community standards
- [ ] Document is source controlled in community OSS repositories
- [ ] Document has been authorised by Executive Sponsor and Principle Architects

## **Accountability**:
- Owner: Paul Baker
- QA/Review: Vanda

**Comment by PaulGregoryBaker** [comment]
After much discussion and debate, the design hasn't change from what was originally presented to the DA.
The completion of the documents in markdown are being captured in subsequent story #2414 .
