### ISSUE TITLE
default mojaloop deploy fails using containerd-cri 

### ISSUE THREAD

**Issue by tdaly61** [mojaloop/project#2447]
**Summary**:
the default helm install of ml using 13.0.2 of the main chart fails on versions of kubernetes using containerd-cri.  This issue is that the mysql (percona) chart uses the docker.io/library/busybox:1.25.0  as an init container image but the cri pull of that images fails because of a bug /incompatibility between that image and the containerd-cri 

This failure has been observed across both Microk8s v1.21 and Rancher K3s v1.21.3

**Severity**:
(Medium)

**Priority**:
(Critical)

**Expected Behavior**
A default install of Mojaloop on k8s versions upto v1.21.x should support the following Kubernetes container runtimes:
- Docker
- Containerd

**Steps to Reproduce**
  1. select a kubernetes engine that uses containerd-cri instead of docker OR seemingly a kubernetes version of v1.21 or later
  2. run a default install e.g. helm  --install --namespace ml-app ml mojaloop/mojaloop --create-namespace
  3. note that the pod ml-centralledger-mysql-0 pods never come online 

**Specifications**
  - Component (if known):/helm/centralledger/requirements.yaml 
  See: 
        name: percona-xtradb-cluster  
        version: 1.0.8  
        repository: https://charts.helm.sh/stable
        alias: mysql
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by: @tdaly61 

**Notes**:
It looks like the bug/incompatibility is described here : https://github.com/containerd/containerd/issues/4756#issuecomment-731287262  and perhaps trying a later version of the percona chart will fix this
- Severity when opened: Well I think it is critical as anyone "trying" mojaloop install will hit issues on recent kubernetes engines
- Priority when opened: as above

**Comment by mdebarros** [comment]
@tdaly61 I would clarify this statement:

```markdown
Expected Behavior
A default install of mojaloop on k8s versions upto v1.21.x should "just work --out of the box"
```

Should be changed to be more specific:
```
Expected Behavior
A default install of Mojaloop on k8s versions upto v1.21.x should support the following Kubernetes container runtimes:
- Docker
- Containerd
```

This is not a "Kubernetes engine" issue, it's specifically a CRI Plugin issue that depends on the installed CRI Plugin.

I have tested this using K8s v1.21.x Docker runtime on my local machine without issues.

**Comment by tdaly61** [comment]
closing as this was taken care of a while back in about Mojaloop v14.0
