### ISSUE TITLE
test-cases that contain unicode characters from Github imports are incorrectly parsed

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2474]
**Summary**:
test-cases that contain Unicode characters from Github incorrectly parsed as per [Testing Toolkit Test Cases v3.0.2 release](https://github.com/mojaloop/testing-toolkit-test-cases/releases/tag/v13.0.2) as per the following files:

- https://github.com/mojaloop/testing-toolkit-test-cases/blob/master/collections/hub/golden_path/feature_tests/p2p_money_transfer/p2p_happy_path_accent_unicode.json#L66
- https://github.com/mojaloop/testing-toolkit-test-cases/blob/master/collections/hub/golden_path/feature_tests/p2p_money_transfer/p2p_happy_path_burmese_unicode.json#L66

Once imported on the UI through the Github import button, they are displayed as follows:

![Screenshot 2021-09-13 at 15.30.11.png](https://images.zenhubusercontent.com/5a0d3bc58a75884b9087a3dd/dae9013c-7b7c-41f3-b1d4-7aa0ec5d579f)
![Screenshot 2021-09-13 at 15.25.19.png](https://images.zenhubusercontent.com/5a0d3bc58a75884b9087a3dd/21dd8b9d-b7b7-4a96-8f98-36be2963cd2a)

**Severity**:
Medium

**Priority**:
High

**Expected Behavior**

The accented and Burmese test cases should correctly parse the Unicode characters as follows:

![Screenshot 2021-09-13 at 16 29 35](https://user-images.githubusercontent.com/11392873/133102346-0d4a77d4-97c2-4640-b674-cd7f56abf95a.png)
![Screenshot 2021-09-13 at 16 29 22](https://user-images.githubusercontent.com/11392873/133102374-9f392d4d-18c5-489e-9618-820ec1df0493.png)

The above screenshots were taken from importing the files directly from the local file system which parses the Unicode characters correctly, unlike via the Github import mechanism.

**Steps to Reproduce**
  1. Import Golden Path collection for [Testing Toolkit Test Cases v3.0.2](https://github.com/mojaloop/testing-toolkit-test-cases/releases/tag/v13.0.2)
  2. Use the "Github" import feature in the Collection Manager for the following use-cases:
      a. hub/golden_path/feature_tests/p2p_money_transfer/p2p_happy_path_accent_unicode.json
      b. hub/golden_path/feature_tests/p2p_money_transfer/p2p_happy_path_burmese_unicode.json
  3. Look at the `POST /repository/parties` operation for each of the above test-cases, and check the payload

**Specifications**
  - Component (if known): 
    - ml-testing-toolkit: **v13.5.1**
    - ml-testing-toolkit-ui: **v13.5.0**
  - Version: (See above)
  - Platform: Helm v13.0.2 RC
  - Subsystem: n/a
  - Type of testing: Manual
  - Bug found/raised by: @mdebarros

**Notes**:

- Severity when opened: Medium
- Priority when opened: High

**Pull Requests**:
- [ ] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/120

**Comment by elnyry-sam-k** [comment]
validated on moja2, looks good now. thanks @vijayg10
