### ISSUE TITLE
TTK Helm - The pods are not being restarted when the configmap changes

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2476]
**Summary**:
<Description regarding what the issue is (with important details) and where it is>

**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Expected Behavior**

**Steps to Reproduce**
  1.
  2.
  3.

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by:

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by mdebarros** [comment]
Supported Helm chart changes included in [Mojaloop Helm v13.0.2 Release](https://github.com/mojaloop/helm/releases/tag/v13.0.2) closed by [mojaloop/helm/pull/448](https://github.com/mojaloop/helm/pull/448).
