### ISSUE TITLE
Docs - Update CI/CD 

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#2481]
As a contributor,
I want to understand the latest CI/CD tools and process for the repos
So I can more easily contribute and be confident in the security of the released code.

We might already have this – but if not, can you please document the following:

 
 Steps, processes that the code goes through for development to final release/download
        Including automation checks (security, license, dependencies) – tools leveraged
        Then image scans, IAC, etc..

## PRs:
- [ ] https://github.com/mojaloop/documentation/pull/330

**Comment by mdebarros** [comment]
I think we should consider switching from CircleCI to Github :D

**Comment by lewisdaly** [comment]
Haha because we don't already have enough work to do...
