### ISSUE TITLE
FSPIOP API version negotiation not handled - Transfers-service

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2536]
**Summary**:

FSPIOP-API Service for **ML-API-Adapter (i.e. Transfers-service)** is not handling API Negotiation according to the [Mojaloop API Specification - Section 3.3.4.3](https://docs.mojaloop.io/mojaloop-specification/fspiop-api/documents/API%20Definition%20v1.1.html#3343-non-acceptable-version-requested-by-client).

**Severity**:
Medium

**Priority**:
High

**Expected Behavior**

1. FSPIOP API Switch Service at Switch should synchronously validate the incoming `accept` request headers, and fail with `HTTP status 406` response to the Source-Participant (i.e. Payer) if the requested version is not supported

**Steps to Reproduce**

1. Send an FSPIOP Payer Request to the FSPIOP API Switch Service with an API version that is not supported by the Switcht

**Specifications**

- Component (if known): ML-API-Adapter (i.e. Transfers-service)
- Version: v11.2.0
- Platform: n/a
- Subsystem: n/a
- Type of testing: manual
- Bug found/raised by: @mdebarros

**Notes**:

- Severity when opened: Medium
- Priority when opened: High

**Tasks** for fixing:
- [ ] PR in central services shared to support version negotiation
- [ ] Docs

**Comment by mdebarros** [comment]
This is what it looks like when we send an unsupported protocol request to the ml-api-adapter:

```json
{
  "status": 406,
  "statusText": "Not Acceptable",
  "body": {
    "errorInformation": {
      "errorCode": "3001",
      "errorDescription": "Unacceptable version requested - The Client requested an unsupported version, see extension list for supported version(s).",
      "extensionList": {
        "extension": [
          {
            "key": "1",
            "value": "0"
          },
          {
            "key": "1",
            "value": "1"
          }
        ]
      }
    }
  },
  "headers": {
    "content-type": "application/json; charset=utf-8",
    "cache-control": "no-cache",
    "content-length": "265",
    "date": "Tue, 09 Nov 2021 08:32:42 GMT",
    "connection": "keep-alive"
  }
}
```

**Comment by elnyry-sam-k** [comment]
Thanks @mdebarros ; looks good
