### ISSUE TITLE
Modify test harness to test Transfer Fulfill 

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#254]
**Goal**:
As a contributor
I would like to _modify the test harness to test Fulfills in transfers_
so that the testing of fulfill process can be automated.

**Discuss**:
- Pre-populate DB with a set of prepares and have GUIDs, as part of testing, etc

**Tasks**:
- [ ] 

**Acceptance Criteria**:
- [ ] 

**Dependencies**:
- n/a

**Accountability**:
- Owner 
- QA/Review

**Comment by elnyry** [comment]
Current QA framework, tests Fulfil process
