### ISSUE TITLE
In error notification to Payer FSP, header for source having wrong value

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2557]
**Summary**:
When the payeefsp is sending an invalid fulfillment, the switch is responding with an error callback to payerfspwith FSPIOP-Source header with the "payee fsp's ID" instead of "switch".

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**:
The error message to the payer fsp includes the switch as the header value for fspiop-source header for error messages that originate in the Switch

**Steps to Reproduce**
  1. Initiate a transfer ( parties, quotes calls and then POST /transfers)
  2. In the PUT /transfers/{ID} the fulfil request by payee fsp, send an invalid value (that passes schema validation)
  3. Notice the error message sent by the Switch to the Payer FSP

**Specifications**
  - Component (if known): central ledger
  - Version: Mojaloop v13.0.2
  - Platform: Any
  - Subsystem: notification handler (possibly fulfil handler)
  - Type of testing: Reported by an implementation team 
  - Bug found/raised by: found & reported by @sri-miriyala

**Notes**:
More details, log: https://github.com/mojaloop/central-ledger/issues/868

- Severity when opened: Medium
- Priority when opened: Medium

**Comment by elnyry-sam-k** [comment]
hi @sri-miriyala can you please confirm which version of central-ledger and ml-api-adapter this was observed on?

**Comment by mdebarros** [comment]
Headers being returned by running the `payee_invalid_fulfilment` test case from the GP Suite:
```JSON
{
  "request": {
    "uniqueId": "1636447657836t78sjc",
    "headers": {
      "content-type": "application/vnd.interoperability.transfers+json;version=1.0",
      "date": "Tue, 09 Nov 2021 08:47:37 GMT",
      "authorization": "{$inputs.NORESPONSE_BEARER_TOKEN}",
      "traceparent": "00-aabbb30ca88d7d0ded99b88cdd87124d-89bc6eb945b33b22-30",
      "user-agent": "axios/0.21.1",
      "connection": "keep-alive",
      "fspiop-http-method": "PUT",
      "fspiop-uri": "/transfers/12749fe3-028f-4f47-b349-af41cf0e0668/error",
      "fspiop-source": "switch",
      "fspiop-destination": "testingtoolkitdfsp",
      "fspiop-signature": "{\"signature\":\"Wxi3q77uMClRNGgEiw7TkvP4RWiSqDNUWiNUZcmHdvtmvxWUlCewkivzFdWrY_fgnktaY9WVbsBrzIyRNyRTRNdlqFLEaWYAQ0KwztrAJAcBru1Xa9kszJJC7tWtQ2VztapGV8uJwhS8e_AXS5-bg7ttfmiTT9W14CO5SRXdwjtqpjBTzBn0lqvP1Jrh_iwrOTBAZW43N1qbIgnT9SuhiEXijQp6vOOAO3F9ZetIj_ZWwXs1pkl7fiVkLus-HIGXSx8vv43Sy6eMmhIpkvPxaNmck_wHUaOpJUxzCrk59QhF0_2AWf66yDiL7E-LaBbKKnQEjAZsPOLVozUOnYu_EQ\",\"protectedHeader\":\"eyJhbGciOiJSUzI1NiIsIkZTUElPUC1VUkkiOiIvdHJhbnNmZXJzLzEyNzQ5ZmUzLTAyOGYtNGY0Ny1iMzQ5LWFmNDFjZjBlMDY2OC9lcnJvciIsIkZTUElPUC1IVFRQLU1ldGhvZCI6IlBVVCIsIkZTUElPUC1Tb3VyY2UiOiJzd2l0Y2giLCJGU1BJT1AtRGVzdGluYXRpb24iOiJ0ZXN0aW5ndG9vbGtpdGRmc3AiLCJEYXRlIjoiVHVlLCAwOSBOb3YgMjAyMSAwODo0NzozNyBHTVQifQ\"}",
      "tracestate": "mojaloop=eyJzcGFuSWQiOiI4OWJjNmViOTQ1YjMzYjIyIiwidGltZUFwaUZ1bGZpbCI6IjE2MzY0NDc2NTc3NDQifQ==",
      "content-length": "108",
      "host": "moja2-ml-testing-toolkit-backend:5000"
    },
    "queryParams": {},
    "body": {
      "errorInformation": {
        "errorCode": "3100",
        "errorDescription": "Generic validation error - invalid fulfilment"
      }
    }
  }
}
```
