### ISSUE TITLE
BizOps portal issues

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#2586]
**Summary**:
There are few minor bugs in the BizOps portal as below:
1. Events not showing up for the 
   - [x] quotes,
   - [x] transfers,
   - [x] settlements @vijayg10
2. [x] Date time drop down is always showing the current date as opposed to the Date on the field. This is for both From and To dates. @kleyow 
3. 403 error while accessing roles @vijayg10
4. [x] Sort on the Amount filed is not working as expected. [Seems, it is sorting based on text than numeric value.] @kleyow  - retested and problem persists. Sort alpha numerical rather than numerical. e.g. 5 is greater then 41
5. [x] Date times are inconsistent across portal. (not showing the same time zone)(Change datetime in filters to UTC or change data to reflect user's timezone) @kleyow 
6. [x] Error transfers and not properly showing up in the error summary. (Transfers object does not contain an `errorCode` string) 
7. [x] Dashboard not showing proper amount of transfers. (Fixed)
8. [x] Shell display area is not scrolling or adjusted enough for microfrontends. @kleyow 
9. [x] Transfer search does not return the amount of transfers shown in dashboard. (Might be API issue) (related to #12) 
10. [x] Move transferId field to top of page. @kleyow 
11. [x] Transfers with no associated DFSP are not protected by RBAC and are visible to everyone. (Api issue) @kirgene (Turn off config settting)
12. [x]  Hub TransferSummary query does not protect protected DFSP's from being included in the summary. (Api issue) (#9) (Not an issue for Hub operator user story. End users don't get access to TransferSummary)
13. [x] **Transfers duplicated** After a transfer is settled I.e. when the settlement batch that a transfer is part of is finalised, then the transfer is duplicated multiple time in the tracing a transfer view (@vijayg10 @kirgene ) Please see screen shot below.
14. [x] Trace a transfer dashboard titles not visible (@kleyow )
15. [x] Total transfers is incorrect and doesn't align with transfer rows and dashboard totals see screen shot below. (It is set correctly, but then changed to the smallest value in the PayerDFSP dashboard.) (@kleyow ) (Most likely an api issue)
16. [x] Payer DFSP and Payee DFSP grid columns not populated. (@kirgene)
17. [x] Payer DFSP and Payee DFSP not populated in transfer basic details modal. (@kirgene) 
18. [x] Trace a transfer microfront end is sending date to the graph ql reporting api that are not in Iso format but friendly text. (An incorrect date configuration of the web browser, will lead to an incorrect date parsing.)(@kleyow )
19. [x] Add Cache Busting to microfrontends so updates are always propagated. (@kleyow)
20. [x] Transfer search does not pull fresh results on click (@kleyow)
21. [x] Remove Settled transfer state option for filtering (@kleyow)
22. [x] Change Total Transfers copy to Total Succesful Transfers (@kleyow)

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing: Manual
  - Bug found/raised by: @sri-miriyala 

**Notes**:

- Severity when opened:
- Priority when opened:

Error List:
1. [ ] Total Errors in dashboard is not counting all the errors. I.e. in the example below querying the last moth of transfers, only one error is shown in the dashboard while 9 aborted transfers exist in the transfers list. see screen shot in comments (10 Jan 2022).
Initial assesment showed that Graph QL transfer summary query result has the same incorrect number I.e. 1.
Error transfers are not properly showing up in the error dashboard summary. (Transfers object does not contain an errorCode string)

<img width="673" alt="Screen Shot 2022-01-10 at 1 04 41 PM" src="https://user-images.githubusercontent.com/38143240/148816376-3f4ac9af-d05f-43fc-8416-408f0eb58719.png">
Note: I logged in as portaladmin user. and the date time stamps are pastmonth.
Payload:
{"operationName":"GetTransferSummaryByPayeeDFSP","variables":{"startDate":"2021-12-10T17:15:18.904Z","endDate":"2022-01-10T17:15:18.908Z"},"query":"query GetTransferSummaryByPayeeDFSP($startDate: DateTimeFlexible, $endDate: DateTimeFlexible) {\n  transferSummary(filter: {startDate: $startDate, endDate: $endDate}) {\n    count\n    errorCode\n    payeeDFSP\n    __typename\n  }\n}\n"}
Response:
{"data":{"transferSummary":[{"count":14,"errorCode":null,"payeeDFSP":"greenbankfsp","__typename":"TransferSummary"},{"count":2,"errorCode":null,"payeeDFSP":"noresponsepayeefsp","__typename":"TransferSummary"},{"count":1,"errorCode":3100,"payeeDFSP":"noresponsepayeefsp","__typename":"TransferSummary"},{"count":8,"errorCode":null,"payeeDFSP":"payeefsp","__typename":"TransferSummary"},{"count":2,"errorCode":null,"payeeDFSP":"payerfsp","__typename":"TransferSummary"},{"count":11,"errorCode":null,"payeeDFSP":"pm4mlreceiverfsp","__typename":"TransferSummary"},{"count":2,"errorCode":null,"payeeDFSP":"testfsp1","__typename":"TransferSummary"},{"count":4,"errorCode":null,"payeeDFSP":"testfsp2","__typename":"TransferSummary"}]}}

**Comment by PaulGregoryBaker** [comment]
![image](https://user-images.githubusercontent.com/40144680/144290536-89360334-1670-4f36-86d7-dc963720370f.png)
Before settlement finalised

**Comment by PaulGregoryBaker** [comment]
![image](https://user-images.githubusercontent.com/40144680/144290810-59e28114-3c1c-4631-87c4-10845a0bed9d.png)
After settlement finalised

**Comment by PaulGregoryBaker** [comment]
![image](https://user-images.githubusercontent.com/40144680/144609726-dc7b2de7-71a2-4044-9107-c5d317af629a.png)

**Comment by PaulGregoryBaker** [comment]
![image](https://user-images.githubusercontent.com/40144680/144610009-e96be849-ea93-45c3-8371-897337632bcb.png)

**Comment by sri-miriyala** [comment]
This is the current state of the portal:
<img width="772" alt="Screen Shot 2021-12-06 at 9 18 07 AM" src="https://user-images.githubusercontent.com/38143240/144862825-6367c4d1-bf0e-427a-8542-18d25cbd38b7.png">

@vijayg10 @kirgene can you pls look into this?

**Comment by sri-miriyala** [comment]
@kleyow  the below are still issues 
Error transfers and not properly showing up in the error summary. (Transfers object does not contain an errorCode string)
Dashboard not showing proper amount of transfers.
Transfer search does not return the amount of transfers shown in dashboard.

**Comment by sri-miriyala** [comment]
The env has the latest versions of API and UI which are 
reporting API latest is - reporting-hub-bop-api-svc v1.0.28 
the latest transfer microfrontend is -  v1.7.0 reporting-hub-bop-trx-ui

And this is what installed in this env: 
Image:         docker.io/mojaloop/reporting-hub-bop-api-svc:v1.0.28

But still am seeing above issues.

**Comment by PaulGregoryBaker** [comment]
Hi Sri,
I just has a look. The total transfers has been changed to total successful transfers. The aborted transfers are not included in this number.
Could this slight change of functionality be the reason?
I re-checked the counts, and they added up for me.
Could you provide an example if you still find there is an error?

**Comment by sri-miriyala** [comment]
@PaulGregoryBaker  thanks for the sessions. 
As discussed opened this ticket here: https://github.com/mojaloop/project/issues/2643
https://github.com/mojaloop/project/issues/2644
