### ISSUE TITLE
Platform Configuration BC - Secrets Client Lib

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#2595]
## **Goal**:
`As a` developer

`I want to` have the initial version of the secrets client lib from the platform configuration BC
  
`so that` I can start using it in other components that require it

Repo name: platform-configuration-bc

Note: this functionality could be included in the platform configuration bc config client lib. Need to decide if it make sense to have just one or split.

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by JulieG19** [comment]
@pedrosousabarreto, my understanding is that using a different application than vault was rejected by TGB. @elnyry-sam-k can you please add more the relevant minutes for this. @pedrosousabarreto , as a result, I am closing this ticket.
