### ISSUE TITLE
Platform Monitoring  BC - Metrics Client Lib

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#2600]
## **Goal**:
`As a` developer

`I want to` have the metrics client library
  
`so that` I can start publishing the metrics related to my code execution

Repo name: platform-monitoring-bc
Module name: metrics-client-lib

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by JulieG19** [comment]
@pedrosousabarreto, what is the status of this ticket? Can I close it as it seems quite old?
