### ISSUE TITLE
Platform configuration BC - Secrets Service

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#2602]
## **Goal**:
`As a` developer

`I want to` have the initial implementation of the platform secrets services
  
`so that` my code can start using the platform secrets functionalities

Note: this is alpha release grade, happy path only and not prod ready

Repo name: platform-configuration-bc
Module name: secret-svc

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by JulieG19** [comment]
@pedrosousabarreto , this story is quite old. Can we close it?

**Comment by JulieG19** [comment]
This ticket is not applicable anymore.
