### ISSUE TITLE
Release the Framework to MMD:QA

### ISSUE THREAD

**Issue by chris-me-law** [mojaloop/project#2623]
As a Hub Operator
I want to have the Finance Portal v3 deployed
So that I can can 

Verify that a standard set of permissions has been implemented
Verify that an MES ticket has been created requesting the deployment. 
Verify the Jira Ticket contains the following details:
- Release notes - a summary of the changes and a list of the ticket details
- Deployment runbook - info on components/services and versions, PRs, scripts, etc and how to deploy them, if needed
- Automated or manual tests to validate the new feature and check for regression.
- Documentation and handover for tech ops team to understand and take ownership of the changes and be able to support the client post release.
- L4 support - during the deployment and just after

**MES Ticket preparation document** can be found [here.](https://docs.google.com/document/d/1aVhtIQSV1htnNH6KnDmhmYgRZYgVcwjoTcHDWqIb0yY/edit)

**Critical:**
- Thitsawork QA Team Involvement in creation and pre-validation of release notes
- Thitsawork QA Team approval of tests
- Focus on Testing on Production Design (Test Currencies)

**Comment by PaulGregoryBaker** [comment]
RBAC design implementation diagram
https://mojaloop.github.io/business-operations-framework-docs/assets/img/BizOps-Framework-IaC-3.xx-&-Mojaloop-13.xx.121e7d3a.png
