### ISSUE TITLE
2.4.05.01 Issue with Central-Directory and Mock-PathFinder Integration

### ISSUE THREAD

**Issue by ksatya77** [mojaloop/project#263]
In testing the new Mojaloop deployment with Mule services, it was noticed that Central-Directory and Mock-Pathfinder integration is not working as expected. This is a placeholder to resolve that issue.

**Steps**:
- Investigate K8s outbound connection configuration?

Update has been applied and tested successfully in local environment. Once k8s aws is available, I will test there and then close the issue.

**Comment by elnyry** [comment]
Miguel: Issue identified; fix implementation currently in progress

**Comment by mdebarros** [comment]
@ksatya77 happy for you to close this. We tested and validated that the issue has been resolved on k8s-phoenix yesterday.
