### ISSUE TITLE
Mojaloop Sandbox infrastructure issues

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2637]
**Summary**:
Mojaloop Sandbox (sandbox.mojaloop.io) is having issues. The documentation is fine but when requests are made based on instructions provided, they are unable to be catered for (getting an infrastructure error).

Internal note: Rancher shows an issue with workloads as well, most likely because of nodes (/ instances) availability

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
The requests and responses (for example) for 3PPI transfers work as indicated in documentation: [https://sandbox.mojaloop.io/guides/payments/3ppi-p2p.html#background](https://sandbox.mojaloop.io/guides/payments/3ppi-p2p.html#background)

**Steps to Reproduce**
  1. Visit sandbox.mojaloop.io
  2. Try 3PPI transfer instructions
  3. Observe results in curl or postman (or a tool used for making the requests)
  4. Message below
  
Request:
```
curl --location --request POST 'http://sandbox.mojaloop.io/switch-ttk-backend/thirdpartyTransaction/partyLookup' \
--header 'accept:  application/json' \
--header 'Content-Type:  application/json' \
--data-raw '{ 
    "transactionRequestId": "b51ec534-ee48-4575-b6a9-ead2955b8069",
    "payee": {
      "partyIdType": "MSISDN",
      "partyIdentifier":"16135551212"
    }
  }'
```

Response:
```
{
    "message": "failure to get a peer from the ring-balancer"
}
```

**Specifications**
  - Component (if known): sandbox.mojaloop.io 
  - Version: latest
  - Platform: AWS / Web
  - Subsystem: AWS components / instances (nodes)
  - Type of testing: Demo / exploratory
  - Bug found/raised by: Yolande Goswell, Sam Kummary

**Notes**:

- Severity when opened: Medium
- Priority when opened: Medium

**Comment by lewisdaly** [comment]
Thanks @elnyry-sam-k I'm taking a look

**Comment by lewisdaly** [comment]
Thanks @elnyry-sam-k this mostly fixed now. I've got some todos on my backlog to make the environment more resilient and reset itself once a week or so.
