### ISSUE TITLE
Mowali reports performance issues - getDailyHubTransactionReport

### ISSUE THREAD

**Issue by sivachundur** [mojaloop/project#2638]
**Summary**:

<not relevant>

**Severity**:
High

**Priority**:
Critical

**Expected Behavior**

**Steps to Reproduce**
  1. Connect to database central_ledger
  2. Run the stored procedure - getDailyHubTransactionReport
  3. Check the metrics for DB server in Azure

**Specifications**
  - Component (if known): Mowali Reports
  - Version:  14.2 
  - Platform: Mowali UAT
  - Subsystem:  
  - Type of testing: Manual generation of Mowali reports
  - Bug found/raised by: Mowali

**Notes**:

- Severity when opened: 
- Priority when opened:

**Comment by elnyry-sam-k** [comment]
Closing this after confirmation from David Shiyanbade
