### ISSUE TITLE
intermittent failures in GP tests for 13.1.0 Release Candidate

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2654]
**Summary**:

13.1.0 Release Candidate tests are not stable with the introduction of CGS test into GP due to the async nature of the Centra-Settlement component.

Moja1 environment runs a daily GP test job. Check the #announcements channel in the Mojaloop slack org to see test result history showing the intermittent failures.

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
- GP tests in 13.1.0 should be consistent and as deterministic as possible

**Steps to Reproduce**
  1. Install 13.1.0 release candidate
  2. Run `helm test` command several times

**Specifications**
  - Component (if known): Helm
  - Version: v13.1.0 Release candidate (13.1.0-13148.8b8fd41)
  - Platform: n/a
  - Subsystem: n/a
  - Type of testing: n/a
  - Bug found/raised by: @mdebarros 

**Notes**:

Investigating 1/31:
1. Timing issue on settlement tests (retry logic)
2. Unknown issue, additional failures (inapplicable windows error)

- Severity when opened: Medium
- Priority when opened: Medium

**Comment by mdebarros** [comment]
```
Testing Toolkit Report
Test Result: PASSED
Test Suite: GP Tests
Environment: moja1.test.mojaloop.live
Total assertions: 2318
Passed assertions: 2318
Failed assertions: 0
Total requests: 551
Total test cases: 120
Passed percentage: 100.00%
Started time: Mon, 31 Jan 2022 13:40:07 GMT
Completed time: Mon, 31 Jan 2022 13:42:57 GMT
Runtime duration: 169576 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-01-31T13%3A42%3A57.345Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: GP CronJob
Environment: moja1.test.mojaloop.live
Total assertions: 2318
Passed assertions: 2318
Failed assertions: 0
Total requests: 551
Total test cases: 120
Passed percentage: 100.00%
Started time: Tue, 01 Feb 2022 08:00:11 GMT
Completed time: Tue, 01 Feb 2022 08:02:54 GMT
Runtime duration: 162948 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-02-01T08%3A02%3A54.484Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: GP CronJob
Environment: moja1.test.mojaloop.live
Total assertions: 2318
Passed assertions: 2318
Failed assertions: 0
Total requests: 551
Total test cases: 120
Passed percentage: 100.00%
Started time: Wed, 02 Feb 2022 08:00:07 GMT
Completed time: Wed, 02 Feb 2022 08:02:54 GMT
Runtime duration: 166548 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-02-02T08%3A02%3A54.348Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: GP CronJob
Environment: moja1.test.mojaloop.live
Total assertions: 2318
Passed assertions: 2318
Failed assertions: 0
Total requests: 551
Total test cases: 120
Passed percentage: 100.00%
Started time: Thu, 03 Feb 2022 08:00:04 GMT
Completed time: Thu, 03 Feb 2022 08:02:38 GMT
Runtime duration: 153854 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-02-03T08%3A02%3A38.716Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: GP CronJob
Environment: moja1.test.mojaloop.live
Total assertions: 2318
Passed assertions: 2318
Failed assertions: 0
Total requests: 551
Total test cases: 120
Passed percentage: 100.00%
Started time: Fri, 04 Feb 2022 08:00:22 GMT
Completed time: Fri, 04 Feb 2022 08:03:09 GMT
Runtime duration: 167730 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-02-04T08%3A03%3A09.989Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: GP CronJob
Environment: moja1.test.mojaloop.live
Total assertions: 2318
Passed assertions: 2318
Failed assertions: 0
Total requests: 551
Total test cases: 120
Passed percentage: 100.00%
Started time: Sat, 05 Feb 2022 08:00:09 GMT
Completed time: Sat, 05 Feb 2022 08:02:53 GMT
Runtime duration: 164083 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-02-05T08%3A02%3A53.647Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: GP CronJob
Environment: moja1.test.mojaloop.live
Total assertions: 2318
Passed assertions: 2318
Failed assertions: 0
Total requests: 551
Total test cases: 120
Passed percentage: 100.00%
Started time: Sun, 06 Feb 2022 08:00:04 GMT
Completed time: Sun, 06 Feb 2022 08:02:39 GMT
Runtime duration: 154979 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-02-06T08%3A02%3A39.381Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: GP CronJob
Environment: moja1.test.mojaloop.live
Total assertions: 2318
Passed assertions: 2318
Failed assertions: 0
Total requests: 551
Total test cases: 120
Passed percentage: 100.00%
Started time: Mon, 07 Feb 2022 08:00:19 GMT
Completed time: Mon, 07 Feb 2022 08:02:52 GMT
Runtime duration: 153140 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-02-07T08%3A02%3A52.680Z.html)

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: GP CronJob
Environment: moja1.test.mojaloop.live
Total assertions: 2318
Passed assertions: 2318
Failed assertions: 0
Total requests: 551
Total test cases: 120
Passed percentage: 100.00%
Started time: Tue, 08 Feb 2022 08:00:12 GMT
Completed time: Tue, 08 Feb 2022 08:02:52 GMT
Runtime duration: 160539 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-02-08T08%3A02%3A52.713Z.html)

**Comment by elnyry-sam-k** [comment]
Closing this after a week of passing results; most recent one: https://mojaloop.slack.com/archives/CG3MAJZ5J/p1644316664519559
