### ISSUE TITLE
Account Lookup Service Helm Charts are not correctly configuring the LIB_RESOUCE_VERSIONS

### ISSUE THREAD

**Issue by sivachundur** [mojaloop/project#2673]
**Summary**:

Account Lookup Service Helm Charts are not correctly configuring the LIB_RESOUCE_VERSIONS environment variable. Luckily this will not impact most use-cases, but its something that needs to be addressed though.

https://github.com/mojaloop/helm/blob/5c8045af6f26455c674a5d411b4acf4650705870/account-lookup-service/chart-service/templates/deployment.yaml

https://github.com/mojaloop/helm/blob/v13.0.2/account-lookup-service/chart-service/templates/deployment.yaml

Please NOTE, this would only impact Mojaloop release version `13.0.2` and older, and this should not be a bug in `13.1.0 `

So most likely we may need to create a 13.0.3 mojaloop patch release.

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
ALS to support the LIB_RESOUCE_VERSIONS parameter in the default helm chart values

**Steps to Reproduce**

1. Import the [Backward compatibility test collection](https://github.com/modusintegration/postman12.0.3/blob/main/postman/backward%20compatibility%20API%20NON%20FOREX.postman_collection.json) to POSTMAN
2. Import the environment file
3. Update the RESOURCE_VERSIONS parameter in the deployment file for sdk-scheme-adapter of payer DFSP to use v1.1 RESOURCE_VERSIONS: parties=1.1,participants=1.1,quotes=1.1,transfers=1.1
4. Trigger the backward compatibility tests  for FSPIOP v1.1
5. Check for the contentType in the request received in the ALS service

**Specifications**
  - Component (if known): account-lookup-service
  - Version: v11.7.7
  - Platform: product-qa
  - Subsystem:
  - Type of testing: FSPIOP v1.1 backward compatibility Tests
  - Bug found/raised by: @sivachundur 

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by elnyry-sam-k** [comment]
This should be no longer applicable as @mdebarros confirmed; should be fixed with v13.1.0 (where versions are made configurable)
