### ISSUE TITLE
Failures in daily cron job running GP tests

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2734]
**Summary**:

There are 18 total failures in the Mojaloop TTK GP tests that run daily. 

Results: Total Assertions: 2535, TOTAL PASSED TESTS: 2517, TOTAL FAILED TESTS: 18

Most recent test results: [here](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-04-05T08%3A03%3A27.319Z.html)

1. All failures except one are in `POST /scenarios` requests related tests, most of them failing with below error; possibly indicating issue with lookup (either a provisioning issue or bug)
```
errorCode: '3200', errorDescription: 'Generic ID not found' }
```
2. and one failure in interchange fee settlement tests

. `[Create Interchange-Fee Settlement for a single Window](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-09-06T17%3A26%3A05.367Z.html#)` fails intermittently (probably timing issue)
Ref: https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-09-06T17%3A26%3A05.367Z.html
  ```
{
  "errorInformation": {
    "errorCode": "3100",
    "errorDescription": "Generic validation error - Inapplicable windows 35"
  }
}
  ```

This bug is to capture these failures and not specific to the root cause.

**Severity**:
High

**Priority**:
Medium

**Expected Behavior**
The cron job runs with 100% pass rate (or zero failures, after running all the tests)

**Steps to Reproduce**
  1. Daily cron job running on a Mojaloop deployment
  2. Review test results (currently on the #announcements channel on Mojaloop slack)
  5.

**Specifications**
  - Component (if known): Lookup, Settlement
  - Version: v13.1.0 of Mojaloop
  - Platform: AWS (moja1)
  - Subsystem: lookup
  - Type of testing: Daily cron job
  - Bug found/raised by: elnyry-sam-k (logged)

**Notes**:

- Severity when opened: High
- Priority when opened: Medium

**Comment by mdebarros** [comment]
Two bug reports have been filed as a result of this story:
1. Helm Test Intermittent failure with 'Generic ID not found' #2925 - https://github.com/mojaloop/project/issues/2925
2. Helm Test Intermittent failure with 'Inapplicable windows' #2926 - https://github.com/mojaloop/project/issues/2926
