### ISSUE TITLE
GP tests are failing when test currencies are used

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2740]
**Summary**:
If I use test currencies such as XXX, XTS in TTK environment values, the GP test collection fails.
I think account lookup service doesn't have these currencies in the enum of the swagger file. I am not sure about the other places in mojaloop services.

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
TTK GP should pass with test currencies

**Steps to Reproduce**
  1. Deploy mojaloop 14.1.0 (13.1.1) version
  2. Change the env variable in TTK 'currency' to 'XXX'
  3. Change the env variable in TTK 'currency2' to 'XTS'
  4. Run TTK GP

**Specifications**
  - Component (if known): account-lookup-service (There may be other services where the test currencies are not listed)
  - Version: 13.1.1
  - Bug found/raised by: @vijayg10 

**Pull Requests**
- https://github.com/mojaloop/transaction-requests-service/pull/92
- https://github.com/mojaloop/account-lookup-service/pull/450
- https://github.com/mojaloop/mojaloop-simulator/pull/154

**Comment by mdebarros** [comment]
The migration-seeds would also need to be updated to include the test currencies --> https://github.com/mojaloop/account-lookup-service/blob/master/seeds/currency.js

**Comment by elnyry-sam-k** [comment]
Thanks Vijay.. Can confirm that ALS swagger doesn't have the test currencies listed in the swagger enum: https://github.com/mojaloop/account-lookup-service/blob/b2e8cf5ef7e4ebe72441f24045be5b0d890c764a/src/interface/api-swagger.yaml#L1061 , so this has to be updated as an immediate fix..

Long term - we also need to look at using api-snippets so that any changes made in one place to the API can be used in all the services..

**Comment by kleyow** [comment]
![image.png](https://images.zenhubusercontent.com/5e8dbb4f85ab382447a8a1b7/bccbb3da-3a73-47be-bad9-fdbd3d92ef40)

Only tests that are failing are transaction-requests-service ones. I've updated the currencies here https://github.com/mojaloop/transaction-requests-service and will close this once that is merged.

**Comment by elnyry-sam-k** [comment]
Thanks Kevin, good find..
