### ISSUE TITLE
Separate repository for community oriented customization / Tools around ML Eco-system 

### ISSUE THREAD

**Issue by zeemzz** [mojaloop/project#2752]
## **Goal**:
`As a` implementer of mojaloop and from open source community member 

`I want to` have a separate incubation repository within mojaloop project so that if some company / contributor have done customization on top of the core which doesn't strictly follow the community standards specified [here](https://docs.mojaloop.io/community/standards/guide.html) but is of use to community or implementer helping them fast track their user requirement can be of use to them.
  
`so that` it will help implementers fast track deployments along side will encourage implementers to open-source components around  mojaloop ML Core team can also then prioritize projects that garner credible support across the world to become the part of the core system. 

The suggested structure could be 

> ML-NonCore-Contributions
   >          -> Projects
   >          -> Design Documents 
 

The project should have a clear instruction defining that this is not part of the core mojaloop product is a community based contribution and doesn't follow coding standards as specified in mojaloop standards.

**Acceptance Criteria**:
- [ ] TBD

**Complexity**:  Low

**Uncertainty**: Low

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry-sam-k** [comment]
Sure, please let one of the maintainers or DA members know and this can be created.. Thanks!
