### ISSUE TITLE
Re-enable git hooks

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#2765]
## **Goal**:
`As a` developer 

`I want to` have pre-commit verification's executed when running "git commit" commands
  
`so that` I increase the code quality of the commits

Should run:
- yarn dep:check
- yarn build
- yarn lint
- yarn test:unit OR preferably yarn test:coverage

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by JulieG19** [comment]
Hi @pedrosousabarreto , apparently no commit under this story. Could you please confirm of this ticket and close this if no longer relevant? Thanks
