### ISSUE TITLE
Accounts and Balances Service

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#2775]
## **Goal**:
`As a` developer

`I want to` create the initial Accounts and Balances Service implementation
  
`so that` other developers can start integrating with it for their use cases

Rule/Notes for future multi-currency support:
- When creating accounts, they should include the ISO code for the currency;
- Before applying an entry, the A&B BC service should make sure both accounts have the same currency, otherwise, return an error.

List of initial endpoints:
- **GET /accounts/{id}/** - getAccountDetails - this should return the details of an account, including positions and excluding movements
- **GET /accounts/{id}/entries** - getAccountEntries - this should return the entries of an account, excluding details
- **POST /accounts/** - createAccount - this should receive initial account, with relevant information (all accounts are created with zero balance by default)
- **POST /accounts/{id}/** - "createAccountEntries - This should receive and array of entry pairs (i.e., credit account Y amount X, debit account Z amount X). Should return the new position of the affected accounts"
- **GET /accounts/?externalId={id}** - "getAccountsDetailsByExternalId" - this should be similar to getAccountDetails, but returns an array of all accounts matching the extId field on the the accounts

Later we can have another task to create this interface in gRPC.

Repo name: accounts-and-balances-bc
Module name: ledger-svc (TBC)

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by goncalogarcia99** [comment]
done - https://github.com/mojaloop/accounts-and-balances-bc/commit/e948bfcae7b92346d3ff2d877b1a5e3c1b8b01ac
