### ISSUE TITLE
[ML Bulk] Duplicate transaction not getting callback for post /bulkTransfers

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/project#2796]
**Summary**:
When re-sending a bulk transfer immediately after it is sent (with the same content, headers, payload), i.e., a duplicate request, no response/callback is received.

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
A callback should be sent (In TTK, shown in the response tab); A duplicate request if unchanged, should be treated as a GET call and response sent or if the bulktransfer is in progress, then no response is sent. If the message has same bulkTransfer ID but different headers / payload, an error callback is sent.

(It appears dup check hasn't been implemented for bulk, need to investigate and follow-up)

**Steps to Reproduce**
  1. Send a bulktransfer capture the transaction id, Quote id, individual transfers ids and the date
  2. Using same data from step 1 attempt to send another transfer
  

**Specifications**
  - Component (if known): bulk services
  - Version: v13.1.1
  - Platform: AWS
  - Subsystem: bulk duplicate checking
  - Type of testing: TTK testing / 
  - Bug found/raised by: Emerson Pereira

**Notes**:

- Severity when opened: Medium
- Priority when opened: Medium

![image](https://user-images.githubusercontent.com/10507686/176887586-b859cd45-e468-4100-8c8f-a9e44f4077fa.png)

**Comment by mdebarros** [comment]
> The below Log shows the `ML-API-Adapter Notification Handler` receiving the notification message from the `Bulk-Transfer-Prepare Handler`, which is then sent to the `PayerFSP` as a standard `Transfers` callback, instead of a `BulkTransfers` callback. This causes the callback to be sent to the `PUT /transfers/{ID}` callback end-point which results in an HTTP 400 (Invalid message) sync-response as the payload does NOT contain a valid `Transfer` callback, but rather an invalid `BulkTransfer` callback.
> 
> > PROPOSED SOLUTION
> > The message sent by the `Bulk-Transfer-Prepare Handler` for `duplicate request`, contains an incorrect action-type `PREPARE_DUPLICATE`. This action type is correct for standard `duplicate requests` for `Transfers` > but not for `BulkTransfers`.
> > A new action type will be added to the `central-services-shared` enums `BULK_PREPARE_DUPLICATE` which will be used as the action for this event. The `ML-API-Adapter Notification Handler` will then be able to correctly ignore this event, and have the `Bulk-API-Adapter Notification Handler` identify this event and process it accordingly and send it to the `PayerFSP`'s  `PUT /bulkTransfer/{ID}` callback end-point.
> 
> ...
>

Pull-requests opened to implement the above solution: 

- https://github.com/mojaloop/central-services-shared/pull/331
- https://github.com/mojaloop/central-ledger/pull/914
- https://github.com/mojaloop/bulk-api-adapter/pull/85

**Comment by mdebarros** [comment]
Helm changes were made in https://github.com/mojaloop/helm/pull/490 to validate these changes.

[testing-toolkit-test-cases/releases/tag/v14.1.0-snapshot.0](https://github.com/mojaloop/testing-toolkit-test-cases/releases/tag/v14.1.0-snapshot.0) was used for this test.

```
Testing Toolkit Report
Test Result: PASSED
Test Suite: Bulk Tests
Environment: moja2.test.mojaloop.live@v14.0.0
Total assertions: 288
Passed assertions: 288
Failed assertions: 0
Total requests: 31
Total test cases: 10
Passed percentage: 100.00%
Started time: Fri, 12 Aug 2022 15:43:46 GMT
Completed time: Fri, 12 Aug 2022 15:45:14 GMT
Runtime duration: 87809 ms
```
[View Report](https://mojaloop-oss-qa-results.s3.us-west-2.amazonaws.com/ttk-tests/reports/TTK-Assertion-Report-multi-2022-08-12T15%3A45%3A14.421Z.html)

**Comment by mdebarros** [comment]
Closing issue with https://github.com/mojaloop/project/issues/2796#issuecomment-1213272495
