### ISSUE TITLE
DOCS: Mojaloop Overview link on the Getting Started page goes to a 404 page

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#2852]
**Summary**:

Clicking the [1. Mojaloop Overview](https://docs.mojaloop.io/getting-started/) link on the [Getting Started - Your First Action] page forward to <https://docs.mojaloop.io/getting-started/demos/mojaloop-overview.html> but a `404` Not found page is displayed.

Upon refresh, the page loads correctly.

**Severity**:
High

**Priority**:
Critical

**Expected Behavior**

Clicking the [1. Mojaloop Overview](https://docs.mojaloop.io/getting-started/) link on the [Getting Started - Your First Action](https://docs.mojaloop.io/getting-started/) page forward to <https://docs.mojaloop.io/getting-started/demos/mojaloop-overview.html>  which is displayed correctly.

**Steps to Reproduce**
  1. Go to  [Getting Started - Your First Action](https://docs.mojaloop.io/getting-started/)
  2. Click [1. Mojaloop Overview](https://docs.mojaloop.io/getting-started/) link

**Specifications**
  - Component (if known): Documentation
  - Version: main
  - Platform: VuePress / AWS CDN
  - Subsystem: n/a
  - Type of testing: n/a
  - Bug found/raised by: @mdebarros 

**Notes**:

- Severity when opened: High
- Priority when opened: Critical

**Comment by tdaly61** [comment]
@elnyry-sam-k @mdebarros do we have any idea what is causing this or how to fix ?

**Comment by elnyry-sam-k** [comment]
@tdaly61 - we suspect this may be a CDN issue but we aren't sure who's supporting that setup at this time (Lewis set it up initially)..
