### ISSUE TITLE
Accounts and Balances BC - Add the auditing entries to the service

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#2857]
Goal:
- Start creating audit entries on account changes (create, update, disable, etc)
- No audit entries should be created for each journal entries

For reference, see the participants BC service:
- The index.ts of the service has the instantiation of the AuditClient
- Check the Aggregate to see the enum with the "AuditedActionNames"
- Check agg.approveParticipant() for an example
- For now, pass an null objet to the securityContext param of the audit function (this will be added later with the authorization specific task)

**Comment by goncalogarcia99** [comment]
done
[commit](https://github.com/mojaloop/accounts-and-balances-bc/commit/258a36b6dd0a65e4d74133d06fa47cbed82650d9)

**Comment by goncalogarcia99** [comment]
done
[commit](https://github.com/mojaloop/accounts-and-balances-bc/commit/86b16004c3dd0fd4836aa30d163bc96ced923b15)
