### ISSUE TITLE
Participants BC - Start using the accounts and balances client

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#2859]
Goal:
- Start using the accounts and balances client and test with it

**Comment by koekiebox** [comment]
Existing codebase needs to be updated to use the latest a+b client.

**Comment by koekiebox** [comment]
`main` branch updated. 

### WIP
https://github.com/mojaloop/participants-bc/pull/2

**Comment by pedrosousabarreto** [comment]
Done already, using the grpc accounts and balances client
