### ISSUE TITLE
Account lookup BC - domain and service

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#2876]
## **Goal**:
Initial version of the account lookup bounded context domain and rest service.

Reference Documentation page with main use cases: https://mojaloop.github.io/reference-architecture-doc/boundedContexts/accountLookupAndDiscovery/

Uses cases to implement:
- associate and dissociate parties
- get party
(for now don't implement the get participants use case)

Correction, implement get party and later the get participants:

**Comment by ruirochawork** [comment]
Test
