### ISSUE TITLE
TTK UI bugs

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2890]
**Summary**:

The following are the list of bugs identified in TTK UI. These can be handled as part of this story or some new stories can be created.

- [x] 1. If there is no metadata in a request, there is no way to enter through the UI. Reason: The info component is not visible if the metadata is null.
- [x] ~~2. If the prefix in API definitions page is empty, we can not set hosts. Reason: There is a condition to check the prefix existence while submitting the form.~~ This might be fixed as part of other story and the issue is fixed now
- [x] Implemented markdown feature for meta info for testcases to enable detail description in markdown format for test cases

**Specifications**
  - Component (if known): ml-testing-toolkit-ui
  - Version: v15.0.0
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by:

**Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/151
- [x] https://github.com/mojaloop/ml-testing-toolkit/pull/223

**Comment by elnyry-sam-k** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/2890?planning-poker) with Zenhub @kleyow @vijayg10
