### ISSUE TITLE
Accounts and Balances BC - Add gRPC service

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#2894]
Create the gRPC accounts and balances service, same features as the current http service and using the same domain lib.

`I want to` <action>
  
`so that` <reason> 

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by goncalogarcia99** [comment]
done
[commit](https://github.com/mojaloop/accounts-and-balances-bc/commit/c1550dbf34e0ebb79fd3d876e9b4318efa3a7074)

**Comment by goncalogarcia99** [comment]
done
[commit](https://github.com/mojaloop/accounts-and-balances-bc/commit/c1550dbf34e0ebb79fd3d876e9b4318efa3a7074)

**Comment by goncalogarcia99** [comment]
[commit](https://github.com/mojaloop/accounts-and-balances-bc/commit/b4084895129704cf7f5f75e58697261987654acd)

fixed the gRPC service
test coverage needs to be increased
