### ISSUE TITLE
Accounts and Balances BC - Add gRPC client lib

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#2895]
Create the gRPC client lib that talks with the gRPC service

Use this lib: https://www.npmjs.com/package/@grpc/grpc-js

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by goncalogarcia99** [comment]
done
[commit](https://github.com/mojaloop/accounts-and-balances-bc/commit/c1550dbf34e0ebb79fd3d876e9b4318efa3a7074)

**Comment by goncalogarcia99** [comment]
[commit](https://github.com/mojaloop/accounts-and-balances-bc/commit/69a0c26e83f61fffeb432490e4180c6f3f773ca8)

fixed gRPC client
test coverage needs to be increased (for now, the gRPC client is only tested with integration tests)
documentation needs to be concluded
