### ISSUE TITLE
Address Security Vulnerabilities of dependencies/packages being used in Mojaloop

### ISSUE THREAD

**Issue by kjw000** [mojaloop/project#292]
As a consumer to Mojaloop I want to ensure that all Mojaloop code is safe and there are no known vulnerabilities in the code.

Please address/resolve the following issues identified as security risks by Github:
https://github.com/mojaloop/central-directory/network/dependencies

LMK if you want me to file a bug for each one.  the risk is growing longer.

**Comment by elnyry** [comment]
Hi Kim, this is on our radar. The issue is with outdated code (currently master), the code in develop branch has updated versions which are not listed as vulnerable. Once a decision is made to merge 'master' with 'develop' and then merged, this should be taken care of.

**Comment by kjw000** [comment]
thanks Sam.  Is there an eta for that?

**Comment by elnyry** [comment]
Hi Kim, as of now haven't discussed that, will bring it up in meetings this week and get back to you.

**Comment by elnyry** [comment]
Except https://github.com/mojaloop/mock-pathfinder/network/dependencies , this issue is now closed for the rest of the central repos (master updated).

For mock-pathfinder, currently its not being worked on as part of the central services, as it is a mock service for pathfinder, so leaving it as it is. and closing this one out.

**Comment by kjw000** [comment]
Miller has requested that we resolve all the dependencies (even the mock-pathfinder) ones before we release phase 2.

**Comment by elnyry** [comment]
Ok, thanks for the update Kim.

Will take this on, in the Packaging Sprint (before the Phase2 wrap event)

**Comment by elnyry** [comment]
Fixed in
https://github.com/mojaloop/mock-pathfinder/pull/6 and
https://github.com/mojaloop/mock-pathfinder/pull/5
