### ISSUE TITLE
Setup VMs for running tests on the deployments

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#293]
**Goal**:
As a contributor
I would like to _setup Windows VMs for running tests (from Test Framework) on the deployments_
so that sanity, initial testing and any JMeter tests can be run later on

**Tasks**:
- [x] Setup a Windows VM to run the tests (from Testing Framework on the Azure setup)
  - [x] AWS
  - [x] Azure

**Acceptance Criteria**:
- [ ] A Windows VM is available and accessible to run the tests (from Testing Framework on the Azure setup)
  - [ ] AWS
  - [ ] Azure

**Dependencies**:
- None currently

**Accountability**:
- Owner @fbotha-stratuscloud 
- Review

**Comment by fbotha-stratuscloud** [comment]
AWS Instance
Server: win-phoenix-desktop1.mojaloop.live

Azure Instance
Server: win-pegasys-desktop1.mojaloop.live
