### ISSUE TITLE
Accounts and Balances - Fix currency types and precision

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#2936]
Decision made on the 16 Sep regarding how to store credit and debit amounts inside the accounts and balances service:
- In accounts, we keep:
  - Currency Code (iso)
  - Currency decimal (number of decimal points)
  - Two monotonic (ever increasing) integer values, one for creditBalance and another for debitBalance (we use node.js BigInt type);
  - Only valid operation on account.creditBalance and account.debitBalance is addition (ie, we add integers to them)
- Conversion to and from bigint must respect the defined decimal numbers for the given currency
- For now we keep a json file with the currency codes and their related decimal numbers inside the domain code of the accounts and balances BC
- We store account amounts in the accounts and balances datastores, using the string representation
- Outside Accounts and balances service we use a string representation of currency amounts - this applies even to the client libs and service apps - only the domain uses bigints inside;

---
This ticket is to reflect this decision..
Actions:
- Create an initial json file on the domain with a few example currencies and their decimal points (EUR, USD, GBP) - Later this file should come from a global configuration, for now can be static;
- change all amounts outside the domain to strings;
- change amounts inside the domain to bigints (where not already)
- add to the domain (aggregate class) two functions to:
  - given a string amount and a currency code, convert to bigint (using the currency decimal info)
  - given a bigint, a currency code, convert to string (using the currency decimal info)

**Comment by elnyry-sam-k** [comment]
hi @pedrosousabarreto , thanks for the details here.. Is this a story?

Also, can we discuss this at the DA please?

**Comment by MichaelJBRichards** [comment]
Can we formally confirm that the method proposed is consistent with [our standard](https://docs.mojaloop.io/community/archive/discussion-docs/mojaloop-decimal.html)?

**Comment by pedrosousabarreto** [comment]
**Caveat emptor:** 
This is alpha version code and none of it, or its related technical decisions, should be considered final or in any way a challenge to current specifications and standards. If any specifications or standards are offended by this code, it shall  be fixed or a change proposal presented to the DA for decision. Please consider any vNext code in this light.

**What this is:**
This is a mechanism to process and store numbers internal to this specific implementation of the _accounts and balances service_, to be used exclusively within it.
It does not, in any way, affect number representation outside this specific implementation of the _accounts and balances service_.

Number representation everywhere else outside _accounts and balances service_, will be as it is in the current Mojaloop implementation.

**Comment by elnyry-sam-k** [comment]
I'm not sure @pedrosousabarreto - was this

> This is alpha version code, and none of it, nor its related technical decisions, should be considered final or in any way a challenge to current specifications and standards. If any specifications or standards are offended by this code, it shall be fixed or a change proposal presented to the DA for decision. Please consider any vNext code in this light.

agreed in the DA or community council or elsewhere?

I'm asking because, if there's an accepted standard, was it evaluated for use and then decided to go another way because of some issue? If not why not use it instead of changing it later or use a standard now that may not be accepted later or is in disagreement with an existing standard? Would it not save time in adoption? 

If vNext code uses accepted standards, I'm of the opinion that it makes adoption and transition later easier. I've been encouraging use of vNext libraries where possible (along with others) so that when the full transition happens, it is less disruptive. Using accepted standards make this easier; of course if a conscious decision was made to go another way, and it is documented, thats a different scenario..

**Comment by elnyry-sam-k** [comment]
Thanks @pedrosousabarreto , I think thats all we're asking here: to go with the existing standards, unless they don't work for vNext (which is a valid reason and can be discussed in the DA).. 

> we will always use the standards by default

About vNext not being production ready, I understand the disclaimer, no issues there.. The problem would be creating new standards (even internally, not just outside the domain) ignoring or not following existing standards.. thats what we're trying to avoid.
