### ISSUE TITLE
Bulk Quotes Implementation is not validating a partial response acceptQuotes PUT \bulkTransactions call

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#2961]
**Summary**:
Given there are 2 transfers in the bulk request and acceptParty is true for both the transfers, When the sender fsp sends the acceptQuote:true for only 1 quote and skips sending anything for the second transfer, ~~Then the PUT response should have details of the 1 transfer for which the acceptQuote:true response was sent.~~
(This is a mis-interpretation of the expected behaviour. A partial response to an accept quotes call is considered an invalid response, and should respond appropriately.)
Then the synchronous response should contain a validation error.

**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Expected Behavior**

**Steps to Reproduce**
  1. Run TTK locally following the instructions https://github.com/mojaloop/sdk-scheme-adapter/tree/mvp/feat/%232809-local-end-to-end-func-tests/test/func
  2. Run TC 6 in https://github.com/mojaloop/sdk-scheme-adapter/blob/mvp/feat/%232809-local-end-to-end-func-tests/test/func/ttk-testcases/bulk-quotes-error-cases.json
  3.

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by: Sridevi Miriyala

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by PaulGregoryBaker** [comment]
This bug was a result of functionality that was not included in the MVP.
The required functionality is additional validation that is described in epic #3015 .
Closing this bug
