### ISSUE TITLE
Test Platform Shared Tools deployments scripts and instructions

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#2967]
Tasks:
- Test the infrastructure docker-compose deployment instructions and scripts here: https://github.com/mojaloop/platform-shared-tools/tree/main/packages/deployment/docker-compose-infra
- Test the Cross-cutting docker-compose deployment instructions and scripts here: https://github.com/mojaloop/platform-shared-tools/tree/main/packages/deployment/docker-compose-cross-cutting
- Review the documentation/instructions and suggest changes to correct them or enhance

Repo is here https://github.com/mojaloop/platform-shared-tools

**Comment by koekiebox** [comment]
@Nikhilbabup is moving onto the `platform-configuration-bc`
@pedrosousabarreto fyi.

**Comment by JulieG19** [comment]
Hi @pedrosousabarreto, could you please update on the status of this ticket? Thanks!
