### ISSUE TITLE
bulk not working when receiver fsp rejects the entire bulk transfer with an error

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#2972]
**Summary**:
Given partyLookup is skipped And there are 2 transfers with the same receiver fspid in the request and acceptParty, acceptQuote is true for both the requests, When the receiver fsp fails the entire transfer batch, Then the callback response should have the party and quote results and a failure for transfer. But currently the final callback is not received.

**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Expected Behavior**

**Steps to Reproduce**
  1. Run TTK locally using instructions https://github.com/mojaloop/sdk-scheme-adapter/tree/mvp/feat/%232809-local-end-to-end-func-tests/test/func
  2. Run TC-BT1 in https://github.com/mojaloop/sdk-scheme-adapter/blob/mvp/feat/%232809-local-end-to-end-func-tests/test/func/ttk-testcases/bulk-transfers-error-cases.json
  3.

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by: Sridevi Miriyala

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by PaulGregoryBaker** [comment]
TC-BT1 test is passing
