### ISSUE TITLE
SDK Bulk - When payerfsp sends a PUT /bulkTransaction/ID to accept party / accept quote for not all transactions, then the payerfsp SDK should throw a validation error

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#2983]
**Summary**:
When the payerfsp responds for party acceptance or quote acceptance, it should include all the transactions in the PUT/bulkTransaction/ID call either accept party / quote to true or false. If not, the payerfsp SDK should result in validation error.

**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Expected Behavior**
ACCEPTANCE CRITERIA:
Verify TC-BQ8 is updated with new asserts.
and it passes successfully with new asserts.
new asserts: to include the validation error for the no.of responses vs. no. of transfers in the POST /bulkTransaction

**Steps to Reproduce**
  1. Run the test case TC-BQ8
  2.
  3.

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by:

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by PaulGregoryBaker** [comment]
This bug was a result of functionality that was not included in the MVP.
The required functionality is additional validation that is described in epic #3015 .
Closing this bug
