### ISSUE TITLE
Bulk Payer SDK - FSPIOP PUT/bulkTransactions/error callback causing undefined read of "currentState"

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#2985]
**Summary**:
Given partyLookup is skipped And there are 2 transfers with the same receiver fspid in the request and acceptParty, acceptQuote is true for both the requests, When the receiver fsp fails the entire transfer batch, Then the callback response should have the party and quote results and a failure for transfer (TC-BT1 test case). Currently it is failing on Payerfsp SDK. Below are the screenshots showing logs.

**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Expected Behavior**

Run TC-BT1 from the tests and it should pass.
Run TC-BT2 and it should pass.
 
**Steps to Reproduce**
  1. Run TC-BT1 test case and check the logs for payer SDK and payee SDK
  2. Screenshot of logs:
  3. 
  4.

<img width="1045" alt="Screen Shot 2022-10-12 at 10 05 44 AM" src="https://user-images.githubusercontent.com/38143240/195366651-126eb548-deb9-4699-8c24-efe0855196ff.png">
<img width="197" alt="Screen Shot 2022-10-12 at 10 05 59 AM" src="https://user-images.githubusercontent.com/38143240/195366656-3240031b-ebd2-46d4-98a0-5d4cfc070470.png">
<img width="1043" alt="Screen Shot 2022-10-12 at 10 06 10 AM" src="https://user-images.githubusercontent.com/38143240/195366657-4218dfd6-cc5c-4f10-be23-bf7d63ac2859.png">
<img width="1054" alt="Screen Shot 2022-10-12 at 10 06 24 AM" src="https://user-images.githubusercontent.com/38143240/195366667-c1f68ed9-4bca-41c5-9d34-ea727ff19275.png">
<img width="1047" alt="Screen Shot 2022-10-12 at 10 07 18 AM" src="https://user-images.githubusercontent.com/38143240/195366673-a5d43d89-90da-4114-a6f3-68501db60281.png">
<img width="1054" alt="Screen Shot 2022-10-12 at 10 07 50 AM" src="https://user-images.githubusercontent.com/38143240/195366680-1ab41b1e-8145-4237-84e8-0c86eb79ffac.png">

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by:

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by kleyow** [comment]
Addressed in https://github.com/mojaloop/sdk-scheme-adapter/pull/403
