### ISSUE TITLE
bulk - Switch related NDC error is not getting propagated on the payer side

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#2993]
**Summary**:
In a bulkTransaction, when there is a NDC error on the Switch side, that error is not coming back in the PUT callback response on the payer side.

**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Expected Behavior**

**Steps to Reproduce**
  1. Submit a bulkTransaction request with transfer amount that exceeds current position. This should trigger an NDC limit error in Switch and that error details should be in the PUT callback response
  2.
  3.

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by: Sridevi Miriyala

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by kleyow** [comment]
Initial investigations lead to me to believe the error handing is not being handled correctly. `PositionHandler::positions::prepare::payerNotifyInsufficientLiquidity--BP2::null--0`  is the trace in the position handler.

I believe https://github.com/mojaloop/central-ledger/blob/83a197cdded36f71c884104587cd67d2f494ce92/src/handlers/positions/handler.js#L165 block is failing and gets dropped to the server error handling block here https://github.com/mojaloop/central-ledger/blob/83a197cdded36f71c884104587cd67d2f494ce92/src/handlers/positions/handler.js#L247
