### ISSUE TITLE
Bulk- intermittent failures when processing 50 transfers

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#2996]
**Summary**:
I am facing intermittent failures (approx 3/10) when testing 50 transfers in a bulk transaction.

**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Expected Behavior**

**Steps to Reproduce**
  1.
  2.
  3.

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by:

**Observation**:

- The switch is sending 'Transfer Expired' to payer in PUT /bulkTransfers callbacks

**Comment by PaulGregoryBaker** [comment]
Because of various other bug fixes, this is no-longer reproduceable. 

Closing issue.
