### ISSUE TITLE
Update the typescript-bc-template project with latest structure

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#3013]
Update the template to include all the recent supporting files, scripts, and package examples.

This is a recurring task, we need to make sure this repo is kept up to date

Package examples:
- service (with dockerfile example)
- internal (non-npm) lib
- npm publish'able lib

**Comment by JulieG19** [comment]
Hi @pedrosousabarreto , could you please provide status update on this one? Thanks!
