### ISSUE TITLE
Bulk prepare handler is freezing if MONGODB is disabled

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#3020]
**Summary**:
Bulk prepare handler is freezing if MONGODB is disabled

**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Expected Behavior**
If the MONGODB is expected to be enabled, the bulk prepare handler should report an error at least instead of freezing.

**Steps to Reproduce**
  1. Set the parameter MONGODB.DISABLED to true in bulk prepare handler
  2. Try a bulkTransfer
  3. The bulk prepare handler consumes first kafka message and then freezes

**Specifications**
  - Component (if known): central-ledger - bulk prepare handler
  - Version: v16.3.0
  - Bug found/raised by: @vijayg10 

**Notes**:
It seems the mongoose model creation is causing this issue at the following line
https://github.com/mojaloop/central-ledger/blob/2a9c21d3d65cc0641fb285c4a977b6d0e0852584/src/handlers/bulk/prepare/handler.js#L192
```
File: src/handlers/bulk/prepare/handler.js
BulkTransferModels.getIndividualTransferModel()
```

**Comment by elnyry-sam-k** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3020?planning-poker) with Zenhub @vijayg10 @mdebarros @kleyow @sri-miriyala
