### ISSUE TITLE
Error responses not coming to payerfsp incase of one batch fails due to timeout or error from payeefsp

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#3021]
**Summary**:
When payeefsp is sending an error response for a batch of POST/bulkQuote request, the payer is not receiving the error. But only receiving the successful response for the other batch.
Same happenning incase of payeefsp do not respond to a batch of POST/bulkQutoes, the payerfsp is not receiving the final PUT callback.

**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Expected Behavior**
TC-BQ9 should run successfully
TC-BQ11 should run successfully.

**Steps to Reproduce**
  1. Run TC-BQ9 and TC-BQ11 from the ttk functional tests collection.
  2.
  3.

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by:

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by kleyow** [comment]
https://github.com/mojaloop/sdk-scheme-adapter/pull/421
