### ISSUE TITLE
TTK UI Bug - JSON Editor in Request Editor is buggy

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#3031]
**Summary**:
The JSON editor in the "Request Editor" is buggy. The changes are not being reflected if we enter wrong JSON format.

**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Expected Behavior**

**Steps to Reproduce**
  1. Create a new Testcase and a request in that and select any post API resource
  2. Enter the following body in the editor tab
      ```
      {
        "name": "{$inputs.TTKSIM2_NAME}",
        "currency": "{$inputs.currency}"
      }
     ```
  3. Now move the curser at the end of 2nd line i.e. the line with `name` param
  4. Try to add a new line below that by pressing enter
  5. Nothing happens, this is a bug
  6. And copy the same line (2nd) and try to paste it after `,`
  7. Nothing happens, this is also an issue
Something is wrong in the JSON validation and the JSON formatter

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by:

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by elnyry-sam-k** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3031?planning-poker) with Zenhub @vijayg10
