### ISSUE TITLE
TTK UI Bug - Configurable Param is not working properly

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#3032]
**Summary**:
- [x] When an element in the request is an array, that should be properly populated in the "Configurable Param" option
- [x] When a property in the request body is selected in the `Configurable Param` dialogue, we are not able to select a different one immediately when we try to change our selection
- [x] When we select "Previous Request" from "Configurable Param" option, it should get the openAPIDefinition of the selected request. Currently its trying to get the path based on the current openAPI definition.

**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Expected Behavior**

**Steps to Reproduce**
  1.
  2.
  3.

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by:

**Pull Requests**:
- [x] https://github.com/mojaloop/ml-testing-toolkit-ui/pull/148

**Comment by elnyry-sam-k** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3032?planning-poker) with Zenhub @mdebarros @vijayg10
