### ISSUE TITLE
Default settlement is not kicked in when there is a missing settlement model

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#3040]
**Summary**:
When there is a settlement model missing for a specific currency, the default settlement model has to kick in and run settlements in a normal fashion. But this is not happening at the moment when I tried with TZS currency.

**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Expected Behavior**
When there's a missing settlement model for a specific currency, the mojaloop default settlement model has to run irrespective of the currency.

**Steps to Reproduce**
  1. Run few transfers with TZS currency.
  2. Close the window
  3. Run settlements 

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by: @sri-miriyala 

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by elnyry-sam-k** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3040?planning-poker) with Zenhub @vijayg10 @mdebarros

**Comment by mdebarros** [comment]
Issue is not re-producable.

Standard Golden Path tests pass fine with `TZS` using the default SettlementModel. In addition, I added an additional test currency `XTS` to futher validate that the default SettlementModel is settling correctly:

![Screenshot 2022-12-07 at 12 02 28](https://user-images.githubusercontent.com/11392873/206184446-6d5db492-d538-4521-9e40-13ec5402b66c.png)

**Comment by mdebarros** [comment]
> Standard Golden Path tests pass fine with `TZS` using the default SettlementModel. In addition, I added an additional test currency `XTS` to futher validate that the default SettlementModel is settling correctly:
> 
> ![Screenshot 2022-12-07 at 12 02 28](https://user-images.githubusercontent.com/11392873/206184446-6d5db492-d538-4521-9e40-13ec5402b66c.png)
> 
> As a result, a bug could not be confirmed.
> 
> However, the issue was due to the incorrect or no SettlementModel being specified when kicking off the Settlement.

@sri-miriyala please confirm if the issue has been resolved by correctly setting the settlementModel on the `POST /settlements` request.
