### ISSUE TITLE
TTK ML-GP is failing without running the entire GP collection

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#3075]
**Summary**:
When run ML GP tests from the TTK UI, they are not running completely. Some tests are neither in pass nor in fail criteria. Below is the screenshot that shows, total number of assertions, number of passed assertions and number of failed assertions. 
<img width="295" alt="Screen Shot 2022-12-16 at 9 21 09 AM" src="https://user-images.githubusercontent.com/38143240/208446989-6c1c415e-dc11-4c2d-abc7-2e7908d64003.png">

Also the test run is not showing as completed. We have to terminate it, to re-run.

**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Expected Behavior**

**Steps to Reproduce**
  1. Deploy v14.1.0 Mojaloop
  2. Run provisioning collection
  3. Run Gp test collection

**Specifications**
  - Component (if known): TTK
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by: @sri-miriyala 

**Tasks for this story (for current estimate)**:
- [x] Reproduce
- [x] Document characteristics of system when reproduced ( browser state, characteristics etc)

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by elnyry-sam-k** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3075?planning-poker) with Zenhub @mdebarros @PaulGregoryBaker @vijayg10

**Comment by kleyow** [comment]
Issue seems to be consistently happening, the amount of tests that pass/run before the UI freezes varies between runs.
On inspection it seems the websocket that is open for getting test results closes after 90s.
I believe this is a configuration that can be changed somewhere. Still investigating.

**Comment by kleyow** [comment]
Follow up. 

I believe the issue is that the ml ttk ui react is soft locking the websocket client from PONGing the server leading to a subsequent disconnection. The client will attempt to reconnect but since the server continue

**Comment by kleyow** [comment]
OutboundRequest.jsx:299 handleIncomingProgress1: 363.741943359375 ms
16:59:12.854 OutboundRequest.jsx:299 handleIncomingProgress1: 363.191162109375 ms
16:59:13.211 OutboundRequest.jsx:299 handleIncomingProgress1: 326.751953125 ms
16:59:13.565 OutboundRequest.jsx:299 handleIncomingProgress2: 331.744140625 ms
16:59:13.913 OutboundRequest.jsx:299 handleIncomingProgress2: 327.23193359375 ms
16:59:14.253 OutboundRequest.jsx:299 handleIncomingProgress2: 325.971923828125 ms
16:59:14.754 OutboundRequest.jsx:299 handleIncomingProgress2: 318.846923828125 ms
16:59:15.100 OutboundRequest.jsx:299 handleIncomingProgress2: 330.16796875 ms


OutboundRequest.jsx:303 handleIncomingProgress1: 920.82080078125 ms
17:05:39.899 OutboundRequest.jsx:303 handleIncomingProgress1: 926.431884765625 ms
17:05:40.890 OutboundRequest.jsx:303 handleIncomingProgress1: 973.029052734375 ms
17:05:41.918 OutboundRequest.jsx:303 handleIncomingProgress1: 1010.11669921875 ms
17:05:42.901 OutboundRequest.jsx:303 handleIncomingProgress2: 970.47607421875 ms
17:05:43.858 OutboundRequest.jsx:303 handleIncomingProgress2: 942.7080078125 ms
17:05:44.925 OutboundRequest.jsx:303 handleIncomingProgress2: 1042.35302734375 ms
17:05:46.027 OutboundRequest.jsx:303 handleIncomingProgress2: 978.429931640625 ms
17:05:48.085 OutboundRequest.jsx:303 handleIncomingProgress2: 941.781982421875 ms

The UI takes roughly 3x the time to process incoming outbound progress from v14->v15 for some reason.

**Comment by kleyow** [comment]
I've addressed this with a fix of increasing the ping timeout of the server so that despite the UI being unresponsive there is ample time for it to PONG.

**Comment by kleyow** [comment]
Follow up story https://github.com/mojaloop/project/issues/3113
