### ISSUE TITLE
[ml-testing-toolkit-ui] > v15 release has poor performance when running an outbound test collection

### ISSUE THREAD

**Issue by kleyow** [mojaloop/project#3113]
**Summary**:
The TTK UI when running a test collection takes an abnormally to process websocket outbound progress messages and display them.

**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Expected Behavior**
The TTK should have similar speed as with v14

**Steps to Reproduce**
  1. Use funtional test enviorment found in sdk-scheme-adapter
  2. Add console.time/timeEnd to https://github.com/mojaloop/ml-testing-toolkit-ui/blob/master/src/views/outbound/OutboundRequest.jsx#L250 code block
  3. Build image and docker-compose up
  4. Run GP collection
  5. Repeat process on both v15 and v14

OutboundRequest.jsx:299 handleIncomingProgress1: 363.741943359375 ms
16:59:12.854 OutboundRequest.jsx:299 handleIncomingProgress1: 363.191162109375 ms
16:59:13.211 OutboundRequest.jsx:299 handleIncomingProgress1: 326.751953125 ms
16:59:13.565 OutboundRequest.jsx:299 handleIncomingProgress2: 331.744140625 ms
16:59:13.913 OutboundRequest.jsx:299 handleIncomingProgress2: 327.23193359375 ms
16:59:14.253 OutboundRequest.jsx:299 handleIncomingProgress2: 325.971923828125 ms
16:59:14.754 OutboundRequest.jsx:299 handleIncomingProgress2: 318.846923828125 ms
16:59:15.100 OutboundRequest.jsx:299 handleIncomingProgress2: 330.16796875 ms

OutboundRequest.jsx:303 handleIncomingProgress1: 920.82080078125 ms
17:05:39.899 OutboundRequest.jsx:303 handleIncomingProgress1: 926.431884765625 ms
17:05:40.890 OutboundRequest.jsx:303 handleIncomingProgress1: 973.029052734375 ms
17:05:41.918 OutboundRequest.jsx:303 handleIncomingProgress1: 1010.11669921875 ms
17:05:42.901 OutboundRequest.jsx:303 handleIncomingProgress2: 970.47607421875 ms
17:05:43.858 OutboundRequest.jsx:303 handleIncomingProgress2: 942.7080078125 ms
17:05:44.925 OutboundRequest.jsx:303 handleIncomingProgress2: 1042.35302734375 ms
17:05:46.027 OutboundRequest.jsx:303 handleIncomingProgress2: 978.429931640625 ms
17:05:48.085 OutboundRequest.jsx:303 handleIncomingProgress2: 941.781982421875 ms

The UI takes roughly 3x the time to process incoming outbound progress from v14->v15 for some reason.

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by:

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by kleyow** [comment]
I believe I have narrowed down this issue to this antd issue https://github.com/ant-design/ant-design/issues/39746 and this commit https://github.com/vijayg10/ml-testing-toolkit-ui/commit/6f6376484752a87f4a7bc54ef33571620163db2f

**Comment by kleyow** [comment]
Another issue talking about antd performance https://github.com/ant-design/ant-design/issues/39167

**Comment by elnyry-sam-k** [comment]
@kleyow feel free to update the estimate
