### ISSUE TITLE
Are the thirdparty helm charts corectly named / using tempates correctly  ? consistently ? 

### ISSUE THREAD

**Issue by tdaly61** [mojaloop/project#3146]
**Summary**:
When deploying thirdparty charts in ML 15 release candidate I notice that the thridparty charts had the names 
auth-svc-d448d59b5-8f2tl                                        
tp-api-svc-99f95b88f-ngq84  
consent-oracle-7c844d4d59-sx28j   
Yet these charts we deployed at part of the helm install ml ./mojaloop command i.e. configured from the top level chart and values => shouldn't they have the helm release prepended to their name for consistency with other charts ? 

e.g. ml-auth-svc, ml-tp-api-svc , ml-consent-oracle

**Severity**:
low 

**Priority**:
medium 

**Expected Behavior**
Not sure , but it looks like the release name "should" be pre-pended. If there is a reason it is not then this ticket can be closed

**Steps to Reproduce**
  1. enable thirdparty charts 
  2. deploy from top level helm as indicated above. 
  3.

**Notes**:

- Severity when opened: 
- Priority when opened:

**Comment by elnyry-sam-k** [comment]
This should be resolved with v15.. @tdaly61 , please confirm so that we can either close or re-prioritize it (if you think it is not fixed)

**Comment by elnyry-sam-k** [comment]
closing this for now, please re-open this if it is an issue.. (should be fixed with ML v15)
