### ISSUE TITLE
2.9 Payload Validations

### ISSUE THREAD

**Issue by nikolayanastasov** [mojaloop/project#315]
**Goal**:
As a developer I would like to _make Payload Validations_ 

**Tasks**:
- [ ] Prepare payload validations

**Acceptance Criteria**:
- [ ] Prepare payload validations

**Dependencies**:
- None currently

**Accountability**:
- Owner 
- QA/Review

**Comment by elnyry** [comment]
Not part of positions.. Handled either at the ml-api-adapter level or elsewhere..
