### ISSUE TITLE
4.17 Position Handler Timeout [2.x ]

### ISSUE THREAD

**Issue by shashi165** [mojaloop/project#316]
**Goal**:
As a developer
I would like to _Implement Position Handler Timeout [2.x ]_
so that

**Tasks**:
- [ ] Implement Position Handler Timeout [2.x ]

**Acceptance Criteria**:
- [ ] Position event handler to consume rejection: decrement position and produce notification, produce transfer.

**Dependencies**:
- #330

**Accountability**:
- Owner 
- QA/Review

**Comment by elnyry** [comment]
Position handler to consume rejection: decrement position and produce notification, produce transfer? - Position Handler implementation already does this
