### ISSUE TITLE
AccountLookupBC - Non-Happy-Path: Party info with wrong header values

### ISSUE THREAD

**Issue by ruirochawork** [mojaloop/project#3181]

**Comment by elnyry-sam-k** [comment]
@ruirochawork , @jfantunes thanks for this issue and using it for tracking.

Without adding too much overhead, can I ask:
- What is the acceptance criteria for this issue?
- Following that, how can we confirm that this was done? 

This probably applies for other issues as well, but I wanted to flag this on one of them to start the discussion.
