### ISSUE TITLE
2.10 Exception Handling

### ISSUE THREAD

**Issue by nikolayanastasov** [mojaloop/project#319]
**Goal**:
As a developer I would like to _create Exception Handling_ 

**Tasks**:
- [ ] Prepare scripts for handling exceptions

**Acceptance Criteria**:
- [ ] Prepare scripts for handling exceptions

**Dependencies**:
- None currently

**Accountability**:
- Owner 
- QA/Review

**Comment by elnyry** [comment]
Moving this to product backlog, as Exception Handling is not prioritized for PI-3

**Comment by elnyry** [comment]
Duplicate of other exception/error handling stories
