### ISSUE TITLE
TransfersBC - Non-Happy-Path: Perform Transfer - PayeeFSP Rejects Transfer

### ISSUE THREAD

**Issue by ruirochawork** [mojaloop/project#3196]
The workflow provided by this UC enables the BC to effect a method through which a Transfer request rejected by the Payee is terminated.

[Reference Architecture](https://mojaloop.github.io/reference-architecture-doc/boundedContexts/transfers/#perform-transfer-payeefsp-rejects-transfer)

**Comment by elnyry-sam-k** [comment]
@jfantunes , @ruirochawork : was just looking at this and checked the diagram here for this scenario: https://mojaloop.github.io/reference-architecture-doc/boundedContexts/transfers/#perform-transfer-payeefsp-rejects-transfer . There's a misleading detail in the digram there. Do you have a sequence diagram or state-transition diagram capturing / depicting this scenario?

**Comment by pedrosousabarreto** [comment]
Hi @elnyry-sam-k please let me know what the misleading detail is so I can take a look.

**Comment by elnyry-sam-k** [comment]
(For closure) Looking at this diagram: https://mojaloop.github.io/reference-architecture-doc/boundedContexts/transfers/#perform-transfer-payeefsp-rejects-transfer , during the step from the Payee DFSP for "PUT /transfers/{ID}/error" / "Payee rejects transfer", in the FSPIOP BC, there's a step to "Validation crypto condition & fulfilment".

In reality, there wouldn't be any crypto-condition and/or fulfilment in a PUT /transfers/{ID}/error message to be validated, as an error callback only contains error information (code, message, extension list). (Minor issue, this line is also missing an arrow head/pointer, should go from Payee DFSP to FSPIOP BC)
