### ISSUE TITLE
TransfersBC - Non-Happy-Path: Perform Transfer - Timeout (Pre-Committed)

### ISSUE THREAD

**Issue by ruirochawork** [mojaloop/project#3198]
The workflow provided by this UC describes how the TransfersBC should handle a specific `transfer` when the timeout of that same transfer has been exceeded and has not yet been committed.

[Reference Architecture](https://mojaloop.github.io/reference-architecture-doc/boundedContexts/transfers/#perform-transfer-timeout-pre-committed)

NOTE: investigate the usage of scheduling for the implementation of the timeout, this is the original design in RefArch, we need to understand if it will be the best performant/scalable approach (vs local timeout implementation)

**Comment by elnyry-sam-k** [comment]
@ruirochawork , @pedrosousabarreto 

Would like to clarify this here, the wording says:
`terminate a Pre-Committed Transfer request `

How can a committed transfer be terminated?

Is there some context missing here

**Comment by ruirochawork** [comment]
Hi @elnyry-sam-k , this is probably a semantic issue, when I've mentioned `terminate` in the task description, I was referring to the `request` of the timeout, not the `transfer` itself.

I've changed the description of the first paragraph so that it's a bit more descriptive.

**Comment by elnyry-sam-k** [comment]
Thanks @ruirochawork .. 

So, the termination of a request to timeout on a committed transfer, is it effectively ignoring that event, because you cannot do anything about a committed transfer? Is that the termination usage here, for that request to time-out?

**Comment by ruirochawork** [comment]
In this task we are talking about the Pre-committed states, if the timeout is triggered after the transfer has already been committed then yes, it is ignored.
