### ISSUE TITLE
Alpha release of vNext - Jun 2023

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#3233]
Epic to contain all alpha release epics and stories.

Objective is to deliver the alpha release in Jun 2023 - PI21

**Comment by elnyry-sam-k** [comment]
@pedrosousabarreto , can you please ensure that the sub-items in the Epic are closed first before the Epic can be closed or move them out into another open Epic if that makes sense.

Here, **seven** sub-items show as still open. Please address this, thank you!

**Comment by elnyry-sam-k** [comment]
There's no change in status, still 6-7 items open in this one..
