### ISSUE TITLE
Participants BC - Withdrawal use case

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#3247]
## **Goal**:
`As an` hub operator

`I want to` be able to perform the participant withdrawals action
  
`so that` the hub accounts can be up to date with deposits and withdrawal performed by participants

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by myo-min-htet** [comment]
I just pick up this ticket.

**Comment by pedrosousabarreto** [comment]
Thanks Ko Myo, I've added the COA_CREATE_JOURNAL_ENTRY to the dev_defaults on the security BC side.
Closing this one.
