### ISSUE TITLE
Transfers BC - Handle *CallbackReport  events from FSPIOP-API and keep state with transfer

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#3249]
Handle the *CallbackReport events at the transfers to make sure we keep delivery reports for callbacks sent by IOPFSP API , originated in transfers, in the transfers BC data stores.

**Comment by JulieG19** [comment]
Hi @pedrosousabarreto, could you please update the status of this ticket and close if this is not relevant? Thanks!

**Comment by JulieG19** [comment]
work done
