### ISSUE TITLE
2.13 Documentation (JSDocs)

### ISSUE THREAD

**Issue by nikolayanastasov** [mojaloop/project#325]
**Goal**:
As a developer I would like to _create Documentation (JSDocs)_ 

**Tasks**:
- [ ] Prepare Documentation (JSDocs)

**Acceptance Criteria**:
- [ ] Prepare Documentation (JSDocs)

**Dependencies**:
- None currently

**Accountability**:
- Owner 
- QA/Review

**Comment by elnyry** [comment]
N/A as not directed against any single component. Currently, this is being checked for each story and covered there
