### ISSUE TITLE
2.14 K8s Config/Charts

### ISSUE THREAD

**Issue by nikolayanastasov** [mojaloop/project#326]
**Goal**:
As a developer I would like to _create K8s Config/Charts_ 

**Tasks**:
- [ ] Prepare K8s Config
- [ ] Prepare K8s Charts

**Acceptance Criteria**:
- [ ] Prepare K8s Config
- [ ] Prepare K8s Charts

**Dependencies**:
- None currently

**Accountability**:
- Owner 
- QA/Review

**Comment by elnyry** [comment]
Not specific to positions as such, so closing it.
