### ISSUE TITLE
AccountLookupBC - Increase test coverage for http-oracle-svc

### ISSUE THREAD

**Issue by jfantunes** [mojaloop/project#3276]
![image.png](https://images.zenhubusercontent.com/62fcc3875c345168b7868b28/02d516a1-5509-4883-aaf0-ead9bea547fb)

Currently, the coverage for the account lookup is like this.

On a separate branch, please increase coverage until 90 on the following services.

1 - http-oracle-svc - This project currently doesn't have tests.

**Comment by pedrosousabarreto** [comment]
Please separate this into 2 tasks and 2 PRs

**Comment by elijah0kello** [comment]
Thanks Pedro. On it
