### ISSUE TITLE
AccountLookupBC - Correct and improve aggregate tests

### ISSUE THREAD

**Issue by jfantunes** [mojaloop/project#3281]
On the branch non-happy-path from Account Lookup BC, the aggregate changed, and now it dispatches several error events instead of a single error event, as it was in the past.

Adapt the aggregate tests to contemplate the multiple error events sent and improve them if necessary.
These tests are located on packages/domain-lib/test/aggregate.test.ts

**Comment by pedrosousabarreto** [comment]
This was already fixed
