### ISSUE TITLE
SDK - /requestToPay is failing at validation

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#3285]
**Summary**:
When I send `/requestToPay` to SDK-Scheme-Adapter(SDK), the SDK is responding with the following error
```
{\"errorCode\":\"3101\",\"errorDescription\":\"Malformed syntax - /requestBody/transactionType/scenario must be string\"}}
```
Observed this in an IaC deployed PM4ML. But tested it with local instance of SDK-scheme-adapter and the issue remains same.

Note: The issue might be with transformation of the `transactionType` details from SDK outbound API format to FSPIOP format.

**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Expected Behavior**
1. `POST /requestToPay` should work as the API call `POST /transfers` in SDK outbound
2. The scenario field should be passed in same way

**Steps to Reproduce**
  1. Send a `POST /requestToPay` http request to an SDK instance
  3. It complains about the `scenario` field format in the payload
  4. If the `scenario` field is object, then the schema validation fails
  5. If that is a string then FSPIOP validation fails at mojaloop switch

**Specifications**
  - Component (if known): mojaloop/sdk-scheme-adapter
  - Version: v22.0.1
  - Bug found/raised by: @vijayg10 

**Pull Requests**
- [x] https://github.com/mojaloop/api-snippets/pull/160
- [x] https://github.com/mojaloop/sdk-scheme-adapter/pull/442

**Comment by elnyry-sam-k** [comment]
@vijayg10 - thanks for the issue! seems like a must fix. Minor comment on the title - should it be "failing at validation" ?

**Comment by vijayg10** [comment]
Tested the fix with the attached TTK test case in an IaC environment. The transaction request is being passed to the core connector at the payee fsp by SDK. The following is the log in SDK of receiverfsp.
```
{"ts":"2023-04-26T15:58:40.302Z","msg":"Executing HTTP POST","ctx":{"hostname":"pm4mlreceiverfsp-scheme-adapter-79dd458fbb-c2kx4","app":"mojaloop-connector-inbound-api","component":"api","request":{"id":"tasteless-able-wooden-queen","path":"/transactionRequests","method":"POST"},"reqOpts":{"method":"POST","uri":"http://pm4mlreceiverfsp-mojaloop-core-connector:3003/transactionrequests","headers":{"Content-Type":"application/json","Accept":"application/json","Date":"Wed, 26 Apr 2023 15:58:40 GMT"},"body":"{\"transactionRequestId\":\"ac31cd97-ce01-43ce-b77b-b920fcf8b931\",\"to\":{\"idType\":\"MSISDN\",\"idValue\":\"25633333333\",\"fspId\":\"pm4mlreceiverfsp\",\"dateOfBirth\":\"2010-10-10\",\"firstName\":\"PM4MLReceiverFirst\",\"middleName\":\"PM4MLReceiverMiddle\",\"lastName\":\"PM4MLReceiverLast\"},\"from\":{\"idType\":\"MSISDN\",\"idValue\":\"25644444444\",\"fspId\":\"pm4mlsenderfsp\"},\"amount\":\"10\",\"currency\":\"USD\",\"transactionType\":\"DEPOSIT\",\"initiator\":\"PAYEE\",\"initiatorType\":\"CONSUMER\"}"}}}
```
[pm4ml-request-to-pay-test.json.zip](https://github.com/mojaloop/project/files/11334956/pm4ml-request-to-pay-test.json.zip)

**Comment by mdebarros** [comment]
See https://github.com/mojaloop/project/issues/3307#issuecomment-1525372285 for test-harness that was used to validate the current RTP functionality.

The following issues observed so far with the SDK/s RTP implementation::

API-Snippets for Mojaloop SDK Backend API on POST /transactionRequest, response transferAmount --> transactionRequestState  (ref: https://github.com/mojaloop/sdk-scheme-adapter/blob/master/modules/api-svc/src/lib/model/lib/shared.js#L219) <-- minor issue that can easily be fixed
RTP on SDK’s payer side requires AUTO_ACCEPT_PARTY=true to be able to complete <-- bug 
SDK’s Inbound API is missing the PUT /transactionRequests/{transactionId}/error  <-- missing implementation
No RTP Tests against the SDK based Payer and Payee FSPs

**Comment by vijayg10** [comment]
Since the followup stories are created for the above mentioned issues, I am closing this story.

**Followup Stories:**
#3320 
#3321 
#3322
