### ISSUE TITLE
[API-Snippets/SDK-Scheme-Adapter]  missing transactionRequestState on Mojaloop SDK-Backend API def for POST /transactionRequest response

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3320]
**Summary**:
Mojaloop SDK-Backend API definition for `POST /transactionRequest` response is missing transactionRequestState.

Instead, there is a `transferAmount` that is assignable to the *transactionRequest* state. I assume this is a typo, and as such it should be renamed to `transactionRequestState`

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**

Mojaloop SDK-Backend API definition for `POST /transactionRequest` response is missing transactionRequestState as referenced in the API definition: https://github.com/mojaloop/api-snippets/blob/master/docs/sdk-scheme-adapter-backend-v2_0_0-openapi3-snippets.yaml#L1351:

```
    transactionRequestResponse:
      description: A response to a request for a quote.
      properties:
        transactionId:
          $ref: '#/components/schemas/transactionId'
        transferAmount: <-- SHOULD be transactionRequestState
          $ref: '#/components/schemas/transactionRequestState'
```

This impacts the following components:
- API-Snippets
- SDK-Scheme-Adapter

**Steps to Reproduce**
N/A.

**Specifications**
  - Component (if known):
      -  API-Snipperts: v17.0.4
      - SDK-Scheme-Adapter: v22.0.4
  - Platform: n/a
  - Subsystem: n/a
  - Type of testing: n/a
  - Bug found/raised by: @mdebarros, @vijayg10 

**Pull Requests**:
- [ ] https://github.com/mojaloop/api-snippets/pull/161

**Comment by chris-me-law** [comment]
Reason for Block: The sequence of Feature Stories required to fix this defect: 
#3345 
#3322

**Comment by vijayg10** [comment]
This issue is already covered in this PR https://github.com/mojaloop/api-snippets/pull/162
So closing the issue.
