### ISSUE TITLE
[SDK-Scheme-Adapter] RTP on SDK’s payer side requires AUTO_ACCEPT_PARTY=true to complete

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3321]
**Summary**:

RTP (Request to Pay) on SDK’s payer side requires AUTO_ACCEPT_PARTY=true to complete when sending `POST /transactionRequest`.

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**

RTP on SDK’s payer should not require AUTO_ACCEPT_PARTY=true to be able to complete.

**Steps to Reproduce**
  1. TBD

**Specifications**
  - Component (if known): SDK-Scheme-Adapter
  - Version: v22.0.4
  - Platform: n/a
  - Subsystem: n/a
  - Type of testing: n/a
  - Bug found/raised by: @mdebarros, @vijayg10 

**Pull Requests**:
- ~https://github.com/mojaloop/sdk-scheme-adapter/pull/443~
- ~https://github.com/mojaloop/api-snippets/pull/161~

**Comment by mdebarros** [comment]
Feature Story https://github.com/mojaloop/project/issues/3345 will resolve this issue.

**Comment by vijayg10** [comment]
This issue is already addressed in PR https://github.com/mojaloop/sdk-scheme-adapter/pull/445

So closing the issue
