### ISSUE TITLE
Core Test Harness - TTK tests failing

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#3359]
**Summary**:
TTK tests in ml-core-test-harness(https://github.com/mojaloop/ml-core-test-harness) are failing. Following is TTK report. It seems the problem is with `FundsIn` operation in TTK provisioning collection.

[ttk-reports.zip](https://github.com/mojaloop/project/files/11598410/ttk-reports.zip)

**Severity**:
High

**Priority**:
Medium

**Expected Behavior**

**Steps to Reproduce**
  1.
  2.
  3.

**Specifications**
  - Component (if known): ml-core-test-harness
  - Version: v0.0.4
  - Platform: MacOS
  - Subsystem:
  - Type of testing:
  - Bug found/raised by: @vijayg10 @elnyry-sam-k 

**Pull Requests**:
- [x] https://github.com/mojaloop/ml-core-test-harness/pull/6

**Comment by PaulGregoryBaker** [comment]
Activity on this issue is related to initial investigation into the cause of the bug.
