### ISSUE TITLE
AdminUI - Create a page/form to define a settlement model

### ISSUE THREAD

**Issue by ruirochawork** [mojaloop/project#3402]
## **Goal**:
`As a` developer

`I want to` have a way of setting a specific settlement model definition 
  
`so that`  it can be available for retrieval in a transfer creation

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by myo-min-htet** [comment]
settlement model creation for the backend process
