### ISSUE TITLE
Create event and subsequent logic for quote error

### ISSUE THREAD

**Issue by jfantunes** [mojaloop/project#3410]
When we try to send putQuotes/id/error in the quoting phase from the payee side, it is getting 400 error.
Add putQuotes/id/error rout as per the FSPIOP api specification.

![image.png](https://images.zenhubusercontent.com/62fcc3875c345168b7868b28/247e9775-163f-4454-9fbf-4eb0a6a44a11)

**Comment by elnyry-sam-k** [comment]
@jfantunes thanks for this issue..

Can you please point out which service the issue is observed against and is it happening when it is directed at the Switch (looking at "send ..... from payee side") ? or is it happening elsewhere..
