### ISSUE TITLE
Review the quote rejected error

### ISSUE THREAD

**Issue by jfantunes** [mojaloop/project#3465]
The route for the quote rejected wasn't added to fspiop API. Currently, it's already been added. Please test to see if it works as expected and give us feedback based on the results.

### Tasks
- [x] Add GetQuoteQueryRejectedResponseEvt handling in the FSPIOP quote event handler
- [ ] Code Review
- [ ] QA Passed

**Comment by myo-min-htet** [comment]
@einghon-phoo , please communicate with QA team to check this is working fine or not.

**Comment by einghon-phoo** [comment]
Sure, will do. Thanks!

**Comment by myo-min-htet** [comment]
@kyaw-soe-tw  I don't see that quote rejected response event do not catch by FSPIOP and please check and review.
