### ISSUE TITLE
Check test coverage of the BC's

### ISSUE THREAD

**Issue by jfantunes** [mojaloop/project#3466]
Iterate through all the BCs and collect test coverage from them.

**Comment by elnyry-sam-k** [comment]
hi @jfantunes - was the test coverage captured somewhere?

**Comment by jfantunes** [comment]
> hi @jfantunes - was the test coverage captured somewhere?

Hi @elnyry-sam-k, yes, they are currently on a spreadsheet that we will publish soon.
