### ISSUE TITLE
[Bug][Central-Ledger] CL Cache expiration with values higher than default causes transfers to fail

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#3474]
**Summary**:
Transfers fail when the cache is increased in Central-Ledger using `CLEDG_CACHE__EXPIRES_IN_MS` (e.g. 2m). This requires further investigation as it may be due to a bug in the underlying cache implementation.

**Severity**:
Medium

**Priority**:
Low

**Expected Behavior**

Transfers should pass when the cache is increased in Central-Ledger using `CLEDG_CACHE__EXPIRES_IN_MS` values larger than the default 1 second (e.g. 2m). 

**Steps to Reproduce**
  1. Configure CLEDG_CACHE__EXPIRES_IN_MS with values larger than the default value (i.e. 1 second)
  2. Run either Functional or PerformanceTests on [ml-core-test-harness](https://github.com/mojaloop/ml-core-test-harness)

**Specifications**
  - Component (if known): Central-Ledger
  - Version: v17.0.3
  - Platform: Tested using the [ml-core-test-harness](https://github.com/mojaloop/ml-core-test-harness) (master-branch)
  - Subsystem: n/a
  - Type of testing: n/a
  - Bug found/raised by: @vijayg10, @mdebarros

**Notes**:

- Severity when opened: Medium
- Priority when opened: Low

**Comment by JaneS321** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3474?planning-poker) with Zenhub @aaronreynoza @sri-miriyala @kleyow @mdebarros @oderayi
