### ISSUE TITLE
ParticipantsBC - implement approval process for account creation

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#3486]
TO BE DETAILED

We need an approval step for the account creation, like funds in/out.

Add to the IParticipantAccount:
  createdBy: string;
  createdDate: number;
  approved: boolean;
  approvedBy: string | null;
  approvedDate: nmber | null;

And implement the approval process in the aggregate.

**Comment by myo-min-htet** [comment]
PR for adding external bankInfo and approval process in aprticipant account.
[https://github.com/mojaloop/participants-bc/pull/11]
