### ISSUE TITLE
Try to remove devDependencies from dockerfile builds

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#3487]
For docker images, try to have the  "--omit=dev" on the npm install command of the final image.
We don't need devDependencies as some might not be arm64 compatible, plus, don't need 

```
# Our images don't need devDependencies
RUN BUILD_LIBRDKAFKA=0 npm install --omit=dev
```

MAKE SURE WE TESTS this doesn't break, husky for example has to be moved from `devDependencies` to `dependencies`

**Comment by JulieG19** [comment]
Hi @pedrosousabarreto, could you please update the status of this ticket and close if this is not relevant? Thanks!

**Comment by JulieG19** [comment]
work done
