### ISSUE TITLE
4.6 Design Duplicate Handling Prepare

### ISSUE THREAD

**Issue by nikolayanastasov** [mojaloop/project#350]
**Goal**:
As a developer I would like to _Design Duplicate Handling Prepare_

**Tasks**:
- [ ] Design Duplicate Handling Prepare

**Acceptance Criteria**:
- [ ] Design Duplicate Handling Prepare

**Dependencies**:
- None currently

**Accountability**:
- Owner 
- QA/Review

**Comment by elnyry** [comment]
Duplicate of #285
