### ISSUE TITLE
Liquidity Check and Fund adjustment process after settlement 

### ISSUE THREAD

**Issue by TW-Ei-Nghon-Phoo** [mojaloop/project#3536]
### Goal: 
**As a hub operator**,
**I want to be able to**  initiate the settlement finalizing process by uploading a settlement initiation report in the Settlement Screen. This report will act as payment instructions to the bank, provide bilateral settlement positions for each DFSP involved in the settlement batch, and validate the balance amount against the Hub's records. Once approved by the checker hub operator, the process should update DFSPs' balances in the Financial Position. 

**Liquidity balance checking process after settlement**

- On the participant central page, there should be a "Liquidity Balance Check" button visible to hub operators.
- When user clicks the "Liquidity Balance Check" button, the system prompts user to upload a settlement balance report(settlement initiation upload report) in Excel format. This report contains balances filled by the settlement bank after each settlement for affected participants.
- After uploading the Excel file, user should be able click the "Validate" button to initiate the balance check process.
- The system will compare the balances from the uploaded Excel file with the balances in the system for each participant.
- If a participant is not listed in the uploaded file, their balance does not need to be checked.
- If the balances for any participants do not match, the system will provide details of the discrepancies, including the difference in balances, fund in and fund out activities required, and the specific amount to be funded in or out for each participant.
- As a hub operator, I should have two options when discrepancies are found:
   - I can choose the "Request Fund Adjustment" button, which will create fund adjustment request records.
   - I can also choose to cancel the activity.
- When I select the "Request Fund Adjustment" button:
   - Fund adjustment request records will be created and appear in the hub operator checker's "Pending Fund Adjustment Requests" page.
   - Hub operator checker can review and manage these requests.
- The hub operator checker can either approve or reject each fund adjustment request, or select all requests for bulk approval or rejection.
- Once a fund adjustment request is approved, the system will perform the necessary fund in and fund out activities to synchronize the balances.
- After the fund adjustment is completed, the balances in the system will be updated to reflect the changes.

- If the balances for any participants match with the system, the hub operator will not need any further action. 
   - The given success message will be shown. "Liquidity balance checking is successful! system and bank balances aligned."
   - And the "Request Fund Adjustment" button will be disabled.

-    In audit log,there should be records of fund in fund out activities of maker and checkers along with file name, settlement ID in note.
-    Data Presence Validation:
   - The system should validate that there is data in each cell of the uploaded Excel file as per the template.
     - Each row and column in the file must adhere to the designated format template.
     - If any cell in the uploaded file does not follow the designated format template:
       - Display a clear and descriptive error message indicating the specific cell or cells with incorrect format.
       - Prevent further processing until the user corrects the format issues.
     - If any cell in the uploaded file is empty:
       - Provide a detailed error message specifying the location of the empty cell.
       - Prevent further processing until the user populates the required data in all cells.

-  Settlement Account ID Matching Validation:
   - For each participant name and currency combination in the uploaded Excel file:
      - Validate that the associated settlement account ID matches the one stored in the system.
      - If a mismatch is found:
        - Display a clear error message indicating the participant name, currency, and settlement account ID that do not match the system records.
        - Prevent further processing until the user corrects the discrepancies. 

-    [Settlement Initiation Report Spec.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdmJYIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bfdb8b1549dc90b6e1464da43d610fb780705614/Spec-%20Settlement%20Initiation%20Report.xlsx)
-    [Design file](https://www.figma.com/proto/80cD3AKOglNk3UhCUxbILi/vNext-Portal?page-id=9%3A10&type=design&node-id=6528-6055&viewport=-1503%2C731%2C0.2&t=3Go11uu3fTnwgjXV-1&scaling=scale-down&starting-point-node-id=6528%3A6055&mode=design)
---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by einghon-phoo** [comment]
```mermaid

flowchart TD
    A[Start] --> B[finalize button in Settlement]
    B --> C[Upload settlement initiation report with balance updated from settlement bank]
    C --> D[Validation if balance from file and system expected value are the same]
    D --> E[Display Warning that balances are not the same]
    E --> F[User Accepts Warning]
    F --> G[Update Balances from system calculated values]
    G --> H[Ask for Adjustment for value from file upload]
    H --> I[Adjustment Approved?]
    I --> |Yes| J[Adjust Amount]
    I --> |No| K[Continue]
    D --> |No Mismatch| L[Notify Checker]
    L --> M[Checker Approves Action]
    L --> N[Checker Rejects Action]
    M --> O[Enable Process Button]
    N --> P[Disable Process Button]
    O --> Q[Click Process]
    Q --> R[Finalize Settlement]
    R --> S[Change State to Settle]
    S --> T[Update Balances in Financial Position]
    T --> U[2 audit transaction record: 1st with system calculated values and 2nd with adjusted value]

    J --> L

```

**Comment by koekiebox** [comment]
Downloaded and uploaded `Spec- Settlement Initiation Report.xlsx`. 

[Spec- Settlement Initiation Report.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdWpuIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5cdb65a7e0fd2c3a4f1d72aa1aa5203da7a93b19/Spec-%20Settlement%20Initiation%20Report.xlsx)

**Comment by pedrosousabarreto** [comment]
@einghon-phoo @myo-min-htet @HtetAungLinn98 
I think this looks great, my only concern is regarding the UI/UX: we do need that page "Pending Fund Adjustment Requests", for now we should create a "Pending Approvals" page as a subpage of Participants (normal participants list will be the first subpage, like quotes for example)"

**Comment by einghon-phoo** [comment]
![updated design](https://github.com/mojaloop/project/assets/132323209/dbd81f72-c41f-47cd-93a2-5cdf7a32a9e5)
Hello @pedrosousabarreto , we have updated the design based on your feedback.

**Comment by pedrosousabarreto** [comment]
@einghon-phoo Now looking at that mockup, I have more suggestions :)
Maybe the "Participants Overview"  submenu page can be a small dashboard, with some key numbers, then we have another submenu for "Participants" list, and another for the "Pending Approvals", where we list all pending approval requests, such as account changes, status changes, funds movements, etc.

What do you think?

**Comment by einghon-phoo** [comment]
> another for the "Pending Approvals", where we list all pending approval requests, such as account changes, status changes, funds movements, etc.

I was thinking the same at first. But one thing I realized is that fields are different for each pending approvals. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2V5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e93b75cda682c105f082c41f83b22dc8b47a5b13/image.png)[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2l5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9b05e548b29d169f3d3a134fe97d49e9a665517a/image.png)

That's why.
But I think it's good to have pending approvals in one place for all participants. User don't have to check every single pages of participants to see if there is any pending approvals she/he have to make. 

How about
>Participants
   > participant overview ( mini dashboard)
   > participant
           > Detail of each participants
   > Fund Adjustments Requests
           > Request
           > change log
   > NDC Change Requests
   > Contact Information Change Request
Please see the detail design in following figma link
https://www.figma.com/proto/80cD3AKOglNk3UhCUxbILi/vNext-Portal?page-id=9%3A10&type=design&node-id=6528-6055&viewport=-1503%2C731%2C0.2&t=LzKrjHNNE2AKKxVy-1&scaling=scale-down&starting-point-node-id=6489%3A8323&mode=design
@pedrosousabarreto

**Comment by einghon-phoo** [comment]
https://www.figma.com/proto/80cD3AKOglNk3UhCUxbILi/vNext-Portal?page-id=9%3A10&type=design&node-id=6685-4421&viewport=-1503%2C731%2C0.2&t=Khsoki9utzaoVKwN-1&scaling=scale-down&starting-point-node-id=6489%3A8323&mode=design
Hello @pedrosousabarreto , could you please review updated design for fund adjustment request design?

**Comment by einghon-phoo** [comment]
Ko @myo-min-htet updated

**Comment by zinzinnyohlaing-tw** [comment]
https://github.com/mojaloop/platform-shared-tools/pull/50 <-- pull request
