### ISSUE TITLE
Enabling and Disabling DFSP Participants

### ISSUE THREAD

**Issue by einghon-phoo** [mojaloop/project#3546]
# **Goal**:
`As a` Hub Operator

`I want to` disable/enable Participant DFSPs
  
`because` In certain cases, it may be necessary to make a DFSP inactive temporarily or permanently. An example scenario is when you observe highly suspicious behavior, or in the case of insufficient liquidity balance during settlement time and the actual cause needs investigation, the risk of money loss being too high. Once the risk has been cleared, you can resume services for the DFSP.

## Acceptance Criteria: Disable DFSP

- Only authorized users, with the necessary permissions, should be able to disable a DFSP via the admin portal.
- When a DFSP is disabled, the following conditions should be met:
- The disabled DFSP should not be able to initiate or process any transactions within the system.
- Hub users should not be able to withdraw funds from or add funds to the disabled DFSP's account.
- A disabled DFSP should have the option to be re-enabled. After re-enabling the DFSP, the following conditions should be met:
- The DFSP should regain its ability to make and process transactions, and its status should be normalized.
- Hub users should be able to withdraw funds from and add funds to the re-enabled DFSP's account as usual.

## Acceptance Criteria: Default DFSP Status

- After a DFSP is onboarded into the system, its default status should be "Enabled." This ensures that newly added DFSPs can actively participate in transactions and interactions within the payment system.

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by pedrosousabarreto** [comment]
We need to have a complete discussion on this matter, as some of these statuses overlap or can be confusing.

Currently, we have this understanding:
- Approved (flag) - was the participant approved at on-boarding, should not be used later (cannot be "disapproved" later);
- Active/enabled (flag) - this would be the equivalent of a soft delete (participant can't do anything if disabled) PM6 requirement Paul Makin's review.
- Paused (flag) - participant cannot be part of transactions (can do everything else) PM8 requirement from Paul Makin's review.

@PaulMakinMojaloop Pls comment here, is this what we want? What else should be blocked when a participant is paused?

**Comment by elnyry-sam-k** [comment]
@pedrosousabarreto 

the description for Active flag seems incorrect, may be a typo. Its likely for the "disabled" flag.

> Approved (flag) - was the participant approved at on-boarding, should not be used later (cannot be "disapproved" later);
> Active/enabled (flag) - this would be the equivalent of a soft delete (participant can't do anything if disabled) PM6 requirement Paul Makin's review.
> Paused (flag) - participant cannot be part of transactions (can do everything else) PM8 requirement from Paul Makin's review.

**Comment by PaulMakinMojaloop** [comment]
"Pause" is a function that must be available to the Hb Operator, and to the Participant themselves (through the Participant Portal).

**Comment by PaulMakinMojaloop** [comment]
"Active/enabled (flag)" seems like a reversal of the state. The purpose is to make a Participant inactive/disabled; effectively all access cut off.

It should also be possible to make the Participant Active again.

Scenario: Participant is not making liquidity available, and is not cooperating. As an ultimate sanction, the hub operator can disable them. Once they make liquidity available (deposit funds), Participant can be re-enabled, and the new liquidity reflected in the system.

**Comment by pedrosousabarreto** [comment]
This was done already on the participants-bc side, only action that can be performed on inactive/disabled participants is a funds-in (Deposit). 

We need to confirm the flag is now respected by the other BC's.
I'm assuming these:
- Account-lookup
- Quotes
- Transfers

Note: We should never block settlements.
