### ISSUE TITLE
Beta release of vNext - Nov 2023

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#3550]
Epic of epics for beta release

**Comment by JulieG19** [comment]
Hi @pedrosousabarreto , could you please update the status of this epic? Also, this ticket is way too big. For the items not completed, could you please take them out and we will use the releases fields to manage what needs to be delivered for the first release? Thanks!

**Comment by JulieG19** [comment]
The Beta release has been released so this ticket can be closed.
