### ISSUE TITLE
Cannot Settle for all transactions with different currencies in one settlement window in finance portal UI

### ISSUE THREAD

**Issue by smthitsaworks** [mojaloop/project#3551]
**Summary**:
We cannot settlement all transactions with different currencies in one settlement window in finance portal UI. As per our investigation process, we found that the issue is due to the hard-coded settlement model. 

Here is the reference .
https://github.com/mojaloop/reporting-hub-bop-settlements-ui/blob/16b4e6ec03ba26d8b3dc8adecfcbabb9f8166144/src/App/SettlementWindows/sagas.ts#L143
![image](https://github.com/mojaloop/project/assets/126569070/a0e1d259-c5a1-4dbb-afcf-34d2ac5c6f92)

**Severity**:
High

**Priority**:
Critical

**Expected Behavior**
The whole settlement process is done UI successfully.

**Steps to Reproduce**
  1. Onboard two DFSPs with two different currencies
  2. Create two settlement models in central ledger( One is MMK and the rest one is USD)
  3. Make MMK transaction and USD transaction between DFSPs. Both MMK and USD transactions are recorded in one settlement window
  4. Close settlement window in Finance portal successfully
  5. Settle the window (At that moment, only one settlement ID is out for MMK transactions and USD transactions left because there is a hard-coded value related to Settlement model (MMK). Please refer to the above GitHub link. As a consequence, USD transaction cannot be settled. Workaround solution is we can settle the window via API (postman). Two settlement IDs are out for MMK and USD transactions differently.)

**Specifications**

    Component (if known): Settlement
    Version: v3.0.1
    Platform: BOFportal
    Subsystem: -
    Type of testing: Settlement testing
    Raised by: ThitsaWorks

Note: The issue is found during our settlement process testing for one or more settlement models with different currencies. It is related to COMESA project.

**Comment by PaulGregoryBaker** [comment]
Hi,
Thanks for logging this. 
Just to know that this is a known issue with the current settlement process. The UI's were not initially designed for multiple currencies. We have created stories to help redefine the UI to handle multiple currencies; unfortunately these stories are still in the backlog.

There is more than one workaround that you can use to get around this issue. (I guess you would be interested in implementing that.)
This is the most practical workarround that can be made without changing any code.
 The settlement model is hardcoded in the UI, and that settlement by default is created with a defined currency.
 This them means that all settlements that use that model must also use the defined currency.
 In Mojaloop a settlement model doen't have to have a defined currency. If that currency is not set, then it is assumed that all currencies can be settled with that settlement model.
 
 I.e. The solution is to ensure that the creation scripts that configure the default settlement model doesn't set the currency.
 
 I hope that this helps.
 Regards
 Paul

**Comment by smthitsaworks** [comment]
Thank you @PaulGregoryBaker for the suggestion. We created the settlement model with no defined currency and tested the transactions with different currencies. It seems working for the settlement process but we need to test more for other operational activities such as generating the settlement reports.

We will let you all know here once we have further updates.

Thank you
Su Mon

**Comment by smthitsaworks** [comment]
Hello @PaulGregoryBaker,

Now the undefined currency in the settlement model works as a temporary solution. As per your message, we are aware of that the story for this issue was created. If it is the ticket for that story and is convenient to share with us,  please kindly let us know the ticket link so that we can keep on track on it.

Regards
Su Mon

**Comment by PaulGregoryBaker** [comment]
Hi @smthitsaworks 

This is the original story. #2611

It has been a while since anyone has had the time to work on it, but there is a lot of interest in FX at the moment, so I am optimistic that someone in the community has the time to address this.

Regards
Paul

**Comment by smthitsaworks** [comment]
Thank you @PaulGregoryBaker. As the original story is in GitHub, let me close this ticket.

**Comment by smthitsaworks** [comment]
let me close this ticket
