### ISSUE TITLE
Participants BC - send event everytime a participant changes

### ISSUE THREAD

**Issue by pedrosousabarreto** [mojaloop/project#3555]
TBD

We need at least a simple event that is sent every time a change is made in a participant record, so we can invalidate caches faster and also inform the reporting bc of the change.

Ideally this event is sent right after the auditing entry and with the actionName of the payload equal to the actionName of the audit entry.

Event name: ParticipantChangedEvt (already in the public message libs)

**Comment by JulieG19** [comment]
Hi @pedrosousabarreto, could you please update the status of this ticket and close if this is not relevant? Thanks!

**Comment by JulieG19** [comment]
work done
