### ISSUE TITLE
Transfer History Display - Column Update

### ISSUE THREAD

**Issue by TW-Ei-Nghon-Phoo** [mojaloop/project#3563]
## **Goal**:
Transfer history should provide following information for hub operator to trace the transactions better. 
[Design File](https://www.figma.com/proto/80cD3AKOglNk3UhCUxbILi/vNext-Portal?page-id=9%3A10&type=design&node-id=6192-2398&viewport=2624%2C-738%2C0.32&t=HVXEJrtXhMknvgwv-1&scaling=scale-down&starting-point-node-id=6192%3A2398&show-proto-sidebar=1)
### Table view
- Transfer ID
- State
- Type
- Currency
- Amount
- Payer FSP Name 
- Payee FSP Name
- Date Submitted
- Error code

### Detail view
General Information
- Transfer ID
- State
- Type
- Currency
- Amount
- Payer FSP Name 
- Payee FSP Name
- Date Submitted
- Error code
- Quote ID

Payer Information
- ID Type
- ID
- First Name
- Middle Name
- Last Name
- FSP ID

Payee Information
- ID Type
- ID
- First Name
- Middle Name
- Last Name
- FSP ID

### Filters
- Payer or Payee FSP (Participant)[done]
- Payer DFSP Name: The fsp name of the Payer DFSP
- Payee DFSP Name: The fsp name of the Payer DFSP
- Transfer State: The state for each transfer (for example: COMMITTED or ABORTED)
- Payer ID Type: The types including MSISDN, EMAIL, PERSONAL_ID, BUSINESS, DEVICE, ACCOUNT_ID, IBAN, ALIAS
- Payee ID Type: The types including MSISDN, EMAIL, PERSONAL_ID, BUSINESS, DEVICE, ACCOUNT_ID , IBAN, ALIAS
- Transfer ID: The unique identifier of the transfer (corresponds to transferID).
- Transfer Type: The transactions types of the transfers
- Currency: The currency of the transfer
- Payer ID value: Enter the full identifier or a fragment of the identifier used to identify the Payer
 - Payee ID value:  Enter the full identifier or a fragment of the identifier used to identify the Payee
-  Date: From start date and end date when the transfers you are looking for happened.

### Sorting 
-. The Transfer lists will be sorted based on the Date Submitted. In case of multiple transactions with the same Date Submitted, the list will be further sorted by the Batch ID in alphabetical order (A-Z).
- Column Order 
  - Transfer ID
  - State
  - Type
  - Currency
  - Amount
  - Payer DFSP Name
  - Payee DFSP Name
  - Date Submitted
  - Error Code

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by einghon-phoo** [comment]
[Screen to update](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3dWQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2f324f0b89934c6504a30e5a84141fe1568887e1/image.png)

**Comment by einghon-phoo** [comment]
ko @HtetAungLinn98 , please comment here filters which will be hard-coded and which ones will be populated through a database after you have decided.

**Comment by einghon-phoo** [comment]
@pedrosousabarreto, Hello, I would like to know if it's possible to add these additional fields to the transfer history table. The information would help hub users to trace better about the transfer when they troubleshoot something. 
Transfer Type, Batch Id,  Quote Id, , Payee ID Value, Payer ID Value, Payer FSP ID, Payee FSP ID,  Payer and Payee First Name[optional], Payer and Payee Last Name[optional]

I also would like to know if it's possible to add export data with CSV file for this history?

**Comment by pedrosousabarreto** [comment]
Thanks @einghon-phoo. If all fields are available shouldn't be a problem.

@ruirochawork can you confirm we have all these fields available in the transfers BC repo?

**Comment by pedrosousabarreto** [comment]
@einghon-phoo For now, we can't use the "Settlement Batch ID" in the list page and list page filter, but we can show it in the transfer detail page.

Later, when we have the Reporting BC transfers SVC completed, we can use it to join all data and add the "Settlement Batch ID" to the list and filter.

Regarding CSV export, we should have a different ticket, but, will have the same limitations for now, can be done in the future.

**Comment by einghon-phoo** [comment]
noted, I will update the ticket
