### ISSUE TITLE
QuotingBC - Increase test coverage to minimum treshold

### ISSUE THREAD

**Issue by ruirochawork** [mojaloop/project#3569]
## **Goal**:
As a developer

I want to increase test coverage

so that it meets the minimum threshold required

**Acceptance Criteria**:
- [ ] TBD

**Complexity**: <High|Medium|Low> > A short comment to remind the reason for the rating

**Uncertainty**: <High|Medium|Low> > A short comment to remind the reason for the rating

---

**Tasks**:
- [ ] TBD [ @? ]

**Done**
- [ ] Acceptance Criteria pass
- [ ] Designs are up-to date
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Changes made to config (default.json) are broadcast to team and follow-up tasks added to update helm charts and other deployment config.
- [ ] TBD

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by PaulMakinMojaloop** [comment]
Can I ask what the minimum threshold is, or where/how it is defined?

**Comment by pedrosousabarreto** [comment]
@PaulMakinMojaloop we haven't decided on a threshold for the work prior to beta, for beta release we will need the usual 90%.

**Comment by JulieG19** [comment]
Work done
