### ISSUE TITLE
Beta Feature Timeline Tracking

### ISSUE THREAD

**Issue by TW-Ei-Nghon-Phoo** [mojaloop/project#3576]
**Hi all**
I would like to request you to add tentative timeline for each of your tasks in the notion file. If it's not convenient for you to use notion, you can also comment your ticket and tentative deadline under this ticket. It would help me to keep track of the project's status. Thanks so much, everyone. 
Notion link: https://www.notion.so/a8e2066968f446acb23ce3534bd85444?v=8acf9492934941238834bd04844d370a

**Comment by JulieG19** [comment]
Hi @TW-Ei-Nghon-Phoo, could you please provide more details about this ticket and close it if no longer relevant? Thanks!

**Comment by JulieG19** [comment]
this ticket can be closed
