### ISSUE TITLE
The notification message published by batch handler is not forwarding the headers properly

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#3581]
**Summary**:
The batch handler is generating the notification kafka messages with constructed headers and not forwarding the headers from original request. Refer [this code](https://github.com/mojaloop/central-ledger/blob/a388391a620abbcda9c8f399223fb27d340e0bff/src/domain/position/prepare.js#L64) where the headers are being constructed.

We need to look at the original (non-batching) [implementation](https://github.com/mojaloop/central-ledger/blob/371210e750830f0497c095b8cc7925e30394876c/src/handlers/positions/handler.js#L161C13-L161C13) and follow the same for notification message production.

**Severity**:
(Low, Medium, High)

**Priority**:
Critical

**Expected Behavior**
Notification messages published by batch handler should contain all the headers from original request properly like content-type, fspiop-signature...etc

**Specifications**
  - Component (if known): central position handler with batch processing
  - Version: feature branch for batch
  - Bug found/raised by: @vijayg10 

**Notes**:

- Severity when opened:
- Priority when opened:

**PRs**:
- [ ] https://github.com/mojaloop/central-ledger/pull/968

**Comment by elnyry-sam-k** [comment]
Updated priority to critical (when batching is used)

**Comment by PaulGregoryBaker** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3581?planning-poker) with Zenhub @aaronreynoza @kleyow @oderayi @sri-miriyala @vijayg10
