### ISSUE TITLE
Batch Implementation - Improper error callbacks generated by switch

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#3582]
**Summary**:
The error callbacks generated by the switch are erroneous. Observed following issues
- The error callback is sent as POST /transfers instead of PUT /transfers/{ID}
- There is no transferID in the body for error callback and causing the validation error in FSP simulators `{"missingProperty":"transferId"},"message":"must have required property 'transferId'"}`
- The source header should be set as `switch`

**Accptance Criteria**
- [x] Verify that the header code is compared to the non-batching handlers. There are other missing information that should be added.
- [x] Add unit test to validate the published kafka notification messages.

**Severity**:
(Low, Medium, High)

**Priority**:
Critical

**Specifications**
  - Component (if known): central position handler with batch processing
  - Version: feature branch for batch
  - Bug found/raised by: @vijayg10 

**PRs**:
- [ ] https://github.com/mojaloop/central-ledger/pull/968

**Comment by elnyry-sam-k** [comment]
Critical when batching is enabled

**Comment by PaulGregoryBaker** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/mojaloop/project/3582?planning-poker) with Zenhub @aaronreynoza @kleyow @oderayi @sri-miriyala @vijayg10
