### ISSUE TITLE
Setup and GP failures when upgrading Mojaloop from v15.1.0 to v15.2.0-rc

### ISSUE THREAD

**Issue by oderayi** [mojaloop/project#3597]
**Summary**:
Setup and golden path test failures are seen when Mojaloop if upgraded from v15.1.0 to v15.2.0-rc.

**Setup failures:**

```
payerfsp Get Status Request after deposit - GET - /participants/{name}/accounts - [1/2]
```

*TTK backend*
```
(node:48) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
```

**GP Failures**
----

**1. Assertion failures while running post /quotes**
- Active and inactive participant -> Send Quote (SIM1 to SIM2) 

**Observations**
- Websocket request for `sim2request` was returning null even though the request was cached/stored properly in redis.
Root cause analysis revealed that in-memory caching in quoting service might be the problem.

**Action taken:**
   - Set quoting-service -> config -> cache -> participant_data_expires_in_ms to 1 in helm values file for v15.2.0

2. Assertion failures while running post  hub/golden_path/feature_tests/post_scenarios/positive.json
- Positive Scenarios -> POST /scenarios

**Observations**

3. From TTK backend
```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
```

**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Expected Behavior**
Setup and GP tests should pass when upgrading Mojaloop from a lower version to a higher version

**Steps to Reproduce**
  1. Install v15.1.0 of Mojaloop with all components
  2. Run GP tests
  3. Upgrade to v15.2.0-rc
  4. Run GP tests
  5. Setup and GP tests should fail

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by:

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by mdebarros** [comment]
A temporary work-around has been implemented as per the following comment: https://github.com/mojaloop/project/issues/3164#issuecomment-1785214340
