### ISSUE TITLE
Successful Inbound Tranx being Pending in Payment Manager

### ISSUE THREAD

**Issue by PhyuSinMyat8** [mojaloop/project#3608]
In payment Manager portal,  inbound transactions are showing “Pending“ status even though the transactions are successful. But the portal from outbound side, is showing correctly.

[Inbound_Transaction](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUNVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--89045a8674f14eb75253f0024338c3e40c52438a/image.png)
[Outbound_transaction](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUdVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ec9fce227c1e9bcce0a8bd983b7a9f0f6447e05e/image.png)
[Inbound_transaction](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUtVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--43bb0fc0bce25d9900a333ba47f67cf047f11724/image.png)
[Transfer_state_being_reserved_for_successfuL_inbound_transaction](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU9VQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fd814dde2a0db0ae5eb306057d888975871f1519/image.png)
[outbound_transaction_with_normal_status](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVNVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dffe62082d1584949bbec3c38a2129522a91c05b/image.png)
[Transfer_state_being_succeeded_for_successfuL_outbound_transaction](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVdVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3020db89c6220ccb8a9c66c4bc51f6f8268b0121/image.png)

**Comment by pedrosousabarreto** [comment]
For the Payee notification to be sent by the HUB, according to the current implementation and the reference architecture, these two things need to happen:
- The FSPIOP protocol version is 1.1
- The  PUT /transfers/{ID} call the payee sends, when accepting the transfers, needs to include `transferState=reserved`

Can we confirm the PM4ML payee is sending this PUT with `transferState=reserved`?

See: 
- https://docs.mojaloop.io/api/fspiop/v1.1/api-definition.html#commit-notification
- https://mojaloop.github.io/reference-architecture-doc/boundedContexts/transfers/#perform-transfer-with-payee-confirmation

It's important to note that the

**Comment by JulieG19** [comment]
Hi @PhyuSinMyat8 , was this defect fixed? if not, we will prioritise in the backlog thanks.

**Comment by YminOo** [comment]
It is resolved. 
Payer side 

Payee side

Payee side transfer details
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEVjQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c68d04d35ebf302a52080125739c593b68f1b2b9/Screenshot%202024-05-28%20at%2012.36.50%E2%80%AFPM.png" alt="Screenshot 2024-05-28 at 12.36.50 PM.png" />
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE1jQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a2b9892008253e34de1f06c093387fb5ae8de85c/Screenshot%202024-05-28%20at%2012.38.49%E2%80%AFPM.png" alt="Screenshot 2024-05-28 at 12.38.49 PM.png" />

**Comment by TW-Ei-Nghon-Phoo** [comment]
FYI @JulieG19
