### ISSUE TITLE
Should encounter error when maker input or checker approves NDC changes if the NDC absolute amt is greater than settlement balance amt

### ISSUE THREAD

**Issue by pthandar** [mojaloop/project#3631]
Currently, the maker can input the NDC (absolute) amount that is more than the settlement balance and the checker can approve NDC changes with that amount. However, NDC(absolute) changed the amount same as the settlement balance itself not with user's control.

### Tasks
- [ ] Acceptance Criteria pass
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Code Review
- [ ] QA Passed

**Comment by YminOo** [comment]
Original accounts

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXV6QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--86703323138c15431deaa4177a6a50057b3c7521/Screenshot%202023-11-08%20at%201.20.34%E2%80%AFPM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTJ6QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4d8c37baf516f88bc7f2ccf2a6a2e145a56e1901/Screenshot%202023-11-08%20at%201.20.55%E2%80%AFPM.png)

After approved to 100,000,000 USD absolute
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTZ6QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--370ff187338a65b0ec7419d3f5614a785aa18b01/Screenshot%202023-11-08%20at%201.12.11%E2%80%AFPM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkN6QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1c434fb85a69846dcb8ce6bdb757dfe8080cb7f0/Screenshot%202023-11-08%20at%201.21.31%E2%80%AFPM.png)

**Comment by einghon-phoo** [comment]
pull request <=== https://github.com/mojaloop/participants-bc/pull/25
