### ISSUE TITLE
Getting insufficient liquidity Error if transaction amount with decimal 3 places and 4 places

### ISSUE THREAD

**Issue by pthandar** [mojaloop/project#3632]
If the transaction amount with decimal 3 places and 4 places, we are getting "payer fsp insufficient liquidity error" even though the NDC amount is enough to make the transaction.

Please check the below SS.

Amount with decimal 4 places.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejJ6QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5bfb69bd03c85b0b26552acf88f29d23c4842f7e/image.png)

Getting insufficient liquidity Error at the Transfer phase.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejZ6QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5c22d1701f68d41ceecbf7568686f874d71b99a8/image.png)

**Comment by pedrosousabarreto** [comment]
Let's check why it is returning the liquidity error, could hide a bigger problem.

Let's also make sure FSPIOP rejects currencies that are not enabled and rejects amounts for which the format doesn't agree with the currency definition.

**Comment by elnyry-sam-k** [comment]
@ruirochawork can you please provide the PR link(s) for the fix to this issue, to help with navigating and for anyone to review it? thank you..

**Comment by pedrosousabarreto** [comment]
Hi @elnyry-sam-k this was reviewed in a pair programing session with me and Rui and not PR created, in doubt we can always refer to the commits.

**Comment by elnyry-sam-k** [comment]
Thanks for the response @pedrosousabarreto and for your review.. 

We have to follow the PR review process please as part of Mojaloop's adopted standards. Can you please make sure these happen for all PRs from now on? 

Also, PRs need to be linked to issues. Thanks again.

**Comment by pedrosousabarreto** [comment]
To further clarify, this was not an issue about liquidity, rather the amount format which was not being checked for the correct number of decimals at the FSPIOP API, and then breaking (as it should) in the A&B liquidity verification.

As requested by my comment 8 days ago, the FSPIOP API now validates all amounts against the platform wide defined currency decimals definitions.
