### ISSUE TITLE
user management.data loading

### ISSUE THREAD

**Issue by PhyuSinMyat8** [mojaloop/project#3639]
**Scenario**

- Firstly, do any action in role management [like creating new role, adding or removing privileges]
- Secondly, go to user management page (or) application management page immediately

**Result**

- If user go to user management page as soon as after doing actions in role management, the data on user management page does not appear. 
- He has to wait over one or two minutes. 
- Only after waiting for a few minutes, he can see the existing data on user management page.

- Application management page also has the same issue. User has to wait a few minutes to see the data on application management page.

**Comment by einghon-phoo** [comment]
to retest after version update @PhyuSinMyat8

**Comment by pedrosousabarreto** [comment]
Could not reproduce, suspect this has been fixed already. Can you retest with latest version of Admin UI 0.1.48+ and Security identity services 0.3.10+?
