### ISSUE TITLE
user management.removing roles

### ISSUE THREAD

**Issue by PhyuSinMyat8** [mojaloop/project#3640]
**Scenario**

- Add 2 roles for test account 
- login test account in another browser 
- remove one role from test account
- Go back to test account

**Result**

- In test account, the removed privileges are stilling working.
- Only if user try to login again that test account, the updated roles and privileges work.

**Comment by pedrosousabarreto** [comment]
Same problem as #3642, link to it

**Comment by pedrosousabarreto** [comment]
Fixed by latest change to security-bc.
All services using the TokenHelper and AuthorizationClient must update to latest versions - will do this separately for the release.

Please test with versions:

    security-bc-authentication-svc:0.5.3
    security-bc-authorization-svc:0.5.3
    security-bc-builtin-identity-svc:0.5.3
    security-bc-client-lib:0.5.4
    security-bc-public-types-lib:0.5.5

**Comment by TW-Ei-Nghon-Phoo** [comment]
QA passed
