### ISSUE TITLE
Being able to proceed as the previous participant status(Disabled/Enabled ) even if the participant status has changed

### ISSUE THREAD

**Issue by pthandar** [mojaloop/project#3651]
I changed the participant status to disabled after that I called the lookup API call using that disabled fsp and got the payee info response even participant status was disabled.

But taking around 3 min, I got the error response ( "detailedDescription": "Got an error response resolving party: { errorInformation: { errorCode: '4000', errorDescription: 'Generic Payer error' } }") that I expected.

The enabled participant case is the same as the above  Disabled participant case.

Please check the below SS.
Enabled the participant on Nov 20 2023,12:09:38 PM
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDdzQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5a27a3d80d8b2128648e2838577e34de510cc114/image.png)

Make the Call on Nov 20 2023,12:09:47 PM
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVBzQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d3b38df9f4d9e98f1f7a1d12ae310606a8a77554/image.png)

Make the Call on Nov 20 2023,12:11:08 PM
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWJzQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dcab211761488ec5c4eaec61be600e28096473c5/image.png)

Make the Call on Nov 20 2023, 12:12:47 PM
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWpzQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f8f9b55cbdaf54b2f7dd31f6efbf623004776bc2/image.png)

Issue Summary :
Being able to proceed as the previous participant status(Disabled/Enabled ) even if the participant status has changed. However, after around 3 minutes, it worked as expected.

**Comment by pedrosousabarreto** [comment]
Participant client cache had inconsistent timeouts across transfers, quotes and lookup. They all have a 30 secs default and a PARTICIPANTS_CACHE_TIMEOUT_MS env var to set this from the outside.

Now that we are sending a ParticipantChangedEvt on participant changes, we can have the participants client-lib automatically invalidating the cache from the event. We need a separate ticket for this.

**Comment by myo-min-htet** [comment]
It already fixed in the latest version of 3 services.
quoting-svc : 0.3.8
transfers-command-handler-svc : 0.3.10
account-lookup-svc : 0.3.9
