### ISSUE TITLE
1.05 Kafka Performance Issue Analysis & Investigation - Part4 - Multi-processing on Consumers

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#366]
## **Goal**:
1. As a contributor
I would like to _perform Kafka Performance Issue Analysis & Investigation_
so that a viable solution can be identified and recommended for implementation
2. As an FSP
I would want _the development team to do analysis regarding Kafka performance issue_
so that transfers can be performant

Notes:
This should be time-boxed for Sprint3.2 and any follow-up or related tasks should be included in a separate story specific to those tasks.

#### Tweak Golden path for Multi-processing on Consumers
- [ ] Kafka Performance Issue Analysis - Tweak Golden for multi-processing 
- [ ] Kafka Performance Issue Analysis - Run performance test, and analyse results for multi-processing of Golden Path consumers for single message on the Stable Testing environment
- [ ] Kafka Performance Issue Analysis - Run performance test, and analyse results for Golden Path consumers for multiple messages on the Stable Testing environment
- [ ] Kafka Performance Issue Analysis - Run performance test, and analyse results for Golden Path consumers for multiple messages on the Stable Testing environment
-----
#### Follow-up story - #363 
-----

## **Acceptance Criteria**:
- [ ] Document Test Results
- [ ] Documented Findings & Recommendations to help resolve Kafka performance issue
- [ ] Translate the follow-up tasks into stories

## **Dependencies**:
- [ ] #362 
- [ ] (Optional) External parties availability

## **Accountability**:
- Owner @mdebarros 
- QA/Review: Design Authority

**Comment by elnyry** [comment]
Closing this now as multi-processing on consumers can now be done and is implemented in various versions (and tested for perf with numbers) of the perf releases/branches. This will be moved to the dev when the perf changes are finalized.
