### ISSUE TITLE
User management.new user creation

### ISSUE THREAD

**Issue by PhyuSinMyat8** [mojaloop/project#3692]
### Scenario 1
- Click "Create User"
- Fill **all the fields** including password and password confirm
- Click "**Cancel**"

**Expected outcome**
- When user clicks "Cancel", the system should redirect to the previous page properly without creating a new user.

**Actual outcome**
- When user clicks "Cancel" after filling all the fields, a new user with the filled data in the fields is created.

### Scenario 2
- Click "Create User"
- Fill **some fields**
- Click "**Cancel**"

**Outcome**
- When user clicks "Cancel" without filling all the fields, the system redirects to the previous page properly with error message: "Invalid user".

<img width="150" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3RwQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1be64f7bb19338eaa0d192646a55ff3532c9afeb/image.png" alt="image.png" />

### Tasks
- [ ] Acceptance Criteria pass
- [ ] Unit Tests pass
- [ ] Integration Tests pass
- [ ] Code Style & Coverage meets standards
- [ ] Code Review
- [ ] QA Passed

**Comment by hsuyeemon-tw** [comment]
https://github.com/mojaloop/platform-shared-tools/pull/55

**Comment by TW-Ei-Nghon-Phoo** [comment]
###QA Passed
