### ISSUE TITLE
NDC amount setup constraint

### ISSUE THREAD

**Issue by TW-Ei-Nghon-Phoo** [mojaloop/project#3695]
## Acceptance Criteria:

1. The system must restrict setting the Net Debit Cap (NDC) amount greater than the settlement account balance.

2. When a user attempts to set an NDC amount exceeding the settlement account balance, display a user-friendly error message: "NDC amount cannot be set greater than settlement account balance."

## Sub Tasks
- [x] Implementation
- [x] Passed Code review
- [ ] Passed QA testing

**Comment by einghon-phoo** [comment]
https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/gh/mojaloop/project/3631

**Comment by SithuKyaw-Thitsaworks** [comment]
Please review the PR for this ticket, https://github.com/mojaloop/participants-bc/pull/28. @elnyry-sam-k, @bushjames, @myo-min-htet
