### ISSUE TITLE
DFSP Settlement Statement Report

### ISSUE THREAD

**Issue by ei-nghon-phoo** [mojaloop/project#3705]
## User Story
As a hub operator wishing to serve connected DFSPs by giving them visibility of their liquidity balances", because it's the hub operator doing it, at least until the Participant Portal is implemented.

### Acceptance Criteria
- [x] **Access to Business Portal:**
  - [x] The authorized users should be able to access the business portal with valid credentials.
- [x] **Report Navigation Overview:**
  - [x] Upon logging in, the DFSP should see an option to view the Reports>>settlement statement report section on the portal.

- [x] **Balance Categories:**
  - [x] The portal should display balance changes categorized into fund deposit, withdrawal, and settlement,reference column in fund withdraw/deposit activities during the selected date range.

- [x] **Updated Balance:**
  - [x] The portal should display the updated balance after each transaction for easy tracking of the liquidity account status.

- [x] **Excel Report Format:**
  - [x] The generated report should adhere to the format specified in the provided Excel file.

- [x] **Export Option:**
  - [x] The DFSP should have the option to export the balance changes and transaction records in a downloadable format that is in excel.

- [x] **Filter Options**:
  - [x] The report should offer four available filters: DFSP name (selected from onboarded DFSP list), start date, end date, and currency selection (options include All, Currency 1, Currency 2).

- [x] **Initial Balance Calculation**:
  - [x] The report should calculate the initial balance of each DFSP at the beginning of the selected date range, considering transactions prior to any activities conducted during the selected period.

- **Error Message for Empty Filtered Range** :
   - If there is no data available within the filtered range, the report should display a clear and informative message under the header names,: "There is no available data in the selected date range and filter criteria. Please adjust your filters or select a different date range."

- Visibility of Export Button:
   - If there is no data to display in the report, the export button should be hidden to prevent users from downloading an empty report.

- Capture of Activity Types:
   - The report should capture fund in, fund out activity, and settlement activity for each DFSP within the selected date range and filter criteria, ensuring comprehensive coverage of financial transactions.

### Detail Specification
[Spec- DFSP Settlement Statement Report]

[Spec- DFSP Settlement Statement Report-2024Apr24.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU9MQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ccf00c16da871c126b27114ab84bab33ce769b80/Spec-%20DFSP%20Settlement%20Statement%20Report-2024Apr24.xlsx)
#edited >> The specification file was updated/revised on APR 24 due to the changes of the field from header to column (Account Number), the reason behind the changes is when the currency parameter was selected for "ALL", the account number in the header cannot show for all currency so we moved it to column.

**Comment by smthitsaworks** [comment]
@JulieG19, we divided this main task into two sub tasks.
3.1 Update Participant BC
3.2 Generate Report and testing

3.1 item can be done in Sprint 1. We will focus on the 3.2 item in Sprint 2.

**Comment by JulieG19** [comment]
Hell, thanks for your comment. I am guessing you are referring to the old settlement report. Is that correct? FIY @koekiebox

**Comment by smthitsaworks** [comment]
Yes, it is one of the existing settlement reports. 
But the new one that we developed in vNext and old one is not exactly the same. For instance, we added some new fields in report header that did not exist in the old one and moved the currency field to the report items for detailed information since one DFSP can have multi currencies transactions. You can take a look at the specification file that we generated. 

For your reference, let me provide the report sample of old and new ones.
Old
<img width="1893" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHVFQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--64bea7267f894294a2d42381f1febca9c3987916/image.png" alt="image.png" />

New 
<img width="1534" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHlFQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--580ea83c9a943ece34aa32d2bc37989006c99f81/image.png" alt="image.png" />

**Comment by PaulMakinMojaloop** [comment]
Please clarify the role of the person who is accessing/causing the report to be generated.

In the existing model, this is done by an employee of the Hub Operator. We have long talked about this being a function that should be carried out by an employee of the participant (DFSP). This is implied by the above. But if this is the case then (1) we have also talked about the Participant portal being delayed to a later release of the vNext codebase, and (2) we need to ensure that the IAM solution can properly and securely support the registration of participant staff, that the proper roles/privileges are in place - and available to participant staff - to allow them to generate this report, and (3) that participant staff cannot be inadvertently assigned roles or privileges that give them access to other hub operator functions.

**Comment by smthitsaworks** [comment]
Hello @PaulMakinMojaloop , this report is intended for the participants. But currently only hub operator can generate this report in the admin portal and provide it to DFSP like we did in the past by using Finance portal. 
When we start thinking the design to generate this report by participant staff,  the roles and privileges are definitely critical tasks to consider.

**Comment by PaulMakinMojaloop** [comment]
Agreed. I was confused by the wording of the opening paragraph: "As a DFSP (Digital Financial Service Provider) enrolled in the Scheme , I want to have visibility into the changes in my balance associated with the liquidity account within the business portal". 

Perhaps this should be "As a hub operator wishing to serve connected DFSPs by giving them visibility of their liquidity balances", because it's the hub operator doing it, at least until the Participant Portal is implemented.

**Comment by smthitsaworks** [comment]
Thank you for your suggestion. We will update the description.

**Comment by TW-Ei-Nghon-Phoo** [comment]
###description updated. FYI @PaulMakinMojaloop

**Comment by smthitsaworks** [comment]
hello ko @kyaw-soe-tw ,
for the date time format, please refer to this updated specification file here.
[Spec- DFSP Settlement Statement Report-2024May7.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN084QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0e0ad4ab3c97e09b397122744922bfc189f4bf77/Spec-%20DFSP%20Settlement%20Statement%20Report-2024May7.xlsx)

**Comment by smthitsaworks** [comment]
hello ko @kyaw-soe-tw ,
for the date time format, please refer to this updated specification file here.
[Spec- DFSP Settlement Statement Report-2024May7.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN084QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0e0ad4ab3c97e09b397122744922bfc189f4bf77/Spec-%20DFSP%20Settlement%20Statement%20Report-2024May7.xlsx)

**Comment by smthitsaworks** [comment]
hello ko @kyaw-soe-tw ,
for the date time format, please refer to this updated specification file here.
[Spec- DFSP Settlement Statement Report-2024May7.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN084QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0e0ad4ab3c97e09b397122744922bfc189f4bf77/Spec-%20DFSP%20Settlement%20Statement%20Report-2024May7.xlsx)

**Comment by SithuKyaw-Thitsaworks** [comment]
Implementation in participant-bc for this ticket is complete. Now, I'm updating admin-ui according to participant-bc-public-types-lib updates. After that, I will test it together with Ko Kyaw Soe's current work on reporting-bc for this ticket.
FYI ma @zinzinnyohlaing-tw and ma su mon.

**Comment by kyaw-soe-tw** [comment]
I have completed for this ticket, I will test it with Ko Sithu Kyaw. FYI ma @zinzinnyohlaing-tw  and ma su mon.

**Comment by elnyry-sam-k** [comment]
@SithuKyaw-Thitsaworks , @kyaw-soe-tw: Thanks for the updates.

There are lot of acceptance criteria here probably too big for one story but in any case, do you have some time to review the current progress against the acceptance criteria? Thank you. Please let me know.

**Comment by SithuKyaw-Thitsaworks** [comment]
@elnyry-sam-k , Me and @kyaw-soe-tw reviewed the code implementation with the acceptance criteria and they are fine. Now, we are going to pass it to QA.

**Comment by SithuKyaw-Thitsaworks** [comment]
Closing this ticket as this implementation complete. Will open related ticket for QA testing.

**Comment by JulieG19** [comment]
Hello,  as agreed before, tickets should be closed in sprint review, so moving it to done. Thanks

**Comment by SithuKyaw-Thitsaworks** [comment]
This ticket features are available in following docker image versions below;
 
mojaloop/participants-bc-participants-svc: 0.6.4
mojaloop/vnext-admin-ui-svc: 0.5.35
mojaloop/reporting-bc-reporting-api-svc: 0.3.39
mojaloop/reporting-bc-settlements-reporting-svc:0.3.18

**Comment by ei-nghon-phoo** [comment]
### issue reported for statement report: #3923
