### ISSUE TITLE
Settlement-related privileges are not still working.

### ISSUE THREAD

**Issue by PhyuSinMyat8** [mojaloop/project#3709]
The user who doesn’t have permission for settlement-related privileges 

- can still access data from models, batches, matrices, and transfer pages and 
- can perform any action on these pages.

Portal version : v 0.1.48 - dev

**Comment by JaneS321** [comment]
@koekiebox please review = waiting for your PR to merge

**Comment by koekiebox** [comment]
> @koekiebox please review = waiting for your PR to merge

@JaneS321 , this is underway. Should be merged over the next couple of days.

**Comment by hsuyeemon-tw** [comment]
https://github.com/mojaloop/settlements-bc/pull/31

**Comment by smthitsaworks** [comment]
QA testing ticket 3898 is left.

**Comment by PhyuSinMyat8** [comment]
### Testing Result

**QA Passed**

### Summary

Privileges from settlement-bc listed below performed their intended actions.
- View Settlement Model 
- Create Settlement Model 
- Get Settlement batch 
- Get Matrix 
- Create Settlement Matrix
- Close Settlement Matrix 
- Dispute Settlement Matrix 
- Lock Matrix 
- Settle Matrix 
- Unlock Matrix

##Test Scenario1

- Created a new user named testUser9
- Didn’t add any role to that user.
- Log in that user

##Expected result for scenario 1

The user should not have access to view the data from models, batches, matrices, and transfer pages and cannot perform any action on these pages like creating settlement matrices, creating settlement models, etc. **→ QA passed**
Please refer to the screen record below for more information.


### Test Scenario2

- Add each privilege from settlement-bc to testRole
- Add that testRole to testUser9
- Log in that user

## Expected result for scenario 2
The user should have the access to perform the respective actions from settlement-bc. [e.g. If “Create Settlement Model” privilege is added, the user should be able to create the settlement model without any error.] **→ QA passed**

### Specification
Updated date of tested version: 2-Aug-24
mojaloop/settlements-bc-settlements-api-svc:0.6.1
mojaloop/settlements-command-handler-svc:0.6.1
mojaloop/settlements-bc-event-handler-svc:0.6.1
mojaloop/interop-apis-bc-fspiop-api-svc:0.6.7
mojaloop/interop-apis-bc-fspiop-event-handler-svc:0.6.6

Result from test scenario 1

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE0wQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d39c8b42f3ce496b053865f308b4669f0e36bed1/settlement%20privileges.mp4)
