### ISSUE TITLE
Discovery Phase Changes

### ISSUE THREAD

**Issue by zarchituntw** [mojaloop/project#3723]
**Changes to the PUT /parties response**

The PUT /parties response will be modified to return information about the currencies in which a beneficiary can receive funds.
This will involve changes to the party object to include information about the currencies available. It would be possible to do this, for instance, by including an optional array of account objects containing the currencies in which the beneficiary can receive.
The proposed new version of the party object, will be as shown below:

| Name  | Type | Description |
| ------------- | ------------- |------------- | 
| partyIdInfo  | partyIdInfo  | Party Id type, id, sub ID or type, and FSP Id.  | 
| merchantClassificationCode | merchantClassificationCode  | Used in the context of Payee Information, where the Payee happens to be a merchant accepting merchant payments.  | 
| name | PartyName | Display name of the Party, could be a real name or a nick name. | 
| personalInfo | PartyPersonalInfo| Personal information used to verify identity of Party such as first, middle, last name and date of birth. | 
| supportedCurrencies| Currency| Up to 16 currencies in which the party can receive funds.. | 

Acceptance Criteria:
- The PUT /parties response will be modified to return information about the currencies in which a beneficiary can receive funds.
**Impacted BC:**
- [x] - fspiop BC
- [x] - Account lookup and Discovery BC
Testing 
- [x] To be able to connect/test and be compatible with LCC
- [x] To be able to connect/test and be compatible with Pm4mL

Reference document for changes:
https://docs.google.com/document/d/1XKY9zz91lGSQSHCf2klx30-BTBOSaeop/edit?usp=drive_link&ouid=112459614529260569028&rtpof=true&sd=true

**Comment by PhyuSinMyat8** [comment]
**QA Passed** for Discovery Phase Changes

![FX-Supported Currencies](https://github.com/mojaloop/project/assets/145109675/4d7da3dc-4659-4f54-9d36-c6b67fa96398)
