### ISSUE TITLE
Security Certificate Management

### ISSUE THREAD

**Issue by TW-Ei-Nghon-Phoo** [mojaloop/project#3751]

**Comment by zinzinnyohlaing-tw** [comment]
https://github.com/mojaloop/cert-management-bc/pull/7 <-- pull request

**Comment by tw-sithumyo** [comment]
https://github.com/mojaloop/cert-management-bc/pull/8

**Comment by tw-sithumyo** [comment]
admin ui and service integration in docker-compose-cross-cutting

https://github.com/mojaloop/platform-shared-tools/pull/52

**Comment by JaneS321** [comment]
Duplicate story #3717 - closed
