### ISSUE TITLE
Agreement Phase: Changes in existing FSPIOP API (Quotes)

### ISSUE THREAD

**Issue by zarchituntw** [mojaloop/project#3755]
**Changes in existing FSPIOP API (Quotes)**
To define who would undertake the currency conversion (Payer or Pyee), a new optional field was added to the POST /quotes data model. This field will allow the payer DFSP to specify which DFSP it wants to undertake currency conversion. This field will be a text enumeration whose name will be converter. It will be a value from the enumeration CurrencyConverter.

The modified form of the /quotes request object will be as given below:

| Name  | Type | Description |
| ------------- | ------------- |------------- | 
| quoteId | CorrelationId | Common ID between the FSPs for the quote object, decided by the Payer FSP. The ID should be reused for resends of the same quote for a transaction. A new ID should be generated for each new quote for a transaction. | 
| transactionId | CorrelationId | Common ID (decided by the Payer FSP) between the FSPs for the future transaction object. The actual transaction will be created as part of a successful transfer process. The ID should be reused for resends of the same quote for a transaction. A new ID should be generated for each new quote for a transaction. | 
| transactionRequestId | CorrelationId | Identifies an optional previously-sent transaction request. | 
| payee | Party | Information about the Payee in the proposed financial transaction. | 
| payer | Party | Information about the Payer in the proposed financial transaction. | 
| amountType | AmountType| **SEND** for send amount, **RECEIVE** for receive amount. | 
| amount | Money| Depending on **amountType**:If **SEND**: The amount the Payer would like to send; that is, the amount that should be withdrawn from the Payer account including any fees. The amount is updated by each participating entity in the transaction. If **RECEIVE**: The amount the Payee should receive; that is, the amount that should be sent to the receiver exclusive any fees. The amount is not updated by any of the participating entities.| 
| converter | CurrencyConverter | PAYER if the payer DFSP intends to perform currency conversion; PAYEE if the payer DFSP wants the payee DFSP to perform currency conversion. If absent and the transfer requires currency conversion, then the converting institution will be inferred from the currency in which the quotation is requested: if the quotation is requested in the source currency, then the payee DFSP should perform currency conversion. If it is in the target currency, then the payer DFSP will perform currency conversion.| 
| conversionRate | FxRate | Used by the debtor party if it wants to share information about the currency conversion it proposes to make; or if it is required by scheme rules to share this information. This object contains the amount of the transfer in the source and target currencies, but does not identify the FXP being used. | 
| fees | Money | Fees in the transaction. The fees element should be empty if fees should be non-disclosed. The fees element should be non-empty if fees should be disclosed. | 
| transactionType | TransactionType | Type of transaction for which the quote is requested. | 
| geoCode| GeoCode | Longitude and Latitude of the initiating Party. Can be used to detect fraud. | 
| note | note | A memo that will be attached to the transaction | 
| expiration| DateTime | Expiration is optional. It can be set to get a quick failure in case the peer FSP takes too long to respond. Also, it may be beneficial for Consumer, Agent, and Merchant to know that their request has a time limit. | 
| extensionList | ExtensionList | TOptional extension, specific to deployment | 

**Acceptance Criteria:**
- [x]  Verify that the conversion was done according to the converter instructions. (in this phase, it will be only PAYER)
- [x]  Verify that the API resource is complies with FSPIOP 2.0 definition
- [x]  Verify a happy path functional test is in place to test the new functionionallity
- [x]  Verify that the new changes can be tested with TTK

**Comment by smthitsaworks** [comment]
@JulieG19, one of TW team members is working on this ticket already. As it can be done during Sprint 1, could you please add it the Sprint 1?
Thank you.

**Comment by JulieG19** [comment]
Hello, 

Can I check the following please:
- which definition will need to be updated?/ have the definition documents been updated?
- @PaulMakinMojaloop , are you aware of this change and was it approved?

**Comment by zarchituntw** [comment]
Hi @JulieG19, 

We are implementing based on the latest FSPIOP specification (v2.0).
https://github.com/mojaloop/api-snippets/blob/main/docs/fspiop-rest-v2.0-openapi3-snippets.yaml

**Comment by PaulMakinMojaloop** [comment]
@JulieG19  Yes it's part of the updated FSPIOP specs to support FX.

**Comment by ZweHMyat** [comment]
POST /quotes
I sent a request with curl to FSPIOP with the following command

curl --location 'http://localhost:4000/quotes' \
--header 'accept: application/vnd.interoperability.quotes+json;version=1.0' \
--header 'content-type: application/vnd.interoperability.quotes+json;version=1.0' \
--header 'date: 2024-05-03' \
--header 'x-forwarded-for: string' \
--header 'fspiop-source: demo-mfi-1' \
--header 'fspiop-destination: demo-mfi-2' \
--header 'fspiop-encryption;' \
--header 'fspiop-signature;' \
--header 'fspiop-uri;' \
--header 'fspiop-http-method;' \
--data '{
    "quoteId": "cc257b7a-a79f-4f55-81f1-f80a6f9f5dff",
    "transactionId": "9f5d9784-3a57-5865-9aa0-7dde77915481",
    "payer": {
        "partyIdInfo": {
            "partyIdType": "MSISDN",
            "partyIdentifier": "123",
            "fspId": "demo-mfi-1"
        },
        "personalInfo": {
            "complexName": {
                "firstName": "Henrik",
                "middleName": "Johannes",
                "lastName": "Karlsson"
            },
            "dateOfBirth": "1966-06-16",
            "kycInformation": "Sample KYC Info"
        },
        "supportedCurrencies": [
            "EUR"
        ]
    },
    "payee": {
        "partyIdInfo": {
            "partyIdType": "MSISDN",
            "partyIdentifier": "456",
            "fspId": "demo-mfi-2"
        },
        "personalInfo": {
            "complexName": {
                "firstName": "Thomas",
                "middleName": "Neo",
                "lastName": "Anderson"
            },
            "dateOfBirth": "1991-03-12",
            "kycInformation": "Sample KYC Info"
        },
        "supportedCurrencies": [
            "USD"
        ]
    },
    "amountType": "RECEIVE",
    "amount": {
        "currency": "EUR",
        "amount": "100"
    },
    "transactionType": {
        "scenario": "DEPOSIT",
        "initiator": "PAYER",
        "initiatorType": "BUSINESS"
    },
    "converter": "demo-mfi-3",
    "currencyConversion": {
        "sourceAmount": {
            "currency": "EUR",
            "amount": "100"
        },
        "targetAmount": {
            "currency": "USD",
            "amount": "109.43"
        }
    }
}'

Post request is sent to the payee
<img width="1513" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemUwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9e6e5f391b9fedef575b4effc5d154b140853129/post_quotes_1.png" alt="post_quotes_1.png" />
<img width="1516" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemkwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cbcb1e0beccefa82c76cccdec63e24eb257a721d/post_quotes_2.png" alt="post_quotes_2.png" />
<img width="1513" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGkwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c307cf2a523b869c6686e8908456b43914d3361b/post_quotes_1_3.png" alt="post_quotes_1_3.png" />


PUT /quotes
Then the payee sent the callback request
<img width="1520" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenEwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--67c4bd40a05db1f133b5ce5fe857016e22816a8f/put_quotes_1.png" alt="put_quotes_1.png" />
<img width="1517" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejIwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--02d83f931b7d84788d525d99adef7e1c2955dd52/put_quotes_2.png" alt="put_quotes_2.png" />

PUT /quotes
Finally, the payer receives the callback
<img width="1516" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEcwQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d44437e3737c35436f8005fe21fa5a5e890c486/put_quotes_2_1.png" alt="put_quotes_2_1.png" />
<img width="1519" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEswQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8b063b8dd4d714f69e35875ffbb989e39b72529a/put_quotes_2_2.png" alt="put_quotes_2_2.png" />
<img width="1520" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME8wQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--66c5b250a518c932c69d075a86a2945c624869cc/put_quotes_2_3.png" alt="put_quotes_2_3.png" />
