### ISSUE TITLE
Technical Documentation : ReadMe Update for account-lookup-bc

### ISSUE THREAD

**Issue by zinzinnyohlaing-tw** [mojaloop/project#3787]
**Goal**:

The task involves adding details following standards to the account-lookup-bc vnext repository

**Acceptance Criteria**:

The readme page of the GitHub repository for "account-lookup-bc" should contain the following sections, following the template.
- [ ] Basic description of the BC / repository
- [ ] Testing, coverage details
- [ ] CI/CD (Continuous Integration/Continuous Deployment) process for the BC
- [ ] Known issues if any
- [ ] Environment variables to be set / configured

**Comment by hsuyeemon-tw** [comment]
PR : https://github.com/mojaloop/account-lookup-bc/pull/18

**Comment by hsuyeemon-tw** [comment]
Hello Sam @elnyry-sam-k, is there anything you would like me to add in this task? Can I continue with this flow in other BC documentations?

**Comment by elnyry-sam-k** [comment]
Thanks @hsuyeemon-tw sure. We were refining the story and added acceptance criteria. 

It would be great if you can add tasks, yes and also we can use this as a template. If you have any questions, lets discuss.
