### ISSUE TITLE
Technical Documentation : ReadMe Update for accounts-and-balances-bc

### ISSUE THREAD

**Issue by zinzinnyohlaing-tw** [mojaloop/project#3788]
The task involves adding more details to the basic description, testing, coverage, and CI/CD (Continuous Integration/Continuous Deployment) process for the following BC.

Acceptance criteria:
-  [ ] Basic description of the BC / repository
-  [ ] Testing, coverage details, how to run
-  [ ] CI/CD (Continuous Integration/Continuous Deployment) process for the BC
-  [ ] Known issues if any
-  [ ] Environment variables to be set / configured

**Comment by hsuyeemon-tw** [comment]
https://github.com/mojaloop/accounts-and-balances-bc/pull/13
