### ISSUE TITLE
Technical Documentation: ReadMe Update for security-bc

### ISSUE THREAD

**Issue by zinzinnyohlaing-tw** [mojaloop/project#3799]
The task involves adding more details to the basic description, testing, coverage, and CI/CD (Continuous Integration/Continuous Deployment) process for the following BC.

- [x]  Basic description of the BC / repository
- [x]  Testing, coverage details
- [x]  CI/CD (Continuous Integration/Continuous Deployment) process for the BC
- [x]  Known issues if any
- [x]  Environment variables to be set / configured

**Comment by hsuyeemon-tw** [comment]
PR Link https://github.com/mojaloop/security-bc/pull/11
