### ISSUE TITLE
Technical Documentation: ReadMe Update for thirdparty-api-bc

### ISSUE THREAD

**Issue by zinzinnyohlaing-tw** [mojaloop/project#3801]
The task involves adding more details to the basic description, testing, coverage, and CI/CD (Continuous Integration/Continuous Deployment) process for the following BC.

- [ ]  Basic description of the BC / repository
- [ ]  Testing, coverage details
- [ ]  CI/CD (Continuous Integration/Continuous Deployment) process for the BC
- [ ]  Known issues if any
- [ ]  Environment variables to be set / configured

**Comment by hsuyeemon-tw** [comment]
PR Link https://github.com/mojaloop/thirdparty-api-bc/pull/4
