### ISSUE TITLE
On-premise-deploy is broken due to unavailable keycloak docker image

### ISSUE THREAD

**Issue by vijayg10** [mojaloop/project#3807]
**Summary**:
docker-compose (in https://github.com/pm4ml/on-premise-deploy) up is throwing an error related keycloak image not found.

**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Expected Behavior**
- We should be able to deploy onprem-deploy and access payment manager UI
- Login should work with username "test" and password "test"

**Pull Requests**
- [x] https://github.com/pm4ml/on-premise-deploy/pull/18
- ~https://github.com/pm4ml/on-premise-deploy/pull/17~ (Don't need this)

**Specifications**
  - Component (if known): https://github.com/pm4ml/on-premise-deploy
  - Bug found/raised by: @vijayg10

**Comment by geka-evk** [comment]
new Keycloak image: quay.io/keycloak/keycloak:12.0.4
