### ISSUE TITLE
Admin UI settlement route name change

### ISSUE THREAD

**Issue by ZweHMyat** [mojaloop/project#3853]
Prefix of settlement routes regarding matrix operations needs to be changed from "matrix" to "matrices".

- Settlement-bc-settlement-svc changed their backend routes regarding matrix operations from "matrix" to "matrices"
- In order to call those routes, admin UI need to update their settlement routes accordingly
- Developer will need to update the matrix routes from "matrix" to "matrices" in settlement service file of admin UI

## Acceptance Criteria
> Generated by [Zenhub AI](https://www.zenhub.com/ai)

 - [ ] **Scenario: Admin UI settlement route name change**
  - Given the settlement routes are using the "matrix" prefix
  - When the prefix is changed to "matrices"
  - Then the route names should be updated accordingly

**Comment by smthitsaworks** [comment]
TW QA team test the one round settlement after this fix. 
The testing result is "Pass".
