### ISSUE TITLE
Understand the performance standards defined

### ISSUE THREAD

**Issue by JulieG19** [mojaloop/project#3880]

**Comment by JulieG19** [comment]
Note from sprint planning: existing tests: https://github.com/mojaloop/ml-core-test-harness/tree/main/packages/k6-tests

Existing tests need to be run against vNext.

**Comment by JulieG19** [comment]
Hi @pedrosousabarreto, just wondering if you had the chance to look at this ticket?

**Comment by pedrosousabarreto** [comment]
Not yet @JulieG19. I'll update as soon as possible.
