### ISSUE TITLE
Update the Admin UI currency dropdown to get from Global Config

### ISSUE THREAD

**Issue by zinzinnyohlaing-tw** [mojaloop/project#3888]

**Comment by hsuyeemon-tw** [comment]
https://github.com/mojaloop/platform-shared-tools/pull/71

**Comment by smthitsaworks** [comment]
This feature will be tested by ThitsaWorks QA team in this ticket (https://app.zenhub.com/workspaces/vnext-workstream-660fc8b866c04915432fd68f/issues/gh/mojaloop/project/3900).
