### ISSUE TITLE
Transfer Prepare & Fulfils are not working against FSPs that don't have lower-case names

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#389]
## **Issue**:
- https://github.com/mojaloop/central-ledger/issues/108

**Tasks**:
- [ ] TBD [ @? ]

**Acceptance Criteria**:
- [ ] TBD

## **Pull Requests**:
- [ ] tbd

## **Follow-up**:
- N/A

## **Dependencies**:
- N/A

## **Accountability**:
- Owner: tbd
- QA/Review: Dev-Team

**Comment by shashi165** [comment]
I created FSPs with different cases like all uppercase(DFSP) and mixed case(Dfsp4) and tested transfer prepare, It works for me. If this is not an issue anymore, we can close the bug

**Comment by elnyry** [comment]
Closing this as per today's discussion..

**Comment by elnyry** [comment]
Please re-open in case there is a recurrence..
