### ISSUE TITLE
To fix: hub operator not able to approve a participant's contact info change request & participant's status change request

### ISSUE THREAD

**Issue by SithuKyaw-Thitsaworks** [mojaloop/project#3891]
**Summary**:
1. In participant's detail page, the contact info change request approval function is not working properly
2. In participant's detail page,  hub operator is not able to approve a participant's status request to enable a participant.

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
1. A hub operator should be able to approve a participant's contact info change request. After a successful approval, the status of the record should change from "Pending" to "Approved by user_name_and_date_time".
2. A hub operator should be approve a participant's status change request to enable or disable.

**Steps to Reproduce**
  For participant's contact info approval bug
  1. Create a contact info change request for a participant with a user
  2. Log in with another user and approve the previously created contact info status change request
   
  For participant's status approval bug
  1. Click "Disable" button to create a status change request for a participant at participant's detail page.
  2. Log in with another user and click "approve" button in the change request list for the previously created request.
  

**Specifications**
  - Component (if known): participants-bc-participants-svc
  - Version: 0.5.11
  - Platform: Mojaloop
  - Subsystem: participants-bc
  - Type of testing: QA smoke testing
  - Bug found/raised by: Yin Min Oo

**Notes**:

- Severity when opened: Medium
- Priority when opened: Medium

**Comment by elnyry-sam-k** [comment]
@SithuKyaw-Thitsaworks can we please follow the bug template please: https://github.com/mojaloop/project/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=

Thank you!

**Comment by SithuKyaw-Thitsaworks** [comment]
Sure @Sam, please let me update the ticket as the bug template.

**Comment by YminOo** [comment]
QA pass for this ticket. 

User can approve/reject the contact info.
Create the contact information with user role
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1hIQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--01312fd2d2539bc2009bd6e52f6b96df71d21962/Screenshot%202024-05-09%20at%2010.44.07%E2%80%AFAM.png" alt="Screenshot 2024-05-09 at 10.44.07 AM.png" />
Approve the request with admin role
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2ZIQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ee582d8a33003e50edaea566257f57e7f52fd7d2/Screenshot%202024-05-09%20at%2010.44.39%E2%80%AFAM.png" alt="Screenshot 2024-05-09 at 10.44.39 AM.png" />
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2pIQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--191327585d0a12f5a2d7214364e707a4e3701162/Screenshot%202024-05-09%20at%2010.45.12%E2%80%AFAM.png" alt="Screenshot 2024-05-09 at 10.45.12 AM.png" />

Reject the request with user role
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNExIQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--447cdd71a1dac2bd642d356c66caed69512a80d6/Screenshot%202024-05-09%20at%2010.59.29%E2%80%AFAM.png" alt="Screenshot 2024-05-09 at 10.59.29 AM.png" />
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFRIQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--44d110720becb309726114e540aecb29c66d363c/Screenshot%202024-05-09%20at%2011.00.10%E2%80%AFAM.png" alt="Screenshot 2024-05-09 at 11.00.10 AM.png" />


User can successfully enable and disable the participant status.
<img width="1673" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlBIQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f763e27ea4501e634791f9ad6d3f7784f52c34d0/Screenshot%202024-05-09%20at%2010.24.05%E2%80%AFAM.png" alt="Screenshot 2024-05-09 at 10.24.05 AM.png" />
**Disable the participant with user role**
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlRIQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e7356912875fb9c59ac967652a61725e99cc6d8d/Screenshot%202024-05-09%20at%2010.24.11%E2%80%AFAM.png" alt="Screenshot 2024-05-09 at 10.24.11 AM.png" />

<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlhIQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dfd08655233d58673a3356f7cd7e3648ed22b33c/Screenshot%202024-05-09%20at%2010.24.16%E2%80%AFAM.png" alt="Screenshot 2024-05-09 at 10.24.16 AM.png" />

**Approved the request with admin role**
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmJIQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7ad7898b733a8026c08f14313cdd98f4a406021d/Screenshot%202024-05-09%20at%2010.26.26%E2%80%AFAM.png" alt="Screenshot 2024-05-09 at 10.26.26 AM.png" />
**Participant status is changed to Disable (Inactive)**
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmZIQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f5e8c57b52a961ca7619bdd20f83015a06b851e5/Screenshot%202024-05-09%20at%2010.26.30%E2%80%AFAM.png" alt="Screenshot 2024-05-09 at 10.26.30 AM.png" />

**Enable the participant with admin role**
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0xIQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6315fe6b1f83898a50c905ec390b34a0021ce6b4/Screenshot%202024-05-09%20at%2010.26.38%E2%80%AFAM.png" alt="Screenshot 2024-05-09 at 10.26.38 AM.png" />
**Approved the request with user role**
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1BIQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--98fa1153d8b8f576f43d984322a9761a5e2c6d79/Screenshot%202024-05-09%20at%2010.41.29%E2%80%AFAM.png" alt="Screenshot 2024-05-09 at 10.41.29 AM.png" />
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1RIQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1f80809ded800c3932ecbace5704899f493f90ff/Screenshot%202024-05-09%20at%2010.41.52%E2%80%AFAM.png" alt="Screenshot 2024-05-09 at 10.41.52 AM.png" />
