### ISSUE TITLE
Net Debit Cap with percentage calculation is not working properly

### ISSUE THREAD

**Issue by NawYinmin** [mojaloop/project#3895]
Summary:
When user create the Net Debit Cap with percentage and approve this, NDC amount is not recalculate and shown 0. It must be calculated according to the related percentage. 

Severity:
Medium

Priority:
Medium

Expected Behavior
 If the user add 1 % to the NDC percentage, then the NDC amount calculation will be 1 % of the settlement amount after the user approve the request.

Steps to Reproduce
  1. Create the Net Debit Cap request with percentage with one user
  2. Approve that request with another user and check for the NDC calculation is correct according to the related percentage of the settlement account

Specifications
  - Component (if known): 
  - Version: 0.5.22
  - Platform: Mojaloop
  - Subsystem:
  - Type of testing: QA smoke testing
  - Bug found/raised by: Yin Min Oo

Notes:

- Severity when opened: Medium
- Priority when opened: Medium

**Comment by ZweHMyat** [comment]
This is fixed now. Here is the PR.
https://github.com/mojaloop/participants-bc/pull/31/files
