### ISSUE TITLE
QA Testing: Settlement-related privileges are not still working. #3709

### ISSUE THREAD

**Issue by zarchituntw** [mojaloop/project#3898]
QA Testing: Settlement-related privileges are not still working. #3709

https://app.zenhub.com/workspaces/vnext-workstream-660fc8b866c04915432fd68f/issues/gh/mojaloop/project/3709

Summary:

1. The users who don't have permission for settlement-related privileges can still access data from models, batches, matrices, and transfer pages and can perform any action on these pages.

Severity:
Medium

Priority:
Medium

**Expected Behavior**

1. Users who don't have settlement-related privileges must not access data from models, batches, matrices, and transfer pages, and cannot perform any action on these pages.

**Steps to Reproduce**
1. Do not assign the settlement-related privileges to the role, and then assign that role to the users. 
2. The users will be unable to perform any settlement-related functions, including accessing models, branches, matrices, and transfers."

**Specifications**

- Component (if known): participants-bc-participants-svc
- Version: 0.5.22
- Platform: Mojaloop
- Subsystem: settlement-bc
- Type of testing: QA smoke testing
- Bug found/raised by: Phyu Sin Myat

**Notes:**

- Severity when opened: Medium
- Priority when opened: Medium

**Comment by elnyry-sam-k** [comment]
@zarchituntw can you please follow the bug report format from the [template](https://github.com/mojaloop/project/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=) so that the details are clear and it can be validated / repro-ed properly, thank you!

**Comment by JulieG19** [comment]
This was demoed during sprint planning and the ticket is resolved.
