### ISSUE TITLE
Participant Name is not redirected to the related participant at the Pending Approval Requests

### ISSUE THREAD

**Issue by zarchituntw** [mojaloop/project#3899]
Summary:
Participant Name is not redirected to the related participant at the Pending Approval Requests

Severity:
Medium

Priority:
Medium

Expected Behavior
1. When the hub operators click on participants' names in the pending approval requests for Fund movements, NDC, and Certificates, it should navigate to the related participant.

Steps to Reproduce
1. At participants, deposit or withdraw funds, update NDC, and upload certificates.
2. Select the participant names in the pending approval requests for Fund movements, NDC, and Certificates; it should redirect to the related participants.

Specifications

Component (if known): participants-bc-participants-svc
Version: 0.5.22
Platform: Mojaloop
Subsystem: participants-bc
Type of testing: QA smoke testing
Bug found/raised by: Yin Min Oo
Notes:

Severity when opened: Medium
Priority when opened: Medium

**Comment by smthitsaworks** [comment]
<img width="1041" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNm5sQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b0aa23ac2ab963d9a08e69cd894f43bb585de0d3/image.png" alt="image.png" />
The testing result is "Pass".
