### ISSUE TITLE
Readme.md and Onboarding.me does not indicate that the sidecar should be disabled for local development

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#390]
## **Issue**:
- https://github.com/mojaloop/central-ledger/issues/38

**Tasks**:
- [ ] TBD [ @? ]

**Acceptance Criteria**:
- [ ] TBD

## **Pull Requests**:
- [ ] tbd

## **Follow-up**:
- N/A

## **Dependencies**:
- N/A

## **Accountability**:
- Owner: tbd
- QA/Review: Dev-Team

**Comment by elnyry** [comment]
Closing this as this step exists now in [Onboarding.md](https://github.com/mojaloop/central-ledger/blob/master/Onboarding.md):
"disable SIDECAR in config/default.json temporary by setting "SIDECAR": { "DISABLED": "true", ... "
