### ISSUE TITLE
QA testing - Update the Admin UI currency dropdown to get from Global Config #3888

### ISSUE THREAD

**Issue by zarchituntw** [mojaloop/project#3900]
QA testing - Update the Admin UI currency dropdown to get from Global Config #3888 and #3913

https://app.zenhub.com/workspaces/vnext-workstream-660fc8b866c04915432fd68f/issues/gh/mojaloop/project/3888
https://app.zenhub.com/workspaces/vnext-workstream-660fc8b866c04915432fd68f/issues/gh/mojaloop/project/3913

Instead of a manual currency dropdown(hardcoded), it will be implemented to show from the global currency config.

Acceptance Criteria:

- [ ] Global currency configuration is displayed in the dropdown.
- [ ]  The currency from new global currency can be transacted and settled.

**Comment by pthandar** [comment]
[currency dropdrown.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXJsQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0ae9323b249df71a414c76b7e2ec52b65f5fe721/currency%20dropdrown.docx)

QA testing --> PASSED
