### ISSUE TITLE
QA testing: Participant Name is not redirected to the related participant at the Pending Approval Requests

### ISSUE THREAD

**Issue by zarchituntw** [mojaloop/project#3906]
QA testing: Participant Name is not redirected to the related participant at the Pending Approval Requests #3899

https://app.zenhub.com/workspaces/mojaloop-project-59edee71d1407922110cf083/issues/gh/mojaloop/project/3899

Summary:
Participant Name is not redirected to the related participant at the Pending Approval Requests

Severity:
Medium

Priority:
Medium

Expected Behavior
1. When the hub operators click on participants' names in the pending approval requests for Fund movements, NDC, and Certificates, it should navigate to the related participant.

Steps to Reproduce
1. At participants, deposit or withdraw funds, update NDC, and upload certificates.
2. Select the participant names in the pending approval requests for Fund movements, NDC, and Certificates; it should redirect to the related participants.

**Specifications**

- Component (if known): participants-bc-participants-svc
- Version: 0.5.22
- Platform: Mojaloop
- Subsystem: participants-bc
- Type of testing: QA smoke testing
- Bug found/raised by: Yin Min Oo

**Notes:**

- Severity when opened: Medium
- Priority when opened: Medium

**Comment by pthandar** [comment]
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0hnQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--696af3a6ae4dc404d4de55fae5bcb17438172379/screen-capture%20%2813%29.webm)



QA Testing --> PASSED
