### ISSUE TITLE
Display the currency from global config at currency dropdown on the Transfer page

### ISSUE THREAD

**Issue by zinzinnyohlaing-tw** [mojaloop/project#3913]
**Acceptance Criteria**

1. It should include the currency from the global config in the currency drop-down.
2. If one of the currencies is selected from the dropdown and then searched, the transaction lists will be displayed according to the selected currency.
3. If 'All' is selected from the currency dropdown, it should display the transaction lists for all currencies.

**Comment by smthitsaworks** [comment]
TW QA team will test this feature in the ticket 3900.
