### ISSUE TITLE
Improvements in the Settlement Reports Preview Screen

### ISSUE THREAD

**Issue by zinzinnyohlaing-tw** [mojaloop/project#3919]
**Acceptance Criteria**

1. At the DFSP Settlement Report and DFSP Settlement Detail Report preview screen, when the report previews are already displayed in the portal, and if the users want to search for another DFSP name and choose a different start/end date and time, the previous report previews should be cleared.
2. The matrix ID in the dropdown should be displayed according to the newly selected DFSP name and start/end date and time, without displaying any previous report preview.
3. When the users select the Matrix ID from the dropdown, the report preview will display information related to the selected Matrix ID.

PR: [https://github.com/mojaloop/platform-shared-tools/pull/80]

**Comment by PaulMakinMojaloop** [comment]
@kyaw-soe-tw Please can you give an update here on your progress?

**Comment by PhyuSinMyat8** [comment]
**### Testing Result**
Clearing the previous report preview when the user choose another settlement ID, and search for another dfsp name and different start date and end date → **passed**

At the DFSP Settlement Report preview screen, when the report previews are already displayed in the portal, and if the user chooses a different settlement id, the previous report previews is automatically cleared.
Besides, if the user choose another dfsp name or different start date and end date and click “Search” button, the previous report previews is cleared and the settlement ID in the dropdown is displayed according to the newly selected DFSP name and start/end date and time.

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODZSQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3d864d5fbf045abb5528999fb31f7cb3a5fcac4b/DFSP%20Settlement%20Report.mp4)

At the DFSP Settlement Detail Report preview screen, when the report previews are already displayed in the portal, and if the user chooses a different settlement id, the previous report previews is automatically cleared.

[Uploading... DFSP Settlement Detail Report.mp4]
