### ISSUE TITLE
[settlements][helm] Mojaloop v16.0.0 deployment on iac fails settlement tests

### ISSUE THREAD

**Issue by kleyow** [mojaloop/project#3950]
**Summary**:
Test cases below fail on v16 of Mojaloop charts.

[new sims] transfers, positions CGS Window1 tests (OTC-649, OTC-645)
[new sims] new transfers window4
Create Settlement for previously closed 5 windows

Investigation needed.
**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Expected Behavior**
Test cases pass

**Steps to Reproduce**
  1. Deploy Mojaloop v16 to iac 
  2. Run GP

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by:

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by elnyry-sam-k** [comment]
@kiswend - have you seen this on any of the deployments recently made that use Mojaloop v16 (and IaC v5)?

**Comment by kiswend** [comment]
@kleyow , which versions of IaC and ansible collection did you use?

**Comment by kleyow** [comment]
@kiswend 
mojaloop_chart_version: 16.0.0
ansible_collection_tag: v5.2.6

**Comment by kleyow** [comment]
The issue was me assuming that gross settelement service was deployed since I assumed mojaloop was configured like default but past work seems to have been overlooked on my end.

The environment I was working on had cgs service set to 
```
  centralsettlement-handler-grosssettlement:
    replicaCount: 0
```

Tests are working fine. Closing.
