### ISSUE TITLE
Filter Transaction View using Transaction Value

### ISSUE THREAD

**Issue by PaulMakinMojaloop** [mojaloop/project#3969]
As a Hub Operator

I want to be able to search for a transaction by value, in order to find out the remaining details of the transaction

So that I can find a transaction even if the only characteristic I know is the value (though the filter can be used in conjunction with other filters, such as Payer DFSP)

The current filters are as follows:
<img width="1323" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejU4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--64b3d460106e7459d5678865fdf4ad650e78b58c/Screenshot%202024-06-20%20at%2014.19.50.png" alt="Screenshot 2024-06-20 at 14.19.50.png" />

A new filter, for transaction value (exact value only, no ranges required) should be added.

The corresponding window for vNow is as follows:

<img width="1438" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenQ4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8c6f443d1ce3972b99e5cd53468e45239aead4e5/Screenshot%202024-06-20%20at%2014.03.22.png" alt="Screenshot 2024-06-20 at 14.03.22.png" />

In this, the value filter is implemented in the "Amount" column - clicking on the column header lets the operator enter a value, which is then used to filter the table.

**Comment by Monicaminzy** [comment]
<img width="1520" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0hLQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0484523e8c998e4dd694db63fa194351bd05ed4c/image.png" alt="image.png" />

<img width="1776" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd25LQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--57f949e25e219557a938a45432e47e15e16551d8/image.png" alt="image.png" />

New filter of exact txn value with various decimal values, corresponding data is displayed. It works well.
