### ISSUE TITLE
To Fix: Amounts with more than four decimals in Pending Approval Requests

### ISSUE THREAD

**Issue by ei-nghon-phoo** [mojaloop/project#4007]
## Description

If the balance amount (without decimals) in the initiation report does not match the expected DFSP settlement amount balance in the portal, the fund adjustment at the liquidity check will differ from the amount in the pending approval requests. Sometimes, the amount may exceed four decimals. Such amounts cannot be approved.

### The balance at the settlement initiation report
<img width="1343" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTVjQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--06d4a80c2cae394470df2e23cadaba1c48cd6291/image.png" alt="image.png" />
<img width="1000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0JjQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ca5da77e3f7f6004348af9b78a74dc7a5ba559ef/image.png" alt="image.png" />
### At Pending Approval Request
<img width="1709" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0ZjQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ca6ecb90a7237db44f1a2acff03e40199ae80f2d/image.png" alt="image.png" />
<img width="1753" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0pjQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3dfc9c262704360288391f158449a1e1337853d4/image.png" alt="image.png" />
<img width="1756" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK05jQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8122277b57abc87e4de6d21b5c79a2af86883675/image.png" alt="image.png" />

**Comment by ei-nghon-phoo** [comment]
### Test Cases for Transaction Handling with Decimal Points

---

#### **Test Case 1: Successful Transaction with Valid Decimal Points**

- **Test Case ID**: TC001
- **Description**: Verify that a new transaction with decimal points less than the maximum allowed points is successful.


- **Expected Result**: 
  - The transaction should be successful.
  - The balance should be correctly reflected (e.g., if the initial balance was 500, the new balance should be 399.75).

---

#### **Test Case 2: Successful Deposit with Valid Decimal Points**

- **Test Case ID**: TC002
- **Description**: Verify that a deposit with decimal points less than the maximum allowed points is successful.
- **Expected Result**: 
  - The deposit should be successful.
  - The balance should be updated correctly (e.g., if the initial balance was 300, the new balance should be 350.75).

---

#### **Test Case 3: Successful Withdrawal with Valid Decimal Points**

- **Test Case ID**: TC003
- **Description**: Verify that a withdrawal with decimal points less than the maximum allowed points is successful.
- **Expected Result**: 
  - The withdrawal should be successful.
  - The balance should be updated correctly (e.g., if the initial balance was 400, the new balance should be 374.50).

---

#### **Test Case 4: Failed Transaction with Excessive Decimal Points**

- **Test Case ID**: TC004
- **Description**: Verify that a new transaction with decimal points exceeding the maximum allowed points is not successful.
- **Expected Result**: 
  - The transaction should NOT be successful.
  - The balance should remain unchanged.

---

#### **Test Case 5: Failed Deposit with Excessive Decimal Points**

- **Test Case ID**: TC005
- **Description**: Verify that a deposit with decimal points exceeding the maximum allowed points is not successful.
- **Expected Result**: 
  - The deposit should NOT be successful.
  - The balance should remain unchanged.

---

#### **Test Case 6: Failed Withdrawal with Excessive Decimal Points**

- **Test Case ID**: TC006
- **Description**: Verify that a withdrawal with decimal points exceeding the maximum allowed points is not successful.
- **Expected Result**: 
  - The withdrawal should NOT be successful.
  - The balance should remain unchanged.

---

**Comment by ei-nghon-phoo** [comment]
Problem background: 
Computers represent floating-point numbers using a fixed number of bits, typically 32 bits (single precision) or 64 bits (double precision). This fixed representation means that not all real numbers can be represented exactly. Some numbers, like 0.1 or 0.01, cannot be precisely represented in binary floating-point format. When a user inputs a number like 23.002, the computer tries to represent it using the available bits. However, since the exact value cannot be represented, the computer stores the closest approximation, which in your example is 23.0029728934. This rounding error occurs because the computer has to fit the number into a fixed number of bits. The more bits used, the more precise the representation, but there will always be some inaccuracy. The problem is exacerbated when performing arithmetic operations on floating-point numbers. Rounding errors can accumulate, leading to unexpected results, such as (0.1 + 0.2) not being equal to 0.3 in a computer's arithmetic.

**Comment by PhyuSinMyat8** [comment]
### Testing Result
**QA** Passed

### Summary

All test Cases for Transaction Handling with Decimal Points passed.

- Test Case 1: Successful Transaction with Valid Decimal Points
- Test Case 2: Successful Deposit with Valid Decimal Points
- Test Case 3: Successful Withdrawal with Valid Decimal Points
- Test Case 4: Failed Transaction with Excessive Decimal Points
- Test Case 5: Failed Deposit with Excessive Decimal Points
- Test Case 6: Failed Withdrawal with Excessive Decimal Points
- Test Case 7: Settlement Initiation Report uploading: Upload the same balance amount in liquidity balance check
- Test Case 8: Settlement Initiation Report uploading: Upload more decimal amount than the initial DFSP settlement amount balance in the portal
- Test Case 10: Settlement Initiation Report uploading: Upload less decimal amount than the initial DFSP settlement amount balance in the portal

Please refer to the test result file below for more information.

### Specification
Updated date of tested version: 8-Aug-24
mojaloop/vnext-admin-ui-svc: 0.5.41
mojaloop/transfers-bc-transfers-api-svc: 0.6.5

[Testing Result_Zenhub Ticket #4007_20240816.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnRuQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e7ed61aae47f06828e88e43684f6d73eeabaf826/Testing%20Result_Zenhub%20Ticket%20%234007_20240816.xlsx)
