### ISSUE TITLE
To Fix: Percentage NDC amount decimal values

### ISSUE THREAD

**Issue by ei-nghon-phoo** [mojaloop/project#4008]
Acceptance Criteria

- The percentage NDC amount should be automatically updated with decimal places if required, when the settlement process is finalized.
- The percentage NDC amount should be automatically updated with decimal places if required, when both the deposit and withdrawal amount from the participant.

<img width="974" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkdpQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f1e264022c28fa643aacaf9a00161aea338a953c/image.png" alt="image.png" />

**Comment by ei-nghon-phoo** [comment]
https://github.com/mojaloop/participants-bc/pull/41

**Comment by PhyuSinMyat8** [comment]
### Testing Result

- QA Passed

### Summary

- The percentage NDC amount adjusts automatically when there are any changes in settlement amount.
- After withdrawing and depositing values, the percentage NDC amount updates correctly.
- After settling the matrix, the percentage NDC amount updates correctly as well.
- If there are decimals in the value of NDC percentage, the system shows two decimal places by rounding up.

Please refer to the screenshot below for more information.

 
**Specification**

- twstm/participants-bc-participants-svc:0.6.4-bd4a72dd49
- curlimages/curl:8.3.0


Decimal values that setup in mongodb
<img width="293" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3VpQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--895ef5d231d44a094b6ae3b52d70a935f0fcf328/1.png" alt="1.png" />

**Testing with the whole number in settlement account**
Initial value [Settlement amount: 4999976]
<img width="1549" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3lpQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7d29715b4c02ae7f541b3ed7c3b5dd866edc26b5/2.png" alt="2.png" />

10% NDC amount [Show correct percentage value]
<img width="1551" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzJpQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--35c4e01e5cb66fce2c59fb4136f164ee1a84f6eb/image.png" alt="image.png" />

20% NDC amount [Show correct percentage value]
<img width="1564" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzZpQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1a3be42f5841595263cd6f8e1918336c94cc5f99/image.png" alt="image.png" />

**Testing with the decimal value in settlement account**
Initial value [Settlement amount: 4,999,974.67]
