### ISSUE TITLE
[35] 4.50 Format the validation(joi)  error message to conform to Specification

### ISSUE THREAD

**Issue by shashi165** [mojaloop/project#410]
Priority: LOW

Current validation error message from ML-API-ADAPTER is not in user friendly format
{
    "id": "BadRequestError",
    "message": "child \"amount\" fails because [child \"amount\" fails because [amount with value \"aa.12\" fails to match the required pattern: /^([0]|([1-9][0-9]{0,17}))([.][0-9]{0,3}[1-9])?$/]]"
}

Format the message to user friendly format

- [x] 1. Change code in the ML API adapter : Transfer routes to throw the Joi error for all Joi payload validations. [@bothadeon]
- [x] 2. Test all possible : Joi errors throws on the Joi payload value validations. [@bothadeon]
- [x] 3. Add a parser to extract the the payload validation error message in a more user friendly format. [@bothadeon]
- [x] 4. Test the parser against all Joi error messages thrown during validation of payload values.[@bothadeon] 
- [x] 5. Change code in the The central services shared : @mojaloop/central-services-error-handling/src/handler.js to call the parser and format the error message according to the API spec for payload validations.[@bothadeon]
- [x] 6. Run complete tests on all the payload fields being validated.[@bothadeon]
- [x] 7. Change/Add unit tests  - Central services error handling.[@bothadeon]
- [x] 8. Change/Add unit tests  - ML-API-Adapter.[@bothadeon] 
- [x] 9. Ensure code coverage pass  - Central services error handling.[@bothadeon]
- [x] 10. Ensure code coverage pass  - ML-API-Adapter.[@bothadeon]
- [x] 11. Pull request  - ML-API-Adapter.[@bothadeon]
- [x] 12. Pull request  - Central services error handling.[@bothadeon]
-

**Comment by elnyry** [comment]
Will get to this but this is not critical

**Comment by elnyry** [comment]
Need to discuss this with Shashi before moving forward

**Comment by elnyry** [comment]
**Expected behavior**:
Should respond with a 400 error with response body that conforms to the spec - something like the below message

errorInformation: 
            {
                “errorCode”: “3101”, 
                “errorDescription”: “Format of the parameter is not valid. For example, amount set to 5.ABC. The error description field should specify which information element is erroneous.", 
                extensionList:
                {
                  extension:
                  [ 
                      { 
                          “key”: “errorDescription”, 
                          “value”: “This is a more detailed error description” 
                      }
                  ]
                }
            }

**Comment by bothadeon** [comment]
Pull request for Feature/410 Add user friendly joi error msg #13 ( "central-error-handling framework changes") : https://github.com/mojaloop/central-services-error-handling/pull/13

**Comment by bothadeon** [comment]
Pull Feature/#410 added user friendly loi error messages #60 ('ml-api-adaptor) : https://github.com/mojaloop/ml-api-adapter/pull/60

**Comment by bothadeon** [comment]
Rajiv / Valentin completed code review and approved both pull requests.
