### ISSUE TITLE
Fulfil Reject should send out two notifications: One to PayerFSP and One to PayeeFSP similar to a successful Fulfil

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#441]
## **Goal**:
As a Switch
I want to _notify both the Payer and Payee in the event of a fulfil reject_
so that all parties are aware of the outcome of the original request (similar to a fulfil commit)

**Tasks**:
- [x] Add another Notification call to the Payee, similar to the Payer notification already provided for Fulfil reject

**Acceptance Criteria**:
- [ ] Notifications for rejects are sent to both FSPs for uniformity

## **Pull Requests**:
- [ ] 

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by HenkKodde** [comment]
Have simulated this with the assistance of Rajiv. notifications should be sent to both Payee and Payer as per the outcome of the simulation and the log entries.
