### ISSUE TITLE
Add documentation (i.e. Swagger Viewer, and swagger.json) end-points to Central-Settlements

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#442]
## **Goal**:
As a user I want to be able to see the documentation for endpoints in Central-Settlements so that I can discover how the API is specified

**Tasks**:
- [ ] Create Swagger for the endpoints in Central-Settlement

**Acceptance Criteria**:
- [ ] Documentation has beed created

## **Pull Requests**:
- [ ] 

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry** [comment]
Not relevant right now
