### ISSUE TITLE
[initContainer] Central Settlements - Stability issue (ML v3.5.2)

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#455]
Priority: HIGH
Env : ML
Version: 3.5.1 and 3.5.2
When I'm trying to connect to central settlements service to test settlements feature, I noticed the connection is intermittent. I used 
http://test-central-settlement.mojaloop.live/v1/settlementWindows

Below is the screenshot of that.
<img width="604" alt="screen shot 2018-09-17 at 2 02 40 am" src="https://user-images.githubusercontent.com/38143240/45608102-c283c180-ba1e-11e8-8544-f9b6f067cbf8.png">

Acceptance Criteria: 
Connection to Central Settlements services must be stable. 
so that I can proceed further testing of settlements feature.

**Comment by elnyry** [comment]
Thanks Sri. This will be looked at, Rajiv raised an issue as well - https://github.com/mojaloop/project/issues/454

**Comment by sri-miriyala** [comment]
Sam, is this available for me to test?

**Comment by elnyry** [comment]
Hi Sri, we don't really know what the issue is yet, but added some additional logging to the settlement service so that we can see what's happening if there is any issue

**Comment by sri-miriyala** [comment]
I tested it and link is working now. I will test again multiple times tomorrow and will update the status.

**Comment by elnyry** [comment]
Re-opening this for the 3.7.1 settlements build.

Sri had issue accessing this endpoint:
curl -X GET \
 'http://test-central-settlement.mojaloop.live/v1/settlementWindows?state=OPEN' \

![image](https://user-images.githubusercontent.com/10507686/46687718-2ada5300-cc19-11e8-9dbe-2bc86d3d39dc.png)

deleted the settlements pod and it started working now....

I think we need to take a look regarding why this is happening after the deployment, though we have the work-around..

**Comment by vgenev** [comment]
please try to check the log. We will have the new errors with error stack deployed, as well tomorrow asap

**Comment by sri-miriyala** [comment]
As per 3.8 release, still I had to delete the central settlements pod for the first time after the deployment.

**Comment by elnyry** [comment]
Need an init-container to fix this, will have to prioritize this soon.

**Comment by sri-miriyala** [comment]
With new releases v4.4.0 and 4.4.1, I found the settlement pod needs restart. That's the latest update on this.

**Comment by HenkKodde** [comment]
Please verify if this happens only during an new deployment or randomly between deployment.

**Comment by elnyry** [comment]
@HenkKodde Its definitely present after every new deployment and lets address that to start with. If there's any issue intermittently after an initial deployment, we'd need a new bug for that, when that happens

**Comment by lewisdaly** [comment]
@elnyry is this something I could look at? It looks like it might be a good place for me to get started with my contributions.

**Comment by elnyry** [comment]
Thanks @lewisdaly , I think @HenkKodde already has a fix in the works, we should see a PR soon, if not today..

Just for reference, please check the pipeline and assignee list for next time.. This is currently 'in progress' as you can see and has assignees, so its taken...

**Comment by elnyry** [comment]
This should now be fixed - with the changes in helm. 

Will re-open this if there is a recurrence after a release of helm in Sprint6.2
