### ISSUE TITLE
Settlement Transfer and Settlement Position Change

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#461]
**Goal**:
As a DFSP
I want to be able to _see changes in my position_
so that _settlements/deposit/withdrawals from the settlement account are correctly reflected and can be read like a bank statement_

As a Hub Operator
I want _changes in position to be reflected as transfers_
so that _the settlement accounts for the DFSPs can be reconciled to the expected results_

**I. Tasks**:
- [x] 1. Design Settlement Position Transfer
  - [x] 1.1. Database schema model change & seeds (ledgerAccountType, ledgerEntryType, transferParticipantRoleType) [@ggrg]
  - [x] 1.2. Update existing sequence diagrams to cater for signed amounts (click [here](https://wmgs-my.sharepoint.com/:o:/r/personal/warren_wmglobalsolutions_com/_layouts/15/WopiFrame2.aspx?sourcedoc=%7B5C9A48EE-0114-4170-B0BF-E480315B9E02%7D&file=OSS_Mojaloop&action=default&RootFolder=%2fpersonal%2fwarren_wmglobalsolutions_com%2fDocuments%2fNotebooks%2fOSS%20Mojaloop%2fOSS_Mojaloop&d=w5c9a48ee01144170b0bfe480315b9e02) for the sign matrix and navigate to _Settlement Position and Signed Amount_ tab) [@ggrg]
  - [x] 1.3. Update existing sequence diagrams to cater for multiple accounts (position & settlement) [@ggrg]
  - [x] 1.4. Participant accounts initialisation process [@ggrg] [src/admin/participants/handler.js](https://github.com/mojaloop/central-ledger/blob/d213d3ad89b0d7147e1ef34996e38e4093485985/src/admin/participants/handler.js#L84) (T 6)
  - [x] 1.5. Sequence diagram for settlement transfer prepare [@ggrg]
  - [x] 1.6. Sequence diagram for settlement transfer execution (commit) [@ggrg]
- [x] ~2. Configure a topic in central-ledger to queue events from central-settlement (similar to the communication between central-ledger and ml-api-adapter through notification-topic)~
- [x] 3. Implement changes to the database, incl. seeds [@ggrg]
  - [x] 3.1. Implement server cached enums in central-ledger [@ggrg]
- [x] 4. Implement signed amounts
  - [x] 4.1. Alter transferParticipant inserts during transfer prepare in central-ledger as per design [@ggrg]
  - [x] 4.2. Alter settlement accounts rollup formula in central-settlement according to the design [@ggrg]
- [x] 5. Update central-ledger codebase so that all references to participantCurrencyId point to the _Position Account_ [@ggrg]
- [x] 6. Update central-ledger admin api so that both accounts (Position & Settlement) are created in place of the currently created sole account (participantCurrency entry) [@ggrg]
- [x] 7. Implement prepare routine for populating settlement transfer from central-settlement. Currently its purpose is to be called after updateSettlementById. That may change underway, but what should happen as minimum when updating settlementParticipantCurrency.currentStateChangeId is to insert newly generated transferId (guid) that will identify the settlement transfer. [@ggrg]
- [x] 8. Implement settlement transfer commit for when the entire settlement is SETTLED. [@ggrg]
- [x] ~9. Would that process affect participantLimit NET_DEBIT_CAP entry at the end~ No
- [x] 10. Unit tests
  - [x] 10.1. central-ledger [@ggrg]
  - [x] 10.2. central-settlement [@ggrg]
- [x] 11. Code coverage
  - [x] ~11.1. central-ledger~ (not improved)
  - [x] 11.2. central-settlement [@ggrg] (improved, but not to 100%)
- [x] 12. Integration tests
  - [x] 12.1. central-ledger [@ggrg]
  - [x] ~12.2. central-settlement~ (not improved)

**Pull Requests**:
- [x] https://github.com/mojaloop/docs/pull/81
- [x] https://github.com/mojaloop/central-ledger/pull/150
- [x] https://github.com/mojaloop/central-settlement/pull/40
- [x] https://github.com/mojaloop/docs/pull/85

**II. Acceptance Criteria**:
Verify that…
- [x] 1. DFSPs have multiple accounts (participantCurrencies) in the same Currency so that there is at least a Position Account and a Settlement Account (T 3, 5, 6)
- [x] 2. All transfers add up to zero in a finalized state (COMMITTED or ABORTED) (T 8)
- [x] 3. Switchable: when an entire settlement is SETTLED, then the settlement transfers take place between a DFSP's Position and Settlement accounts. (T 8)
- [x] 4. Alternative to 3, is that this is recorded after each individual participant's account has been settled - this will not be done now. (T 7)
- [x] 5. Transfers wrt Position need to clearly distinguished, use the ledgerEntryType with additional enumerations: SettlementDeposit, SettlementWithdrawal, PositionDeposit, PositionWithdrawal - to indicate when part of the Settlement Process rather than externally triggered (T 3)

**III. Implementation notes**:
- [x] 1. Add a new enumeration table: ledgerAccountType with initial values of [Position, Settlement](T 3, 5)
- [x] 2. Add ledgerAccountTypeId to the participantCurrency so that the accounts can be distinguished (T 3, 5, 6)
- [x] 3. Update existing queries against participantCurrency to filter in the join / where on the  ledgerAccountTypeId (T 6)
- [x] ~4. When a Settlement is complete and is SETTLED it places messages for each DFSP Position to be settled on to a topic for the PostionSettlementHander (a new handler described below) (T 7, 8)~ Not applicable anymore
- [x] 5. Implement a separate PositionSettlementHandler that
  - [x] a) ~Relying on the reservedValue mechanism against the position, this allows us to modify the position in a horizontally scaled manner. It also will modify two positions - the DFSP Position ledger account and the DFSP Settlement Ledger account in the single process (T 7, 8)~ Not applicable anymore
  - [x] b) ~This will still need to minimize the length of DB transactional locking on the position, so "prepare" the transfer first - adding rows (INSERT into) transferDuplicateCheck, transfer, transferPariticpant, transferfulfilmentDuplicateCheck (T 7)~ Not applicable anymore but the performance of the transactions to be **monitored**
  - [x] c) Then finalize it against both positions within the DBTransaction : transferFulfilment transferStateChange, particpantPositionChange (x2) and UPDATE participantPosition (x2) (T 8)
  - [x] d) Defaults for omitted or N/A columns
    - [x] i. transferId = generated uuid
    - [x] ii. transferDuplicateCheck = hash of request / message from Kafka
    - [x] iii. ilpPacket = none
    - [x] iv. ilpCondition, ilpFulfilment = "0"
    - [x] ~v. settlementWindow is set when finalising the transfer~ (settlementWindowId = NULL)
    - [x] vi. transferParticipantRoleTypeId = DFSP_SETTLEMENT_ACCOUNT / DFSP_POSITION_ACCOUNT
    - [x] vii. ledgerEntryTypeId = SETTLEMENT_NET_RECIPIENT / SETTLEMENT_NET_SENDER (also add POSITION_DEPOSIT / POSITION_WITHDRAWAL)
    - [x] ~viii. transferFulfilment = current open settlement Window (net effect is zero, but it will important to have in settlementTransferParticipant table for reporting)~ (settlementWindowId = NULL)
- [x] 6. Not expecting a corresponding Quote for this as needs to work in core OSS mode.

**Dependencies**:
- none

**Accountability**:
- Owner @ggrg @wdcmb 
- QA/Review

**Comment by RobReeve** [comment]
The DFSP should be able to see their position, but there is a risk that they may set a position that does not reflect their balance. So any "DFSP can make changes to their position" should only be a request for the operator to make the change.

**Comment by elnyry** [comment]
This is a huge story and since we are just following kanban approach for the PI 3.5 (Sprints 3.6, 3.7), moving this over to 3.7
