### ISSUE TITLE
GET /settlementWindowByParam - repetition of the results

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#474]
Priority: Medium
Env: ML AWS, v3.5.2
Tool : Postman
API : Settlements
Endpoint: GET /settlementWindowByParams
Description: 
When I'm trying to validate the settlements API, for filtering the settlement windows based on params values. 
Values given: 
Participant Id = 1 
other params not given.
Result: 
Response contains multiple instances of the same settlement window. For this specific participant, I got 7 instances, which are 2 from settlementwindow ID=4, 2 from settlement window ID =5 and 4 from settlement window ID =1. All of these show multiple occurrence of the each window with same status.
The same result (multiple occurrence of the same result) if I choose, participant Id and State.
Screenshot:
<img width="853" alt="screen shot 2018-09-24 at 1 22 15 am" src="https://user-images.githubusercontent.com/38143240/45938877-11d86d80-bf9c-11e8-836c-0943e7a82df9.png">

<img width="842" alt="screen shot 2018-09-20 at 12 39 17 am" src="https://user-images.githubusercontent.com/38143240/45938881-1ac93f00-bf9c-11e8-8639-5d799eed7076.png">

Expected result:
One instance of each window for the given parameters, without repetitions.

**Comment by ggrg** [comment]
Fixed!

**Comment by sri-miriyala** [comment]
Tested and working as expected. Hence closed.
Request:
curl -X GET \
  'http://test-central-settlement.mojaloop.live/v1/settlementWindows?participantId=2' \
  -H 'Cache-Control: no-cache' \
  -H 'Postman-Token: b60adecd-b99a-4b8a-90f3-914cd1a8d766'
Response:
<img width="515" alt="screen shot 2018-10-03 at 9 32 56 am" src="https://user-images.githubusercontent.com/38143240/46413606-54fab500-c6ef-11e8-803d-2ce192dad072.png">
