### ISSUE TITLE
GET /settlmentBySettlementParticipantAccount - no results obtained upon providing three required params

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#475]
Priority: High
Env: ML AWS, v3.5.2
Tool : Postman
API : Settlements
Endpoint: GET /settlementBySettlementParticipantAccount
Description: 
Given the three params in the request, Settlement 
Participant Id = 1 
Settlement id = 2 / 1 / 3
Account Id =1
Result: 
Error msg.
{ "statusCode": 400, "error": "Bad Request", "message": "Invalid request params input" }
<img width="748" alt="screen shot 2018-09-24 at 1 53 51 am" src="https://user-images.githubusercontent.com/38143240/45939277-53b6e300-bf9f-11e8-9151-57f6245fc914.png">
Expected result:
Expecting all the windows that are associated with the given params.

**Comment by sri-miriyala** [comment]
Hi Georgi - I see you are sending a GET request. Is it not a PUT request? Swagger def says it is a PUT.

**Comment by elnyry** [comment]
Hi Sri,
Sorry but I don't understand.. The snapshot and the details, title in the bug refer to the GET on this. Is that another bug you are referring to about? May be I'm missing something..

**Comment by sri-miriyala** [comment]
@ggrg.. Pls ignore the previous screen shot that I pasted in the story. In accordance with the Curl command you posted above, below I'm including the curl command I used to test against the AWS env. 
curl -X GET \
  http://test-central-settlement.mojaloop.live/v1/settlements/1/participants/1/accounts/1 \
  -H 'Cache-Control: no-cache' \
  -H 'Postman-Token: d1f68615-109a-e0d1-dedf-b43315469139'

and here is the response I received.
{
    "statusCode": 500,
    "error": "Internal Server Error",
    "message": "An internal server error occurred"
}

**Comment by sri-miriyala** [comment]
Tested and is working as expected. But I noticed an invalid response when I send a participant Id and account Id, which is not associated with that participant Id.
So below is the bug I opened on this issue.
https://github.com/mojaloop/project/issues/491
Hence this is closed.
