### ISSUE TITLE
GET /settlements - without passing any params

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#479]
Priority: Medium
Tool : Postman
API : Settlements
Endpoint: GET /settlements
Description:
When I'm trying to call the GET /settlements without passing any parameters, it is failing as expected but in the response error msg it is not giving any meaningful error information back.
Below are the request and responses from postman.
Request :
curl -X GET 
http://test-central-settlement.mojaloop.live/v1/settlements 
-H 'Cache-Control: no-cache' 
-H 'Postman-Token: 0abf4700-af3e-57eb-60e2-07509362142c'
Response:
{ "statusCode": 404, "error": "Not Found", "message": "Cannot read property 'find' of undefined" }
Expected response:
A meaningful error msg in response, for all the errors as per the missing fields.

Acceptance Criteria:
Error msg should be appropriate and should give information which fields are missing in the request. 
Ex: Atleast one parameter is required.

**Comment by ggrg** [comment]
Hello Sri - I can not reproduce what is described above. Here's a screenshot of the response I get:
<img width="806" alt="getsettlementsbyparams" src="https://user-images.githubusercontent.com/20338055/46153727-fe672400-c273-11e8-9cdf-2e7bcdb186f4.png">

**Comment by sri-miriyala** [comment]
Hi Georgi - I'm testing against ML AWS env. 
Here is my request:
curl -X GET \
  http://test-central-settlement.mojaloop.live/v1/settlements \
  -H 'Cache-Control: no-cache' \
  -H 'Postman-Token: 09e7c2af-70f2-49d9-e50d-9065bd4c8ef1'

Response 
    "statusCode": 404,
    "error": "Not Found",
    "message": "Cannot read property '_core' of undefined"
}

Behavior is as expected. Just the error msg needs to be updated. Your local response is good.

**Comment by elnyry** [comment]
Ok Georgi is using the latest version whereas the one on AWS is a version lower - since, as you know we've rolled it back

**Comment by sri-miriyala** [comment]
ok.. Thanks Sam. Which version is in AWS now? 3.6.1?

**Comment by sri-miriyala** [comment]
Got it... central settlements is 3.5.0 
and central ledger is 3.6.1

**Comment by elnyry** [comment]
Looks like for Georgi locally the latest version is working fine.. Let me know when you think we can move to the latest version for central-settlement

**Comment by elnyry** [comment]
Should be able to verify this now - since the last deployment

**Comment by sri-miriyala** [comment]
Tested but still the error msg is not appropriate. It shd be like the one, Georgi's local response " Atleast one param is required."
Below is request:
curl -X GET \
  http://test-central-settlement.mojaloop.live/v1/settlement \
  -H 'Cache-Control: no-cache' \
  -H 'Postman-Token: fbfca4ef-54f6-4402-8839-b3bb1cfcc495'

Response:
{
    "statusCode": 404,
    "error": "Not Found",
    "message": "Not Found"
}

**Comment by sri-miriyala** [comment]
Sorry my request sent earlier missing 's' in settlements

With the right request, it is working as expected.
Hence closed.
Screen shot:
<img width="868" alt="screen shot 2018-10-04 at 8 16 09 am" src="https://user-images.githubusercontent.com/38143240/46474221-5213c900-c7b0-11e8-96f7-ca579714a4f5.png">
