### ISSUE TITLE
POST limits - Negative amount should not be allowed

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#484]
Priority : Low
Severity: High
Tool : Postman
API : Limits
Env: ML AWS v3.5.2

Description:
I'm able to set the limits of payerfsp to a negative amount, which should not be allowed by Switch.

Steps to reproduce:
In postman, for POST /limits request provide amount as "-1000" along with DFSP name, limit type and currency. Send the request. You get a response with the body showing the "-1000" is set as NDC.

Screenshot:
<img width="695" alt="screen shot 2018-09-28 at 9 18 45 am" src="https://user-images.githubusercontent.com/38143240/46211371-61eb6300-c301-11e8-945a-467e40571d10.png">

Acceptance Criteria:
An error msg indicating that, this action is not permitted.

**Comment by sri-miriyala** [comment]
Needs some additional vetting before we can consider this as a bug. Rob to followup on this.

**Comment by elnyry** [comment]
Ok. In that case, moving this to Post-PI3

**Comment by sri-miriyala** [comment]
As per Rob's input, I'm closing this bug for now.
