### ISSUE TITLE
As a Hub Operator, I want to see all Settlement Windows

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#502]
Priority : HIGH
API : Settlements

Description:
As a Hub operator, I want to see a full list, and state of all Settlement Windows that includes
Window ID, Net Settlement Position by DFSP and currency, number of transactions per DFSP, Start Date (and end Date) + Time, State, Sub State

**Comment by elnyry-sam-k** [comment]
@sri-miriyala - is this still relevant?

**Comment by elnyry-sam-k** [comment]
Please re-open if this is relevant and/or still needed
