### ISSUE TITLE
Settlement API - UpdateSettlementById is failing

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#503]
PRIORITY: HIGH
Environment: Mojaloop AWS
Deployment Version: 3.7

Regression testing the new deployment, I am finding that UpdateSettlementById is failing where as in the previous deployment similar request worked fine. As per the Settlement API spec, there is no change.  Below are my curl requests and response.

curl -X PUT \
  http://test-central-settlement.mojaloop.live/v1/settlements/3 \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: c144dfb3-380c-4497-9781-a3c6e78da142' \
  -d '{
  "participants": [
    {
      "id": 1,
      "accounts": [
        {
          "id": 1,
          "reason": "reason",
          "state": "SETTLED"
        }
      ]
    }
  ]
}'

{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "Invalid time value"
}

**Comment by ggrg** [comment]
The problem seems to be a missing config in default.json:
`"TRANSFER_VALIDITY_SECONDS": "432000"`

**Comment by elnyry** [comment]
Thanks Georgi.. that does seem to be the issue.

After I updated the configMaps to have that config for central-settlement, the request from postman worked fine.

![image](https://user-images.githubusercontent.com/10507686/46725210-56048700-cc99-11e8-8785-13cee876c682.png)

**Comment by sri-miriyala** [comment]
Tested against bug fix and working as expected.
