### ISSUE TITLE
Unable to create a new participant using admin API

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#504]
Priority: Low (after triage changed form High)
Env : ML AWS
Version: 3.7

Description:
I tried to test the cross currency transfer scenario. As part of that I'm trying to add a new participant. Below is the request and the response that I received.
curl -X POST \
  http://test-central-ledger.mojaloop.live/admin/participants \
  -H 'Authorization: Basic YWRtaW46YWRtaW4=' \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: 0af9df8d-d34f-4dcf-9363-ecce3f4ef245' \
  -d '{
  "name": "payer4fsp",
  "currency": "USD"
}'

RESPONSE:
{
    "id": "InternalServerError",
    "message": "An internal server error occurred"
}

Expected Response:
New participant is created with a given currency.

**Comment by elnyry** [comment]
I suspect its some intermittent issue with the central admin service. It appears that went down, even though the pod looks fine. I've used this to setup the initial test data for 6 FSPs and it worked fine. 

I deleted the pod (central-ledger service) and when it came back it registered an FSP fine.

**Comment by sri-miriyala** [comment]
I checked that it is working fine too. Yeah, agreed. Let me update the priority to LOW.

**Comment by sri-miriyala** [comment]
Working as expected after the fix. I was able to successfully create a participant with currency "INR". Hence closed
