### ISSUE TITLE
Payeefsp position not getting updated correctly after the settlement processed

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#510]
Priority : HIGH
Env : ML AWS
Version: 3.7.1

Description: 
As part of testing the position reset logic after the settlement is processed, I noticed the position of payerfsp is getting updated correctly but the payeefsp position got updated incorrect. When settlement takes place, amount from payerfsp settlement account will be deducted (-) and credited(+) to payeefsp settlement account. So are the positions accordingly. payerfsp position should be reaching towards "0" and payeefsp position should also be reaching towards "0". But what I have noticed is payeefsp position getting double entered.

Steps to reproduce:
1. On a new settlement window, I sent a transfer from payerfsp to payeefsp with an amount "99" USD, which is COMMITTED.
2.  Now I made sure the positions of payerfsp is +99 and pyeefsp's is -99
3. I closed that window
4. Created a settlement on that window - I made sure the net settlement amount per participant on an account reflected, are correct.
5. Updated payerfsp account to "SETTLED" - Made sure settlement window state and settlement states are PENDING_SETTLEMENT
6. Updated payeefsp account to "SETTLED" - Made sure settlement window state and settlement states are "SETTLED"
7. Now I checked the positions, hoping both will be at "0"
8. payerfsp position is "0" as expected. But, payeefsp position is showing "-198" which is also should be "0".
Screenshot:
Request:
curl -X GET \
  http://test-central-ledger.mojaloop.live/admin/participants/payeefsp/positions \
  -H 'Cache-Control: no-cache' \
  -H 'Postman-Token: 411844ef-2ecc-412b-bc8e-a39a5d4e4675'
Response:
<img width="790" alt="screen shot 2018-10-11 at 12 55 53 pm" src="https://user-images.githubusercontent.com/38143240/46820676-cb815d80-cd54-11e8-9b54-d24228a7a960.png">

Expected result:
Payeefsp position after the settlement is processed, should be updated to "0"

**Comment by ggrg** [comment]
Hi @sri-miriyala, I was not able to reproduce the case. Here's the result I get for the payee dfsp on the same environment after completing all the steps: 
![position](https://user-images.githubusercontent.com/20338055/46857611-f7aee400-ce11-11e8-846d-6ac0e76e0c65.png)

**Comment by elnyry** [comment]
Thanks for looking at this quickly, Georgi. Maybe when Sri is available, we can have a quick chat and see if we can repro it together.

**Comment by sri-miriyala** [comment]
Hi Georgi...Even it is working fine for me now. Not sure if the new deployment from yesterday might have fixed this issue. I will keep testing more and try to close this bug later today.

**Comment by sri-miriyala** [comment]
It is working as expected. Hence closed.
