### ISSUE TITLE
POST limits lower than position of a participant - BUG

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#511]
Priority: HIGH
Env: ML AWS
Version: 3.7 and 3.7.2

Description:
When I try to update the NDC, using POST /limits, it is allowing a lower value than the current position value is. 

Request:
curl -X GET \
  http://test-central-ledger.mojaloop.live/admin/participants/payerfsp/positions \
  -H 'Cache-Control: no-cache' \
  -H 'Postman-Token: 9fb2847a-6f71-4691-96a8-a9c4b0aa3eb3'
position of payerfsp screenshot:
<img width="747" alt="screen shot 2018-10-12 at 1 10 19 am" src="https://user-images.githubusercontent.com/38143240/46849047-69a80e80-cdbb-11e8-9fda-9b2345283df6.png">

Set NDC:
<img width="746" alt="screen shot 2018-10-12 at 1 11 26 am" src="https://user-images.githubusercontent.com/38143240/46849067-8b08fa80-cdbb-11e8-9895-2a8036cfc4b1.png">

Expected Behavior:
The API should not allow to set NDC a lower value than the current position.

**Comment by elnyry** [comment]
Yeah this shouldn't happen.

Validation in step-12 in the sequence diagram [here](https://github.com/mojaloop/docs/blob/develop/CentralServices/seq_diagrams/participant/seq-manage-participant-limit-1.1.0.svg) should've failed for this , we've even discussed this internally, looks like its missing in the implementation however.

**Comment by RobReeve** [comment]
@elnyry please note that there is a case in settlement where the NDC has to be set lower than the position. This will be adjusted when the position is applied, however to prevent a transaction being allowed, the control (the limit) should be updated first.

**Comment by elnyry** [comment]
Closing this, until either requirements are clarified or if this is classified as a bug for sure. Currently there seems to be ambiguity whether or not this is even a bug in the first place.
