### ISSUE TITLE
Security Vulnerability Found in interop-ilp-conditions

### ISSUE THREAD

**Issue by kjw000** [mojaloop/project#515]
As a github developer I need to address any potential security issues with the Mojaloop code base.

- Potential Security issue found in repo: mojaloop/interop-ilp-conditions
- Component: com.fasterxml.jackson.core:jackson-databind  ver 2.6.7.1 
- Defined in pom.xml

Review: https://github.com/mojaloop/interop-ilp-conditions/network/alert/pom.xml/com.fasterxml.jackson.core:jackson-databind/open

**Comment by lewisdaly** [comment]
I saw that the https://github.com/mojaloop/interop-ilp-conditions project has been deprecated. Does this issue still need to be addressed?

**Comment by elnyry** [comment]
Thats correct @lewisdaly , we shouldn't be.. If it was relevant, it would've been taken care of, by now.. I'll close it soon.
