### ISSUE TITLE
Content-Type, Accept Header issue - Transfers

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#516]
Priority: High
Env : ML AWS

Description: 
The current transfers is accepting a Header, content type "application/json". But as per the API Spec, the Content type should be 
Content-Type=[application/vnd.interoperability.transfers+json;version=1.0]

Expected behavior:
Transfers request should take content type "application/vnd.interoperability.transfers+json;version=1.0" without errors.

Tasks:
- [x] Change validation of **Content-Type** header from application/json to "_application/vnd.interoperability.transfers+json;version=1.0_" as per the API Specification
- [x] Fix code to relay an incoming **Accept** header (as optional for the time-being as that applies to POST, GET requests and not PUT), with value "_application/vnd.interoperability.transfers+json;version=1_", as per the Spec
- [x] Update/Fix tests

**PR**
- [x] https://github.com/mojaloop/ml-api-adapter/pull/65

**Follow-up tasks**
- [x] Update scripts in 'postman' repo to use the updated headers

**Notes**:
This change is to conform to the Specification (API Definition), so it is nothing out of the ordinary. This would necessitate that the postman scripts need to be updated to use the updated values for these headers.

**Comment by sri-miriyala** [comment]
Tested and working as expected for /parties /quotes and /transfer. 
Hence closed.

**Comment by sri-miriyala** [comment]
Had to reopen as the format of the response body is not as per API spec.
After the fix,
For the incorrect Header filed, I'm getting a response code 400-Bad request, and the response body is below.

{ "id": "BadRequestError", "message": "Invalid content-type header" }
Screenshot:
<img width="707" alt="screen shot 2018-10-20 at 9 24 40 pm" src="https://user-images.githubusercontent.com/38143240/47262215-54fd0200-d4b0-11e8-84b4-1971b534f6c0.png">
Response body is not as per API Spec. 
Expected Response body: It shoud mention error code:3101, and error Description: "Invalid Content-Type Header"
It should be like the below one:
{
"errorInformation": {
"errorCode": 0,
"errorDescription": "string",
"extensionList": {
"extension": [

{ "key": "string", "value": "string" }
]
}
}
}

**Comment by elnyry** [comment]
@sri-miriyala is this fixed now or still active?

**Comment by elnyry** [comment]
I think its been fixed for a while now.. Current message looks like this

```
{
    "errorInformation": {
        "errorCode": "3101",
        "errorDescription": "Malformed syntax - content-type",
        "extensionList": {
            "extension": [
                {
                    "key": "cause",
                    "value": "FSPIOPError: content-type\n    at createFSPIOPError (/opt/ml-api-adapter/node_modules/@mojaloop/central-services-error-handling/s"
                }
            ]
        }
    }
}
```
