### ISSUE TITLE
GET /transfers - Internal server error

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#519]
Priority: Medium
Env : ML AWS
Version: 3.8
API: GET /transfers
Description:
When I try to hit the GET /transfers end point to view the details of the previous transfer, I'm getting Internal server error. Below are the Request and response.
REQUEST:
curl -X GET \
http://test-ml-api-adapter.mojaloop.live/transfers/25a00155-c777-4629-a6b7-61cf0d16f499 \
-H 'Accept: application/vnd.interoperability.transfers+json;version=1' \
-H 'Cache-Control: no-cache' \
-H 'Content-Type: application/vnd.interoperability.transfers+json;version=1.0' \
-H 'Date: Fri, 19 Oct 2018 01:58:49 GMT' \
-H 'FSPIOP-Source: payerfsp' \
-H 'Postman-Token: cea4d27a-c0fc-49cf-b2f7-934bc28192ba'
RESPONSE:
{ "id": "InternalServerError", "message": "An internal server error occurred" }
Expected Response:
I should get a response depending on the state of the original transfer.

**Pull Requests**:
- [x] https://github.com/mojaloop/central-settlement/pull/48 (merged into mojaloop:bugfix/491InvalidResponseForGetSettlementBySettlementParticipantAccount) -- not relevant to the reported bug

**Comment by elnyry** [comment]
Deon worked on this; PR - https://github.com/mojaloop/central-ledger/pull/192

**Comment by ggrg** [comment]
Relates to [Story #452](https://github.com/mojaloop/project/issues/452)

**Comment by ggrg** [comment]
I was unable to reproduce the bug locally running the latest code for central-ledger and ml-api-adapter. During a session with @sri-miriyala we also tried to run previous commits - 5648361 and fa93b14 respectively, but we were unable to reproduce it as well. Still the reported bug was confirmed to remain on env: ML AWS. @elnyry, please deploy latest code and restart services.

**Comment by sri-miriyala** [comment]
With new release that has fix for GET/transfers/{ID}, this issue is resolved. When I query GET /transfers/{ID}, I got a 200-Ok response in postman and the current state of the transfer at payerfsp simulator logs. 
<img width="1409" alt="screen shot 2018-11-29 at 1 07 13 am" src="https://user-images.githubusercontent.com/38143240/49203048-c021da00-f374-11e8-9aa8-1b91043d5574.png">

<img width="1152" alt="screen shot 2018-11-29 at 1 06 56 am" src="https://user-images.githubusercontent.com/38143240/49203052-c57f2480-f374-11e8-8f72-f6b6445e7b6e.png">

Hence closing this issue.
