### ISSUE TITLE
Missing "Accept" header in GET /transfers - Incorrect Error code and Description

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#521]
Priority: Medium
Env : ML AWS
Version: 3.8
API: GET /transfers
Description:
When I hit the GET /transfers end point with missing mandatory "Accept" header,  to view the details of the previous transfer, I'm getting http response code 400 - bad request which is correct but incorrect error code and error msgs in the response body. Below are the Request and response.
REQUEST:
GET /transfers/f31515ef-2159-4c4c-acdb-b34e44f640fc HTTP/1.1
Host: test-ml-api-adapter.mojaloop.live
Content-Type: application/vnd.interoperability.transfers+json;version=1.0
Date: Mon, 22 Oct 2018 02:37:57 GMT
FSPIOP-Source: payerfsp
Cache-Control: no-cache
Postman-Token: 0123d322-07f7-4168-9d20-c1faf9081816
RESPONSE:
{
    "errorInformation": {
        "errorCode": 400,
        "errorDescription": "Bad Request",
        "extentionList": {
            "extention": [
                {
                    "key": "joiValidationError",
                    "value": "child \"accept\" fails because [accept with value \"*/*\" fails to match the required pattern: /application\\/vnd.interoperability[.]/]"
                }
            ]
        }
    }
}
Screenshot:
<img width="764" alt="screen shot 2018-10-21 at 10 49 21 pm" src="https://user-images.githubusercontent.com/38143240/47276234-a1654200-d583-11e8-924b-f54fe41e01d5.png">

Expected Response:
I should get a response with error code: 3102 
Error description : Missing mandatory "Accept" header. 

Bug raised by : @sri-miriyala

**Comment by elnyry** [comment]
Lets revisit this after the #519 issue is fixed

**Comment by elnyry** [comment]
Fixed now
```
```
