### ISSUE TITLE
ML-API-Adapter Notification Handler Failures in 3.8.2 version

### ISSUE THREAD

**Issue by ksatya77** [mojaloop/project#524]
**Release**: 3.8.2
**Environment**: New Deployment
**Description**: Deployed 3.8.2 release in a new environment. When trying to process transfers, seeing the below error in ML-Adapter-Notification Handler.
**Impact**: End-End Transfers not working
**Error Stack Trace:**      
 line: null,
       method: 'parse',
       native: false },
     { column: 28,
       file: '/opt/ml-api-adapter/src/models/participant/participantEndpoint.js',
       function: 'Request.request [as _callback]',
       line: 64,
       method: 'request [as _callback]',
       native: false },
     { column: 22,
       file: '/opt/ml-api-adapter/node_modules/request/request.js',
       function: 'Request.self.callback',
       line: 185,
       method: 'callback',
       native: false },
     { column: 13,
       file: 'events.js',
       function: 'emitTwo',
       line: 126,
       method: null,
       native: false },
     { column: 7,
       file: 'events.js',
       function: 'Request.emit',
       line: 214,
       method: 'emit',
       native: false },
     { column: 10,
       file: '/opt/ml-api-adapter/node_modules/request/request.js',
       function: null,
       line: 1161,
       method: null,
       native: false },
     { column: 13,

Below is the output of participantEndpoint:
mysql> select * from participantEndpoint;
+-----------------------+---------------+----------------+---------------------------------------------------------------------------------------------+----------+---------------------+-----------+
| participantEndpointId | participantId | endpointTypeId | value                                                                                       | isActive | createdDate         | createdBy |
+-----------------------+---------------+----------------+---------------------------------------------------------------------------------------------+----------+---------------------+-----------+
|                     1 |             1 |              3 | http://pi41-simulators.casa-dev.svc.cluster.local/payerfsp/transfers                        |        1 | 2018-10-26 17:57:20 | unknown   |
|                     2 |             2 |              3 | http://pi41-simulators.casa-dev.svc.cluster.local/payeefsp/transfers                        |        1 | 2018-10-26 17:59:13 | unknown   |
|                     3 |             1 |              4 | https://k8s-casa-azure-uat0-simulators.casahub.live/payerfsp/transfers/{{transferId}}       |        1 | 2018-10-28 22:30:12 | unknown   |
|                     4 |             1 |              5 | https://k8s-casa-azure-uat0-simulators.casahub.live/payerfsp/transfers/{{transferId}}/error |        1 | 2018-10-28 22:31:44 | unknown   |
|                     5 |             2 |              4 | https://k8s-casa-azure-uat0-simulators.casahub.live/payeefsp/transfers/{{transferId}}       |        1 | 2018-10-28 22:33:13 | unknown   |
|                     6 |             2 |              5 | https://k8s-casa-azure-uat0-simulators.casahub.live/payeefsp/transfers/{{transferId}}/error |        1 | 2018-10-28 22:33:36 | unknown   |
+-----------------------+---------------+----------------+---------------------------------------------------------------------------------------------+----------+---------------------+-----------+

**Comment by elnyry** [comment]
Thanks Murthy for logging this.

As per our discussions, please close this if this is now resolved. Will note the change we wanted to make in parameterizing the source URL.
