### ISSUE TITLE
FundsIn is not updating the Hub reconciliation balance appropriately

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#541]
**Summary**:
When pre-funding DFSP's settlements accounts using FundsIn feature, the HUB reconciliation account did not get updated correctly for the first time after creating the accounts. This happened with currency "USD".

**Severity**: High

**Priority**: High (if this can be reproduced)

**Expected Behavior**:
1. When I put funds in payerfsp using FundsIn
2. Hub reconciliation account should be showing that amount as it's balance.
For example, if I put $500 in DFSP's settlement account using FundsIn, HUB reconciliation account should show up $500 in that account.
3. When I put $500 in payeefsp using FundsIn
4. Hub reconciliation account should show $1000 in it's account showing the total amount as a result of above two DFSP's deposits

**Steps to Reproduce**:
- covered above ^^ in 'expected behavior' section

**Issues/Tasks**:
- [ ] Reproduce issue and then fill in below tasks based on the outcome

**Specifications**
  - **Component**: central services
  - **Version**:
    - central-ledger version v4.1.1
    - central-settlement v4.1.0
    - ml-api-adapter v4.1.1
    - helm 3.8.7
  - **Platform**: ML switch on AWS - 'dev' envt
  - **Subsystem**: admin API central-ledger
  - **Type of testing**: manual/acceptance testing
  - **Bug found/raised by**: Sri @sri-miriyala 

**Notes**:
Actual Behavior:
1. I deposited 2*$500 in Payerfsp
2. I deposited 2*$500 in Payeefsp
3. I deposited 1*$500 in testfsp1
4. I deposited 1*$500 in testfsp2

As a result of all FundsIn, HUB reconciliation shoud show up $3000 in its balance, but showed only $2000.

- Comments: I tried to replicate it but could not find it again but the HUB reconciliation balance did not get updated during the settlements process.
- Screen shot from DB after completing 1 and 2 steps is attached as well
<img width="510" alt="screen shot 2018-12-06 at 12 00 08 am" src="https://user-images.githubusercontent.com/10507686/49578872-c1549780-f970-11e8-85c3-b2c0e2beff12.png">
<img width="927" alt="screen shot 2018-12-06 at 12 03 56 am" src="https://user-images.githubusercontent.com/10507686/49578873-c1ed2e00-f970-11e8-8b7e-7b198a910e23.png">

- Severity when opened: High
- Priority when opened:  High

**PRs**:
- [ ]

**Comment by elnyry** [comment]
Thanks Georgi, moving this to review and assigned to validate and close..

**Comment by sri-miriyala** [comment]
I will validate it with new release as I noticed this, only one time when I did first time FundsIn with new release.

**Comment by elnyry** [comment]
Closing this based on an offline communication with Sri
