### ISSUE TITLE
pods are on init 0/1

### ISSUE THREAD

**Issue by GeekGuste** [mojaloop/project#542]
Hi everyone
I installed the version 4.0.1 of the mojaloop chart (with helm). But the status of 8 pods are on init 0/1. With the previous version (3.8.7) 7 pods were on init 0/1. Would this be due to the version of the mojaloop chart installed? If so, can you send me the stable version? Also there are 6 pods (handlers) that are always on init 0/1 whatever the version installed. The containers of these pods had status pending. And in the logs of the init-container of one of these pods I have the following repetitive error:

[2018-12-07 14: 50: 58,414] WARN [Client NetworkClientId = admin-1] Connection to node -1 could not be established. Broker may not be available. (Org.apache.kafka.clients.NetworkClient)
Exception in thread "main" java.lang.RuntimeException: Request METADATA failed on list (pi3-kafka: 9092 (id: -1 rack: null))
       at kafka.admin.AdminClient.kafka $ admin $ AdminClient $$ sendAnyNode (AdminClient.scala: 105)
       at kafka.admin.AdminClient.findAllBrokers (AdminClient.scala: 163)
       at kafka.admin.AdminClient.awaitBrokers (AdminClient.scala: 154)
       at kafka.admin.BrokerApiVersionsCommand $ .execute (BrokerApiVersionsCommand.scala: 42)
       at kafka.admin.BrokerApiVersionsCommand $ .main (BrokerApiVersionsCommand.scala: 36)
       at kafka.admin.BrokerApiVersionsCommand.main (BrokerApiVersionsCommand.scala)
waiting for Kafka

When I tired to get logs of the container centralledger-handler-admin-transfer, I get the following error:

Error from server (BadRequest): container "centralledger-handler-admin-transfer" in pod "pi3-centralledger-handler-admin-transfer-6787b6dc8d-x68q9" is waiting to start: PodInitializing

And the status of the pod pi3-kafka-0 is still on CrashLoopBackOff.

I am using a vps on ubuntu 16.04 with RAM 12GB, 2vCores, 2.4GHz, Rom 50GB at OVH for the deployment.

**Comment by HenkKodde** [comment]
@jeffplesko is assisting via slack general channel. Requested the logs and/or a kubectl describe pod output on the kafka pod to get a better idea of why the CrashLoopBackOff is happening? 
Following logs were provided:
kafka-pod;
Name:               pi3-kafka-0
Namespace:          demo
Priority:           0
PriorityClassName:  <none>
Node:               vps205307/144.217.243.137
Start Time:         Fri, 07 Dec 2018 06:09:42 -0500
Labels:             app=kafka
                    controller-revision-hash=pi3-kafka-5dff5d5d8
                    release=pi3
                    statefulset.kubernetes.io/pod-name=pi3-kafka-0
Annotations:        <none>
Status:             Running
IP:                 192.168.62.56
Controlled By:      StatefulSet/pi3-kafka
Containers:
  kafka-broker:
    Container ID:  docker://33552c20f3ce2a7d5b6c0b2c4f847b2b23843d622b8ba47baa0939b8ee9e4f0c
    Image:         confluentinc/cp-kafka:4.0.1-1
    Image ID:      docker-pullable://confluentinc/cp-kafka@sha256:e4064b902da1be8c6696cc9f76dd7adeb36fbc86d945d86c927bcb06fc0ddaca
    Port:          9092/TCP
    Host Port:     0/TCP
    Command:
      sh
      -exc
      export KAFKA_BROKER_ID=${HOSTNAME##*-} && \
      export KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${POD_IP}:9092 && \
      exec /etc/confluent/docker/run
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 11 Dec 2018 03:17:15 -0500
      Finished:     Tue, 11 Dec 2018 03:18:15 -0500
    Ready:          False
    Restart Count:  1527
    Liveness:       exec [sh -ec /usr/bin/jps | /bin/grep -q SupportedKafka] delay=30s timeout=5s period=10s #success=1 #failure=3
    Readiness:      tcp-socket :kafka delay=30s timeout=5s period=10s #success=1 #failure=3
    Environment:
      POD_IP:                                   (v1:status.podIP)
      KAFKA_HEAP_OPTS:
      KAFKA_ZOOKEEPER_CONNECT:                 pi3-zookeeper:2181
      KAFKA_LOG_DIRS:                          /opt/kafka/data/logs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:  1
      KAFKA_JMX_PORT:                          5555
    Mounts:
      /opt/kafka/data from datadir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from pi3-token-9cgkp (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  datadir:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
  pi3-token-9cgkp:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  pi3-token-9cgkp
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                      From                Message
  ----     ------     ----                     ----                -------
  Warning  Unhealthy  45m (x4245 over 3d21h)   kubelet, vps205307  Liveness probe failed:
  Normal   Pulled     40m (x1517 over 3d21h)   kubelet, vps205307  Container image "confluentinc/cp-kafka:4.0.1-1" already present on machine
  Warning  Unhealthy  25m (x5025 over 3d21h)   kubelet, vps205307  Readiness probe failed: dial tcp 192.168.62.56:9092: connect: connection refused
  Normal   Created    10m (x1526 over 3d21h)   kubelet, vps205307  Created container
  Warning  BackOff    39s (x19115 over 3d21h)  kubelet, vps205307  Back-off restarting failed container

KAFKA - Broker
+ export KAFKA_BROKER_ID=0
+ export KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.62.56:9092
+ exec /etc/confluent/docker/run
# Set environment values if they exist as arguments
if [ $# -ne 0 ]; then
  echo "===> Overriding env params with args ..."
  for var in "$@"
  do
    export "$var"
  done
fi
+ '[' 0 -ne 0 ']'
echo "===> ENV Variables ..."
+ echo '===> ENV Variables ...'
===> ENV Variables ...
env | sort
+ env
+ sort
ALLOW_UNSIGNED=false
COMPONENT=kafka
CONFLUENT_DEB_VERSION=1
CONFLUENT_MAJOR_VERSION=4
CONFLUENT_MINOR_VERSION=0
CONFLUENT_MVN_LABEL=
CONFLUENT_PATCH_VERSION=1
CONFLUENT_PLATFORM_LABEL=
CONFLUENT_VERSION=4.0.1
CUB_CLASSPATH=/etc/confluent/docker/docker-utils.jar
HOME=/root
HOSTNAME=pi3-kafka-0
KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.62.56:9092
KAFKA_BROKER_ID=0
KAFKA_HEAP_OPTS=
KAFKA_JMX_PORT=5555
KAFKA_LOG_DIRS=/opt/kafka/data/logs
KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
KAFKA_VERSION=1.0.0
KAFKA_ZOOKEEPER_CONNECT=pi3-zookeeper:2181
KUBERNETES_PORT=tcp://10.96.0.1:443
KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_SERVICE_HOST=10.96.0.1
KUBERNETES_SERVICE_PORT=443
KUBERNETES_SERVICE_PORT_HTTPS=443
LANG=C.UTF-8
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PI3_CENTRALDIRECTORY_PORT=tcp://10.108.113.167:3000
PI3_CENTRALDIRECTORY_PORT_3000_TCP=tcp://10.108.113.167:3000
PI3_CENTRALDIRECTORY_PORT_3000_TCP_ADDR=10.108.113.167
PI3_CENTRALDIRECTORY_PORT_3000_TCP_PORT=3000
PI3_CENTRALDIRECTORY_PORT_3000_TCP_PROTO=tcp
PI3_CENTRALDIRECTORY_POSTGRESQL_PORT=tcp://10.106.123.199:5432
PI3_CENTRALDIRECTORY_POSTGRESQL_PORT_5432_TCP=tcp://10.106.123.199:5432
PI3_CENTRALDIRECTORY_POSTGRESQL_PORT_5432_TCP_ADDR=10.106.123.199
PI3_CENTRALDIRECTORY_POSTGRESQL_PORT_5432_TCP_PORT=5432
PI3_CENTRALDIRECTORY_POSTGRESQL_PORT_5432_TCP_PROTO=tcp
PI3_CENTRALDIRECTORY_POSTGRESQL_SERVICE_HOST=10.106.123.199
PI3_CENTRALDIRECTORY_POSTGRESQL_SERVICE_PORT=5432
PI3_CENTRALDIRECTORY_POSTGRESQL_SERVICE_PORT_POSTGRESQL=5432
PI3_CENTRALDIRECTORY_SERVICE_HOST=10.108.113.167
PI3_CENTRALDIRECTORY_SERVICE_PORT=3000
PI3_CENTRALDIRECTORY_SERVICE_PORT_HTTP_API=3000
PI3_CENTRALENDUSERREGISTRY_PORT=tcp://10.107.240.85:3001
PI3_CENTRALENDUSERREGISTRY_PORT_3001_TCP=tcp://10.107.240.85:3001
PI3_CENTRALENDUSERREGISTRY_PORT_3001_TCP_ADDR=10.107.240.85
PI3_CENTRALENDUSERREGISTRY_PORT_3001_TCP_PORT=3001
PI3_CENTRALENDUSERREGISTRY_PORT_3001_TCP_PROTO=tcp
PI3_CENTRALENDUSERREGISTRY_POSTGRESQL_PORT=tcp://10.105.254.150:5432
PI3_CENTRALENDUSERREGISTRY_POSTGRESQL_PORT_5432_TCP=tcp://10.105.254.150:5432
PI3_CENTRALENDUSERREGISTRY_POSTGRESQL_PORT_5432_TCP_ADDR=10.105.254.150
PI3_CENTRALENDUSERREGISTRY_POSTGRESQL_PORT_5432_TCP_PORT=5432
PI3_CENTRALENDUSERREGISTRY_POSTGRESQL_PORT_5432_TCP_PROTO=tcp
PI3_CENTRALENDUSERREGISTRY_POSTGRESQL_SERVICE_HOST=10.105.254.150
PI3_CENTRALENDUSERREGISTRY_POSTGRESQL_SERVICE_PORT=5432
PI3_CENTRALENDUSERREGISTRY_POSTGRESQL_SERVICE_PORT_POSTGRESQL=5432
PI3_CENTRALENDUSERREGISTRY_SERVICE_HOST=10.107.240.85
PI3_CENTRALENDUSERREGISTRY_SERVICE_PORT=3001
PI3_CENTRALENDUSERREGISTRY_SERVICE_PORT_HTTP_API=3001
PI3_CENTRALEVENTPROCESSOR_PORT=tcp://10.108.146.51:3080
PI3_CENTRALEVENTPROCESSOR_PORT_3080_TCP=tcp://10.108.146.51:3080
PI3_CENTRALEVENTPROCESSOR_PORT_3080_TCP_ADDR=10.108.146.51
PI3_CENTRALEVENTPROCESSOR_PORT_3080_TCP_PORT=3080
PI3_CENTRALEVENTPROCESSOR_PORT_3080_TCP_PROTO=tcp
PI3_CENTRALEVENTPROCESSOR_SERVICE_HOST=10.108.146.51
PI3_CENTRALEVENTPROCESSOR_SERVICE_PORT=3080
PI3_CENTRALEVENTPROCESSOR_SERVICE_PORT_HTTP=3080
PI3_CENTRALKMS_PORT=tcp://10.101.213.233:8080
PI3_CENTRALKMS_PORT_8080_TCP=tcp://10.101.213.233:8080
PI3_CENTRALKMS_PORT_8080_TCP_ADDR=10.101.213.233
PI3_CENTRALKMS_PORT_8080_TCP_PORT=8080
PI3_CENTRALKMS_PORT_8080_TCP_PROTO=tcp
PI3_CENTRALKMS_POSTGRESQL_PORT=tcp://10.102.69.146:5432
PI3_CENTRALKMS_POSTGRESQL_PORT_5432_TCP=tcp://10.102.69.146:5432
PI3_CENTRALKMS_POSTGRESQL_PORT_5432_TCP_ADDR=10.102.69.146
PI3_CENTRALKMS_POSTGRESQL_PORT_5432_TCP_PORT=5432
PI3_CENTRALKMS_POSTGRESQL_PORT_5432_TCP_PROTO=tcp
PI3_CENTRALKMS_POSTGRESQL_SERVICE_HOST=10.102.69.146
PI3_CENTRALKMS_POSTGRESQL_SERVICE_PORT=5432
PI3_CENTRALKMS_POSTGRESQL_SERVICE_PORT_POSTGRESQL=5432
PI3_CENTRALKMS_SERVICE_HOST=10.101.213.233
PI3_CENTRALKMS_SERVICE_PORT=8080
PI3_CENTRALLEDGER_HANDLER_ADMIN_TRANSFER_PORT=tcp://10.111.137.76:3000
PI3_CENTRALLEDGER_HANDLER_ADMIN_TRANSFER_PORT_3000_TCP=tcp://10.111.137.76:3000
PI3_CENTRALLEDGER_HANDLER_ADMIN_TRANSFER_PORT_3000_TCP_ADDR=10.111.137.76
PI3_CENTRALLEDGER_HANDLER_ADMIN_TRANSFER_PORT_3000_TCP_PORT=3000
PI3_CENTRALLEDGER_HANDLER_ADMIN_TRANSFER_PORT_3000_TCP_PROTO=tcp
PI3_CENTRALLEDGER_HANDLER_ADMIN_TRANSFER_SERVICE_HOST=10.111.137.76
PI3_CENTRALLEDGER_HANDLER_ADMIN_TRANSFER_SERVICE_PORT=3000
PI3_CENTRALLEDGER_HANDLER_ADMIN_TRANSFER_SERVICE_PORT_HTTP_API=3000
PI3_CENTRALLEDGER_HANDLER_TIMEOUT_PORT=tcp://10.102.173.94:3000
PI3_CENTRALLEDGER_HANDLER_TIMEOUT_PORT_3000_TCP=tcp://10.102.173.94:3000
PI3_CENTRALLEDGER_HANDLER_TIMEOUT_PORT_3000_TCP_ADDR=10.102.173.94
PI3_CENTRALLEDGER_HANDLER_TIMEOUT_PORT_3000_TCP_PORT=3000
PI3_CENTRALLEDGER_HANDLER_TIMEOUT_PORT_3000_TCP_PROTO=tcp
PI3_CENTRALLEDGER_HANDLER_TIMEOUT_SERVICE_HOST=10.102.173.94
PI3_CENTRALLEDGER_HANDLER_TIMEOUT_SERVICE_PORT=3000
PI3_CENTRALLEDGER_HANDLER_TIMEOUT_SERVICE_PORT_HTTP_API=3000
PI3_CENTRALLEDGER_HANDLER_TRANSFER_FULFIL_PORT=tcp://10.110.2.151:3000
PI3_CENTRALLEDGER_HANDLER_TRANSFER_FULFIL_PORT_3000_TCP=tcp://10.110.2.151:3000
PI3_CENTRALLEDGER_HANDLER_TRANSFER_FULFIL_PORT_3000_TCP_ADDR=10.110.2.151
PI3_CENTRALLEDGER_HANDLER_TRANSFER_FULFIL_PORT_3000_TCP_PORT=3000
PI3_CENTRALLEDGER_HANDLER_TRANSFER_FULFIL_PORT_3000_TCP_PROTO=tcp
PI3_CENTRALLEDGER_HANDLER_TRANSFER_FULFIL_SERVICE_HOST=10.110.2.151
PI3_CENTRALLEDGER_HANDLER_TRANSFER_FULFIL_SERVICE_PORT=3000
PI3_CENTRALLEDGER_HANDLER_TRANSFER_FULFIL_SERVICE_PORT_HTTP_API=3000
PI3_CENTRALLEDGER_HANDLER_TRANSFER_GET_PORT=tcp://10.108.0.192:3000
PI3_CENTRALLEDGER_HANDLER_TRANSFER_GET_PORT_3000_TCP=tcp://10.108.0.192:3000
PI3_CENTRALLEDGER_HANDLER_TRANSFER_GET_PORT_3000_TCP_ADDR=10.108.0.192
PI3_CENTRALLEDGER_HANDLER_TRANSFER_GET_PORT_3000_TCP_PORT=3000
PI3_CENTRALLEDGER_HANDLER_TRANSFER_GET_PORT_3000_TCP_PROTO=tcp
PI3_CENTRALLEDGER_HANDLER_TRANSFER_GET_SERVICE_HOST=10.108.0.192
PI3_CENTRALLEDGER_HANDLER_TRANSFER_GET_SERVICE_PORT=3000
PI3_CENTRALLEDGER_HANDLER_TRANSFER_GET_SERVICE_PORT_HTTP_API=3000
PI3_CENTRALLEDGER_HANDLER_TRANSFER_POSITION_PORT=tcp://10.101.26.15:3000
PI3_CENTRALLEDGER_HANDLER_TRANSFER_POSITION_PORT_3000_TCP=tcp://10.101.26.15:3000
PI3_CENTRALLEDGER_HANDLER_TRANSFER_POSITION_PORT_3000_TCP_ADDR=10.101.26.15
PI3_CENTRALLEDGER_HANDLER_TRANSFER_POSITION_PORT_3000_TCP_PORT=3000
PI3_CENTRALLEDGER_HANDLER_TRANSFER_POSITION_PORT_3000_TCP_PROTO=tcp
PI3_CENTRALLEDGER_HANDLER_TRANSFER_POSITION_SERVICE_HOST=10.101.26.15
PI3_CENTRALLEDGER_HANDLER_TRANSFER_POSITION_SERVICE_PORT=3000
PI3_CENTRALLEDGER_HANDLER_TRANSFER_POSITION_SERVICE_PORT_HTTP_API=3000
PI3_CENTRALLEDGER_HANDLER_TRANSFER_PREPARE_PORT=tcp://10.97.250.214:3000
PI3_CENTRALLEDGER_HANDLER_TRANSFER_PREPARE_PORT_3000_TCP=tcp://10.97.250.214:3000
PI3_CENTRALLEDGER_HANDLER_TRANSFER_PREPARE_PORT_3000_TCP_ADDR=10.97.250.214
PI3_CENTRALLEDGER_HANDLER_TRANSFER_PREPARE_PORT_3000_TCP_PORT=3000
PI3_CENTRALLEDGER_HANDLER_TRANSFER_PREPARE_PORT_3000_TCP_PROTO=tcp
PI3_CENTRALLEDGER_HANDLER_TRANSFER_PREPARE_SERVICE_HOST=10.97.250.214
PI3_CENTRALLEDGER_HANDLER_TRANSFER_PREPARE_SERVICE_PORT=3000
PI3_CENTRALLEDGER_HANDLER_TRANSFER_PREPARE_SERVICE_PORT_HTTP_API=3000
PI3_CENTRALLEDGER_MYSQL_PORT=tcp://10.110.133.76:3306
PI3_CENTRALLEDGER_MYSQL_PORT_3306_TCP=tcp://10.110.133.76:3306
PI3_CENTRALLEDGER_MYSQL_PORT_3306_TCP_ADDR=10.110.133.76
PI3_CENTRALLEDGER_MYSQL_PORT_3306_TCP_PORT=3306
PI3_CENTRALLEDGER_MYSQL_PORT_3306_TCP_PROTO=tcp
PI3_CENTRALLEDGER_MYSQL_SERVICE_HOST=10.110.133.76
PI3_CENTRALLEDGER_MYSQL_SERVICE_PORT=3306
PI3_CENTRALLEDGER_MYSQL_SERVICE_PORT_MYSQL=3306
PI3_CENTRALLEDGER_SERVICE_PORT=tcp://10.97.59.126:3000
PI3_CENTRALLEDGER_SERVICE_PORT_3000_TCP=tcp://10.97.59.126:3000
PI3_CENTRALLEDGER_SERVICE_PORT_3000_TCP_ADDR=10.97.59.126
PI3_CENTRALLEDGER_SERVICE_PORT_3000_TCP_PORT=3000
PI3_CENTRALLEDGER_SERVICE_PORT_3000_TCP_PROTO=tcp
PI3_CENTRALLEDGER_SERVICE_PORT_3001_TCP=tcp://10.97.59.126:3001
PI3_CENTRALLEDGER_SERVICE_PORT_3001_TCP_ADDR=10.97.59.126
PI3_CENTRALLEDGER_SERVICE_PORT_3001_TCP_PORT=3001
PI3_CENTRALLEDGER_SERVICE_PORT_3001_TCP_PROTO=tcp
PI3_CENTRALLEDGER_SERVICE_SERVICE_HOST=10.97.59.126
PI3_CENTRALLEDGER_SERVICE_SERVICE_PORT=3000
PI3_CENTRALLEDGER_SERVICE_SERVICE_PORT_HTTP_API=3000
PI3_CENTRALLEDGER_SERVICE_SERVICE_PORT_HTTP_API_ADMIN=3001
PI3_CENTRALSETTLEMENT_PORT=tcp://10.100.248.188:3007
PI3_CENTRALSETTLEMENT_PORT_3007_TCP=tcp://10.100.248.188:3007
PI3_CENTRALSETTLEMENT_PORT_3007_TCP_ADDR=10.100.248.188
PI3_CENTRALSETTLEMENT_PORT_3007_TCP_PORT=3007
PI3_CENTRALSETTLEMENT_PORT_3007_TCP_PROTO=tcp
PI3_CENTRALSETTLEMENT_SERVICE_HOST=10.100.248.188
PI3_CENTRALSETTLEMENT_SERVICE_PORT=3007
PI3_CENTRALSETTLEMENT_SERVICE_PORT_HTTP_API=3007
PI3_EMAILNOTIFIER_PORT=tcp://10.108.166.63:3081
PI3_EMAILNOTIFIER_PORT_3081_TCP=tcp://10.108.166.63:3081
PI3_EMAILNOTIFIER_PORT_3081_TCP_ADDR=10.108.166.63
PI3_EMAILNOTIFIER_PORT_3081_TCP_PORT=3081
PI3_EMAILNOTIFIER_PORT_3081_TCP_PROTO=tcp
PI3_EMAILNOTIFIER_SERVICE_HOST=10.108.166.63
PI3_EMAILNOTIFIER_SERVICE_PORT=3081
PI3_EMAILNOTIFIER_SERVICE_PORT_HTTP=3081
PI3_FORENSICLOGGINGSIDECAR_LEDGER_PORT=tcp://10.111.147.172:5678
PI3_FORENSICLOGGINGSIDECAR_LEDGER_PORT_5678_TCP=tcp://10.111.147.172:5678
PI3_FORENSICLOGGINGSIDECAR_LEDGER_PORT_5678_TCP_ADDR=10.111.147.172
PI3_FORENSICLOGGINGSIDECAR_LEDGER_PORT_5678_TCP_PORT=5678
PI3_FORENSICLOGGINGSIDECAR_LEDGER_PORT_5678_TCP_PROTO=tcp
PI3_FORENSICLOGGINGSIDECAR_LEDGER_POSTGRESQL_PORT=tcp://10.104.240.27:5432
PI3_FORENSICLOGGINGSIDECAR_LEDGER_POSTGRESQL_PORT_5432_TCP=tcp://10.104.240.27:5432
PI3_FORENSICLOGGINGSIDECAR_LEDGER_POSTGRESQL_PORT_5432_TCP_ADDR=10.104.240.27
PI3_FORENSICLOGGINGSIDECAR_LEDGER_POSTGRESQL_PORT_5432_TCP_PORT=5432
PI3_FORENSICLOGGINGSIDECAR_LEDGER_POSTGRESQL_PORT_5432_TCP_PROTO=tcp
PI3_FORENSICLOGGINGSIDECAR_LEDGER_POSTGRESQL_SERVICE_HOST=10.104.240.27
PI3_FORENSICLOGGINGSIDECAR_LEDGER_POSTGRESQL_SERVICE_PORT=5432
PI3_FORENSICLOGGINGSIDECAR_LEDGER_POSTGRESQL_SERVICE_PORT_POSTGRESQL=5432
PI3_FORENSICLOGGINGSIDECAR_LEDGER_SERVICE_HOST=10.111.147.172
PI3_FORENSICLOGGINGSIDECAR_LEDGER_SERVICE_PORT=5678
PI3_INTEROP_SWITCH_PORT=tcp://10.107.96.237:8088
PI3_INTEROP_SWITCH_PORT_8088_TCP=tcp://10.107.96.237:8088
PI3_INTEROP_SWITCH_PORT_8088_TCP_ADDR=10.107.96.237
PI3_INTEROP_SWITCH_PORT_8088_TCP_PORT=8088
PI3_INTEROP_SWITCH_PORT_8088_TCP_PROTO=tcp
PI3_INTEROP_SWITCH_POSTGRESQL_PORT=tcp://10.110.135.55:5432
PI3_INTEROP_SWITCH_POSTGRESQL_PORT_5432_TCP=tcp://10.110.135.55:5432
PI3_INTEROP_SWITCH_POSTGRESQL_PORT_5432_TCP_ADDR=10.110.135.55
PI3_INTEROP_SWITCH_POSTGRESQL_PORT_5432_TCP_PORT=5432
PI3_INTEROP_SWITCH_POSTGRESQL_PORT_5432_TCP_PROTO=tcp
PI3_INTEROP_SWITCH_POSTGRESQL_SERVICE_HOST=10.110.135.55
PI3_INTEROP_SWITCH_POSTGRESQL_SERVICE_PORT=5432
PI3_INTEROP_SWITCH_POSTGRESQL_SERVICE_PORT_POSTGRESQL=5432
PI3_INTEROP_SWITCH_SERVICE_HOST=10.107.96.237
PI3_INTEROP_SWITCH_SERVICE_PORT=8088
PI3_INTEROP_SWITCH_SERVICE_PORT_INTEROP_SWITCH=8088
PI3_KAFKA_PORT=tcp://10.109.164.215:9092
PI3_KAFKA_PORT_9092_TCP=tcp://10.109.164.215:9092
PI3_KAFKA_PORT_9092_TCP_ADDR=10.109.164.215
PI3_KAFKA_PORT_9092_TCP_PORT=9092
PI3_KAFKA_PORT_9092_TCP_PROTO=tcp
PI3_KAFKA_SERVICE_HOST=10.109.164.215
PI3_KAFKA_SERVICE_PORT=9092
PI3_KAFKA_SERVICE_PORT_BROKER=9092
PI3_ML_API_ADAPTER_HANDLER_NOTIFICATION_PORT=tcp://10.103.87.140:8088
PI3_ML_API_ADAPTER_HANDLER_NOTIFICATION_PORT_8088_TCP=tcp://10.103.87.140:8088
PI3_ML_API_ADAPTER_HANDLER_NOTIFICATION_PORT_8088_TCP_ADDR=10.103.87.140
PI3_ML_API_ADAPTER_HANDLER_NOTIFICATION_PORT_8088_TCP_PORT=8088
PI3_ML_API_ADAPTER_HANDLER_NOTIFICATION_PORT_8088_TCP_PROTO=tcp
PI3_ML_API_ADAPTER_HANDLER_NOTIFICATION_SERVICE_HOST=10.103.87.140
PI3_ML_API_ADAPTER_HANDLER_NOTIFICATION_SERVICE_PORT=8088
PI3_ML_API_ADAPTER_HANDLER_NOTIFICATION_SERVICE_PORT_ML_API_ADAPTER=8088
PI3_ML_API_ADAPTER_SERVICE_PORT=tcp://10.109.45.50:8088
PI3_ML_API_ADAPTER_SERVICE_PORT_8088_TCP=tcp://10.109.45.50:8088
PI3_ML_API_ADAPTER_SERVICE_PORT_8088_TCP_ADDR=10.109.45.50
PI3_ML_API_ADAPTER_SERVICE_PORT_8088_TCP_PORT=8088
PI3_ML_API_ADAPTER_SERVICE_PORT_8088_TCP_PROTO=tcp
PI3_ML_API_ADAPTER_SERVICE_SERVICE_HOST=10.109.45.50
PI3_ML_API_ADAPTER_SERVICE_SERVICE_PORT=8088
PI3_ML_API_ADAPTER_SERVICE_SERVICE_PORT_ML_API_ADAPTER=8088
PI3_MOCKPATHFINDER_PORT=tcp://10.101.49.212:8080
PI3_MOCKPATHFINDER_PORT_15353_TCP=tcp:/...

**Comment by HenkKodde** [comment]
Looks like the main issue is with ZOOKEEPER resulting in a timeout and causing the service to shut down.

echo "===> Check if Zookeeper is healthy ..."
+ echo '===> Check if Zookeeper is healthy ...'
===> Check if Zookeeper is healthy ...
cub zk-ready "$KAFKA_ZOOKEEPER_CONNECT" "${KAFKA_CUB_ZK_TIMEOUT:-40}"
+ cub zk-ready pi3-zookeeper:2181 40
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:zookeeper.version=3.4.10-39d3a4f269333c922ed3db283be479f9deacaa0f, built on 03/23/2017 10:13 GMT
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:host.name=pi3-kafka-0.pi3-kafka-headless.demo.svc.cluster.local
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.version=1.8.0_102
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.vendor=Azul Systems, Inc.
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.home=/usr/lib/jvm/zulu-8-amd64/jre
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.class.path=/etc/confluent/docker/docker-utils.jar
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.io.tmpdir=/tmp
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:java.compiler=<NA>
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.name=Linux
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.arch=amd64
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:os.version=4.4.0-139-generic
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:user.name=root
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:user.home=/root
[main] INFO org.apache.zookeeper.ZooKeeper - Client environment:user.dir=/
[main] INFO org.apache.zookeeper.ZooKeeper - Initiating client connection, connectString=pi3-zookeeper:2181 sessionTimeout=40000 watcher=io.confluent.admin.utils.ZookeeperConnectionWatcher@1ddc4ec2
[main-SendThread(pi3-zookeeper.demo.svc.cluster.local:2181)] INFO org.apache.zookeeper.ClientCnxn - Opening socket connection to server pi3-zookeeper.demo.svc.cluster.local/10.110.88.170:2181. Will not attempt to authenticate using SASL (unknown error)
[main] ERROR io.confluent.admin.utils.ClusterStatus - Timed out waiting for connection to Zookeeper server [pi3-zookeeper:2181].
[main-SendThread(pi3-zookeeper.demo.svc.cluster.local:2181)] WARN org.apache.zookeeper.ClientCnxn - Client session timed out, have not heard from server in 40032ms for sessionid 0x0
[main] INFO org.apache.zookeeper.ZooKeeper - Session: 0x0 closed
[main-EventThread] INFO org.apache.zookeeper.ClientCnxn - EventThread shut down for session: 0x0.

**Comment by GeekGuste** [comment]
Thanks, @HenkKodde 
![pods list](https://user-images.githubusercontent.com/36772043/49795719-a13b2480-fd32-11e8-867e-db477e850712.PNG)

 I also noticed that zoo-keper was still on pending.
This is the logs of zookeeper below
[pie-zookeeper.txt](https://github.com/mojaloop/project/files/2667258/pie-zookeeper.txt)

The logs of the zookeeper-server container is empty.

**Comment by elnyry** [comment]
Can you please check the Events, Conditions at 'pod' level using the **k8s dashboard** and check there to see where the issue is?

If things still don't work out may be we can setup a call soon if that works for you.. Let me know which TZ you are located in and then we can discuss.

**Comment by GeekGuste** [comment]
Hi @elnyry 
My timezone is GMT +0

**Comment by GeekGuste** [comment]
![dash1](https://user-images.githubusercontent.com/36772043/49970550-fee69100-ff2b-11e8-839a-85669b4f42a7.PNG)
![dash2](https://user-images.githubusercontent.com/36772043/49970552-fee69100-ff2b-11e8-9be9-67538fd50b98.PNG)

**Comment by GeekGuste** [comment]
Hi everyone
I upgraded the RAM to 24 and 2 CPU to 4. All pods are running now.
![pod-mojaloop](https://user-images.githubusercontent.com/36772043/50116595-eb4c6a80-024a-11e9-8e66-d95f1004df93.PNG)

**Comment by elnyry** [comment]
Thats good. Thanks for the update

**Comment by elnyry** [comment]
@GeekGuste can we close this now?

**Comment by GeekGuste** [comment]
Yes. Ok.Thank you for your help.
