### ISSUE TITLE
Unable to create new DFSP

### ISSUE THREAD

**Issue by WayaAfrica** [mojaloop/project#543]
GCP
Helm 4.1

Getting an error when we try to create new DFSP using Admin (using postman json test script).

Similar to issue https://github.com/mojaloop/project/issues/504

Error message
"{"id":"BadRequestError","message":"Cannot read property 'findOne' of undefined"}"

**Comment by HenkKodde** [comment]
Please confirm if the HTTP request is similar to this.
POST /admin/participants HTTP/1.1
Host: test-central-ledger.mojaloop.live
Cache-Control: no-cache
Content-Type: application/json
Postman-Token: e1aa127d-6844-4bdb-9464-277c0699cfbe

{
    "name": "mockfsp1",
	"currency":"USD"
}

**Comment by WayaAfrica** [comment]
Yes, identical


{
    "name": "payerfsp",
    "currency":"USD"
}

**Comment by WayaAfrica** [comment]
Any update?

**Comment by sri-miriyala** [comment]
This error usually indicates there is prob with DB. Can you confirm that you see participants table in your Central Ledger DB?

**Comment by elnyry** [comment]
The current issue is that for some reason the central ledger service is unable to connect to the sidecar

**Comment by elnyry** [comment]
Able to create FSPs now, so past this issue. Currently @WayaAfrica is figuring out FSP I think.

**Comment by elnyry** [comment]
@WayaAfrica can we close this now?

**Comment by WayaAfrica** [comment]
yes please
