### ISSUE TITLE
issue with "Install nginx-ingress for load balancing & external access"

### ISSUE THREAD

**Issue by rpalamattom** [mojaloop/project#548]
While trying to run the helm --namespace kube-public install stable/nginx-ingress command as part of inginx/ingress installation on GCloud, we get the following error:
renjith@cloudshell:~ (mojaloop-prod)$ helm --namespace kube-public install stable/nginx-ingress
**_Error: no available release name found_**

**Comment by HenkKodde** [comment]
Please have a look at the following addressing a similar issue. To summarise - it is most likely an RBAC issue. Have a look at the documentation to set up Tiller with RBAC. https://docs.helm.sh/using_helm/#role-based-access-control goes into detail about this.

The issue logged: https://github.com/helm/helm/issues/3839

**Comment by elnyry** [comment]
Closing this as there is no follow-up. Please re-open if there is a recurrence or an update to this.
