### ISSUE TITLE
Unable to connect to Kubernetes dashbord.yaml

### ISSUE THREAD

**Issue by rpalamattom** [mojaloop/project#550]
renjith@cloudshell:~ (mojaloop-prod)$ kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.
yaml
Unable to connect to the server: dial tcp 104.154.147.42:443: i/o timeout

**Comment by mdebarros** [comment]
Hi @rpalamattom,

It would seem that your local Kubernetes CLI Tool (kubectl) is unable to establish a connection to your Kubernetes Master nodes to make the necessary API calls.

Please make sure that ports 443 (assuming that is the correct port) is open to you, and the IP is fully valid and connectable within your network.

Did you configure your kubectl with the correct server/context/user information in your ~/.kube/config?

If you are using Rancher, you should be able to generate the config from your Kubernetes Cluster screen with the button `Kubeconfig File`. Please refer to the following documentation if you need more help here -> https://rancher.com/docs/rancher/v2.x/en/k8s-in-rancher/kubectl/

Kind Regards,
Miguel

**Comment by rpalamattom** [comment]
Hi Miguel,

 

Many thanks for the update.

 

I am trying to set up on GCloud and facing issues there. I was able to perform this last week and only started facing the issue this week.

 

I tried to ping to the IP , both locally and from the cloud shell but wasn’t going through. In terms of the kube config, I have been following the steps as per the guide.

 

Kind Regards,

 




Renjith Palamattom 

Applied Payments Technology

InfoPark-Kochi

Kerala, India

Land: +91 484 485 0362  | Mobile: +91 9535 88 7527

renjith@appliedpaymentstech.com <mailto:renjith@appliedpaymentstech.com> 

www.appliedpaymentstech.com

Confidential: This electronic message and all contents contain information from appliedpaymentstech.com <http://appliedpaymentstech.com> , which may be privileged, confidential or otherwise protected from disclosure. The information is intended to be for the addressee only. If you are not the addressee, any disclosure, copy, distribution or use of the contents of this message is prohibited. If you have received this electronic message in error, please notify the sender immediately and destroy the original message and all copies.

**Comment by rpalamattom** [comment]
Issue resolved after enabling master network authorization with the blocked CIDR

**Comment by rpalamattom** [comment]
Issue resolved after enabling master network authorization on the cluster with the blocked CIDR

**Comment by rpalamattom** [comment]
Hi Miguel,

 

It looks like the yaml link is not accessible today.

 

I tried to deploy a second cluster and is not able to connect now, with error 404

 

Kind Regards,

 




Renjith Palamattom 

Applied Payments Technology

InfoPark-Kochi

Kerala, India

Land: +91 484 485 0362  | Mobile: +91 9535 88 7527

renjith@appliedpaymentstech.com <mailto:renjith@appliedpaymentstech.com> 

www.appliedpaymentstech.com

Confidential: This electronic message and all contents contain information from appliedpaymentstech.com <http://appliedpaymentstech.com> , which may be privileged, confidential or otherwise protected from disclosure. The information is intended to be for the addressee only. If you are not the addressee, any disclosure, copy, distribution or use of the contents of this message is prohibited. If you have received this electronic message in error, please notify the sender immediately and destroy the original message and all copies.
