### ISSUE TITLE
unable to access Kubernetes dashboard

### ISSUE THREAD

**Issue by rpalamattom** [mojaloop/project#555]
https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml

Getting error 404: Not Found

**Comment by elnyry** [comment]
This from the 'general' channel on slack: "_From the official kubernetes github repository in the README.md, the latest link to use is https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml_"

**Comment by elnyry** [comment]
@rpalamattom hey Renjith, closing this for now.. Please re-open if you have an issue
