### ISSUE TITLE
Address new Critical Security Vulnerabilities

### ISSUE THREAD

**Issue by kjw000** [mojaloop/project#571]
As a developer we need to address newly introduced critical and high security vulnerabilities:

In Mojaloop/central-ledger & Mojaloop/ml-api-adapter:

Known critical severity   security vulnerability detected in growl < 1.10.0 defined in package-lock.json.
package-lock.json update suggested: growl ~> 1.10.0.

Known high severity   security vulnerability detected in deep-extend < 0.5.1 defined in package-lock.json.
package-lock.json update suggested: deep-extend ~> 0.5.1.

**Comment by elnyry** [comment]
central-ledger issue is fixed now. ml-api-adapter to be updated soon.

**Comment by elnyry** [comment]
ml-api-adapter is now updated as well to get rid of these..
