### ISSUE TITLE
GET transfers not working in ML AWS

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#582]
API: GET /transfers
Version: 4.3.2
Env: ML AWS

Description:
GET /transfers is not working which is widely used in many of the DFSP edge cases.

*Business Impact: *
DFSPs can not get the status of the particular transfer in the switch. If there are any delays in the network and the COMMITTED or ABORTED msg is not received then either the sending DFSP or the receiving DFSP can send the request GET/transfers/

{ID} to know the status of the transfer. Depending on the status, they will disburse the amounts or send notification to end user.

Expected Behavior:
1. When GET /transfer/{ID} request is sent to switch
2. We get "200 - received" response code from Postman
3. Switch should be providing the current status of the transfer back to the requesting DFSP

Actual Behavior:
1. When GET /transfer/{ID} request is sent to switch
2. I got "200 - received" response code from Postman
3. But no response at the payerfsp simulator log.

CURL:
curl -X GET \
http://test-ml-api-adapter.mojaloop.live/transfers/b902aed8-7a36-409c-922c-63f9e47f4cb3 \
-H 'Accept: application/vnd.interoperability.transfers+json;version=1' \
-H 'Content-Type: application/vnd.interoperability.transfers+json;version=1.0' \
-H 'Date: Tue, 22 Jan 2019 04:06:27 GMT' \
-H 'FSPIOP-Source: payerfsp' \
-H 'Postman-Token: 0481e0ad-cd31-4634-b045-740ea6f4c875' \
-H 'cache-control: no-cache'

Note: This feature was working before. There is an enhancement to this feature in this release 4.3.2 which made it not working.

Also, because of this issue... I can not validate Enhancement: Check FSPIOP-Source for GET /transfers and respond only when the transfer is associated with that FSP: mojaloop/project/issues/565 from release 4.3.2.

ACCEPTANCE CRITERIA
GET /transfers/{ID} should provide the current status of the transfer at the simulator logs.

**Comment by ggrg** [comment]
Hi @sri-miriyala, lately I recently have used local GET /transfers request extensively and I'm pretty sure it's working. What I would question is how do you see the calls to 
`http://ec2-18-130-80-55.eu-west-2.compute.amazonaws.com:8444/payerfsp/transfers/{{transferId}}` and how do you check if the server that accepts the callbacks is running? The endpoint above was acquired by
`GET http://{{CL}}/participants/payerfsp/endpoints`

**Comment by elnyry** [comment]
Thanks Georgi..

Hi Sri, it does work on the current master, the current deployment (4.3.2?) has a spelling error 'particpant' instead of 'participant' in one of the queries for GET. It is fixed in the new 4.4.0 release, already made over this commit 8days ago by Georgi: https://github.com/mojaloop/central-ledger/commit/ff124deb92c504c8a4909d67cc4495a3cd04e9ca

**Comment by elnyry** [comment]
Closing this now as Sri confirmed that with v4.4.1 of central-ledger (and helm v4.4.1), this is working as expected for normal transfers as well as Settlement transfers
