### ISSUE TITLE
Transfers processing and inconsistent response - ML AWS

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#583]
API: Transfers
Endpoint: POST /transfers
Version: ML v4.3.2
Env: ML AWS

*Description: *
Weird behavior noted in transfers. Sometimes getting error msg and then transfer COMMITTED msgs in simulator logs. But Postman is taking the first error msg from Simulator logs and failing the tests.

Business Impact:
P2P Money transfers can not happen smoothly.

Expected Behavior:
1. When POST /transfers request is sent with valid input params
2. The transfer can be COMMITTED or ABORTED
3. The final result (only one) will be sent to Simulator logs 
4. As part of automated testing, postman is collecting this result and validating the tests accordingly.

Actual Behavior:
1. When POST /transfers request is sent with valid input params
2. The result at the logs is "undefined" 
3. As part of automated testing, postman is collecting this "undefined" result and failing tests accordingly as it was expecting "COMMITTED" msg.
4. But again the simulator logs showing a transfer COMMITTED msgs

Note:
The transfers is taking ~19 sec, end to end. Performance is highly dropped. It was taking ~1 sec earlier.
Below are the logs from different services that shows timestamps at each service.
ml-api-adapter-service-8fd568f9d-nrvzv] 2019-01-21T23:04:07.285Z - info: Producer.sendMessage:: messageProtocol:'{"id":"ac5539a6-3ed0-4c5e-a483-4d74af917b36”
centralledger-handler-transfer-prepare] 2019-01-21T23:04:12.131Z - info: TransferService::prepare
centralledger-handler-transfer-prepare] 2019-01-21T23:04:19.474Z - info: Producer.sendMessage::
centralledger-handler-transfer-position] 2019-01-21T23:04:21.296Z - info: PositionHandler::positions
centralledger-handler-transfer-position] 2019-01-21T23:04:23.261Z - info: Producer.sendMessage::
ml-api-adapter-handler-notification] 2019-01-21T23:04:23.321Z - info: Notification::consumeMessage::processMessage
centralledger-handler-transfer-position] 2019-01-21T23:04:26.585Z - info: PositionHandler::positions::commit
ml-api-adapter-handler-notification] 2019-01-21T23:04:26.941Z - info: Notification:consumeMessage
ml-api-adapter-handler-notification] 2019-01-21T23:04:26.969Z - info: [cid=ac5539a6-3ed0-4c5e-a483-4d74af917b36, fsp=payerfsp] ~ NotificationHandler::sendCallback := Callback successful with status code: 200
ml-api-adapter-service-8fd568f9d-nrvzv] 2019-01-21T23:04:23.449Z - info: Producer.sendMessage:: messageProtocol:'{"id":"ac5539a6-3ed0-4c5e-a483-4d74af917b36","to":"payerfsp","from":"payeefsp","type":"application/json","content":{"headers":{"x-forwarded-for":"18.130.80.55","content-type":"application/vnd.interoperability.transfers+json;version=1.0","fspiop-source":"payeefsp","fspiop-destination":"payerfsp","date":"2019-01-21T23:04:07.000Z"},"payload":{"fulfilment":"qt0gzqQoTXvxuRQfHnFmrFiQ2zwd_UWDKF4asLU0e2I","completedTimestamp":"2019-01-21T23:04:23.410Z","transferState":"COMMITTED"}}

ACCEPTANCE CRITERIA
POST /transfers should be working consistently. 
End to end transfers should take less than 1sec.

**Comment by elnyry** [comment]
Closing this, thanks to Sri's inputs - after deploying versions 4.4.0 for central-ledger, ml-api-adapter, central-settlement.. (on the AWS dev envt)

**Comment by sri-miriyala** [comment]
With the new release v4.4.0 from OSS team, transfers are taking 0.2 sec end to end. This also includes simulator time. Exceptional performance.
But will keep testing for couple more days to make sure the performance stays intact.
<img width="1426" alt="screen shot 2019-01-22 at 2 01 07 pm" src="https://user-images.githubusercontent.com/38143240/51559343-a8844080-1e4f-11e9-8ab2-d36b821b810b.png">
