### ISSUE TITLE
Update postman collections with new Accept and Content-Type headers

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#594]
**Summary**:
The current postman collections on the mojaloop/postman repository is out of date. The is need to be updated and reviewed

**Severity**:
Low

**Priority**:
Medium

**Expected Behaviour**
Postman scripts should trigger the REST endpoints on the API with the correct payloads, headers and/or URI Parameters

**Steps to Reproduce**
  1. Download the postman collection and environment from the master branch
  2. Import them into postman
  3. Run request

**Specifications**
  - Component (if known): Postman
  - Version: 0.1
  - Platform: Postman
  - Bug found/raised by: @rmothilal 

**Notes**:

- Severity when opened: Low
- Priority when opened: Medium

**Comment by elnyry** [comment]
Develop branch has the up-to-date collection, for the time being that needs to be used.

This bug can be resolved when the current develop is merged with master (and develop deleted as agreed upon)

**Comment by elnyry** [comment]
Closing this because this PR is now merged: https://github.com/mojaloop/postman/pull/5
