### ISSUE TITLE
New contributor tasks

### ISSUE THREAD

**Issue by kjw000** [mojaloop/project#598]
As a new contributor to Mojaloop I want to understand and easily be able to pick up tasks that are appropriate.

- stories are tagged with new contributor or help wanted
- stories are clearly noted with the information required
- stories have associated members/folks that can help them and approve pr
- contributors have a wide range of diff stories and or tasks to get their feet wet on the Mojaloop project

**Comment by elnyry** [comment]
Moving this to next Sprint as this wasn't prioritized and a few other stories were added mid-way

**Comment by elnyry** [comment]
1. #400 
2. #629
3. #482
4. #405

**Comment by kjw000** [comment]
Thanks Sam!

**Comment by kjw000** [comment]
We also need to identify several larger epics/stories for the DFS labs team to include on for the Goggle Summer of Code interns that they are offering to us for assistance.  http://docs.osc.dial.community/en/latest/soc.html    
Ideally we need to identify some of these before the end of the month.

**Comment by elnyry** [comment]
Added a couple more:https://github.com/mojaloop/project/issues/513
https://github.com/mojaloop/project/issues/235
