### ISSUE TITLE
Bug - Grafana dashboards are not displaying any metrics

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#601]
**Summary**:
Grafana dashboards are not displaying any metrics

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
Grafana dashboards should display metrics

**Steps to Reproduce**
  1. Go to Grafana dashboard
  2. Look at metrics
  3. Decide if life is worth living due to the lack of metrics
  4. ...
  5. Profit!!

**Specifications**
  - Component (if known): Helm
  - Version: v4.4.1 release
  - Platform: Dev/Test environments
  - Type of testing: manual
  - Bug found/raised by: @mdebarros 

**Dependencies**:
- [x] Blocked due to pending new dev1 environment setup

**Notes**:
Dashboards need to be updated with the correct metric variable names. The current names were pulled from the Performance Stream which is not aligned to the released instrumentation.

- Severity when opened: Medium
- Priority when opened: Medium

**Comment by mdebarros** [comment]
Dashboard fixes via the following PR: https://github.com/mojaloop/helm/pull/149

**Comment by mdebarros** [comment]
@NicoDuvenage please verify/update your tests based on the following document https://github.com/mojaloop/helm/blob/master/monitoring/METRICS.md

**Comment by elnyry** [comment]
To be validated in #673
