### ISSUE TITLE
Document links and references are pointing to outdated branches.

### ISSUE THREAD

**Issue by HenkKodde** [mojaloop/project#613]
**Summary**:
Documents and sequence diagrams within the *docs* repository are pointing to outdated branches that are now deleted. These links will need to be updated to refer to the appropriate documents and references within the master branch to allow community members the opportunity to access relevant references revered too.

**Severity**:
Low

**Priority**:
Medium

**Expected Behavior**
All links and references in the *docs* repository should link to documents and references in the master branch.

**Steps to Reproduce**
N/A

**Specifications**
  - Bug found/raised by: @HenkKodde 

**Notes**:
- Severity when opened: Low (repetitional)
- Priority when opened: Medium (repetitional)

**PR**
- [x] PR - https://github.com/mojaloop/docs/pull/117

**Comment by elnyry** [comment]
Closing this as the PR is now merged. Thanks Henk.
