### ISSUE TITLE
DB Query details in error message when "attempting to close a settlement window on an ID that does not exist"

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#617]
**Summary**:
As can be seen in the snippet in the below sections, (SQL query details being displayed) the DB Query detail is being shown in error message when "attempting to close a settlement window on an ID that does not exist". This is neither safe nor graceful and needs to be addressed.

**Severity**:
Medium
(Since the attempt itself is wrong and an error is being given)

**Priority**:
medium

**Expected Behavior**
1. When an attempt is made to close a Settlement window, it is either closed if its a valid request or
2. An error message is thrown with only necessary details if its an invalid request.

**Steps to Reproduce**
  1. After deployment of a ML Switch, attempt to close a Settlement window with a non-existing settlement window ID
  2. An error message is thrown. Below is the response
```
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": {
        "errorInformation": {
            "errorDescription": "insert into `settlementWindowStateChange` (`createdDate`, `reason`, `settlementWindowId`, `settlementWindowStateId`) values ('2019-02-07 19:05:41.162', 'string', 4, 'CLOSED') - ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`central_ledger`.`settlementWindowStateChange`, CONSTRAINT `settlementwindowstatechange_settlementwindowid_foreign` FOREIGN KEY (`settlementWindowId`) REFERENCES `settlementWindow` (`settlemen)"
        }
    }
}
```
**Pull Requests**:
- [x] https://github.com/mojaloop/central-settlement/pull/62

**Specifications**
  - Component (if known): Switch Operations
  - Version: v5.1.0
  - Platform: AWS Dev
  - Subsystem: central-settlement
  - Type of testing: Functional/Regression 
  - Bug found/raised by: @sri-miriyala 

**Notes**:

- Severity when opened: Medium
- Priority when opened: Medium

**Comment by sri-miriyala** [comment]
This issue is resolved with v5.1.2.
<img width="1053" alt="screen shot 2019-02-12 at 8 06 56 am" src="https://user-images.githubusercontent.com/38143240/52637509-60c86600-2e9d-11e9-87aa-72ca766b6516.png">

Hence closing.
