### ISSUE TITLE
Automate the CD pipeline for central-services-shared

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#62]
**Goal**:
As a developer I would like to automate the CD pipeline for central-services-shared so that I can shorten the delivery cycle

**Tasks**:
- [ ] 

**Acceptance Criteria**:
- [x] Define and document the deployment process and requirements
- [x] Automate the deployment to Nodejs.com for master and develop push tags

**Dependencies**:
- None currently

**Comment by mdebarros** [comment]
Documentation for CI/CD created via this PR:
https://github.com/mojaloop/docs/pull/9

PR: 
https://github.com/mojaloop/central-services-shared/pull/7
