### ISSUE TITLE
Automate the CD pipeline for central-kms

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#63]
**Goal**:
As a developer I would like to automate the CD pipeline for central-kms so that I can shorten the delivery cycle

**Tasks**:
- [ ] 

**Acceptance Criteria**:
- [ ] Define and document the deployment process and requirements
- [ ] Automate the deployment through k8s for master and develop push tags

**Dependencies**:
- None currently

**Comment by elnyry** [comment]
Outdated issue
