### ISSUE TITLE
Extra transferId in fulfillment response from NotificationHandler

### ISSUE THREAD

**Issue by ksatya77** [mojaloop/project#641]
**Summary**:
We are noticing that the fulfillment response that gets sent to FSPs from notification handler has an extra transferId as part of the body

**Severity**:
High

**Priority**:
Highest

**Expected Behavior**
There should not be a transferId as part of PUT /transfer/{ID} response that goes out of notification handler

**Steps to Reproduce**
  1. Trigger a transfer from payerfsp to payeefsp
  2. Capture the PUT /transfer/{ID} notification that gets sent to FSPs
  3.

**Specifications**
  - Component (if known): central services / ml-api-adapter
  - Version: 5.1.1
  - Platform: AWS dev
  - Subsystem: Notification Handler
  - Type of testing: ?
  - Bug found/raised by: @ksatya77 

**Notes**:

- Severity when opened: HIGH
- Priority when opened: HIGH

**Pull Requests**
- [x] https://github.com/mojaloop/central-ledger/pull/248

**Deployments**
- [ ] Deployment to dev environment ready for testing [ @elnyry ]

**Comment by elnyry** [comment]
Hotfix released v5.1.1-hotfix.1 - https://hub.docker.com/r/mojaloop/central-ledger/tags/
