### ISSUE TITLE
Final state for timed-out transfers being returned as EXPIRED_RESERVED (an internal status)

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#654]
**Summary**:
For expired transfers, the final state is being stored as EXPIRED_RESERVED which is an internal state. The issue with this is that for a GET call on this transfer, the transferState is being sent as it is and thats an issue because EXPIRED_RESERVED is an internal state and it should be ABORTED that is either the final state (or it should be reported as such every time, which is not ideal). The get-transfers-handler needs to do the mapping between internal and external transferStates and respond with one of the states from the Specification (Received, Reserved, Committed, Aborted)

**Severity**:
High

**Priority**:
Medium

**Expected Behavior**
1. On a Mojaloop Switch system, for an expired transfer, when a valid GET call is made
2. The callback sends a status as ABORTED, which is a state identified in the Specification.

**Steps to Reproduce**
1. On a Mojaloop Switch system, for an expired transfer, when a valid GET call is made
2. The callback sends a status as EXPIRED_RESERVED, which is not a state identified in the Specification.

**Specifications**
  - Component (if known): central services
  - Version: v5.2.0
  - Platform: AWS 'Dev'
  - Subsystem: timeout-handler, position-handler
  - Type of testing: Reviewing of sequence diagrams
  - Bug found/raised by: @elnyry 

**Notes**:
- Severity when opened: High
- Priority when opened: Medium

**Bugfix**:
- [x] GET /transfers is now using transferState.enumeration field instead of transferStateChange.transferStateId
- [x] The above mentioned change also addresses another *bug*, where GET /transfers returns INVALID state. It is also intended to address the newly introduced states for story #281 
- [x] Code coverage restored at 100% (previously Branches: 99.86% ( 711/712 ))

**Pull requests**:
- [ ] https://github.com/mojaloop/central-ledger/pull/253

**Comment by sri-miriyala** [comment]
This has been fixed with v5.3.1.
Now the state returned is "ABORTED".
