### ISSUE TITLE
Automate the CD pipeline for central-fraud-sharing

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#66]
**Goal**:
As a developer I would like to automate the CD pipeline for central-fraud-sharing so that I can shorten the delivery cycle

**Tasks**:
- [ ] 

**Acceptance Criteria**:
- [x] Define and document the deployment process and requirements
- [x] Automate the deployment to Nodejs.com for master and develop push tags

**Dependencies**:
- None currently

**Comment by mdebarros** [comment]
Documentation for CI/CD created via this PR:
https://github.com/mojaloop/docs/pull/9

PR: 
https://github.com/mojaloop/central-fraud-sharing/pull/1

SonarQube:
https://s3-us-west-2.amazonaws.com/elasticbeanstalk-us-west-2-886403637725/sonar/central-fraud-sharing/lcov.info

See Published NPM deployments from CircleCI: 
$ npm view @mojaloop/central-fraud-sharing

Output:
{ name: '@mojaloop/central-fraud-sharing',
  'dist-tags': { snapshot: '1.1.0-snapshot.4', latest: '**1.1.0-snapshot.4**' },
  versions: [ '**1.1.0-snapshot.4**' ],
  time:
   { created: '2018-02-20T13:34:50.204Z',
     '**1.1.0-snapshot.4': '2018-02-20T13:34:50.387Z**',
     modified: '2018-02-20T13:34:50.582Z' },
