### ISSUE TITLE
Automate the CD pipeline for central-services-database

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#67]
**Goal**:
As a developer I would like to automate the CD pipeline for central-services-database so that I can shorten the delivery cycle

**Tasks**:
- [ ] 

**Acceptance Criteria**:
- [x] Define and document the deployment process and requirements
- [x] Automate the deployment to Nodejs.com for master and develop push tags

**Dependencies**:
- None currently

**Comment by mdebarros** [comment]
Documentation for CI/CD created via this PR:
https://github.com/mojaloop/docs/pull/9

PR: 
https://github.com/mojaloop/central-services-database/pull/8

SonarQube:
https://s3-us-west-2.amazonaws.com/elasticbeanstalk-us-west-2-886403637725/sonar/central-services-database/lcov.info

See Published NPM deployments from CircleCI: 
$ npm view @mojaloop/central-services-database

Output:
{ name: '@mojaloop/central-services-database',
  description: 'Shared database code for central services',
  'dist-tags': { latest: '0.4.0', snapshot: '**1.1.0-snapshot**' },
  versions: [ '0.3.0', '0.4.0', '**1.1.0-snapshot**' ],
  time:
   { modified: '2018-02-20T12:10:32.520Z',
     created: '2017-11-27T07:38:54.522Z',
     '0.3.0': '2017-11-27T07:38:54.522Z',
     '0.4.0': '2018-02-07T12:24:39.784Z',
     '**1.1.0-snapshot': '2018-02-20T12:10:32.304Z**' },

**Comment by elnyry** [comment]
CI Looks good (CC Data on S3 and and build on CircleCI)
