### ISSUE TITLE
Automate the CD pipeline for central-services-error-handling

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#68]
**Goal**:
As a developer I would like to automate the CD pipeline for central-services-error-handling so that I can shorten the delivery cycle

**Tasks**:
- [ ] 

**Acceptance Criteria**:
- [x] Define and document the deployment process and requirements
- [x] Automate the deployment to Nodejs.com for master and develop push tags

**Dependencies**:
- None currently

**Comment by mdebarros** [comment]
Documentation for CI/CD created via this PR:
https://github.com/mojaloop/docs/pull/9

PR: 
https://github.com/mojaloop/central-services-error-handling/pull/9

SonarQube:
https://s3-us-west-2.amazonaws.com/elasticbeanstalk-us-west-2-886403637725/sonar/central-services-error-handling/lcov.info

See Published NPM deployments from CircleCI: 
$ npm view @mojaloop/central-services-error-handling

Output:
{ name: '@mojaloop/central-services-error-handling',
  description: 'Hapi error handling module',
  'dist-tags': { latest: '0.5.0', snapshot: '**1.1.0-snapshot**' },
  versions: [ '0.2.2', '0.2.3', '0.4.0', '0.5.0', '**1.1.0-snapshot**' ],
  time:
   { modified: '2018-02-20T12:25:50.528Z',
     created: '2017-11-27T15:34:02.976Z',
     '0.2.2': '2017-11-27T15:34:02.976Z',
     '0.2.3': '2017-11-29T10:37:41.184Z',
     '0.4.0': '2018-02-07T13:02:31.319Z',
     '0.5.0': '2018-02-12T21:11:05.667Z',
     '**1.1.0-snapshot': '2018-02-20T12:25:50.339Z**' },
