### ISSUE TITLE
GET /settlements by State = SETTLED & by SettlementWindowID not working

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#682]
**Summary**:
GET /settlements by State = "SETTLED" is not giving the relevant settlements in the response

**Severity**:
Medium
**Priority**:
Medium

**Expected Behavior**

When I call GET /settlements by params where state = "SETTLED" should return all the settled settlements.
**Steps to Reproduce**
  1. I created settlement on a closed window and ran settlements - prepare, reserve, Commit and Settle requests.
  2. When I do GET /settlements by ID I was able to see that settlement status as "SETTLED"
<img width="1416" alt="screen shot 2019-03-07 at 1 39 03 pm" src="https://user-images.githubusercontent.com/38143240/54010508-11442580-413d-11e9-9285-16b4d849769f.png">

  3. When I do GET /settlements by state = "SETTLED", I do not see the previously settled settlement.
But I see the below error:
<img width="1438" alt="screen shot 2019-03-07 at 12 55 00 am" src="https://user-images.githubusercontent.com/38143240/54010499-01c4dc80-413d-11e9-94a6-23eb6287b080.png">

**Specifications**
  - Component (if known): Settlements
  - Version: 5.2.0
  - Platform: MAC
  - Subsystem: 
  - Type of testing: Functional
  - Bug found/raised by: Sri

Note:
Several issues found. Pls read the comments.

**Comment by elnyry** [comment]
Hi Sri @sri-miriyala , this may as well be a bug, but in the second snapshot, the "fromDateTime" and "toDateTime" range doesn't include the settlement 87's time.. Settlement 87 time seems to be after 18hrs on 7th (created and changed both), whereas the range in the query ends at 17:32:28 on 7th

Can you please confirm?

**Comment by sri-miriyala** [comment]
Yes Sam... I tried longer intervals of time, but did not work either.
Here is another screenshot:
<img width="1439" alt="screen shot 2019-03-08 at 1 41 20 am" src="https://user-images.githubusercontent.com/38143240/54012202-53706580-4143-11e9-905f-7994e01d2a2a.png">

**Comment by sri-miriyala** [comment]
Not working for Settlement window Id param as well. For ex, the above settlement "87" is in the settlement window "144". When I query by settlementWindow ID = "144" is giving "404- Not found" error.
<img width="1438" alt="screen shot 2019-03-08 at 1 43 47 am" src="https://user-images.githubusercontent.com/38143240/54012386-e5786e00-4143-11e9-941c-f859cf809b9a.png">

Not working for previous window = "143" too.

This is only working for settlementWindowID = 1
<img width="1440" alt="screen shot 2019-03-08 at 1 46 36 am" src="https://user-images.githubusercontent.com/38143240/54012438-0a6ce100-4144-11e9-976d-e94ada7ec491.png">

**Comment by sri-miriyala** [comment]
Looks like the root issue is different... When I query most of the GET /settlements by params, all of them are returning only settlement ID "1" details.
Also... GET /settlementWindow by Id is giving below error:
<img width="1436" alt="screen shot 2019-03-08 at 1 56 59 am" src="https://user-images.githubusercontent.com/38143240/54013234-59b41100-4146-11e9-8373-e1c6b886b1ea.png">

**Comment by ggrg** [comment]
@elnyry, @sri-miriyala, this issue was fixed with https://github.com/mojaloop/central-settlement/pull/67 which was addressing https://github.com/mojaloop/project/issues/678. We need to make a new release and upgrade the environment.

**Comment by elnyry** [comment]
@sri-miriyala please re-open this if there is a repro with deployments using the current versions (>v5.3.2)
