### ISSUE TITLE
PUT Headers are incorrect when sending through a GET/POST Transfers Request

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#687]
**Summary**:
When sending through a `GET /transfers/{ID}` or alternatively a duplicate (when either in state = `COMMITTED` or `ABORTED`) `POST /transfer/{ID}` the subsequent PUT callback headers contain the original headers unmodified including FSPIOP-URI, FSPIOP-HTTP-Method, FSPIOP-Source, FSPIOP-Destination, FSPIOP-Signature etc... The source should be "switch" as per API spec, destination should be to originating FSPID and JWS headers should be removed (it can be assumed signing will be done outside the switch core at this point)

**Severity**:
High

**Priority**:
Critical

**Expected Behavior**

When sending through a `GET /transfers/{ID}` or alternatively a duplicate (when either in state = `COMMITTED` or `ABORTED`) `POST /transfer/{ID}` the subsequent PUT callback header should:
- have correct FSPIOP-Source and FSPIOP-Destination headers set
- not contain any signature related headers

**Steps to Reproduce**
  1. Send through a `GET /transfers/{ID}` or alternatively a duplicate (when either in state = `COMMITTED` or `ABORTED`) `POST /transfer/{ID}`
  2. Monitoring the PUT Callback response

**Specifications**
  - Component (if known): ml-api-adapter & central-ledger
  - Version: v5.3.x
  - Platform: DEV0, DEV1
  - Subsystem: n/a
  - Type of testing: Manual
  - Bug found/raised by: @bushjames 

**PRs**:
- [x] https://github.com/mojaloop/central-ledger/pull/260
- [x] https://github.com/mojaloop/central-ledger/pull/262
- [x] https://github.com/mojaloop/ml-api-adapter/pull/96
- [x] https://github.com/mojaloop/ml-api-adapter/pull/97
- [x] https://github.com/mojaloop/helm/pull/154
- [x] https://github.com/mojaloop/helm/pull/155
- [x] https://github.com/mojaloop/helm/pull/157

**Notes**:

- Severity when opened: High
- Priority when opened: Critical

**Comment by mdebarros** [comment]
New releases:
- https://github.com/mojaloop/ml-api-adapter/releases/tag/v5.4.0
- https://github.com/mojaloop/central-ledger/releases/tag/v5.4.0

Deployment and updates to Helm are still pending.

**Comment by sri-miriyala** [comment]
For GET Transfer request: Upon validating this fix as part of 5.4.0 release, still having issues getting the FSPIOP-Destination header in the PUT callback. As this header is optional and is not included in the original request, is not being sent in PUT callback.

For Duplicate transfer request: The headers in PUT callback are same as the original POST request. According to the API spec, they need to be same as the GET transfers request. 

 Discussed with @mdebarros and waiting on the fix for this.

**Comment by sri-miriyala** [comment]
Duplicate Transfers:

<img width="948" alt="Screen Shot 2019-03-21 at 2 37 14 PM" src="https://user-images.githubusercontent.com/38143240/54776606-dc2cde00-4be6-11e9-997e-5221f7d6f36c.png">

GET transfers:

<img width="792" alt="Screen Shot 2019-03-21 at 2 39 01 PM" src="https://user-images.githubusercontent.com/38143240/54776728-1a2a0200-4be7-11e9-8c8c-04fcb02678e7.png">


Both are returning the correct headers.
