### ISSUE TITLE
Headers Validation Failed - Block Transfer Feature

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#697]
**Summary**:
The below Headers validation Failed in PUT callback on block transfer feature.
1. ACCEPT Header should not be returned in PUT callback
2. FSPIOP-Source should be Switch but it is coming as payerfsp.
3. FSPIOP-Destination should be payerfsp but it is coming as payeefsp

**Severity**:
HIGH
**Priority**:
Critical

**Expected Behavior**
1. When I send POST /transfers request with a high transfer amount so that the payee NDC limit exceeds
2. The transfer should be blocked and the response to payerfsp should contain "ABORTED" status and the Error msg "Payerfsp has insufficient liquidity to perform the transfer"
3. In that PUT callback to payerfsp, 
             a. ACCEPT header should not be sent in PUT callback
             b. FSPIOP-Source should be "Switch"
             c. FSPIOP-Destination should be "payerfsp"

**Steps to Reproduce**
  1. Send POST /transfer request from payerfsp to payeefsp with an amount exceeds the NDC of payerfsp
  2. Transfer failed with "ABORTED" status to payerfsp
  3. In that PUT callback to payerfsp, observe the headers returned by switch.

**From Simulator logs:**
<img width="926" alt="Screen Shot 2019-03-22 at 1 05 20 AM" src="https://user-images.githubusercontent.com/38143240/54801721-9dc30d80-4c3e-11e9-92ff-21f29c4f6e50.png">

**From Postman tests:**
<img width="1270" alt="Screen Shot 2019-03-22 at 1 07 38 AM" src="https://user-images.githubusercontent.com/38143240/54801797-ef6b9800-4c3e-11e9-8d97-7ce36b15b480.png">

**Pull Requests:**
- [x] https://github.com/mojaloop/ml-api-adapter/pull/98
- [x] https://github.com/mojaloop/central-ledger/pull/264

**Specifications**
  - Component (if known): Transfer / Central-Ledger
  - Version: 5.4.1
  - Platform: MAC OS
  - Subsystem:
  - Type of testing: API Contract testing
  - Bug found/raised by: Sri

**Notes**:

- Severity when opened: HIGH
- Priority when opened: HIGH

**Comment by ggrg** [comment]
Hi @sri-miriyala, thanks for the detailed report. I agree, except the statement we need to include ABORTED in the response. 
> and the response to payerfsp should contain "ABORTED" status

The problem is that we don't have it at the /error endpoint. @elnyry, please confirm.

**Comment by elnyry** [comment]
Hi @sri-miriyala @ggrg I think thats how it is supposed to be. In fact the PUT with ABORTED is less informative than the error callback since the error callback contains some information regarding why the failure happened. A PUT call on /transfers/{ID} on the other hand doesn't tell the Payer anything and there's ambiguity regarding why it happened and where it was rejected, Switch or the Payee..

**Comment by ggrg** [comment]
@elnyry, we are ready for release 5.5.0
@sri-miriyala, please validate and close, if resolved

**Comment by sri-miriyala** [comment]
<img width="750" alt="Screen Shot 2019-04-01 at 2 11 01 PM" src="https://user-images.githubusercontent.com/38143240/55349592-15d3d380-5488-11e9-802b-f03a6800c6c2.png">
This is working as expected. Closing the bug
