### ISSUE TITLE
Timeout scenario - Content Type Header value incorrect in PUT callback

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#698]
**Summary**:
In transfers Timeout scenario, when the payerfsp receives PUT callback regarding transfer "ABORTED" status, the headers in the PUT contain malformed Content Type Header.

**Severity**:
( High)

**Priority**:
(Critical)

**Expected Behavior**
Content Type Header in the PUT callback to payerfsp should be "application/vnd.interoperability.transfers+json;version=1"

**Steps to Reproduce**
  1. Send a POST /transfer - Prepare
  2. Do not send tranfer - fulfil
  3. After the expiry time, payefsp gets a callback response from switch saying that the tranfer is ABORTED due to timedout.
  4. In that PUT callback, check the Content Type Header value, which is "application/json"

FROM SIMULATOR LOGS:
<img width="923" alt="Screen Shot 2019-03-22 at 1 29 14 AM" src="https://user-images.githubusercontent.com/38143240/54802498-f7790700-4c41-11e9-9925-f995850c6c7e.png">

**Pull Requests:**
- [ ] https://github.com/mojaloop/ml-api-adapter/pull/98
- [ ] https://github.com/mojaloop/central-ledger/pull/264

**Specifications**
  - Component (if known): Central Ledger and Ml-api-adapter
  - Version: 5.4.1
  - Platform: MAC OS
  - Subsystem: 
  - Type of testing: API Contract Testing
  - Bug found/raised by: Sri

**Notes**:

- Severity when opened: HIGH
- Priority when opened: HIGH

**Comment by ggrg** [comment]
@elnyry, we are ready for release 5.5.0
@sri-miriyala, please validate and close, if resolved

**Comment by sri-miriyala** [comment]
<img width="657" alt="Screen Shot 2019-04-01 at 2 03 39 PM" src="https://user-images.githubusercontent.com/38143240/55349172-06a05600-5487-11e9-833b-73ac4f830e80.png">

**Comment by sri-miriyala** [comment]
Content-Type header is now working as expected
