### ISSUE TITLE
Headers validation failure - Payeefsp ABORT

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#699]
**Summary**:
For the Payeefsp "ABORT" transfers scenario, when I send the PUT /transfers with fulfilment manually with "ACCEPT" Header, it is not giving any error 400-bad request rather accepting the request by giving 200.

**Severity**:
( Medium)

**Priority**:
(Medium)

**Expected Behavior**
the PUT /transfers with "Accept" header should be blocked by giving bad request error with 400 code. 

**Steps to Reproduce**
  1. Send POST /transfers request from payerfsp to noresponsepayeefsp
  2. manually send PUT /transfers with valid fulfilement, state = "ABORTED" and provide "ACCEPT" header
  3. Then send the request, you see a 200-OK on the postman screen.

**Specifications**
  - Component (if known): Central ledger & ml-api-adapter
  - Version: 5.4.1
  - Platform: Mac OS
  - Subsystem:
  - Type of testing: API contract Testing
  - Bug found/raised by: Sri

<img width="1023" alt="Screen Shot 2019-03-22 at 1 51 11 AM" src="https://user-images.githubusercontent.com/38143240/54803225-03b29380-4c45-11e9-8cef-11ef9bb2896d.png">

**Notes**:

- Severity when opened: Medium
- Priority when opened: medium

**Comment by ggrg** [comment]
Hi @sri-miriyala, the explained behaviour is due to last line of the setting:
```
      headers: Joi.object({
        'content-type': Joi.string().required().regex(/application\/vnd.interoperability[.]/),
        'date': Joi.date().format('ddd, D MMM YYYY H:mm:ss [GMT]').required(),
        'x-forwarded-for': Joi.string().optional(),
        'fspiop-source': Joi.string().required(),
        'fspiop-destination': Joi.string().optional(),
        'fspiop-encryption': Joi.string().optional(),
        'fspiop-signature': Joi.string().optional(),
        'fspiop-uri': Joi.string().optional(),
        'fspiop-http-method': Joi.string().optional()
      }).unknown(false).options({ stripUnknown: true }),
```
if we remove `.options({ stripUnknown: true })`, it would almost impossible to send requests because of validation errors like the following:
```
{
    "key": "joiValidationError",
    "value": **"\"accept\" is not allowed**. \"cache-control\" is not allowed. \"postman-token\" is not allowed. \"user-agent\" is not allowed. \"host\" is not allowed. \"accept-encoding\" is not allowed. \"content-length\" is not allowed. \"connection\" is not allowed"
}
```
So I'd suggest keep it like that unless there is explicit requirement not to allow anything else.

**Comment by elnyry** [comment]
I agree with the assessment Georgi, we shouldn't probably be that strict at this time. However, lets add this as an item on the DA and follow it up with discussions. For the time-being, since this is not high priority anyway, lets leave it in the backlog or blocked pipeline

I just added this to the DA list, so we can address this on the next DA call

**Comment by elnyry** [comment]
@sri-miriyala @ggrg , we had this conversation last week or the week before that during the DA meeting and the majority of the group agreed that this behavior is acceptable (Especially since unrecognized/unknown headers are stripped off and do not enter the system).

**Comment by elnyry** [comment]
Going to close this one out, please let me know if you have any questions, concerns

**Comment by elnyry** [comment]
Closing this one as discussed
