### ISSUE TITLE
FAQ Link in the contributors guide is 404

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#706]
**Summary**:
The contributors guide [here](https://docs.mojaloop.live/contributors-guide/) lists a FAQ that no longer exists.

https://github.com/mojaloop/mojaloop/blob/master/FAQ.md

**Severity**:
Low

**Priority**:
Low

**Expected Behavior**
Clicking on the link should direct the user to the FAQ.

**Notes**:
I couldn't find the FAQ in the main repo, if it no longer exists, then perhaps we should remove this reference.

I'm quite happy to make a PR myself, I just need some guidance on where to find the FAQ or if we should remove the link to it.

**Comment by elnyry** [comment]
Fixed but looks like it needs redeployment

**Comment by elnyry** [comment]
Fixed - http://mojaloop.io/documentation/contributors-guide/
