### ISSUE TITLE
Automate the CD pipeline for pathfinder-query-client

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#71]
**Goal**:
As a developer I would like to automate the CD pipeline for pathfinder-query-client so that I can shorten the delivery cycle

**Tasks**:
- [ ] 

**Acceptance Criteria**:
- [x] Define and document the deployment process and requirements
- [x] Automate the deployment to Nodejs.com for master and develop push tags

**Dependencies**:
- None currently

**Comment by mdebarros** [comment]
Documentation for CI/CD created via this PR:
https://github.com/mojaloop/docs/pull/9

PR: 
https://github.com/mojaloop/pathfinder-query-client/pull/6

SonarQube:
https://s3-us-west-2.amazonaws.com/elasticbeanstalk-us-west-2-886403637725/sonar/pathfinder-query-client/lcov.info

See Published NPM deployments from CircleCI: 
$ npm view @mojaloop/pathfinder-query-client

Output:
{ name: '@mojaloop/pathfinder-query-client',
  description: 'Library for querying PathFinder DNS records.',
  'dist-tags': { latest: '0.2.0', snapshot: '**1.1.0-snapshot**' },
  versions: [ '0.2.0', '**1.1.0-snapshot**' ],
  time:
   { modified: '2018-02-20T12:38:31.509Z',
     created: '2017-11-30T15:25:50.736Z',
     '0.2.0': '2017-11-30T15:25:50.736Z',
     '**1.1.0-snapshot': '2018-02-20T12:38:31.245Z**' },
