### ISSUE TITLE
Direct database access in test environment

### ISSUE THREAD

**Issue by regicorbin** [mojaloop/project#728]
## **Goal**:
As a tester I want to connect directly to the test environment database so that I can pull dynamic test data and verify expected results against the database

**Tasks**:
- [ ] Grant direct read access to the test environment database to Regi Corbin [ @elnyry  ]

**Acceptance Criteria**:
- [ ] Regi can access the test database from his computer

## **Pull Requests**:
- [ ] TBD

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: TBC
- QA/Review: TBC

**Comment by elnyry** [comment]
Moving this to review as we had several follow-up discussions..
