### ISSUE TITLE
FSPIOP-URI header is getting removed in forwarding transfers request to payeefsp

### ISSUE THREAD

**Issue by ksatya77** [mojaloop/project#733]
**Summary**:
Upon receiving the transfers request from payer fsp, Switch forwards it to payee fsp. At this point FSPIOP-URI header is getting dropped when the request is forwarded to payee fsp

**Severity**:
High

**Priority**:
High

**Expected Behavior**
FSPIOP-URI header should be forwarded to receiver fsp

**Steps to Reproduce**
  1. Send a prepare request with fspiop-uri header
  2. In the outgoing request going from switch to payee fsp, make sure fspiop-header is present and is the same as the one sent in the original request
  3.

**Specifications**
  - Component (if known): ML-API-Adapter Notification Handler
  - Version: 5.5.2
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by: @ksatya77 

**Notes**:

- Severity when opened: High
- Priority when opened: High

**Comment by elnyry** [comment]
Thanks Murthy, here are the PRs:
- https://github.com/mojaloop/ml-api-adapter/pull/100
- https://github.com/mojaloop/ml-api-adapter/pull/99

**Comment by sri-miriyala** [comment]
This is validated  in new version of ML API adapter and is working as expected. Hence closed.
