### ISSUE TITLE
Block transfer error code is not according to the API spec

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#741]
**Summary**:
The error code - 4001 supposed to be a string. But it is coming as an integer.
**Severity**:
( High)

**Priority**:
(Critical)

Actual Behavior:
1. When we run block transfer feature from postman collections
2. after running the transfer with an amount that exceeds NDC
3. Simulators are receiving error code - 4001 and error msg - Payerfsp has insufficient liquidity to perform the transfer

Expected behavior:
1. When we run block transfer feature from postman collections
2. after running the transfer with an amount that exceeds NDC
3. Simulators are receiving error code - 4001 and error msg - Payerfsp has insufficient liquidity to perform the transfer
4. BUT this error code 4001 needs to be a string ("4001") rather than integer as per the SPEC.

<img width="854" alt="Screen Shot 2019-04-23 at 10 33 09 AM" src="https://user-images.githubusercontent.com/38143240/56599312-4bba3280-65c4-11e9-8f06-fd8c143de897.png">

**Specifications**
  - Component (if known): Central Ledger, ML API adapter
  - Version:
  - Platform: MAC OS
  - Subsystem: Mojaloop
  - Type of testing: Functional
  - Bug found/raised by: Sri

**Comment by elnyry** [comment]
Priority not High for OSS..

Severity cannot be high given any context, as this affects only a limited are of Mojaloop

Will get this looked at this week though..

**Comment by elnyry** [comment]
@ggrg considering that #742 is now closed, can this one be as well?

**Comment by elnyry** [comment]
Thanks, confirmed
