### ISSUE TITLE
Oracle not showing under simulator documentation endpoint

### ISSUE THREAD

**Issue by rmothilal** [mojaloop/project#782]
**Summary**:
The oracle endpoints are not returned on the /documentation endpoint on the simulator

**Severity**:
Low
**Priority**:
Low
**Expected Behaviour**
The endpoints for the oracles should be shown when the /documentation endpoint is hit

**Steps to Reproduce**
  1. Run simulator
  2. Request /documentation endpoint

**Tasks**
- [x] update tags in src/oracle/routes.js from [oracle, participants] to [api, oracle]
- [x] test functionality works correctly

**Specifications**
  - Component (if known): Simulator
  - Version: 6.2.0
  - Platform:
  - Subsystem:
  - Type of testing: Manual
  - Bug found/raised by: @mdebarros 

**Notes**:
The fix is to update the tags variable in the src/oracle/routes.js from [oracle, participants] to [api, oracle]

- Severity when opened: Low
- Priority when opened: Low

**Comment by elnyry** [comment]
Thanks @rmothilal
