### ISSUE TITLE
Change the GitHub description text "CORE COMPONENT", "CORE RELATED" to a github topic

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#788]
## **Goal**:
As a project maintainer I want to clarify the projects in the github repository.

_This is small and nitpicky, but I thought someone might value the suggestion. Close if you don't think it's worthwhile._

When first being onboarded to the project, I found the "CORE COMPONENT" and "CORE RELATED" text in the descriptions to be untidy when browsing around the Mojaloop Project Github. 

I was thinking that by removing the "CORE COMPONENT" all caps text in the description, we could add github topics, such as `core-component`, which would make the repos look a little tidier.

Here's an example from my own forks:

![Screen Shot 2019-05-27 at 5.20.56 pm.png](https://images.zenhubusercontent.com/5cd963af3613073e20e46e60/c62d9205-997d-440c-a214-c9fcadacd9c9)

Like I said, nit-picky, but it might make it easier for newcomers to grok what each service is. It also has the added benefit of users are then able to click on the topic, and get directed to a page of all the related repos (eg. all core-related repos under mojaloop).

**Tasks**:
- [ ] For each repo that has CAPITAL TEXT at the start of the description, change the description to remove caps and replace with a github topic

**Acceptance Criteria**:
- [ ] All relevant repo descriptions and topics are updated

## **Pull Requests**:
- N/A

## **Follow-up**:
- N/A

**Dependencies**:
- N/A

## **Accountability**:
- Owner: @lewisdaly 
- QA/Review: TBC

**Comment by millerabel** [comment]
This seems super helpful, being able to see a page with all related repos. Thanks Lewis!

— Miller

On May 27, 2019, at 2:25 AM, Lewis Daly <notifications@github.com> wrote:

Goal:

As a project maintainer I want to clarify the projects in the github repository.

This is small and nitpicky, but I thought someone might value the suggestion. Close if you don't think it's worthwhile.

When first being onboarded to the project, I found the "CORE COMPONENT" and "CORE RELATED" text in the descriptions to be untidy when browsing around the Mojaloop Project Github.

I was thinking that by removing the "CORE COMPONENT" all caps text in the description, we could add github topics, such as core-component, which would make the repos look a little tidier.

Here's an example from my own forks:



Like I said, nit-picky, but it might make it easier for newcomers to grok what each service is. It also has the added benefit of users are then able to click on the topic, and get directed to a page of all the related repos (eg. all core-related repos under mojaloop).

Tasks:

 For each repo that has CAPITAL TEXT at the start of the description, change the description to remove caps and replace with a github topic
Acceptance Criteria:

 All relevant repo descriptions and topics are updated
Pull Requests:

N/A
Follow-up:

N/A
Dependencies:

N/A
Accountability:

Owner: @lewisdaly
QA/Review: TBC

**Comment by elnyry** [comment]
Yes, thanks @lewisdaly .. will follow-up on this

**Comment by lewisdaly** [comment]
Done for the major repos. I left a few of the old looking ones on the 3rd page.

Example of viewing all `core-related` repos:
https://github.com/search?q=topic%3Acore-component+org%3Amojaloop&type=Repositories
