### ISSUE TITLE
OpenAPI Swagger documentation missing details for account-lookup-service

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#794]
**Summary**:

OpenAPI Swagger documentation end-point: `http://account-lookup.local/documentation` is missing all examples, models and expected responses are not being shown as part of the documentation.

**Severity**:
Low

**Priority**:
Low

**Expected Behavior**
Each request should contain examples, models and expected responses are not being shown as part of the documentation.

**Steps to Reproduce**
  1.
  2.
  3.

**Specifications**
  - Component (if known):
  - Version: v6.3.x
  - Platform: n/a
  - Subsystem: n/a
  - Type of testing: n/a
  - Bug found/raised by: @mdebarros 

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by elnyry** [comment]
@mdebarros do you think this is still relevant? I can see the Swagger now on http://xxx-account-lookup.xxxx.xxxxx/documentation on the QA envt..

**Comment by lewisdaly** [comment]
@elnyry I think it is... if we ignore the format differences, we can see the central-ledger swagger prefills some header values and gives us a body example:

central-ledger:

<img width="1443" alt="Screen Shot 2019-09-23 at 4 49 37 pm" src="https://user-images.githubusercontent.com/1683980/65412708-5fdbb780-de22-11e9-9306-b73995d4d3fa.png">

and in the als:

<img width="1021" alt="Screen Shot 2019-09-23 at 4 49 51 pm" src="https://user-images.githubusercontent.com/1683980/65412746-7124c400-de22-11e9-9974-632145580cff.png">

**Comment by elnyry** [comment]
Thanks Lewis
