### ISSUE TITLE
FSPIOP-URI is not returned in POST /transfers response after participant is disabled

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#799]
**Summary**:
After a participant is disabled, when I try to send a transfer the resulting PUT response is not having FSPIOP-URI header

**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Expected Behavior**
FSPIOP-URI is supposed to be returned in the response for the transfer after the participant is disabled

**Steps to Reproduce**
  1. Disable the participant
curl -X PUT \
  http://test-central-ledger.mojaloop.live/participants/payerfsp \
  -H 'Authorization: Bearer {{BEARER_TOKEN}}' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: be802cb5-05d6-4045-8046-e31d7d837124' \
  -H 'cache-control: no-cache' \
  -d '{
  "isActive": false
}'
  2. Send a transfer
curl -X POST \
  http://test-ml-api-adapter.mojaloop.live/transfers \
  -H 'Accept: application/vnd.interoperability.transfers+json;version=1' \
  -H 'Content-Type: application/vnd.interoperability.transfers+json;version=1.0' \
  -H 'Date: Thu, 30 May 2019 00:28:05 GMT' \
  -H 'FSPIOP-Destination: payeefsp' \
  -H 'FSPIOP-HTTP-Method: POST' \
  -H 'FSPIOP-Signature: {"signature":"iU4GBXSfY8twZMj1zXX1CTe3LDO8Zvgui53icrriBxCUF_wltQmnjgWLWI4ZUEueVeOeTbDPBZazpBWYvBYpl5WJSUoXi14nVlangcsmu2vYkQUPmHtjOW-yb2ng6_aPfwd7oHLWrWzcsjTF-S4dW7GZRPHEbY_qCOhEwmmMOnE1FWF1OLvP0dM0r4y7FlnrZNhmuVIFhk_pMbEC44rtQmMFv4pm4EVGqmIm3eyXz0GkX8q_O1kGBoyIeV_P6RRcZ0nL6YUVMhPFSLJo6CIhL2zPm54Qdl2nVzDFWn_shVyV0Cl5vpcMJxJ--O_Zcbmpv6lxqDdygTC782Ob3CNMvg\",\"protectedHeader\":\"eyJhbGciOiJSUzI1NiIsIkZTUElPUC1VUkkiOiIvdHJhbnNmZXJzIiwiRlNQSU9QLUhUVFAtTWV0aG9kIjoiUE9TVCIsIkZTUElPUC1Tb3VyY2UiOiJPTUwiLCJGU1BJT1AtRGVzdGluYXRpb24iOiJNVE5Nb2JpbGVNb25leSIsIkRhdGUiOiIifQ"}' \
  -H 'FSPIOP-Source: payerfsp' \
  -H 'FSPIOP-URI: /transfers' \
  -H 'Postman-Token: ce23c205-ea54-4f2d-80cf-ef01d0b23101' \
  -H 'cache-control: no-cache' \
  -d '{
  "transferId": "d01e7705-2ffa-49ee-90f1-7c21aa52e9d9",
  "payerFsp": "payerfsp",
  "payeeFsp": "payeefsp",
  "amount": {
    "amount": "1",
    "currency": "USD"
  },
  "expiration": "2019-05-31T13:12:10.525Z",
  "ilpPacket": "AQAAAAAAAADIEHByaXZhdGUucGF5ZWVmc3CCAiB7InRyYW5zYWN0aW9uSWQiOiIyZGY3NzRlMi1mMWRiLTRmZjctYTQ5NS0yZGRkMzdhZjdjMmMiLCJxdW90ZUlkIjoiMDNhNjA1NTAtNmYyZi00NTU2LThlMDQtMDcwM2UzOWI4N2ZmIiwicGF5ZWUiOnsicGFydHlJZEluZm8iOnsicGFydHlJZFR5cGUiOiJNU0lTRE4iLCJwYXJ0eUlkZW50aWZpZXIiOiIyNzcxMzgwMzkxMyIsImZzcElkIjoicGF5ZWVmc3AifSwicGVyc29uYWxJbmZvIjp7ImNvbXBsZXhOYW1lIjp7fX19LCJwYXllciI6eyJwYXJ0eUlkSW5mbyI6eyJwYXJ0eUlkVHlwZSI6Ik1TSVNETiIsInBhcnR5SWRlbnRpZmllciI6IjI3NzEzODAzOTExIiwiZnNwSWQiOiJwYXllcmZzcCJ9LCJwZXJzb25hbEluZm8iOnsiY29tcGxleE5hbWUiOnt9fX0sImFtb3VudCI6eyJjdXJyZW5jeSI6IlVTRCIsImFtb3VudCI6IjIwMCJ9LCJ0cmFuc2FjdGlvblR5cGUiOnsic2NlbmFyaW8iOiJERVBPU0lUIiwic3ViU2NlbmFyaW8iOiJERVBPU0lUIiwiaW5pdGlhdG9yIjoiUEFZRVIiLCJpbml0aWF0b3JUeXBlIjoiQ09OU1VNRVIiLCJyZWZ1bmRJbmZvIjp7fX19",
  "condition": "HOr22-H3AfTDHrSkPjJtVPRdKouuMkDXTR4ejlQa8Ks"
}'
  3. Access the PUT response. The response headers are as below
headers:
x-forwarded-for:"70.106.205.67"
content-type:"application/vnd.interoperability.transfers+json;version=1.0"
date:"2019-05-31T13:11:10.000Z"
fspiop-source:"switch"
fspiop-destination:"payerfsp"
fspiop-http-method:"put"

**Specifications**
  - Component (if known): central ledger
  - Version: 
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by: Sridevi Miriyala

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by ggrg** [comment]
Hi @sri-miriyala, @elnyry, I wouldn't qualify this as bug, because it was desired output. Please, have a look at the comments section to issue https://github.com/mojaloop/project/issues/737. It is applicable to #799, because the error "Generic validation error: Participant dfsp2 is inactive" is sent from the switch to dfsp1 (payer). 

For your convenience I'm also attaching a screenshot:

![image](https://user-images.githubusercontent.com/20338055/58893208-55bd6e00-86f8-11e9-9522-fcf9d3aa331a.png)
