### ISSUE TITLE
Investigate potential Big Data platform vendors adherence to the defined requirements

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#80]
**Goal**:
Investigate potential Big Data platform vendors adherence to the defined requirements

**Tasks**:
- [ ] 

**Acceptance Criteria**:
- [ ] Define a list of candidates providing the capabilities as set out in the requirements
- [ ] Document findings and recommendations

**Dependencies**:
- [ ] #33

**Comment by HenkKodde** [comment]
Do we understand how the data is to be utilized. We need to insure the require Manage Information Service (MIS) information is available in a 'data warehouse' environment - normally a database of some sort. Most BI tools set can then "plug and play" to provide the information required - providing we understand and provide the appropriate data to complement the requirements for the "Big Data" requirements and expectation.

**Comment by elnyry** [comment]
Based on discussion with Bryan, de-scoping this for current work and moving it to PI-2.
