### ISSUE TITLE
Mojaloop chart does not support ingress 0.22.* or later 

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#802]
**Summary**:
Mojaloop chart does not support ingress 0.22.* or later due to the rewrite rules no longer being backwards compatible.

See the following issue for more information: https://github.com/mojaloop/helm/issues/196

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
- [ ] Ingress's should be configured with the new annotations. 
- [ ] Value files to be updated to include both annotations but include comments for users to understand why and where one would choose the specific annotations depending on the version of ingress being used.
- [x] Add an FAQ item to describe the issue and fix dependant on using which version of ingress (e.g. later than or including v0.22, and version earlier than 0.22)

**Steps to Reproduce**

Deploy an existing version (v6.3.1 or earlier) of Helm chart to a K8s environment that contains Nginx Ingress controller with version 0.22 or later.

**Specifications**
  - Component (if known):
  - Version: v6.3.1 or earlier
  - Platform: Helm
  - Subsystem:
  - Type of testing: manual
  - Bug found/raised by: @mdebarros (on behalf of community)

**Notes**:

- Severity when opened: Medium
- Priority when opened: Medium

**Comment by mdebarros** [comment]
Pull request for FAQ --> https://github.com/mojaloop/documentation/pull/69

**Comment by elnyry-sam-k** [comment]
@mdebarros - can you please review if we close this now?

**Comment by mdebarros** [comment]
Closing this as it's no longer an issue.

The newer versions of the NGINX Ingress Controllers handle this more elegantly.

**Comment by elnyry-sam-k** [comment]
Thanks @mdebarros
