### ISSUE TITLE
Mojaloop Gitbook loads mixed http/https content

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#809]
**Summary**:
I noticed when browsing the documentation that I was getting browser warnings about mixed http/https content.

One of the main culprits seems to be the mojaloop logo: `http://mojaloop.io/images/logo.png`

**Severity**:
Low

**Priority**:
Low

**Expected Behavior**
All content on mojaloop.io should load https content **only**

**Steps to Reproduce**
  1. Navigate to https://mojaloop.io/documentation/
  2. Open the console and see the warning:
> Loading mixed (insecure) display content “http://mojaloop.io/images/logo.png” on a secure page

**Specifications**
  - Component (if known): mojaloop/documentation
  - Platform: Firefox
  - Bug found/raised by: @lewisdaly 

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by elnyry** [comment]
Thanks Lewis for this.

**Comment by kjw000** [comment]
Agree - thanks.  I dont get this error for some reason.

**Comment by lewisdaly** [comment]
You might also see a warning at the top like this:

<img width="383" alt="Screen Shot 2019-06-11 at 9 50 56 pm" src="https://user-images.githubusercontent.com/1683980/59277945-a8b49980-8c93-11e9-98b3-a66d4c8a4387.png">

**Comment by lewisdaly** [comment]
Fixed!
