### ISSUE TITLE
GET /parties - no JWS headers returned at payeefsp

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#810]
**Summary**:
After the ALS implementation, In GET /parties call, Switch not forwarding the JWS headers to payeefsp.

**Severity**:
(High)

**Priority**:
(medium)
**Expected Behavior**

When sending GET /parties call from payerfsp, switch is supposed to forward the JWS headers to payeefsp.  
**Steps to Reproduce**
  1.  Register a party in payeefsp
  2. Send GET /parties request with all valid params, including JWS headers from payerfsp
  3. In the logs at payeefsp, I see JWS headers are missing.

**Specifications**
  - Component (if known): ALS
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing: Contract / API
  - Bug found/raised by: SRI

**Comment by elnyry** [comment]
@sri-miriyala can you please add the specific headers and describe expected behavior explicitly?

**Comment by sri-miriyala** [comment]
Below are the headers that are being sent on the request:
curl -X GET \
  http://dev1-account-lookup.mojaloop.live/parties/MSISDN/27713803912 \
  -H 'Accept: application/vnd.interoperability.parties+json' \
  -H 'Content-Type: application/vnd.interoperability.parties+json;version=1.0' \
  -H 'Date: Sat, 20 Jul 2019 14:24:30 GMT' \
  -H 'FSPIOP-HTTP-Method: GET' \
  -H 'FSPIOP-Signature: {"signature":"iU4GBXSfY8twZMj1zXX1CTe3LDO8Zvgui53icrriBxCUF_wltQmnjgWLWI4ZUEueVeOeTbDPBZazpBWYvBYpl5WJSUoXi14nVlangcsmu2vYkQUPmHtjOW-yb2ng6_aPfwd7oHLWrWzcsjTF-S4dW7GZRPHEbY_qCOhEwmmMOnE1FWF1OLvP0dM0r4y7FlnrZNhmuVIFhk_pMbEC44rtQmMFv4pm4EVGqmIm3eyXz0GkX8q_O1kGBoyIeV_P6RRcZ0nL6YUVMhPFSLJo6CIhL2zPm54Qdl2nVzDFWn_shVyV0Cl5vpcMJxJ--O_Zcbmpv6lxqDdygTC782Ob3CNMvg\",\"protectedHeader\":\"eyJhbGciOiJSUzI1NiIsIkZTUElPUC1VUkkiOiIvdHJhbnNmZXJzIiwiRlNQSU9QLUhUVFAtTWV0aG9kIjoiUE9TVCIsIkZTUElPUC1Tb3VyY2UiOiJPTUwiLCJGU1BJT1AtRGVzdGluYXRpb24iOiJNVE5Nb2JpbGVNb25leSIsIkRhdGUiOiIifQ"}' \
  -H 'FSPIOP-Source: payerfsp' \
  -H 'FSPIOP-URI: /parties/MSISDN/27713803912' \
  -H 'Postman-Token: 8997ac7b-21d7-4b37-920a-3dcca08ab02d' \
  -H 'cache-control: no-cache'

**Below are the headers that are received at the payeefsp side:**
<img width="892" alt="Screen Shot 2019-07-20 at 10 28 28 AM" src="https://user-images.githubusercontent.com/38143240/61579883-324c5800-aad9-11e9-9f40-11ed9e712f9f.png">

As you can notice in the output, Accept, fspiop-method, fspiop-uri headers are not forwarded by ALS service to payeefsp

**Comment by elnyry** [comment]
To be addressed as part of #902.. @rmothilal please confirm. Thank you..

**Comment by elnyry** [comment]
@rmothilal just FYI, this is still reproducible on the latest DEV2 envt (v7.3.1-snapshot of ALS)

**Comment by elnyry** [comment]
Fixed now.. Please re-open if there's a repro. (Fixed in helm version v7.4.0, ALS 7.4.0-snapshot)

![image](https://user-images.githubusercontent.com/10507686/63460468-340c9100-c474-11e9-9e93-a3f2b065410b.png)
