### ISSUE TITLE
central-ledger docker compose kafka container not accessible to host machine 

### ISSUE THREAD

**Issue by ndonnan** [mojaloop/project#841]
**Summary**:
When following the central-ledger onboarding instructions under section 3. Running Locally (with dependencies inside of docker) it says to run the following docker compose command:

`docker-compose up ml-api-adapter mysql kafka mockserver temp_curl`

This results in the kafka container not being accessible from the host machine and when running central-ledger locally it is not able to connect to kafka.

![image](https://user-images.githubusercontent.com/4749176/60604257-8f48ce00-9db7-11e9-9c3a-1757f77d7e90.png)
 
Starting kafka using the following script does not have these issues and the central-ledger doesn't have any errors:

`sh ./test/util/scripts/restart.sh`

**Severity**:
Low

**Priority**:
Low

**Expected Behavior**
The central-ledger component starts on the local host without kafka host resolution errors.

**Steps to Reproduce**
  Run the central-ledger onboarding steps to run locally up to
`npm run start`

**Specifications**
  - Component (if known): central-ledger
  - Version: latest
  - Platform: MacOs
  - Type of testing: manual
  - Bug found/raised by: Neal

**Notes**:

- Severity when opened: Low
- Priority when opened: Low

**Comment by lewisdaly** [comment]
Yeah this was a problem I had as well when setting up the `docker-compose` files, but I don't actually recall how I resolved the issue...

**Comment by lewisdaly** [comment]
[This](https://rmoff.net/2018/08/02/kafka-listeners-explained/) guide looks like it might help us resolve the issue. It looks like we might need to provide some extra config that the johnnypark/kafka-zookeeper docker image doesn't let us set via environment variables

**Comment by lewisdaly** [comment]
@ndonnan I have a PR to fix this in central-ledger.

**Comment by ndonnan** [comment]
@lewisdaly it looks like central ledger is now able to connect on my machine with the changes in your branch
