### ISSUE TITLE
central-ledger onboarding postman collection 'Mojaloop v0.1 draft' is no longer in the postman repo

### ISSUE THREAD

**Issue by ndonnan** [mojaloop/project#842]
**Summary**:
The onboarding documentation for the central-ledger says to test with the postman collection 'Mojaloop v0.1 draft' which is no longer in the postman repo.

**Severity**:
Low

**Priority**:
Low

**Expected Behavior**
The onboarding document references a postman collection in the repo.

**Steps to Reproduce**
Follow section '5.1 Testing the central-ledger API with Postman' in the [Onboarding](https://github.com/mojaloop/central-ledger/blob/master/Onboarding.md) document

**Specifications**
  - Component (if known): central-ledger
  - Version: current
  - Platform: all
  - Type of testing: manual
  - Bug found/raised by: Neal

**Notes**:
The old postman collection being referred to should be resurrected and renamed to something like 'Mojaloop local dev'. Any missing requests should be added to the collection and existing calls updated to work with the current API.

- Severity when opened: Low
- Priority when opened: Low

**Comment by elnyry** [comment]
This should now be fixed in #941 , please re-open if you think otherwise.
