### ISSUE TITLE
ml-api-adapter metadata endpoint returns a 500 internal server error

### ISSUE THREAD

**Issue by ndonnan** [mojaloop/project#845]
**Summary**:
ml-api-adapter metadata endpoint returns a 500 internal server error

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
A list or available api endpoints is return with a 200 response:
{
  "directory": "http://ml-api-adapter",
  "urls": {
    "health": "http://ml-api-adapter/health",
    "metrics": "http://ml-api-adapter/metrics",
    "transfer_getById": "http://ml-api-adapter/transfers/:id",
    "transfers": "http://ml-api-adapter/transfers",
    "transfer_fulfilment": "http://ml-api-adapter/transfers/:id",
    "transfer_abort": "http://ml-api-adapter/transfers/:id/error"
  }
}

**Steps to Reproduce**
  1. Start up ml-api-adapter locally
  2. curl http://localhost:3000/
  3. Returns 500: {"id":"InternalServerError","message":"An internal server error occurred"}

**Specifications**
  - Component (if known): ml-api-adapter
  - Version: 6.4.0
  - Platform: all
  - Subsystem:
  - Type of testing: manual
  - Bug found/raised by: Neal

**Notes**:

- Severity when opened: Medium
- Priority when opened: Medium

**Comment by mdebarros** [comment]
I am confused as to what some of these metadata end-points are used for. Blocking bug for now until we can discuss the issue @ndonnan.

**Comment by ndonnan** [comment]
This is no longer needed as the endpoint should be removed
