### ISSUE TITLE
New Health Checks break the integration and functional runners of many CI/CD Pipelines

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#855]
**Summary**:
With the new health checks, we consider a service **healthy** when the necessary sub-services it depends upon (e.g. kafka, database) is also up and running.

The Integration and Functional test runners currently use the health checks for multiple services to test for *liveness*, before proceeding to run the tests. Since these environments don't always spin up and configure the necessary sub-services, the health checks will always return a `502` Gateway Error.

There are 2 options for how we fix this, an easy option and a hard:
1. **Easy** - Make sure the liveness check in the runners receives a `200` or `502` (but not any other response such as `404` or `500`)
2. **Hard** - Add the other necessary services to make the health checks return a `200`. This may require some mocking, be fiddly, and be somewhat counter to the point of the tests in the first place.

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
- The integration tests should pass for the following services:
  - `central-settlement`
  - `central-ledger`
  - `central-directory`

- The functional tests should pass for the following services:
  - `ml-api-adapter`
  - `central-ledger`
  - `central-directory`

**Steps to Reproduce**
  1. Run the circleCI builds on master for the above repositories
  2. Observe that the integration and functional runner hang indefinitely

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by:

**Notes**:

- Severity when opened: Medium
- Priority when opened: Medium

**Comment by lewisdaly** [comment]
We need to add the following snippet to the functional and integration runners, to assess the liveness of the services instead of the healthyness:
```
#!/usr/bin/env bash

DOCKER_NETWORK="integration-test-net"


fcurl() {
  # curl $@
  docker run -i \
    --network $DOCKER_NETWORK \
    --link simulator-int \
    --entrypoint curl \
    "jlekie/curl:latest" \
    --silent --head --fail -I\
    "$@"
}

# Make sure the service is alive, not necessarily healthy
fcurl_alive() {
  RESPONSE_CODE=$(fcurl "$@" | grep HTTP/1.1 | awk {'print $2'})
  echo $RESPONSE_CODE

  case ${RESPONSE_CODE} in
    200)
     echo 'Is alive'
      ;;
    502)
      echo 'Is alive'
      ;;
    *)
      echo 'Is not alive!'
      exit 1
      ;;
  esac
}


fcurl_alive "http://simulator-int:8444/healtsddh"

echo "result is: $?"
```

**Comment by lewisdaly** [comment]
Considering that all of the health checks are merged in now, and we haven't seen many integration or functional test failures that haven't already been fixed, I think this is resolved.

**Comment by elnyry** [comment]
@lewisdaly in that case, can this be closed ?

**Comment by lewisdaly** [comment]
@elnyry Sure. We can always re-open or make a new issue if we see this problem again.
