### ISSUE TITLE
"Here" link in the documentation /versioning.html page is broken

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#856]
**Summary**:
In the [versioning page](https://mojaloop.io/documentation/contributors-guide/standards/versioning.html#current-version), the "here" link to the current version information is broken. It currently redirects to `https://mojaloop.io/documentation/contributors-guide/mojaloop-deployment/current-versions.md`, which gives us a 404.

We need to fix this link. I did some digging around, but I can't find where exactly this page should link to.

**Severity**:
Low

**Priority**:
Low

**Expected Behavior**

**Steps to Reproduce**
  1. Navigate to the [linked page](https://mojaloop.io/documentation/contributors-guide/standards/versioning.html#current-version)
  2. Click on the "here" link
  3. Observe a nasty 404 error

**Specifications**
  - Component (if known): mojaloop/documentation
  - Version: v7.0.0
  - Platform: N/A
  - Subsystem: N/A
  - Type of testing: N/A
  - Bug found/raised by: @lewisdaly 

**Notes**:

- Severity when opened: Low
- Priority when opened: Low

**Comment by elnyry** [comment]
Should be fixed with this, (but will have to be released) - https://github.com/mojaloop/documentation/pull/108#pullrequestreview-282331270
