### ISSUE TITLE
Map User Stories of Potential lab users

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#858]
- Define user profiles for different lab users
- Outline the needs each of these users have, and how a lab may or may not serve these needs
- Write out user stories for these profiles and prioritize

**Comment by kjw000** [comment]
moving to 7.2

**Comment by lewisdaly** [comment]
Copying in notes from the Mid-PI Review:

## Users

We divide users in 2 camps: Primary users and Secondary users. These classifications are up for debate.

### Primary Users
1. DFSPs needing to integrate with Mojaloop: (shorthand: Implementing DFSP)
2. Organisations/Individuals wishing to learn about Mojaloop and wanting to build and test functionality or use cases as a DFSP (shorthand: Evaluating DFSP)
3. Organisations/Individuals wishing to learn about Mojaloop and wanting to build and test functionality or use cases as a Hub Operator (shorthand: Evaluating Hub Operators)
4. Regulators, Organisations or Individuals wishing to understand and evaluate Mojaloop and how it might impact their existing service (shorthand: General Evaluators)


### Secondary Users
5. Systems Integrators wishing to offer Mojaloop as a Service or pieces of Mojaloop integration as a Service (Systems integrator)
6. Individual Contributors (including bug bounty hunters?) (Individual Contributor)
7. Fintechs operating on top of or who will operate on top of a mojaloop-enabled switch (Mojaloop-powered fintech)

## Use Cases

__a.__ Test a Mojaloop compatible DFSP implementation  
__b.__ Validate assumptions about Mojaloop  
__c.__ View and use a reference implementation  
__d.__ Learn about Mojaloop internals  
__e.__ Learn about Mojaloop-enabled switches and associated use cases (technology)  
__f.__ Assess how Mojaloop will change fintech business landscape  


|  __Usecase:__                   | a. Test DFSP Impl | b. Validate Assumptions | c. Reference Impl | d. Learn Internals | e. Learn about Tech | f. Evaluate Business Cases  |
| :------------------------------- | :---: | :---: | :---: | :---: | :---: | :---: |
| __User:__                        |       |       |       |       |       |       |    
| __1. Implementing DFSP__         |   X   |       |   X   |       |       |       |
| __2. Evalutating DFSP__          |       |   X   |   X   |       |   X   |   X   |
| __3. Evaluating Hub Operator__   |       |       |   X   |       |   X   |   X   |
| __4. General Evaluator__         |       |       |       |       |   X   |   X   |
| __5. Systems Integrator__        |   X   |   X   |   X   |   X   |       |       |
| __6. Individual Contributor__    |       |   X   |   X   |   X   |       |       |
| __7. Mojaloop-powered fintech__  |       |   X   |       |       |   X   |   X   |

**Comment by lewisdaly** [comment]
As discussed in the Mid-PI review, I'm going to spend some more time diving a little closer into some of these use cases (will be taken care of in following ticket)
