### ISSUE TITLE
Establish needs and use cases for the Lab

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#859]
Starting from the user stories that were written in 7.1, list the potential needs and use cases for the lab.

Example use cases could be:
- managed lab hosted by the Mojaloop entity, shared with a number of users
- self-hosted lab for new fintechs t

**Comment by lewisdaly** [comment]
As per the Mid-PI Review discussion, dive deeper into the use cases we already have found in the user/use case matrix

**Comment by kjw000** [comment]
@lewisdaly - please add this to the sprint that it will be addressed.

**Comment by lewisdaly** [comment]
Updated to sprint 7.4 - sorry was planning to do this in 7.3, but things got away from me.

**Comment by lewisdaly** [comment]
This is currently being tackled in the slack channel, as well as in the working document on my fork [here](https://github.com/vessels-tech/documentation/blob/feature/lab-discussion/discussions/workbench.md).

>Note: this won't be final resting place of this document, I just wanted to keep it in source control for now.

**Comment by kjw000** [comment]
moving to 7.5 to finish up.
