### ISSUE TITLE
Determine underlying cause why Settlements Component fails (with no new changes) after running successfully

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#865]
**Summary**:
In order to get an all-clear run on the regression test:
(https://raw.githubusercontent.com/mojaloop/postman/master/Golden_Path.postman_collection.json)
I had to redeploy a few pods.

Amongst them were the centralsettlement, account-lookup-service, ml-api-adapter-service, quotingservice. This immediately resolved the test failures that occurred on Settlements inside the Golden Path test pack. There was then a few take-on or setup scripts that needed to be executed (like the oracle registration and adding FSPs to the simulator etc) to get a few "new" errors resolved and after that, we had a clean run.

Unfortunately, getting to this stage, re-deploying a few pods, hides the underlying issue as the logs were cleared as a result of that. After discussions, it is thought to be a possible Database that became inoperational but we will have to monitor the situation very closely and resolve the failing regression test AFTER the log files were scrutinized.

**Severity**:
(Medium)

**Priority**:
(Medium)

**Expected Behavior**
When Settlements start failing without any new functional deployment or changes to the regression tests, FIRST determine the issue in settlements before fixing the regression run.

**Steps to Reproduce**
  1. Wait for Regression to fail (with no changes deployed) in the Settlements Component
  2. Investigate underlying cause
  3. Create a new Bug to fix the cause, if determined.

**Specifications**
  - Component (if known): Dev-1 Mojaloop deployment
  - Type of testing: Regression
  - Bug found/raised by: [ @NicoDuvenage ]

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by elnyry-sam-k** [comment]
No-repro in a while, please re-open if there's a repro
