### ISSUE TITLE
Database may lose precision on currencies with more than 2 decimals

### ISSUE THREAD

**Issue by ramirogm** [mojaloop/project#867]
**Summary**:
Database may lose precision on currencies with more than 2 decimals

doesn’t the database type loses precision if a transfer with more decimals comes in like 1.4409 CLF?

https://github.com/mojaloop/documentation/blob/master/mojaloop-technical-overview/central-ledger/assets/database/central-ledger-ddl-MySQLWorkbench.sql#L623

```
CREATE TABLE `transfer` (
  `transferId` varchar(36) NOT NULL,
  `amount` decimal(18,2) NOT NULL,
  `currencyId` varchar(3) NOT NULL,
  `ilpCondition` varchar(256) NOT NULL,
  `expirationDate` datetime NOT NULL,
  `createdDate` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`transferId`),
  KEY `transfer_currencyid_index` (`currencyId`),
  CONSTRAINT `transfer_currencyid_foreign` FOREIGN KEY (`currencyId`) REFERENCES `currency` (`currencyid`),
  CONSTRAINT `transfer_transferid_foreign` FOREIGN KEY (`transferId`) REFERENCES `transferDuplicateCheck` (`transferid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

API Interfaces for both Quoting-Service and ML-API-Adapter will need to be check to ensure that 4 decimals are supported.

**Severity**: High

**Priority**: High

**Expected Behavior**

**Steps to Reproduce**
  1 I looked at the schema definition. Haven't tested
  2.
  3.

**Specifications**
  - Component (if known):
  - Version: All versions till helm v7.1.0 
  - Platform: central-services
  - Subsystem: Data Model (DB)
  - Type of testing:
  - Bug found/raised by: @ramirogm 

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by kjw000** [comment]
Please ensure everyone reviews the L1P/Mojaloop standard on how we agreed to handle decimals from the start of this project.  https://github.com/mojaloop/documentation/blob/master/discussions/decimal.md

We need to have a DA discussion on our proposal going forward; we should not change the standard for how we store data in the transaction file store but we most likely will need a new format once data is extracted and transformed to another storage solution for analysis/query purposes.

**Comment by elnyry** [comment]
@ramirogm the issue reported here is now fixed here: https://github.com/mojaloop/project/issues/949

However, the follow-up issue that came out of this can be tracked here: #952
