### ISSUE TITLE
MySQL Pods not starting on helm release from scratch

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#918]
### Summary:
Version `6.3.1` of the Helm release fails to bring up the central-ledger and account-lookup-service mysql pods. This breaks all new deployments of the existing helm charts.

This is caused by the `metrics` container that is launched along side the `mysql` container as a part of the `percona-xtradb-cluster` helm chart. The metrics container is launched from the `prom/mysqld-exporter` docker image, and doesn't specify a tag. 

2 weeks ago, there was a new release of `prom/mysqld-exporter`, which is broken for the current configuration of the `percona-xtradb-cluster` chart.

### Workarounds:

There are 2 possible workarounds, depending on the user's use case.

*Option 1.* If the user doesn't plan on using metrics reporting, they can disable `metricsExporter` in the associated `values.yaml` files:
```yaml
...
## When set to true will create sidecar for `prom/mysqld-exporter`
## metrics exporting
metricsExporter:
    enabled: false
...
```

*Option 2.* Install the helm chart as normal, and log into the kubernetes dashboard, and manually specify the `v0.11.0` tag of the metrics docker container. This needs to be done for the `central-ledger` and `account-lookup-service` stateful sets.

---

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
`central-ledger` and `account-lookup-service` stateful sets should start up normally.

**Steps to Reproduce**
  1. Start from a kubernetes environment with helm installed
  2. Install the Mojaloop helm chart: `helm install --namespace=mojaloop --name=dev --repo=http://mojaloop.io/helm/repo mojaloop`
  3. Observe that the mysql pods do not start

**Specifications**
  - Component (if known): v6.3.1
  - Version:
  - Platform: helm
  - Subsystem:
  - Type of testing:
  - Bug found/raised by: @lewisdaly 

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by lewisdaly** [comment]
There is a PR in the works for the required helm chart changes (refer to #919). Until then, disabling the `metricsExporter` is our workaround.

**Comment by mdebarros** [comment]
The issue has been resolved by this PR for the Helm charts --> https://github.com/mojaloop/helm/pull/200

This includes the fixes for the percona-xtradb-cluster helm chart to allow the metricsexporter tag to be set as part of the deployment as a fix for `Option 1` as described in this issue.

**Comment by lewisdaly** [comment]
Can verify that version `7.4.0` of the helm charts fixes this issue.
