### ISSUE TITLE
Not able to specify a docker tag for `prom/mysqld-exporter` in the Helm charts

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/project#919]
**Summary**:
This issue is to track the external changes required to fix #918

The percona-xtradb-cluster [helm chart](https://github.com/helm/charts/blob/06c9b6e464818578d3841d030031cc4987ae181c/stable/percona-xtradb-cluster/templates/statefulset.yaml#L137) does not specify a version for the `prom/mysqld-exporter` sidecar container, which caused

**Tasks**:
- [x] Open a PR in the helm/charts repo that will allow us to specify a tag for the `prom/mysqld-exporter` docker image

**Severity**:
High

**Priority**:
Medium

**Expected Behavior**
We should be able to dynamically configure the docker image tag of the `prom/mysqld-exporter` sidecar container so that future releases don't break existing deployments/helm charts.

**Specifications**
  - Component (if known): percona-xtradb-cluster
  - Version: `0.6.4`
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by: @lewisdaly

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by lewisdaly** [comment]
Pull request for helm/charts repo: https://github.com/helm/charts/pull/16253

**Comment by lewisdaly** [comment]
The above pull request has been merged into the `helm/charts` repo, so now it's just a case of upgrading to version `1.0.1` of the chart.

**Comment by mdebarros** [comment]
The issue has been resolved by this PR for the Helm charts --> https://github.com/mojaloop/helm/pull/200

This includes the fixes for the percona-xtradb-cluster helm chart to allow the metricsExporter tag to be set as part of the deployment.
