### ISSUE TITLE
Regression Testing - Token of Environment Variable file for Postman changes which causes "Access Denied" and failure of run

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#932]
**Summary**:
It seems like every week (7 days) the token of the environment variables file for the Postman Collections, changes. This file is located in a private repository "deploy-config" in the mojaloop org, under "postmanEnvironments" directory. The current file in use is "Mojaloop-DEV1.postman_environment.json".

This causes the cronJob activated Regression run to fail when it attempts to read the variables from that file.

The manual fix has always been to update the passed-in parameter (2nd parameter is the URL to the environment file to use for a run) with the new token obtained from going into the "deploy-config" repo and getting a "raw" version of the file in question to see the new token for that file.

**Severity**:
Low

**Priority**:
Low

**Expected Behavior**
We need an automated way of retrieving the current token and injecting that into the parameter list for each run....or we need to be able to turn off the token being changed by GitHub.

**Steps to Reproduce**
  1. Check the results of the Regression run (on the Slack channel in "mojaloop/announcements" every day. You will notice after a few runs that the failure report says something in the line of "Access Denied"

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing:
  - Bug found/raised by:

**Notes**:

- Severity when opened: Medium
- Priority when opened: Medium

**Comment by lewisdaly** [comment]
@NicoDuvenage I think one approach would be to create a [Deploy Key](https://developer.github.com/v3/guides/managing-deploy-keys/#deploy-keys) on github for the `mojaloop/deploy-config` repo which we store on the regression test ec2 server.

With a deploy key, we can just clone the repo once, then pull master (or whatever branch we need) before running the test to make sure the `Mojaloop-DEV1.postman_environment.json` file is up to date.

newman then just needs to change from loading a remote file to referring to wherever the repo is cloned locally.
