### ISSUE TITLE
Quotes issue with checking active / inactive status of a participant

### ISSUE THREAD

**Issue by elnyry** [mojaloop/project#933]
**Summary**:
The Quotes service seems to have an issue with checking active / inactive status of a participant. This is causing the quotes to pass-through some times when participant is inactive and vice-versa.

**Severity**:
Medium

**Priority**:
Medium

**Expected Behavior**
1. Quotes service should fail with a error code  that participant wasn't found (2001) when a participant is Inactive. (Likewise when its active, the quotes POST requests should go through without issue)

**Steps to Reproduce**
  1. On a given Mojaloop deployment, de-activate a participant and re-activate it. After de-activating it, run a POST /quotes request and its not getting de-activated.
  2.
  3.

**Specifications**
  - Component (if known): central services
  - Version: v7.3.1-snapshot 
  - Platform: AWS
  - Subsystem: quoting-service
  - Type of testing: Functional, regression
  - Bug found/raised by: @elnyry @mdebarros 

PRs:
- [x] https://github.com/mojaloop/quoting-service/pull/16
- [x] https://github.com/mojaloop/quoting-service/pull/17

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by mdebarros** [comment]
PR for fix: https://github.com/mojaloop/quoting-service/pull/12

The issue was Quoting-Service implemented a cache layer over the DB for most "GET" or query operations. I commented out the `getParticipant` operation and added an appropriate comment.
