### ISSUE TITLE
Environmental Variables of type Boolean are represented as a String by the Config object

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#934]
**Summary**:
Environmental Variables are not being set by the Config object as a Boolean type, and instead, are set a string value.

**Severity**:
Low

**Priority**:
Low

**Expected Behavior**
Declare an Environmental Variable for any Boolean Configuration (e.g. `export CLEDG_SIDECAR_DISABLED=true`) should be represented as a Boolean type.

Fix:
1. Include the following import on the config.js:
`require('parse-strings-in-object')` <-- ref: https://www.npmjs.com/package/parse-strings-in-object#example-in-rc-config

Example implemented in the Event SDK:
`const RC = require('parse-strings-in-object')(require('rc')('EVENT_SDK', require('../../config/default.json')))`

**Steps to Reproduce**
  1. Declare an Environmental Variable for any Boolean Configuration (e.g. `export CLEDG_SIDECAR_DISABLED=true`)
  2. This will be correctly assigned to the Config object, but it will be a string instead of a Boolean

**Specifications**
  - Component (if known): Central-Ledger, ML-API-Adapter, Batch-API-Adapter, Central-Settlements, Account-lookup-service, etc
  - Version: all
  - Platform: n/a
  - Subsystem: n/a
  - Type of testing: manual
  - Bug found/raised by: @mdebarros 

## **Pull Requests**:
- [x] https://github.com/mojaloop/account-lookup-service/pull/134
- [x] https://github.com/mojaloop/ml-api-adapter/pull/251
- [x] https://github.com/mojaloop/bulk-api-adapter/pull/13
- [x] https://github.com/mojaloop/central-settlement/pull/176
- [x] https://github.com/mojaloop/transaction-requests-service/pull/8
- [x] https://github.com/mojaloop/quoting-service/pull/81 [@gibaros, @ggrg]

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by gibaros** [comment]
Fixes have been applied and merged to account-lookup-service, ml-api-adapter, bulk-api-adapter, central-settlement, transaction-requests-service and quoting-service.
