### ISSUE TITLE
Switch is not stripping off Accept Header in PUT calls, when passing to Payer FSP

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#935]
**Summary**:
As per the API spec, the PUT calls from payeefsp should not send any Accept Header. If the Accept Header is sent, it is to be strip off by the Switch and fwd the msg to payer FSP.

**Severity**:
High
**Priority**:
HIgh
**Expected Behavior**
1. Send a valid POST /quotes request to noresponsepayeefsp
2. Respond with 400 in light of the below screenshot from the API Spec which explicitly calls out Accept header shouldn't be there. ~Send PUT /quotes from noresponsepayeefsp to payerfsp with Accept Header, which should not be sent as per API spec~
3. Switch is supposed to block the response from Payee FSP (noresponsepayeefsp) with 400- bad request ~or strip off the Accept header from payee FSP and forward the response to payer FSP.~

**Steps to Reproduce**
 1. Sent a valid POST /quotes request to noresponsepayeefsp
2. Sent PUT /quotes from noresponsepayeefsp to payerfsp with Accept Header
3. Switch is accepting the response from Payee FSP (noresponsepayeefsp) without any issues and forwarding to payer FSP.

Screenshot from API Spec:
<img width="784" alt="Screen Shot 2019-08-14 at 2 29 24 PM" src="https://user-images.githubusercontent.com/38143240/63174438-f50fb300-c00f-11e9-994e-42e84dfcc902.png">

Response:

<img width="959" alt="Screen Shot 2019-08-15 at 12 10 40 PM" src="https://user-images.githubusercontent.com/38143240/63174381-d6112100-c00f-11e9-9dad-51e0b62ff7cd.png">

**Specifications**
  - Component (if known): all PUT and PUT /error
  - Version: 
  - Platform: MAC OS
  - Subsystem: Mojaloop
  - Type of testing: Integration
  - Bug found/raised by: Sri

**Notes**:

- Severity when opened:
- Priority when opened:

## Pull Requests
- [x] https://github.com/mojaloop/simulator/pull/51
- [x] https://github.com/mojaloop/quoting-service/pull/22

**Comment by elnyry** [comment]
@sri-miriyala can you please confirm if this is for quotes **only** or if it exists for ALS, transfers, transaction requests?

**Comment by elnyry** [comment]
@sri-miriyala @oderayi , We now have this released with simulator [v7.5.0](https://github.com/mojaloop/simulator/releases/tag/v7.5.0) and quoting-service [v7.4.2-shapsnot](https://github.com/mojaloop/quoting-service/releases/tag/v7.4.2-snapshot), which I think we should be able to see deployed within a day if not today..
