### ISSUE TITLE
Settlements API error format is not as per Spec

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/project#956]
**Summary**:
When I query some of the negative cases from Settlements, I found the error msg format is incorrect when compared to API spec.
**Severity**:
(Low, Medium, High)

**Priority**:
(Critical, Medium, Low)

**Expected Behavior**
Error msg format shd match API spec

**Steps to Reproduce**
  1. Call the API 'GET /settlement windows with non existent ID '0'
  2. Check the error msg in the body of the response

**Included with the bugfix**:
- [x] mojaloop/simulator dependencies upgrade [@ggrg]
- [x] fixing the reported issue on all GET/PUT/POST endpoints [@ggrg]
- [x] implementation of error handling plugin to server setup [@ggrg]
- [x] multiple replace of "Internal Server Error" with "Validation Error" [@ggrg]
- [x] unit tests fixes related to the above changes [@ggrg]
- [x] mojaloop/central-settlement dependencies upgrade [@ggrg]
- [x] addition of `npm-check-updates` pre-commit hook [@ggrg]
- [x] improve tests coverage [@ggrg]
- [x] add [7.5.0](https://github.com/mojaloop/central-settlement/releases/tag/v7.5.0) release [@ggrg]

**Pull Requests**:
- [x] https://github.com/mojaloop/simulator/pull/58
- [x] https://github.com/mojaloop/central-settlement/pull/110

**Specifications**
  - Component (if known): Central Settlements
  - Version: 
  - Platform: Mac OS
  - Subsystem: Mojaloop
  - Type of testing: API
  - Bug found/raised by: Sri

**Notes**:
<img width="1227" alt="Screen Shot 2019-08-30 at 4 49 42 AM" src="https://user-images.githubusercontent.com/38143240/64008124-715fc700-cae3-11e9-8944-16e68d9f9240.png">

- Severity when opened: Med
- Priority when opened: Med

**Comment by elnyry** [comment]
Thanks @sri-miriyala .. We'll look into this.

First we need to see if this was a regression because of the recent changes, as the error format was fixed a while ago as part of this issue - https://github.com/mojaloop/project/issues/501 (Thanks Sri for pointing that out)

**Comment by ggrg** [comment]
Thanks @sri-miriyala - the reported bug has been confirmed. Currently I get `http code 500 Internal Server Error` with response: 
```
{
    "statusCode": 500,
    "error": "Internal Server Error",
    "message": "An internal server error occurred"
}
```
Busy fixing it...

**Comment by elnyry** [comment]
Tests to be added to Golden path postman collection via this story - https://github.com/mojaloop/project/issues/987 (It will then be part of the regular regression testing)
