### ISSUE TITLE
ErrorHandling plugin needs to use the joi validation error message instead of label when using hapi-openapi

### ISSUE THREAD

**Issue by ndonnan** [mojaloop/project#959]
**Summary**:
ErrorHandling plugin needs to use the joi validation error message instead of label when using hapi-openapi

**Severity**:
Low

**Priority**:
Low

**Expected Behavior**
The errorInformation response should have a descriptive error message when using the hapi-openapi plugin

**Steps to Reproduce**
  1. Use the hapi-openapi plugin.
  2. Submit a http request with a validation error producing a Joi error.
  3. The error handler plugin should check for the presence of the hapi-openapi plugin and use the message instead of label field from the Joi error

**Specifications**
  - Component (if known): central-service-error-handling
  - Version: Current
  - Platform: All
  - Subsystem:
  - Type of testing: Manual
  - Bug found/raised by: Georgi

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by lewisdaly** [comment]
@ndonnan I think I've managed to reproduce this on the `account-lookup-service`. Can you please check and let me know if I'm on the right track?


1. Execute the following example request (this has an invalid `oracleIdType`):

```bash
curl -X POST \
  http://localhost:4001/oracles \
  -H 'Accept: application/vnd.interoperability.participants+json;version=1' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 171' \
  -H 'Content-Type: application/vnd.interoperability.participants+json;version=1.0' \
  -H 'Date: Tue 24 Sep 2019 14:57:53 PST' \
  -H 'Host: localhost:4001' \
  -d '{
  "oracleIdType": "MSISDN2",
  "endpoint": {
    "value": "http://moja-simulator.local/oracle",
    "endpointType": "URL"
  },
  "currency": "USD",
  "isDefault": true
}'
```


2. The result is:

```json
{
    "errorInformation": {
        "errorCode": "3101",
        "errorDescription": "Malformed syntax - PartyIdTypeEnum"
    }
}
```


Are you saying that this `errorDescription` field is incorrect, and that it should have more error information?
