### ISSUE TITLE
Investigate the need to upgrade the version of Scala for central-kms

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/project#96]
**Goal**:
As a developer I would like to upgrade the version of Scala (if required) of central-kms so that we can make use of new features and upgrade the dependencies for performance and stability

**Tasks**:
- [ ] 

**Acceptance Criteria**:
- [ ] Upgraded scala version and dependencies to the latest version
- [ ] Ensure all included tests pass

**Dependencies**:
- None currently

**Comment by elnyry** [comment]
central-kms is not actively maintained anymore, so upgrading it cannot be prioritized
