### ISSUE TITLE
Unable to upgrade dependencies in central-event-stream lib

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#962]
**Summary**:
Central-services-stream fails tests when upgrading the following dependencies:
- Bump sinon from 7.2.4 to 7.4.2  dependencies
- Bump async from 2.6.2 to 3.1.0  dependencies
- Bump node-rdkafka from 2.6.1 to 2.7.1  dependencies
- Bump tape from 4.10.1 to 4.11.0  dependencies
- Bump tap-xunit from 2.3.0 to 2.4.1  dependencies
- Bump raw-body from 2.4.0 to 2.4.1  dependencies

**Severity**:
Low

**Priority**:
Medium

**Expected Behavior**
All tests should pass with the latest dependencies.

**Steps to Reproduce**
  1. Clear out the `reject` list in the [.ncurc.json](https://github.com/mojaloop/central-services-stream/blob/master/.ncurc.json) file.
  2. Run `npm run dep:update`
  3. Run `npm run test`

**Specifications**
  - Component (if known): central-event-stream
  - Version: v7.4.0
  - Platform: n/a
  - Subsystem: testing
  - Type of testing: manual
  - Bug found/raised by: @gibaros, @mdebarros 

**Notes**:

- Severity when opened: Low
- Priority when opened: Medium

**Comment by ggrg** [comment]
Just checked - this issue has been resolved.
