### ISSUE TITLE
GET/participants did not respond with participant's list

### ISSUE THREAD

**Issue by amarmodus** [mojaloop/project#973]
**Summary**:
The participants list is not returned when GET/participants called. below is the log: Error from server (ServiceUnavailable): the server is currently unable to handle the request (get pods d1-743-01-account-lookup-service-admin-778c6b55dd-p9t82)

![image.png](https://images.zenhubusercontent.com/5d4d50c49a260333fcc985e5/0e34ce41-6d19-48a2-8a28-fe996262c925)

**Severity**:
(Low)

**Priority**:
(Low)

**Expected Behavior**
![image.png](https://images.zenhubusercontent.com/5d4d50c49a260333fcc985e5/6e0b6d9d-2e5c-422b-b201-1f176d417afc)

**Steps to Reproduce**
  1. Load OSS-API-Tests postman collection
  2. Run Admin-API, Get Participation List request

**Specifications**
  - Component (if known):
  - Version:
  - Platform:
  - Subsystem:
  - Type of testing: 
  - Bug found/raised by: Sri/Amar

**Notes**:
This issue was seen by Sri, When rerunning it was ok.

- Severity when opened:
- Priority when opened:

**Comment by sri-miriyala** [comment]
This issue is with all admin endpoints. Am not able to see GET/ participants, GET /endpoints, GET /positions etc

**Comment by oderayi** [comment]
@elnyry @sri-miriyala @amarmodus  All Golden Path tests are passing now. Moving issue to review.

**Comment by elnyry** [comment]
Thanks @oderayi .. @amarmodus @sri-miriyala if you're ok with this, would like to close it out..

**Comment by amarmodus** [comment]
![Screenshot 2019-10-15 13 39 11](https://user-images.githubusercontent.com/53434415/66832162-3c071f80-ef51-11e9-8611-7312e3064bf7.png)

GET / Participants ok, Golden path tests ok, Hence closing the issue.
