### ISSUE TITLE
Quoting service is failing when trying to send errorCallbacks due to validation failures

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#988]
**Summary**:
Quoting service is failing when trying to send error callbacks due to validation failures.

This is due to some bugs in the code that the handleException & sendErrorCallback expects request.headers but are not being passed in.

This results in the incorrect exception being sent through.

**Severity**:
High

**Priority**:
Critical

**Expected Behavior**

**Steps to Reproduce**
  1. Send a PUT Quote request with an `accept` header so that validation fails

**Specifications**
  - Component (if known): quoting-service
  - Version: v7.4.x
  - Platform: all
  - Subsystem:
  - Type of testing:
  - Bug found/raised by: @mdebarros 

**Tasks**:
- [x] Error endpoints fixed
- [x] Config to support debugging, etc

**Notes**:

- Severity when opened: High
- Priority when opened: Critical

**Comment by elnyry** [comment]
Fixed in v8.1.1-snapshot, verified..
