### ISSUE TITLE
Docker image for transaction-requests-service is fails to start

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/project#996]
**Summary**:

Docker image for transaction-requests-service is unable to start:
```
npm ERR! missing script: start
npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2019-09-28T07_18_40_815Z-debug.log
```

**Severity**:
Critical

**Priority**:
Medium

**Expected Behavior**
Docker image should start up.

Fix: Define `start` script in package.json.

**Steps to Reproduce**
  1. Build Docker image
  2. Start Docker image

**Specifications**
  - Component (if known): transaction-requests-service
  - Version: v7.4.1-snapshot
  - Platform: Docker
  - Subsystem: n/a
  - Type of testing: manual
  - Bug found/raised by: @mdebarros 

**Notes**:

- Severity when opened:
- Priority when opened:

**Comment by elnyry** [comment]
Fixed now with https://github.com/mojaloop/transaction-requests-service/releases/tag/v8.2.1-snapshot
